- benchmarks/CMakeLists.txt
The usage of Debian-specific options broke the build for Fedora.
Signed-off-by: Neal Gompa <ngompa13@gmail.com>
> benchmarks: Use standard options to install perf framework on non-Debian

- include/platform/mir/graphics/wayland_allocator.h
- src/platforms/mesa/server/buffer_allocator.cpp
- src/platforms/mesa/server/buffer_allocator.h
- src/server/frontend/wayland/wayland_connector.cpp
Releasing Wayland buffers must occur on the executor thread. (LP: #1728069)
> Releasing Wayland buffers must occur on the executor thread. (LP: #1728069)

- .gitmodules
- CMakeLists.txt
- include/server/mir/server.h
- src/server/frontend/wayland/wayland_connector.cpp
- src/server/server.cpp
- src/server/symbols.map
- tests/acceptance-tests/CMakeLists.txt
- tests/acceptance-tests/wayland/CMakeLists.txt
- tests/mir_test_framework/headless_display_buffer_compositor_factory.cpp
This integrates `wlcs` with the Mir test-suite, gated on MIR_RUN_ACCEPTANCE_TESTS.
It then fixes the bugs exposed!
> Add wlcs tests

- src/server/scene/basic_surface.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
This fixes the build with (unreleased) Clang 6, and then fixes the upper-bound validation I noticed at the same time.
> Fix window attribute validation

- bors.toml
We only have a single node available at the moment, so sometimes it's
busy.
> bors: increase CI timeout

- doc/getting_involved_in_mir.md
Attempting to follow the "Getting involved in mir" guide leads to
an error when cmake looks for wlcs and can't find it. This commit
adds the git commands to fetch the wlcs repo so that the build
works.
Fixes #42
> Add git submodule steps in getting involved guide

- debian/mir-test-tools.install
This fixes¹ the package builds, which are complaining that we don't install mir_wlcs_tests anywhere.
¹: Well, should fix ☺
> Install mir_wlcs_tests with the rest of the tests

- tools/dev-upload.sh
Travis uses trusty, which doesn't yet have the long versions.
>  tools: use short dpkg-buildpackage options

- src/client/mir_screencast.cpp
We need the request in order to invoke the client's callback, but once the client's callback has been
completed we are no longer guaranteed that mir_screencast_release won't be called.
Ensure we don't try and access freed state in the case of heavily loaded systems,
such as our CI ☺.
Fixes #62
> Screencast: Take more care around lifetimes in screencast_done().

- tests/performance-tests/CMakeLists.txt
Both mir_client_startup_performance_test and mir_compositor_performance_test does not depend on GMock, this results in a build race condition between the tests and GMock.
This results in build failure on UBports arm node (64 cores)  since the tests get built before GMock is done.
> Add missing GMock dependencies for performance_tests

- include/server/mir/scene/null_session_listener.h
- include/server/mir/scene/session_listener.h
- src/server/scene/application_session.cpp
- src/server/scene/session_manager.cpp
- tests/include/mir/test/doubles/mock_session_listener.h
These parallel the surface creation/destruction observers, and are needed by
wlcs to correlate Mir objects with their Wayland counterparts.
> SessionListener: Add buffer_stream_{created,destroyed} observers.

- include/server/mir/server.h
- src/server/frontend/wayland/wayland_connector.cpp
- src/server/frontend/wayland/wayland_connector.h
- src/server/server.cpp
This lets code access the wl_display* in the Wayland event-loop thread context.
This is useful for shells which wish to expose additional Wayland extensions,
or for other parts of Mir which require more visibility into the Wayland context.
> Add Server::run_on_wayland_display().

- include/test/mir/test/event_factory.h
- tests/mir_test/event_factory.cpp
- tests/mir_test_framework/fake_input_device_impl.cpp
For pointer motion events, at least for now.
> mtf::FakeInputDevice: Add the ability to synthesise the event time.

- src/server/frontend/wayland/wayland_connector.cpp
We were calculating the buffer size as the number of *pixels* in the buffer, but, of course,
each pixel is generally more than one byte!
This resulted in the GL driver attempting to access outside the bounds of the data array,
and a segfault.
Fixes #78
> WlShmBuffer: Calculate buffer size correctly.

- src/miral/runner.cpp
Work items in the main loop should be allowed to die before the server objects they reference.
> Don't extend the life of the main loop after server shuts down (Fixes #88)

- examples/wayland_client.c
- src/server/frontend/wayland/wayland_connector.cpp
wayland_client: Calculate buffer size correctly.
We were setting the stride incorrectly in wayland_client, it is documented as the number of
bytes and we were using the number of pixels.
This resulted in the GL driver attempting to access outside the bounds of the data array,
and a segfault.
Fixes #78 (better) and #94
> wayland_client: Calculate buffer size correctly. 

- debian/control
- debian/mir-test-tools.install
- tests/performance-tests/CMakeLists.txt
Make the mir-smoke-test-runner script available for manual testing
> Add mir-smoke-test-runner to mir-test-tools

- src/server/frontend/wayland/wayland_connector.cpp
This fixes the wlcs test BadBufferTest.client_lies_about_buffer_size
> WlShmBuffer: Guard against definitely-invalid strides.

- examples/miral-shell/miral-xrun.sh
Avoids problems running in a miral "desktop"
> [miral-xrun] If MIR_SOCKET or WAYLAND_DISPLAY is set, then use it to run the X server

- src/server/frontend/wayland/wayland_connector.cpp
Both Ubuntu Artful and Fedora 27 builders have the compiler segfaulting.
This avoids that problem.
> Workaround gcc segfault (Fixes #97)

- examples/miral-shell/miral-app.sh
- examples/miral-shell/miral-desktop.sh
- tools/mir-smoke-test-runner.sh
Specify WAYLAND_DISPLAY to avoid clashing with desktop. If available, use $MIR_SOCKET as host socket.
> Tidy up smoke test script (again)

- src/server/frontend/default_ipc_factory.cpp
- src/server/frontend/session_mediator.cpp
- tests/acceptance-tests/test_nested_input.cpp
This fixes another failure mode of NestedInput* tests.
Best seen intermittently with NestedInput.pressed_keys_on_vt_switch_are_forgotten:
$rm core;stress -c 4 -t 200&while cmake-build-debug/bin/mir_acceptance_tests --logging on --gtest_filter=NestedInput.pressed_keys_on_vt_switch_are_forgotten; do :; done
When the servers are shut down the static ThreadExecutor in src/server/frontend/default_ipc_factory.cpp is "quiesced" but it can still be running tasks where the nested server "talks" to the host connection to release buffers and/or the connection after both servers have existed.
This also fixes the intermittent failures in NestedInput.on_input_device_state_nested_server_emits_input_device_state
Also important is a test that hung intermittently using the first version of this PR: …
> Don't queue work that owns a buffer to ThreadExecutor (which lives too long)

- src/server/frontend/wayland/wayland_connector.cpp
- src/server/frontend/wayland/wayland_connector.h
- src/server/frontend/wayland/wayland_default_configuration.cpp
Wayland check SessionAuthorizer::connection_is_allowed on client connection, this is needed for unity8 to accept wayland applications.
> Wayland check SessionAuthorizer::connection_is_allowed on client connection

- src/server/frontend/wayland/wayland_connector.cpp
Some stubs implemented and windows are only created when we know their size.
> More Wayland core support: menus are placed correctly.

- src/server/input/surface_input_dispatcher.cpp
- src/server/input/surface_input_dispatcher.h
The WLCS tests ported from Weston include tests moving a surface underneath the pointer rather than moving the pointer over a surface. Mir currently fails them as we only send input events in response to hardware events.
Part one, because there are other obvious testcases to write which Mir will likewise fail.
> Pointer events on surface movement (Part 1)

- doc/getting_and_using_mir.md
- examples/miral-shell/miral-app.sh
- examples/miral-shell/miral-desktop.sh
- examples/miral-shell/miral-run.sh
- src/miral/runner.cpp
- src/server/frontend/wayland/wayland_connector.cpp
- src/utils/run.cpp
Stop using qtubuntu when launching Qt applications and use wayland instead. (Plus fix some resulting issues seen on Fedora 27 and Artful)
> no-more-qtubuntu

- examples/miral-shell/miral-desktop.sh
- src/server/frontend/wayland/CMakeLists.txt
- src/server/frontend/wayland/wayland_connector.cpp
- src/server/frontend/wayland/wlshmbuffer.cpp
- src/server/frontend/wayland/wlshmbuffer.h
Fixes crash when events are targeted at a destroyed window.
Also includes some useful cherry-picks from the xdg-shell work.
> more-wayland-core-fixes

- include/server/mir/frontend/buffer_stream.h
- src/server/compositor/stream.cpp
- src/server/compositor/stream.h
- src/server/frontend/CMakeLists.txt
- src/server/scene/basic_surface.cpp
- tests/include/mir/test/doubles/mock_buffer_stream.h
- tests/include/mir/test/doubles/stub_buffer_stream.h
- tests/integration-tests/test_surface_stack_with_compositor.cpp
- tests/unit-tests/compositor/test_stream.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
mf::BufferStream::{add,remove}_observer(ms::SurfaceObserver) exists as an implementation detail
of BasicSurface, which needs to provide the SurfaceObserver::frame_posted observable.
Rather than pass the whole SurfaceObserver down to the BufferStream, just add a callback
to run on buffer submition to the BufferStream.
If need be this can be switched out to a full BufferStreamObserver, but it is not currently
needed.
> mf::BufferStream: Don't pretend to be a scene::Surface.

- .travis.yml
- spread.yaml
glm-devel didn't get an update along with gcc:
https://bugzilla.redhat.com/show_bug.cgi?id=1542941
> [travis] disable fedora builds for now and use IPv4 in spread

- include/server/mir/scene/null_surface_observer.h
- include/server/mir/scene/surface_observer.h
- include/server/mir/shell/surface_ready_observer.h
- src/include/server/mir/scene/surface_event_source.h
- src/include/server/mir/scene/surface_observers.h
- src/server/input/cursor_controller.cpp
- src/server/input/surface_input_dispatcher.cpp
- src/server/scene/CMakeLists.txt
- src/server/scene/application_session.cpp
- src/server/scene/basic_surface.cpp
- src/server/scene/legacy_scene_change_notification.cpp
- src/server/scene/legacy_surface_change_notification.cpp
- src/server/scene/legacy_surface_change_notification.h
- src/server/scene/null_surface_observer.cpp
- src/server/scene/surface_event_source.cpp
- src/server/shell/abstract_shell.cpp
- src/server/shell/surface_ready_observer.cpp
- tests/acceptance-tests/test_client_cursor_api.cpp
- tests/acceptance-tests/test_confined_pointer.cpp
- tests/acceptance-tests/test_nested_mir.cpp
- tests/acceptance-tests/test_surface_modifications.cpp
- tests/acceptance-tests/test_surface_morphing.cpp
- tests/acceptance-tests/test_surface_specification.cpp
- tests/integration-tests/test_stale_frames.cpp
- tests/unit-tests/input/test_cursor_controller.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
- tests/unit-tests/scene/test_legacy_scene_change_notification.cpp
This is useful when a component wants to monitor many (or all)
of the ms::Surfaces in the scene.
> Pass active surface through ms::SurfaceObserver

- tests/integration-tests/CMakeLists.txt
- tests/integration-tests/graphics/mesa/CMakeLists.txt
- tests/unit-tests/platforms/mesa/kms/CMakeLists.txt
- tests/unit-tests/platforms/mesa/x11/CMakeLists.txt
Fix rawhide linking for mir_unit_tests_mesa-kms
(To reproduce enable MIR_LINK_TIME_OPTIMIZATION but DON'T enable MIR_USE_LD_GOLD)
> Fix link errors encountered on rawhide

- src/server/frontend/wayland/wayland_connector.cpp
(The most obvious effect is ensuring that windows being created are drawn immediately.)
> Commit Mir window changes before submitting the corresponding buffer.

- .travis.yml
glm has now been updated to work with the recently updated g++
> Restore Fedora 27 in CI

- src/server/input/surface_input_dispatcher.cpp
- src/server/input/surface_input_dispatcher.h
While this doesn't currently cause us any problems, its the sort of thing that will plausibly do so in the future.
> Fix unregistration of ms::SurfaceObservers in SurfaceInputDispatcher

- src/server/frontend/wayland/wayland_connector.cpp
Otherwise they'll have essentially random values, and we'll send an unnecessary wl_pointer.axis event.
This isn't too harmful for real clients, but it kills the wlcs tests because we don't have an axis
event handler set up!
> WlPointer: Initialise last coördinate values to 0.

- examples/miral-shell/miral-app.sh
- examples/miral-shell/miral-desktop.sh
- examples/miral-shell/miral-run.sh
- examples/miral-shell/miral-xrun.sh
This prevents annoying delays when starting GTK applications followed by
WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
> Add NO_AT_BRIDGE=1 to client environment.

- examples/miral-shell/floating_window_manager.cpp
- examples/miral-shell/floating_window_manager.h
- src/server/frontend/wayland/basic_surface_event_sink.cpp
- src/server/frontend/wayland/basic_surface_event_sink.h
- src/server/frontend/wayland/wayland_connector.cpp
1. Connects up Wayland move() requests with the CSD move support.
2. Implements move in the "floating" window manager
3. Consolidates the move logic
NB GTK apps on *Artful* don't work with this but Qt apps and weston-terminal do.
(On Bionic, Fedora 27 and rawhide GTK apps seem fine.)
> Allow Window movement to be initiated by Wayland clients (Fixes #61)

- src/platforms/mesa/server/buffer_allocator.cpp
Without this mir will not run with proprietary nividia drivers using the
X platform.
Wayland is sure to not work, but it's better then not working at all.
> Don't crap out if we can't bind to wayland display

- examples/server_example_adorning_compositor.cpp
- include/platform/mir/graphics/transformation.h
- src/platforms/mesa/server/kms/bypass.cpp
- src/platforms/mesa/server/kms/display_buffer.cpp
- src/server/compositor/occlusion.cpp
- src/server/graphics/nested/display_buffer.cpp
- tests/unit-tests/compositor/test_default_display_buffer_compositor.cpp
glm::mat4 has a perfectly acceptable default constructor so this should be unnecessary
but GCC 7.3.0 in bionic-proposed warns about this.
> Explicitly initialise glm::mat? identity matricies.

- .travis.yml
Linode stopped listing ubuntu-17.10 images, hopefully temporarily?
> travis: disable Ubuntu 17.10 based tests

- src/server/frontend/wayland/CMakeLists.txt
- src/server/frontend/wayland/wayland_connector.cpp
- src/server/frontend/wayland/wayland_connector.h
- src/server/frontend/wayland/wayland_utils.h
- src/server/frontend/wayland/wl_mir_window.cpp
- src/server/frontend/wayland/wl_mir_window.h
- src/server/frontend/wayland/wl_surface.cpp
- src/server/frontend/wayland/wl_surface.h
Some changes of note:
- renamed `get_wlsurface(resource)` to `WlSurface::from(resource)`
- `nullWlMirWindow;` is now `nullWlMirWindowPtr` (and the `NullWlMirWindow` type is not exposed)
> moved surface code from wayland_connector.cpp to wl_surface.cpp

- .gitignore
- benchmarks/CMakeLists.txt
- benchmarks/mir_perf_framework_setup.py.in
mir-perf-framework is released alongside the rest of Mir, so it should be versioned in the same manner.
Signed-off-by: Neal Gompa <ngompa13@gmail.com>
> benchmarks: Configure mir-perf-framework with the Mir version

- src/protocol/wrapper_generator.cpp
- src/server/frontend/wayland/basic_surface_event_sink.cpp
- src/server/frontend/wayland/basic_surface_event_sink.h
- src/server/frontend/wayland/core_generated_interfaces.h
- src/server/frontend/wayland/wl_seat.cpp
- src/server/frontend/wayland/wl_seat.h
- src/server/frontend/wayland/xdg_shell_generated_interfaces.h
- Renamed bind() to bind_thunk()
- Created a virtual bind() function (not pure virtual, empty by default) that can be overridden by globals and is called after an instance is created (WlSeat needed this)
- Call wl_global_destroy() in the destructor of global wayland objects (and store a pointer to the wl_global to allow this)
- Refactored WlSeat to use the improved generated class instead of rolling its own wayland vtable.
> changed code that autogenerates globals to facilitate refactoring WlSeat

- src/server/frontend/wayland/wayland_connector.cpp
- src/server/frontend/wayland/wl_mir_window.cpp
- src/server/frontend/wayland/wl_mir_window.h
- src/server/frontend/wayland/wl_pointer.cpp
- src/server/frontend/wayland/wl_surface.h
- src/server/frontend/wayland/wl_touch.cpp
Improves experimental xdg-shell support.
Drag resizing of xdg-shell clients works on F27 and Artful (with some flickering)
On bionic weston-terminal seems happy. But there are some remaining issues:
Qt apps hang after resize (pre-existing)
GTK apps crash on interaction (pre-existing)
> fix-handling-of-set_window_geometry

- examples/server_example_adorning_compositor.cpp
- include/platform/mir/graphics/transformation.h
- include/test/mir/test/doubles/null_display_buffer.h
- src/platforms/mesa/server/kms/bypass.cpp
- src/platforms/mesa/server/kms/display_buffer.cpp
- src/platforms/mesa/server/x11/graphics/display_buffer.cpp
- src/renderers/gl/renderer.cpp
- src/server/compositor/occlusion.cpp
- src/server/graphics/nested/display_buffer.cpp
- src/server/graphics/offscreen/display_buffer.cpp
- src/server/scene/basic_surface.cpp
- tests/include/mir/test/doubles/fake_renderable.h
- tests/include/mir/test/doubles/stub_renderable.h
- tests/unit-tests/compositor/test_default_display_buffer_compositor.cpp
- tests/unit-tests/graphics/offscreen/test_offscreen_display.cpp
- tests/unit-tests/platforms/mesa/kms/test_display_buffer.cpp
GLM 0.9.9-a2 conveniently changes the behaviour of the default constructor from constructing
an identity matrix to constructing a 0-matrix. This makes much of Mir sad.
Explicitly initialise *identity* matricies everywhere.
> Explicitly initialise glm matricies, take 2.

- tests/acceptance-tests/test_nested_input.cpp
- tests/acceptance-tests/test_nested_mir.cpp
Opinions may legitimately differ on whether this is a good idea (vote accordingly). However, these intermittent failures are a PITA. Also:
1. We're not working on the code these test; and,
2. "Nested" only works with the legacy libmirclient AND the Mir EGL patch to mesa
I've not deleted them as they should compile and we may want to reinstate in the future (e.g. if we address 2).
> Disable flaky tests for nested servers (workaround for #138, #143, #147 & #148)

- .travis.yml
Same as Fedora Rawhide, Ubuntu devel may be in an inconsistent state,
allow it to fail.
> [travis] allow ubuntu-devel to fail, too

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wl_mir_window.cpp
- src/server/frontend_wayland/xdg_shell_v6.cpp
- src/server/scene/basic_surface.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
Handling this correctly in Mir means Qt apps can create surfaces and XDG shell windows as they expect
> Windows can have content when created

- src/server/frontend_wayland/wayland_connector.cpp
The GDK crash is sorted 
https://github.com/MirServer/mir/pull/207 is in the pipeline
and issue #127 looks like a QtWayland problem
So let's say xdg-shell is good enough!
> Enable xdg-shell v6

- src/server/graphics/software_cursor.cpp
Server supplying zero sized cursor image to Mir causes Mir to die with an obscure error message:
"Failed to map file: Invalid argument"
Catch zero sized cursor image and throw with a better error message.
Will help other Mir users when encountering #120
> Software cursor: throw exception for zero sized cursor image

- src/platforms/mesa/server/kms/real_kms_output.cpp
If the current mode advertised by the crtc does not exist in the list of modes, fall back to using the mode named "preferred" as current mode. Some VMs specify this.
Fixes nested server run on VMWare: https://bugs.launchpad.net/mir/+bug/1661295
> KMS platform - fallback if crtc mode invalid

- src/include/platform/mir/options/default_configuration.h
- src/platform/options/default_configuration.cpp
- src/platforms/mesa/server/kms/platform_symbols.cpp
Previously we were calling `probe()` twice - once, before option parsing, to
guess what graphics platform we would be using and then call its
`add_platform_options()`, and then one during graphics initialisation.
Instead, unconditionally call `add_platform_options()` on every graphics
platform we can lay our hands on, and only call `probe()` when we're
working out which graphics platform to construct.
> Options: Present all graphics platform options.

- src/server/frontend_wayland/wl_pointer.cpp
- src/server/frontend_wayland/wl_pointer.h
A convention has grown that each mouse wheel click is reported as a multiple of 10. Without this multiplier, most clients would fail to scroll at all.
> Wayland: fix mouse wheel scrolling

- src/server/frontend_wayland/wl_subcompositor.cpp
- src/server/frontend_wayland/wl_subcompositor.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/wl_surface_role.h
The main idea of this PR is encapsulate all double buffered surface state in a single class, and restructure the surface committing system to work like so:
* requests are made to the surface that modify the pending state
* WlSurface::commit() is called
* it calls WlSurfaceRole::commit(state) with its pending state
* that can either call WlSurface::commit(state), or it can cache the state to be committed later (this will be done for synchronized subsurfaces)
* in WlSurface::commit(state) the buffer is actually created and submitted
* the role then does whatever committing it needs to do
> Restructure WlSurface::commit()

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wl_subcompositor.cpp
- src/server/frontend_wayland/wl_subcompositor.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
* removed `WlSurfaceRole::new_buffer_size()`
* changed the `surface` member of `WlAbstractMirWindow` from a `wl_resource*` to a `WlSurface*`
> refactored WlAbstractMirWindow

- examples/miral-shell/miral-app.sh
- examples/miral-shell/miral-desktop.sh
- examples/miral-shell/miral-run.sh
This is most useful on 16.04LTS where the toolkit Wayland support tends to be flaky. E.g. 
o Qt clients hang.
o GDK clients crash when xdg-shell v5 is unavailable (instead falling back to wl_shell or gtk-mir)
> Provide options to use toolkit libmirclient support in miral-desktop, miral-app and miral-run

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wl_pointer.cpp
- src/server/frontend_wayland/wl_pointer.h
- src/server/frontend_wayland/wl_subcompositor.cpp
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
Enable Wayland clients to set and hide the cursor
> Implement WlSurface::set_cursor()

- src/miral/CMakeLists.txt
src/miral/CMakeLists.txt has some hardcoded compile flags inherited from its days as a standalone project.
These should be inherited from the parent project instead. (Fixes #266)
> Don't force -flto for libmiral

- debian/rules
- spread/build/fedora/task.yaml
I'm not sure why this is required, but running CMake twice reliably
causes the `wlcs` tests to run. (See #273 for example).
Do the simple, not very costly, thing rather than stare deeper into
the CMake void.
> build: Run cmake twice(‽) to pick up wlcs tests

- src/server/scene/application_session.cpp
For tiling, we need to set the surface state to "maximized" so that Wayland clients obey exactly.
That wasn't working as the wayland_frontend wasn't being notified of the actual state.
> Configure new surfaces after attaching observers

- src/server/input/surface_input_dispatcher.cpp
The event "goes stale" and can cause a segfault. (Fixes #276)
> Don't remember recent surface events after the input dispatcher is shut down.

- debian/rules
> Drop temporary workaround for broken mesa "Mir EGL" patch in 18.04

- src/miral/application_authorizer.cpp
- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- src/miral/keymap.cpp
- src/miral/runner.cpp
- src/miral/set_window_management_policy.cpp
- src/miral/window_info.cpp
- src/miral/window_management_options.cpp
- src/miral/window_specification.cpp
- tests/miral/test_server.cpp
- tests/miral/test_window_manager_tools.h
- tests/miral/window_id.cpp
We don't need any of this now that MirAL is shipped with Mir.
> Remove obsolete checks on Mir version in MirAL code.

- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
qtwayland gets confused by receiving these event out of order. (Fixes #280)
> Sequence xdg-top-level and xdg-surface configure events correctly.

- src/server/frontend_wayland/wl_surface.cpp
Restores the previous behaviour. (Fixes #289)
> The role needs to be notified when a surface is destroyed

- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
We messed up the handling of frames in a recent refactor: this restores the correct behaviour. (Fixes #284)
> When a surface is rendered acknowledge all frames that have been committed.

- examples/miral-shell/miral-desktop.sh
The final "sudo" commands could request a password (on an inactive VT) and didn't wait for Mir to exit before switching VT.
> [miral-desktop] Fix synchronization and timeout issues

- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/xdg_shell_v6.cpp
Maximised/Fullscreen/minimized requests need to be handled immediately. (Fixes #297)
> [Wayland] Implement/correct implementation of window state changes in xdg-shell

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
Implement the common state changing logic in WlAbstractMirWindow. (Fixes: #311)
> Consolidate the fullscreen (and other Window state) handling

- spread/build/fedora/task.yaml
Make is no longer preinstalled on the GCE images.
> [spread] add make to build dependencies

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wl_pointer.cpp
- src/server/frontend_wayland/wl_subcompositor.cpp
- src/server/frontend_wayland/wl_subcompositor.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
Changed WlSurface::surface_id from a variable to a getter and added a surface id getter to WlSurfaceRole. This is needed to get the surface id for subsurfaces, and is better design imo.
> Switched WlSurface::surface_id from variable to getter

- src/server/frontend_wayland/wl_pointer.cpp
- src/server/frontend_wayland/wl_pointer.h
Move some logic out of the handle_* functions. Allows for grouping *some* events into the same pointer frame, and helps with other stuff I've been working on.
> send frame events better

- src/server/scene/legacy_scene_change_notification.cpp
Both Wayland and Mir clients can provide content when creating a window, we need draw them before another buffer is submitted.  (Fixes #328)
> Notify the compositor of surfaces that have content before they are added to the scene.

- src/server/frontend_wayland/wl_subcompositor.cpp
- src/server/frontend_wayland/wl_subcompositor.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
Now there are two ways to signal that the buffer list needs a refresh. the buffer list is refreshed when buffers are added, removed, offsets are changed or (in the future) input regions are changed.
Both surfaces and surface roles have `invalidate_buffer_list()`, which recursively goes up the subsurface tree and triggers an immediate buffer list refresh with `populate_buffer_list()`. This is called when a asynchronous subsurface is committed.
For synchronous subsurfaces and non-subsurfaces, `SurfaceState::buffer_list_needs_refresh()` returns if a buffer list refresh is needed on that commit.
> Rework buffers update

- src/server/glib_main_loop_sources.cpp
> We can't safely destroy objects whose implementation may lie in a .so that's been unloaded.

- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
* The frame notifications are copied by value into the lamda now, and there is no need to hold them in the surface. (Does this screw stuff up? Was there a reason we were maintaining a list in the surface before, or was that legacy?)
* Frame notifications are now sent even if there is no buffer or if the buffer is null (this is consistent with Weston)
This fixes the gedit lockup when subsurfaces are dismissed.
> Send frame notifications even if there is no buffer

- src/server/frontend_wayland/CMakeLists.txt
- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wl_region.cpp
- src/server/frontend_wayland/wl_region.h
- src/server/frontend_wayland/wl_subcompositor.cpp
- src/server/frontend_wayland/wl_subcompositor.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/wl_surface_role.h
- tests/mir_test_framework/canonical_window_manager.cpp
Added support for Wayland supplied input regions. They are stored as a vector of rectangles both in `WlSurface` and (since input region is double buffered) in WlSurfaceState`. They are stored relative to the wayland surface (`offset` must be added to them to make them relative to the logical Mir window). They are accessed by the `WlAbstractMirWindow` by `populate_surface_data()`.
The most noticeable effect of this PR is that GTK windows are now resizable. Also, it's needed for subsurface input.
> Input regions

- src/server/graphics/software_cursor.cpp
Correct the glm matrix used for software cursor transformation (Fixes #322)
> Correct the glm matrix used for software cursor transformation (Fixes #322)

- src/server/frontend_wayland/wayland_connector.cpp
- tests/mir_test_framework/async_server_runner.cpp
I had many threads called "mir_wlcs_tests." this makes it easier to follow
> Give more threads useful names

- src/server/frontend_wayland/wlshmbuffer.cpp
Don't hold a lock while potentially destroying an object that uses it. (Fixes #355)
> Don't hold a lock while potentially destroying an object that uses it.

- src/server/glib_main_loop_sources.cpp
- src/server/input/default_input_device_hub.cpp
Ensure ExternalInputDeviceHub::remove_observer() synchronizes memory across threads. (Fixes #359)
> Ensure ExternalInputDeviceHub::remove_observer() synchronizes memory across threads

- tests/performance-tests/CMakeLists.txt
The mir_add_wrapped_executable() function provides the correct install() invocation, luckily it overwrites the incorrect binary. But we shouldn't need luck.
> Don't install the mir_performance_tests "wrapper" before installing the real executable

- src/include/server/mir/default_server_configuration.h
- src/server/default_server_configuration.cpp
- src/server/report/default_server_configuration.cpp
- src/server/server.cpp
- src/server/symbols.map
- tests/mir_test_framework/server_runner.cpp
Defer initializing DefaultServerConfiguration::reports until any subclasses have been fully constructed. (Fixes #361)
> Defer initializing DefaultServerConfiguration::reports until any subclasses have been fully constructed. (Fixes #361)

- include/server/mir/main_loop.h
- src/include/server/mir/glib_main_loop.h
- src/server/glib_main_loop.cpp
- tests/include/mir/test/doubles/mock_main_loop.h
- tests/unit-tests/test_glib_main_loop.cpp
This adds a couple of new APIs to GLibMainLoop:
* `bool GLibMainLoop::running()`, which returns whether or not the main loop is active, and
* `run_with_context_as_thread_default()`, which runs the supplied functor with GLibMainLoop's `GMainContext*` as the thread-default main context.
These are useful for integrating with various GIO components, such as GDBus, which use the thread-default main loop for dispatch.
> GLibMainLoop extensions

- tests/unit-tests/test_logind_console_services.cpp
Ignore the return value of write when outputting diagnostics. (Fixes #376)
> Ignore the return value of write when outputting diagnostics. (Fixes #376)

- examples/example-server-lib/titlebar_config.cpp
Add a couple more places to look for font files.
Maybe we should stop with the special cases and emulate something like this?
```
find /usr/share/fonts/ -name Ubuntu-B.ttf -or -name FreeSansBold.ttf
```
> [miral-shell] Fix default font on Ubuntu 18.04 and Arch

- benchmarks/frame-uniformity/touch_producing_server.cpp
- include/test/mir/test/event_factory.h
- include/test/mir_test_framework/fake_input_device.h
- tests/acceptance-tests/test_client_input.cpp
- tests/integration-tests/test_touchspot_visualization.cpp
- tests/mir_test/event_factory.cpp
- tests/mir_test_framework/fake_input_device_impl.cpp
Improvements to the mock touch class, including changing its input coordinates to be the same as screen coordinates.
Note: these changes are needed for upcoming WLCS tests.
> Mock touch improvements

- tests/mir_test_framework/canonical_window_manager.cpp
stopped CanonicalWindowManagerPolicy from clipping input shape to surface bounds (fixes subsurface input tests)
> stopped clipping input shape to input shape to surface bounds

- src/server/console/default_configuration.cpp
- src/server/console/linux_virtual_terminal.h
- tests/unit-tests/console/test_linux_virtual_terminal.cpp
Make the signature of VTFileOperations::ioctl() match that of ::ioctl(). (Fixes #395)
> Make the signature of VTFileOperations::ioctl() match that of ::ioctl()

- src/server/input/surface_input_dispatcher.cpp
Don't synthesize events during gestures. (Fixes #179)
> Don't synthesize pointer events during gestures

- tests/acceptance-tests/test_session_mediator_report.cpp
Some time ago we switched from synchronous reporting to async. Obviously this test was overlooked in the transition. (Fixes #196)
> Update SessionMediatorReportTest.session_connect_called to reflect asynchronous notifications

- tests/unit-tests/console/test_logind_console_services.cpp
[LogindConsoleServices test] Stop the mainloop thread in test cases, instead of leaving it running while destroying objects it may reference. (Fixes #398)
> [LogindConsoleServices test] Stop the mainloop thread in test cases, instead of leaving it running while destroying objects it may reference

- src/server/frontend_wayland/output_manager.cpp
- src/server/frontend_wayland/output_manager.h
- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
- src/server/frontend_wayland/xdg_shell_v6.h
[Wayland] Make use of the specified output in fullscreen requests. (Fixes #423)
> [Wayland] Make use of the specified output in fullscreen requests. (Fixes #423)

- src/miral/runner.cpp
[miral::MirRunner] don't use the main loop before the server has been initialized. (Fixes #437)
> [miral::MirRunner] don't use the main loop before the server has been initialized. (Fixes #437)

- src/platforms/mesa/server/kms/egl_helper.cpp
- src/platforms/mesa/server/kms/egl_helper.h
- tests/mir_test_doubles/mock_egl.cpp
- tests/unit-tests/platforms/mesa/kms/test_display.cpp
- tests/unit-tests/platforms/mesa/kms/test_display_configuration.cpp
- tests/unit-tests/platforms/mesa/kms/test_display_generic.cpp
- tests/unit-tests/platforms/mesa/kms/test_display_multi_monitor.cpp
> mesa-kms: Select EGLConfig matching our GBM format.

- src/server/frontend_wayland/basic_surface_event_sink.cpp
- src/server/frontend_wayland/basic_surface_event_sink.h
- src/server/frontend_wayland/wl_surface_role.cpp
- src/server/frontend_wayland/xdg_shell_v6.cpp
Note there are couple of racy wlcs tests this breaks:
XdgToplevelV6Configuration.maximized_and_unmaximized
XdgToplevelV6Configuration.fullscreened_and_restored
These are fixed in: https://github.com/MirServer/wlcs/pull/58
> Ensure resize configuration events are not superseded. (Fixes #449)

- src/server/frontend_wayland/output_manager.cpp
Don't send output events that are not supported in the agreed protocol version. (Fixes #389)
> Don't send output events that are not supported in the agreed protocol version. (Fixes #389)

- examples/miral-kiosk/kiosk_window_manager.cpp
[miral-kiosk] Don't allow apps to specify size of "maximized" windows. (Fixes #454)
> [miral-kiosk] Don't allow apps to specify size of "maximized" windows. (Fixes #454)

- .travis.yml
- tools/process_snaps.py
- tools/requirements.txt
This will look through the `dev` and `rc` PPAs to see if the snaps published in the `edge` and `candidate` channels, respectively, are up to date. And if not, it will trigger the appropriate launchpad snap recipes.
> [travis] process snaps in CI

- .travis.yml
- process snaps first
- don't do it if outside of `MirServer/mir`, otherwise we don't have credentials
>  [travis] fix snap triggering rules

- debian/mir-demos.install
Strip internal tests from mir-test-tools package. (Fix mir-demos too)
> Strip internal tests from mir-test-tools package

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wayland_connector.h
- src/server/frontend_wayland/wayland_default_configuration.cpp
Refactor creation of Wayland extensions so that the connector doesn't need to know what they are.
This is a small step towards towards shells being able to specify the extensions Mir enables.
> Refactor creation of Wayland extensions so that the connector doesn't need to know what they are.

- src/miral/CMakeLists.txt
- src/miral/join_client_threads.h
Prevent spurious symbols being exported on Cosmic. (Fixes #475)
> Prevent spurious symbols being exported on Cosmic. (Fixes #475)

- debian/mir-test-tools.install
- examples/mir_demo_server/CMakeLists.txt
Re-instate mir_demo_server (but only in mir-test-tools).
mir_demo_server is used by mir-smoke-test-runner
> Re-instate mir_demo_server (but only in mir-test-tools)

- CMakeLists.txt
- src/miral/CMakeLists.txt
- src/miral/join_client_threads.h
Fix spurious symbols, take three (Fixes #475)
Workaround #475 in a way that doesn't require source changes.
Unlike Cosmic's bfd linker the gold linker doesn't add spurious debugging symbols. As an added bonus, the gold linker is roughly twice as fast as the bfd linker, and produces better warnings.
> Fix spurious symbols, take three (Fixes #475)

- examples/mir_demo_server/server_example.cpp
- examples/miral-shell/shell_main.cpp
Don't offer X11 support in miral-shell (yet)
> Don't offer X11 support in miral-shell (yet)

- src/miral/x11_support.cpp
- src/platform/options/default_configuration.cpp
- src/platforms/mesa/server/x11/graphics/graphics.cpp
1. rename pre-existing "--x11-displays" to "--x11-output" for Mir-on-X11
2. rename new "--display" to "--x11-display-experimental" for Xwayland display
Note that we can use "--x11-display" in scripts already as boost.Options will resolve that to "--x11-display-experimental".
> Fixup X11 related config names

- examples/miral-shell/miral-desktop.sh
- src/include/platform/mir/options/configuration.h
- src/platform/options/default_configuration.cpp
- src/platform/symbols.map
- src/server/console/default_configuration.cpp
- tests/mir_test_framework/headless_test.cpp
- tests/unit-tests/platforms/mesa/kms/test_platform.cpp
For display managers like LightDM or GDM this can let them explicitly select how they expect Mir to interact - via logind or to handle to console on its own.
For tests we can explicitly select the NullConsoleProvider, to speed up the tests and to ensure the tests don't accidentally modify the system they're running on.
Use this new configuration option in the test harness.
> ServerConfiguration: Add an option to select the ConsoleServices provider

- src/server/frontend_wayland/xdg_shell_v6.cpp
I haven't found an app in the wild that doesn't specify gravity, but you don't need to according to the protocol. Mir would crash (unwrap a null optional in the window manager) without this fix. I was hitting this on the popup defaults wlcs test, which is currently in a PR.
> [Wayland] Default for positioner gravity

- src/server/frontend_wayland/xdg_shell_v6.cpp
Removed wrapper functions and the `set_next_commit_action()` system. This does change behavior slightly, but I could not find any evidence of breakage on GTK, QT or Weston apps. From my analysis of `WAYLAND_DEBUG` output, it appears the new behavior matches both weston and wlroots. It does break one WLCS test (`XdgSurfaceV6Test.gets_configure_event`), which is dealt with [here](https://github.com/MirServer/wlcs/pull/65).
> More XDG shell cleanups

- src/include/server/mir/default_server_configuration.h
- src/server/console/default_configuration.cpp
- src/server/console/logind_console_services.cpp
- src/server/glib_main_loop.cpp
- tests/unit-tests/console/test_logind_console_services.cpp
- tests/unit-tests/test_glib_main_loop.cpp
We need to pass the_console_services() through to a number of components, some of which (like platform probing) don't have anywhere to stash an owning reference. This means we construct and destroy the_console_services() multiple times during server startup.
So, use a shared_ptr<> rather than a CachedPtr<> for console_services, leaving DefaultServerConfiguration to have an owning ref and guaranteeing single-construction.
This exposes a bug in `LogindConsoleServices`; the `Device` destructor did not actually release the logind device resulting in further attempts to acquire the device to error with an “already acquired” error; fixed by actually calling `ReleaseDevice` on `Device` destruction.
*That* exposed a deadlock in `GLibMainLoop::run_with_context_as_thread_default()` when called from …
> Ensure the_console_services() is constructed only once. 

- src/server/frontend_wayland/wayland_connector.cpp
[Wayland] creating a shell_surface should associate a role immediately. (Fixes #512)
> [Wayland] creating a shell_surface should associate a role immediately.

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
- src/server/frontend_xwayland/xwayland_wm_shellsurface.h
As the commit log says:
* made client private in `WindowWlSurfaceRole`, and switched to using `wayland::XdgSurfaceV6::client`
* stopped using `Shell`s where they weren't needed
* fixed an issue where we were not using the correct parent object (no change in behavior is detectable)
> More XDG shell cleanup

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
- src/server/frontend_wayland/xdg_shell_v6.h
- src/server/frontend_xwayland/xwayland_wm_shellsurface.cpp
- src/server/frontend_xwayland/xwayland_wm_shellsurface.h
Stacked on top of #515 
Made `XdgToplevelV6` and `XdgPopupV6` inherent from `WindowWlSurfaceRole` (`XdgSurfaceV6` used to inherit from it). Some advantages of this are:
* Eliminates the messy `notify_resize` `std::function` passing without the need of a new abstract class.
* Handles objects being destroyed more safely (this didn't seem to be a problem, but with the old system, it looked to me like there were some nasty segfault opportunists. They might not all be handled, but its definitely better)
* Matches what a surface role is in the protocol, specifically this, where I originally got the idea:
```
<request name="get_xdg_surface">
<description summary="create a shell surface from a surface">
This creates an xdg_surface for the given surface. While xdg_surface
itself is not a role, the …
```
> Made toplevels and popups window roles

- tests/miral/test_server.cpp
#including `null_logger.h` wasn't working, so I just copied it.
> Suppressed logging in Miral tests

- src/platforms/mesa/server/kms/display.cpp
- tests/unit-tests/platforms/mesa/kms/test_display.cpp
The ConsoleServices implementation now ensures DRM master is acquired upon resume and
dropped upon suspend; trying to do so again will result in failures in drmDropMaster.
> mesa-kms: Don't try to manage drmMaster

- src/client/mir_connection.cpp
- src/server/frontend_wayland/wl_keyboard.cpp
With #532 and this I can run the example shells and only see "-fsanitize=function" errors (mostly from function-signature punning in libmirclient).
> Fix a couple of ubsan error reports

- debian/libmiral3.symbols
- examples/miral-shell/shell_main.cpp
- include/miral/miral/wayland_extensions.h
- src/include/platform/mir/options/configuration.h
- src/miral/CMakeLists.txt
- src/miral/symbols.map
- src/miral/wayland_extensions.cpp
- src/platform/options/default_configuration.cpp
- src/platform/symbols.map
- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wayland_connector.h
- src/server/frontend_wayland/wayland_default_configuration.cpp
This provides a foundation for future development.
But this is likely to gain complexity over time:
* A shell may want to validate the selected extensions.
* Some extensions may be mutually incompatible.
* We may want to change the default from "enable everything".
> Provide a configuration mechanism for enabling the supported Wayland extensions

- src/server/server.cpp
We must not extend the life of the main loop when stopping the server. (Fixes #543)
> Fix racy shutdown

- src/platforms/mesa/server/x11/input/input_platform.cpp
My systems have various peculiarities, so ideally someone would verify this doesn't break keyboard grabbing on miral shell before landing. (Fixes #549)
> Fixed keyboard grab issue on Arch

- src/platforms/evdev/fd_store.cpp
- src/platforms/evdev/fd_store.h
- src/platforms/evdev/libinput_ptr.cpp
- src/platforms/evdev/platform.cpp
- src/server/console/linux_virtual_terminal.cpp
This fixes a number of bugs in VT switching, and add some paranoia that will hopefully make us fail in a more easily-recoverable fashion if we fail.
> Fix VT switching with LinuxVirtualTerminal

- tests/miral/test_server.cpp
Nothing good can come of probing or, worse, loading a real ConsoleServices implementation.
> miral::TestDisplayServer: Use NullConsoleServices.

- src/platforms/mesa/server/kms/cursor.cpp
- src/platforms/mesa/server/kms/cursor.h
[mesa] Use both id and drm_fd as output identifier as we're not sure of the uniqueness of either. (Fixes #556)
> [mesa] Use both id and drm_fd as output identifier as we're not sure of the uniqueness of either. (Fixes #556)

- include/platform/mir/console_services.h
- include/server/mir/input/composite_event_filter.h
- src/include/server/mir/default_server_configuration.h
- src/include/server/mir/input/vt_filter.h
- src/platforms/evdev/platform.cpp
- src/server/console/CMakeLists.txt
- src/server/console/ioctl_vt_switcher.cpp
- src/server/console/ioctl_vt_switcher.h
- src/server/console/linux_virtual_terminal.cpp
- src/server/console/linux_virtual_terminal.h
- src/server/console/logind_console_services.cpp
- src/server/console/logind_console_services.h
- src/server/console/null_console_services.h
- src/server/default_server_configuration.cpp
- src/server/input/default_configuration.cpp
- src/server/input/event_filter_chain_dispatcher.cpp
- src/server/input/event_filter_chain_dispatcher.h
- src/server/input/vt_filter.cpp
- src/server/server.cpp
- tests/include/mir/test/doubles/null_console_services.h
- tests/include/mir/test/doubles/stub_console_services.h
- tests/mir_test_doubles/stub_console_services.cpp
- tests/unit-tests/console/test_logind_console_services.cpp
- tests/unit-tests/graphics/test_platform_prober.cpp
Add a `VTSwitcher` interface that can be provided by `ConsoleServices`, implement it for `LogindConsoleServices` and `LinuxVirtualTerminal`, and then use it in the `input::VTFilter` to switch VTs, rather than directly opening `/dev/tty0` and frobbing it.
Fixes #459.
> LogindConsoleServices: Support VT switching

- src/server/shell/abstract_shell.cpp
- tests/miral/active_window.cpp
Parents of the active window should also have focus. (Fixes #522)
> Parents of the active window should also have focus. (Fixes #522)

- src/platforms/mesa/server/kms/real_kms_output.cpp
Disconnected hardware has no modes: invent a (slow) refresh rate. (Fixes #587)
> Disconnected hardware has no modes: invent a (slow) refresh rate. (Fixes #587)

- examples/example-server-lib/sw_splash.cpp
- src/server/frontend_wayland/output_manager.cpp
[Wayland] Remove hard coded values for output geometry (screen orientation and pixel arrangement). (Fixes #601)
> [Wayland] Remove hard coded values for output geometry (screen orientation and pixel arrangement). (Fixes #601)

- tests/CMakeLists.txt
This check was incorrectly using the Debian package name (`libgtest-dev`) instead of the RPM package name (`gtest-devel`). Fixing this check makes Mir build properly against Google Test 1.8.1.
Signed-off-by: Neal Gompa <ngompa13@gmail.com>
> tests: Use the correct package name to detect gtest on RPM distributions

- src/gl/tessellation_helpers.cpp
- src/include/gl/mir/gl/primitive.h
- src/renderers/gl/renderer.cpp
- tests/unit-tests/renderers/gl/test_gl_renderer.cpp
This code is here to support features that have never been started. It's
not very useful!
> Remove some dead code from gl::Renderer.

- tests/include/mir/test/barrier.h
Barrier contains a std::mutex, which is a non-copyable type, so the `= default` CopyAssign
we have is effectively an `= delete`. Make this explicit.
Caught by Clang 8.0
> mt::Barrier: Drop invalid defaulted CopyAssign.

- examples/miral-shell/spinner/CMakeLists.txt
- src/server/CMakeLists.txt
- src/server/console/CMakeLists.txt
- src/server/input/CMakeLists.txt
- tests/mir_test_framework/CMakeLists.txt
- tests/umock-acceptance-tests/CMakeLists.txt
- tests/unit-tests/CMakeLists.txt
- tests/unit-tests/platforms/mesa/kms/CMakeLists.txt
- tests/unit-tests/platforms/mesa/x11/CMakeLists.txt
Fix FTBFS on Fedora 29 caused by glib's variadic macros.
Unfortunately this doesn't seem fixable by wrapping the glib headers
with #pragma, "-Wno-variadic-macros" needs to be applied to the whole
translation unit.
> Fix FTBFS on Fedora 29 caused by glib's variadic macros.

- src/common/posix_rw_mutex.cpp
Don't call pthread_rwlockattr_setkind_np() on systems where it is not defined.
(One of the Musl build issues.)
> Don't call pthread_rwlockattr_setkind_np() on systems where it is not defined.

- src/miral/basic_window_manager.cpp
I've seen some weird focus behaviour the most obvious case being when there is a single application in egmde and pressing Alt-Tab.
I tracked this down to this code: the problem is less obvious in miral-shell because egmde doesn't use workspaces and skips the initial loop (which masks the broken logic).
(I hope reviewers consider the lack of tests to be "pre-existing" as setting up a test fixture for this code is more work than I have headspace for today.)
> Clarify and fix focus switching logic.

- src/platform/graphics/platform_probe.cpp
- src/server/console/minimal_console_services.cpp
- tests/unit-tests/console/test_minimal_console_services.cpp
When probing platforms we can (depending on the order mesa-kms and mesa-x11 are
probed - they both return "supported") select mesa-kms despite X11 owning DRM master. (Fixes #644)
Unsurprisingly, mesa-kms does not work without DRM Master.
> Do not select mesa-kms when Xorg owns DRM master

- src/core/anonymous_shm_file.cpp
if not raw_fd will only be set inside if's scope, once outside if's
scope it will use the raw_fd set by memfd_create
> Make sure we set raw_fd outside of the if's scope

- include/platform/mir/graphics/program_factory.h
- src/renderers/gl/renderer.cpp
- src/renderers/gl/renderer.h
This looks nicer, makes it possible for shaders to use more than the 3 textures we were defining.
As an added benefit, all our *existing* shaders don't notice, as looking up the uniform location for `tex[0]` resolves to the attribute location for `tex`.
> mg::ProgramFactory: Use a uniform array of textures, rather than tex, tex1, tex2

- src/server/console/minimal_console_services.cpp
- tests/unit-tests/console/test_minimal_console_services.cpp
The original fix for #644 was acknowledged to be ugly. Upstream libdrm didn't have a
drmIsMaster() function which is what would be necessary to make a proper fix.
Import the `drmIsMaster()` call from https://lists.freedesktop.org/archives/dri-devel/2018-November/196972.html and use it
to make a proper fix.
> MinimalConsoleServices: Better check for DRM master.

- debian/control
- debian/rules
- spread/build/ubuntu/task.yaml
- tests/unit-tests/platforms/eglstream-kms/server/test_utils.cpp
This simplifies the mess of nvidia dependencies by depending
on something that exists in the PPA for *all* our supported
releases and on all our supported architectures.
> Debian packaging: Depend on libnvidia-egl-wayland-dev

- .travis.yml
- spread.yaml
- spread/build/fedora/task.yaml
Upgrading proved to be unreliable, on the google provider we can use a
pre-built rawhide image instead.
There is now a Fedora 29 image, too, so use it.
Also reduce the spread timeout so it fits under travis's one.
> [spread] fix fedora rawhide and add 29

- examples/miral-shell/spinner/miregl.cpp
There's no need to reject EGL 1.5 here.
Since the NVIDIA driver now supports 1.5, this causes the spinner
to bail on startup on the eglstream-kms platform. (Fixes #661)
> miral/eglapp: Accept EGL versions ≥ 1.4

- examples/example-server-lib/decoration_provider.cpp
- examples/example-server-lib/decoration_provider.h
- examples/example-server-lib/floating_window_manager.cpp
This simplifies the DecorationProvider code. (The mirclient API based "titlebar" logic ignores Wayland clients anyway).
We need to follow up with something similar to #666: This is the final "internal clients" needing to be migrated from the mirclient API to Wayland.
(Needed to function on Nvidia as mirclient API doesn't work on Nvidia.)
> Strip out legacy titlebar logic

- examples/example-server-lib/decoration_provider.cpp
- examples/example-server-lib/decoration_provider.h
- examples/example-server-lib/wayland_helpers.cpp
- examples/example-server-lib/wayland_helpers.h
This fixes the background when the screen is rotated left or right:
miral-app
(in the session)
mirout output 1 rotate left
The client wasn't receiving notifications of output reconfiguration because it wasn't running an event loop.
> [miral-shell] DecorationProvider: Respond to output events

- src/platforms/eglstream-kms/server/platform_symbols.cpp
`glGetString(GL_VERSION)` requires a current context bound.
We should actually bind a current context before calling it!
> eglstreams-kms: Fix NVIDIA driver version detection.

- src/platforms/eglstream-kms/server/platform_symbols.cpp
- src/platforms/mesa/server/display_helpers.cpp
- src/platforms/mesa/server/kms/platform_symbols.cpp
- tests/include/mir/test/doubles/mock_drm.h
- tests/mir_test_doubles/mock_drm.cpp
- tests/unit-tests/platforms/mesa/kms/test_display.cpp
- tests/unit-tests/platforms/mesa/kms/test_platform.cpp
If the NVIDIA drivers are in use, but the experimental KMS support is not enabled,
the eglstream-kms driver would still bind to the device as the EGL implementation
claims to support everything we need.
Check explicitly for modesetting support on the node we're planning to use, so
we can fall back to something that might work. (Fixes: #672)
> {eglstream,mesa}-kms: Ensure queried nodes actually support modesetting.

- tests/privileged-tests/ui_get_sysname_ioctl_override.cpp
Support libcs with POSIX ioctl arguments
POSIX defines ioctl() with an int request parameter, while glibc uses unsigned long.
> Don't hardcode request type for ioctl()

- src/server/console/CMakeLists.txt
- src/server/frontend_wayland/generator/CMakeLists.txt
Stop deleting generated Wayland and dbus protocol files in a `make clean`, replaces #690.
> Dont clean generated files (better)

- src/common/sharedlibrary/CMakeLists.txt
- src/common/sharedlibrary/shared_library.cpp
Yet another fix for the musl dlvsym problem, alternative to #683, #687 and #698
* Uses cmake and an #ifdef to remove dlvsym
* Defaults to using dlvsym if anything goes wrong in the build system
* Puts the ifdef right where the function is called
* Uses the `load_symbol(function_name)` method for minimal redundancy
> William enters the dlvsym fray

- tests/unit-tests/shared_library_test.cpp
This looks a workaround that became obsolete some time in the last five years.
> Use the gmock HasSubstr matcher instead of a weird, broken, home grown alternative.

- src/platforms/mesa/server/kms/platform_symbols.cpp
Make it possible to disable probing for KMS on platforms where drmCheckModesettingSupported() is unreliable. (Workaround for #704)
> Make it possible to disable probing for KMS on platforms where drmCheckModesettingSupported() is unreliable.

- tests/test-clients/mir-stress/src/mir-stress.cpp
- tests/test-clients/mir-stress/src/threading.cpp
- tests/test-clients/mir-stress/src/threading.h
Make it possible to run `mir_stress` with `mir_demo_server --test-client`. (Fixes #709)
This is needed for running this `mir_stress` test as part of the `mir-test-tools` snap.
> Make it possible to run `mir_stress` with `mir_demo_server --test-client`. (Fixes #709)

- examples/example-server-lib/CMakeLists.txt
- examples/example-server-lib/decoration_provider.cpp
- examples/example-server-lib/wallpaper_config.cpp
- examples/example-server-lib/wallpaper_config.h
- examples/mir_demo_server/server_example.cpp
- examples/miral-shell/shell_main.cpp
This will be useful for snapping up the mir-test-tools (as a confined snap cannot access the installed fonts)
> Provide config option for wallpaper font in mir_demo_shell

- cmake/MirCommon.cmake
- tests/acceptance-tests/wayland/CMakeLists.txt
- tools/discover_gtests.sh
Since the wlcs binary requires the integration library as a command line parameter we need to
fiddle with the test discovery harness.
> Split out wlcs tests in `make ptest`

- examples/mir_demo_server/server_example_test_client.cpp
Delete misleading comment and simplify the code around it.
> Simplify code

- tests/acceptance-tests/wayland/miral_integration.cpp
Relying on the `WLCS_*_VERSION` macros is dangerous; supporting a new version will almost
always require sourceful changes, rather than just rebuilding against new headers.
> WLCS Integration: Explicitly set the version we support.

- src/platforms/mesa/server/display_helpers.cpp
- src/platforms/mesa/server/kms/display_buffer.cpp
`GBM_FORMAT_XRGB8888` is semantically the same, and the Mali gbm only
supports the non-deprecated `GBM_FORMAT_…` enums.
Closes: #606
> mesa-kms: Switch from deprecated GBM_BO_FORMAT_… enums.

- src/platforms/mesa/server/kms/platform_symbols.cpp
- tests/unit-tests/platforms/mesa/kms/test_platform.cpp
We were checking for the EGL_MESA_platform_gbm extension, an old pre-standardisation version of
the GBM platform extension. Some drivers (hello, Mali!) support EGL_KHR_platform_gbm but not
the Mesa-namespaced version, so preferentially check for the KHR standard extension.
Fixes: #600
> mesa-kms: Check for EGL_KHR_platform_gbm extension.

- src/platforms/mesa/server/kms/display_buffer.cpp
- src/platforms/mesa/server/kms/real_kms_output.cpp
- tests/include/mir/test/doubles/mock_drm.h
- tests/mir_test_doubles/mock_drm.cpp
Use `drmGetPrimaryDeviceNameFromFd()` on both the GBM device and the DRM
device we plan to output to; in the single GPU case these should match,
in the hybrid case they may differ and so we need to migrate the
rendering.
Simply comparing the `drm_fd_` and `gbm_device_get_fd()` return values
is unreliable - there's no guarantee that `gbm_create_device()` won't
internally `dup()` the DRM file descriptor passed in.
Likewise, checking whether both file descriptors point to the same file
is unreliable - `gbm_create_device()` may choose to open a different
file (specifically, the rendernode associated with the DRM node passed
in).
Comparing the primary device nodes for both file descriptors *should* be
reliable.
Closes: #607
> mesa-kms: More rigorously detect hybrid GPU setups.

- include/platform/mir/graphics/egl_extensions.h
- include/test/mir/test/doubles/mock_egl.h
- src/platform/graphics/egl_extensions.cpp
- src/platform/symbols.map
- src/platforms/mesa/server/buffer_allocator.cpp
- src/platforms/mesa/server/kms/egl_helper.cpp
- src/platforms/mesa/server/kms/egl_helper.h
- tests/mir_test_doubles/mock_egl.cpp
- tests/unit-tests/graphics/test_platform_prober.cpp
- tests/unit-tests/platforms/mesa/kms/test_display.cpp
- tests/unit-tests/platforms/mesa/kms/test_platform.cpp
This lets us explicitly ask for a GBM-backed EGL platform, rather than just hoping
the libEGL can correctly guess what we've handed in is a pointer to a `gbm_device`.
This is necessary for Mali support, as Mali's libEGL will *not* guess that what
you've passed in to `eglGetDisplay()` is a `gbm_device*`.
> mesa-kms: Use EGL_EXT_platform_base.

- src/platforms/mesa/server/display_helpers.cpp
- src/platforms/mesa/server/kms/platform_symbols.cpp
- tests/unit-tests/platforms/mesa/kms/test_platform.cpp
`drmCheckModesettingSupported()` requires a (PCI) BusID to query. Some
devices (such as the RPi3) the DRM device isn't actually hooked up to a
PCI bus, so we can't make this check.
Handle this case by making failure in `drmCheckModesettingSupported()`
non-fatal.
Closes: #704
> mesa-kms: Handle failure to detect KMS in platform probe.

- src/miral/basic_window_manager.cpp
- src/miral/mru_window_list.cpp
- tests/miral/mru_window_list.cpp
Restore minimized windows when they receive input focus. (Fixes: #305)
>   Restore minimized windows when they receive input focus

- include/server/mir/shell/abstract_shell.h
- src/server/shell/abstract_shell.cpp
- tests/mir_test_framework/basic_window_manager.cpp
Change the behaviour of AbstractShell::focus_next_session() to not notify clients. (Fixes: #742)
But preserve the obsolete behaviour in BasicWindowManager::focus_next_session() used in some old tests.
Note that this shouldn't affect Unity8 as that implements its own focus behavior.
> Change the behaviour of AbstractShell::focus_next_session() to not notify clients

- src/server/scene/basic_surface.cpp
- src/server/scene/basic_surface.h
- tests/unit-tests/scene/test_basic_surface.cpp
Fixes #735. Not the direction we discussed, but real easy and it looks to me like it's somewhat correct
> Check that the buffer stream has a buffer before setting cursor

- examples/miral-shell/miral-app.sh
This is useful when testing features that only mir_demo_server exposes
> Add an undocumented option to miral-app to run mir_demo_server

- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
Fixes #674. Check to make sure the window has a non-zero size before modifying the surface.
> Check for zero size Windows in WindowWlSurfaceRole

- tests/acceptance-tests/wayland/CMakeLists.txt
Tests added in https://github.com/MirServer/wlcs/pull/85, https://github.com/MirServer/wlcs/pull/86 and https://github.com/MirServer/wlcs/pull/87 should land in WLCS and be enabled, but will not pass in Mir. This disables them with GTest options in CMake as suggested by @RAOF.
> Disable new WLCS tests that wont pass in Mir

- CMakeLists.txt
By "chance", the current protocols pass the check, but they shouldn't be checked.
Other protocols (e.g. KWin's "server-decoration" protocol) would fail.
(As a byproduct, this also cleans up some wlcs submodule legacy.)
> Don't "GPL-required" check protocols

- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
- src/server/frontend_xwayland/xwayland_wm.cpp
This improves the listen sockets
X11 should now work without need for lazy override
I also moved lazy to use the listen sockets mir creates
> XWayland: Improve listen/x-client sockets

- include/server/mir/frontend/buffer_stream.h
- src/server/compositor/stream.cpp
- src/server/compositor/stream.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/scene/application_session.cpp
- src/server/scene/basic_surface.cpp
- tests/include/mir/test/doubles/mock_buffer_stream.h
- tests/include/mir/test/doubles/stub_buffer_stream.h
- tests/unit-tests/compositor/test_stream.cpp
- tests/unit-tests/scene/test_surface.cpp
A `BufferStream`'s size is now just the size of the most recent buffer (or the initial size sent to the constructor, if there is no buffer yet). This simplifies the code, fixes #604, and the non-atomic resize problem noted in a TODO in wl_surface.cpp.
> Remove `BufferStream::resize()`

- src/miral/static_display_config.cpp
Use function 'std::abs' (not '::abs') for double parameter. (Fixes #770)
> Use function 'std::abs' (not '::abs') for double parameter.

- src/server/symbols.map
Additional symbol needed for g++8.3/ld/Alpine. (Fixes #771)
> Additional symbol needed for g++8.3/ld/Alpine

- debian/libmiral3.symbols
- include/miral/miral/wayland_extensions.h
- src/miral/symbols.map
- src/miral/wayland_extensions.cpp
- tests/miral/wayland_extensions.cpp
Make it easy to "do the right thing" with WaylandExtensions.
That is adding and enabling an extension (which is the common case).
> Make it easier to "do the right thing" with WaylandExtensions.

- src/wayland/generated/wayland_wrapper.cpp
- src/wayland/generated/wayland_wrapper.h
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.cpp
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.h
- src/wayland/generated/xdg-shell-unstable-v6_wrapper.cpp
- src/wayland/generated/xdg-shell-unstable-v6_wrapper.h
- src/wayland/generated/xdg-shell_wrapper.cpp
- src/wayland/generated/xdg-shell_wrapper.h
- src/wayland/generator/interface.cpp
- src/wayland/generator/interface.h
Provide a way to identify the type of a wl_resource.
This is one small piece of providing `convert(resource) -> Window`
> Add is_instance() to wrapper types

- include/miral/miral/wayland_extensions.h
- src/miral/wayland_extensions.cpp
Put the WaylandExtensions(string) constructor back the way it was in 1.1.
While adding support for "bespoke" Wayland extensions we widened the contract to permit "bespoke" extensions to be specified here. But since #775 that's no longer the way to do it and we should revert this change.
> Put the WaylandExtensions(string) constructor back the way it was in 1.1

- debian/control
- spread/build/fedora/task.yaml
- src/server/report/lttng/CMakeLists.txt
Userspace Statically Defined Tracepoints are approximately zero-cost (the introduce a single
noop into the codestream + some ELF metadata in the DSO) and can be consumed with various
tracing frameworks, most notably ftrace & bpftrace.
LTTNG has support for generating a USDT for each LTTNG tracepoint, but only if such support is enabled.
> LTTNG: Generate USDT tracepoints from LTTNG tracepoints.

- src/server/report/lttng/CMakeLists.txt
This reverts commit f50906dcb7842f454b9dd8d01f2dae8f76dd7607.
Turns out that CI doesn't pick up this ICE, as it's only on 16.04 PPA builds,
Fixes: #790
> Revert "Try dropping workaround for gcc ICE"

- src/server/report/lttng/compositor_report_tp.h
- src/server/report/lttng/input_report_tp.h
- src/server/report/lttng/scene_report_tp.h
Another tiny one; LTTng recommend combining events with the same fields into a tracepoint-class and then instantiating tracepoint-instances.
> Use LTTng best practices

- src/miral/internal_client.cpp
Ensure internal clients don't hang because of queued requests. (Fixes #753)
> Ensure internal clients don't hang because of queued requests

- src/server/frontend_xwayland/xwayland_server.cpp
Make sure Xwayland exits to ensure a clean shutdown. (Fixes: #796)
> Make sure Xwayland exits to ensure a clean shutdown

- src/platforms/mesa/server/x11/X11_resources.cpp
- src/platforms/mesa/server/x11/X11_resources.h
- src/platforms/mesa/server/x11/graphics/display.cpp
- src/platforms/mesa/server/x11/graphics/display.h
- src/platforms/mesa/server/x11/graphics/display_buffer.cpp
- src/platforms/mesa/server/x11/graphics/display_buffer.h
- src/platforms/mesa/server/x11/graphics/display_configuration.cpp
- src/platforms/mesa/server/x11/graphics/display_configuration.h
- src/platforms/mesa/server/x11/graphics/graphics.cpp
- src/platforms/mesa/server/x11/graphics/platform.cpp
- src/platforms/mesa/server/x11/graphics/platform.h
- src/platforms/mesa/server/x11/input/input.cpp
- src/platforms/mesa/server/x11/input/input_platform.cpp
- tests/unit-tests/platforms/mesa/x11/test_display.cpp
- tests/unit-tests/platforms/mesa/x11/test_display_generic.cpp
- tests/unit-tests/platforms/mesa/x11/test_graphics_platform.cpp
- tests/unit-tests/platforms/mesa/x11/test_platform.cpp
Enhance the `--x11-output` option to support a colon separated list of output sizes. Outputs are lined up horizontally from Mir's perspective, and are each shown in a different X11 window. Useful if you need to test multi-output code paths and do not have auxiliary physical display handy.
> Support multi-output in Mir-onX

- .travis.yml
Rawhide builds are failing: "Package 'glesv2', required by 'virtual:world', not found".
Disable rawhide builds until we have a fix.
> Disable rawhide builds in CI (until we have a fix)

- src/server/input/key_repeat_dispatcher.cpp
- src/server/input/key_repeat_dispatcher.h
Don't lock KeyRepeatDispatcher::repeat_state_mutex unnecessarily in a callback. (Fixes #818)
> Don't lock KeyRepeatDispatcher::repeat_state_mutex unnecessarily

- src/server/shell/abstract_shell.cpp
Ensure an already focussed surface really gets input focus. (Fixes #823)
> Ensure an already focussed surface really gets input focus

- src/miral/wayland_extensions.cpp
- src/server/frontend_wayland/wayland_default_configuration.cpp
I originally incorrectly used `zxdg_output_v1` as the name for the XDG output interface. This is a name of the object in the interface, but not the global object, which is used by everything else.
> Rename zxdg_output_v1 -> zxdg_output_manager_v1

- src/server/frontend_wayland/wl_surface.cpp
We want to use `wl_resource_post_event()` (which is what is generated for
`wl_buffer_send_release()` by wayland-scanner), as this marks the connection
as flushable (ie: we want the client to receive this event now).
We want the release events to make it to the client ASAP, so they can act
on it.
> Wayland: Eagerly send buffer release events.

- src/miral/minimal_window_manager.cpp
When the user clicks on an unfocused window, the window gets focus. We were not also sending that click event through to the client, and with this PR we are. I believe this is a better UX, and it fixes a layer-shell bug where unforeseeable windows could not be clicked. Most importantly, it is the standard behavior in other desktops (tested on Gnome Wayland and MacOS).
EDIT: to test:
* Open two windows next to each other
* Click in the unfocused one
* Note that it becomes focused, and also the click action happens (menu opens, icon is selected, whatever)
> Allow unfocused windows to receive mouse down events

- tests/acceptance-tests/test_client_authorization.cpp
Avoid hanging server used by ClientCredsTestFixture.session_authorizer_receives_pid_of_connecting_clients during TearDown(). (Fixes: #852)
> Avoid hanging server used by ClientCredsTestFixture.session_authorizer_receives_pid_of_connecting_clients during TearDown()

- src/platforms/eglstream-kms/server/egl_output.cpp
- src/platforms/eglstream-kms/server/egl_output.h
We use mgek::EGLOutput with std::shared_ptr and std::vector.
We may not throw from the destructor when used with the standard library.
Therefore: Make mgek::EGLOutput::~EGLOutput() noexcept. (Might "fix" #858, or expose an underlying issue.)
> Make mgek::EGLOutput::~EGLOutput() noexcept

- include/test/mir_test_framework/process.h
- tests/mir_test_framework/process.cpp
Mitigate racy code in multi-process based tests:
1. Give a stronger hint to the scheduler that "something else" should run; And,
2. Use a longer timeout before giving up
Hopefully this will reduce the incidence of #863.
NB This change should be safe to land empirically as:
1. It doesn't touch production code; and,
2. It only affects failing tests
(Most of the tests affected are based on the mirclient API, so we can anticipate the better fix of "delete the racy test".)
> Mitigate racy code in multi-process based tests

- tests/miral/CMakeLists.txt
- tests/miral/depth_layer.cpp
- tests/miral/display_reconfiguration.cpp
- tests/miral/drag_active_window.cpp
- tests/miral/modify_window_specification.cpp
- tests/miral/modify_window_state.cpp
- tests/miral/output_updates.cpp
- tests/miral/raise_tree.cpp
- tests/miral/select_active_window.cpp
- tests/miral/test_window_manager_tools.cpp
- tests/miral/test_window_manager_tools.h
- tests/miral/window_placement.cpp
- tests/miral/window_placement_anchors_to_parent.cpp
- tests/unit-tests/scene/test_mediating_display_changer.cpp
Forgot to PR this earlier. This moves the implementation of `TestWindowManagerTools` to a new `test_window_manager_tools.cpp` file. It also moves `TestWindowManagerTools` into the `mir::test` namespace and adds tests for output updates. I needed similar tests for application zones, so I thought I'd add outputs as well.
> Refactor TestWindowManagerTools and add output tests

- debian/libmiral3.symbols
- examples/example-server-lib/tiling_window_manager.cpp
- examples/example-server-lib/tiling_window_manager.h
- include/miral/miral/window_management_policy.h
- include/miral/miral/zone.h
- src/miral/CMakeLists.txt
- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- src/miral/symbols.map
- src/miral/window_management_policy.cpp
- src/miral/window_management_trace.cpp
- src/miral/window_management_trace.h
- src/miral/zone.cpp
- tests/miral/CMakeLists.txt
- tests/miral/application_zone.cpp
- tests/miral/output_updates.cpp
- tests/miral/test_window_manager_tools.h
- tests/miral/zone.cpp
Adds a new `Zone` class to miral and updates about application zones. These are the areas we talked about which maximized windows will fill. Right now there is one application zone per output and each covers the entire area of its output, but they will shrink to accommodate exclusive zones when layer shell is implemented. On top of #855
> Application zone

- src/server/compositor/multi_monitor_arbiter.cpp
- tests/unit-tests/compositor/test_multi_monitor_arbiter.cpp
This doesn't fix any bug we've seen in the wild, it's just to make the code more readable and correct. The code was clearly wrong before (clearing current_buffer_users without advancing the buffer) but the case where that would manifest as a bug is obscure. I captured such a situation in the 2nd test I add, which works as follows:
Compositor A acquires a buffer
Compositor B acquires the same buffer
Compositor A acquires the buffer again
A new buffer is added to the schedule
Compositor B tries to acquire
What should happen (and does with this PR) is the new buffer is returned. With the old code current_buffer_users had been cleared in step 3 and only A had been added back, so the schedule would not advance and the old buffer would be returned.
> Comment, refactor and fix minor logic error in MultiMonitorArbiter

- src/wayland/CMakeLists.txt
Fix INCLUDEDIR for the mirwayland.pc file. (Fixes #873)
> Fix includes specified by mirwayland.pc

- src/server/compositor/multi_monitor_arbiter.cpp
- src/server/compositor/multi_monitor_arbiter.h
A `std::set<>` is highly likely to be backed by some form of tree structure. While that's got better
asymptotic behaviour than a linear search through a vector, we're extremely unlikely to have more
than 10 outputs here, and the common case is *1* output.
There are other microöptimisations here - a SmallVec would be an obvious choice - but just do
the simplest thing because I haven't done any benchmarking ☺
> Better data structure for MultiMonitorArbiter::current_buffer_users.

- debian/libmircommon-dev.install
- src/common/CMakeLists.txt
- src/common/mircommon.pc.in
- src/platform/mirplatform.pc.in
- src/wayland/mirwayland.pc.in
Add a package config file for mircommon and reference it mirwayland and mirplatform. (Fixes: #868)
> Add a package config file for mircommon

- src/server/frontend_wayland/data_device.cpp
- src/wayland/generated/wayland_wrapper.cpp
- src/wayland/generated/wayland_wrapper.h
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.h
- src/wayland/generated/xdg-output-unstable-v1_wrapper.h
- src/wayland/generated/xdg-shell-unstable-v6_wrapper.h
- src/wayland/generated/xdg-shell_wrapper.h
- src/wayland/generator/interface.cpp
- src/wayland/generator/interface.h
- src/wayland/generator/wrapper_generator.cpp
[Wayland] Add a constructor-from-parent for objects that can be server-constructed. (Fixes: #871)
> wayland/generator: Add a constructor-from-parent for objects that can be server-constructed

- src/miral/CMakeLists.txt
- src/miral/check-and-update-debian-symbols.py
Before CMake would call `dpkg-gensymbols` and spit out a warning if the symbols were wrong. Now, it calls a new python script that checks, transforms them into C++ symbols and automatically adds them to the debian symbols file.
> Auto update debian symbols

- src/server/frontend_wayland/output_manager.cpp
- src/server/frontend_wayland/output_manager.h
- src/server/frontend_wayland/wayland_connector.cpp
Wayland: process output update notifications on the correct thread. (Fixes: #886)
> Wayland: process output update notifications on the correct thread

- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- tests/miral/CMakeLists.txt
- tests/miral/initial_window_placement.cpp
- tests/miral/popup_window_placement.cpp
It may be useful to review this commit-by-commit. This fixes #899 by simply removing the code that tries to position parent-less windows relative to existing windows of the same application. In some cases the old behavior may be desirable, but `BasicWindowManager` is too complex already to continue adding support for complex unneeded features. If in the future we build a more modular, abstracted and generally better engineered window manager, we can think about reintroducing such features. Also, the old behavior was untested, so it must not have been *that* important.
> Do not place parentless windows relative to existing windows

- debian/libmiral3.symbols
- include/core/mir_toolkit/common.h
- include/miral/miral/window_info.h
- include/miral/miral/window_specification.h
- include/server/mir/scene/surface_creation_parameters.h
- include/server/mir/shell/surface_specification.h
- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- src/miral/symbols.map
- src/miral/window_info.cpp
- src/miral/window_specification.cpp
- src/server/frontend_wayland/layer_shell_v1.cpp
- src/server/scene/surface_creation_parameters.cpp
- src/server/shell/surface_specification.cpp
- tests/miral/CMakeLists.txt
- tests/miral/window_placement_attached.cpp
Add the `mir_surface_type_attached` window state, and two new properties to windows: `attached_edges` and `exclusive_rect`. These will be important for implementing layer surfaces. I still need to add tests, but I want to throw this up now so I can start getting feedback on it.
> Add mir_window_state_attached

- include/test/miral/test_display_server.h
- tests/acceptance-tests/wayland/miral_integration.cpp
- tests/mir_test_framework/test_display_server.cpp
- tests/mir_test_framework/test_wlcs_display_server.cpp
[wlcs test fixture] Configure wayland extensions. (Fixes #906)
1. Ensure all supported Wayland extensions are switched on by default.
2. Fix command-line processing so that `--wayland-extensions` can be used.
> [wlcs test fixture] Configure wayland extensions

- examples/example-server-lib/floating_window_manager.cpp
- include/core/mir/geometry/dimensions.h
- include/core/mir/geometry/displacement.h
- include/core/mir/geometry/size.h
- tests/miral/display_reconfiguration.cpp
Add a functions to make our ~over-engineered~ expressive and typesafe geometry system more usable. Hopefully this will get rid of randomly subtracting `Width{}` or `X{}` from everything in the expression until it compiles.
> Add missing geometry overloads and converters

- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- tests/miral/window_placement_attached.cpp
This adds support for exclusive zones to `BasicWindowManager`. We already have `exclusive_rect` property floating around. This PR uses it to shrink the application zones and the windows inside them. To accomplish this I had to reshuffle some calls, and move responsibility of placing attached surfaces into `update_windows_for_outputs()`.
> [MirAL]: Exclusive zones

- examples/example-server-lib/floating_window_manager.cpp
- src/server/frontend_wayland/layer_shell_v1.cpp
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
This implements the bulk of Layer Shell features:
* Anchors
* Depth layers
* Resizing
* Exclusive zones
Still needs WLCS tests, that will be my next mir related thing. You can test manually with gtk-layer-demo from [GTK Layer Shell](https://github.com/wmww/gtk-layer-shell).
> Make Layer Shell usable

- src/server/frontend_wayland/layer_shell_v1.cpp
- src/server/frontend_wayland/xdg_shell_stable.cpp
- src/server/frontend_wayland/xdg_shell_stable.h
Allow layer shell surfaces to make XDG popups.
If you desire to test you can do so with gtk-layer-demo from [GTK Layer Shell](https://github.com/wmww/gtk-layer-shell), though It's probably sufficient to just convince yourself it doesn't break XDG shell. WLCS tests will be ready at some point.
> Layer shell popups

- src/server/frontend_wayland/layer_shell_v1.cpp
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
As far as I know, the previous behavior wasn't causing any bugs. It was, however causing `modify_window()` to get called unnecessarily each frame in some cases (tested with wlroots/examples/simple). The reason was that `pending_window_size` wasn't getting set, so `committed_window_size` wasn't getting updated so it thought the size had changed each time. Now it correctly managers pending and current size, and keeps track of if the size has been set explicitly.
This entire system probably will need a rewrite at some point, but now is not the time.
> Wayland frontend: update window size more correctly

- tests/mir_test_framework/test_wlcs_display_server.cpp
Every time a new shell surface protocol is added, I forget to add it to the `is_window` list. That's all good and well, except the error gets eaten by Mir and I end up digging through GDB to solve the strange bug. This clarifies the error, and more importantly, actually shows it.
> Printf common WLCS integration error

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wayland_connector.h
- src/server/frontend_wayland/wayland_default_configuration.cpp
[Wayland] To accommodate GTK3 publish bespoke extensions before wl_seat. (Fixes #922)
> [Wayland] To accommodate GTK3 publish bespoke extensions before wl_seat

- src/client/rpc/mir_basic_rpc_channel.cpp
- src/include/common/mir/protobuf/display_server.h
- src/include/common/mir/protobuf/display_server_debug.h
Add header that needs to be explicitly included for protobuf 3.8. (Fixes #913)
> Fix FTBFS with protobuf 3.8

- src/server/frontend_wayland/layer_shell_v1.cpp
- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/server/frontend_wayland/wl_surface_event_sink.cpp
- src/server/frontend_wayland/xdg_shell_stable.cpp
- src/server/frontend_wayland/xdg_shell_stable.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
- src/server/frontend_xwayland/xwayland_wm_shellsurface.h
This PR is mostly to lay the groundwork for fixes to layer shell.
* It splits `WindowWlSurfaceRole::set_geometry()` into `::set_offset()`, `::set_width()` and `::set_height()`
* It has some fixes and simplification for how XDG surfaces send the `.configure` event
* It adds a new `WindowWlSurfaceRole::handle_commit()` virtual method, which will be needed by `LayerSurfaceV1`, but will also probably end up being useful for other things.
> Wayland frontend size management improvements

- examples/mir_demo_server/server_example_test_client.cpp
Don't assume we have a mir socket, because that's no longer true. (Fixes #927)
> Don't assume we have a mir socket, because that's no longer true

- src/client/event_printer.cpp
- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- src/miral/window_management_trace.cpp
- tests/miral/initial_window_placement.cpp
- tests/miral/window_placement_attached.cpp
Fixes and tests some logic around attached and maximized windows. The biggest part of the diff is the logic of `active_output()` being moved into the new `active_display_area()` (which `active_output()` then uses).
> Window manager: fix attached and maximized window placement

- examples/miral-shell/miral-run.sh
Fix miral-run to work without a Mir socket.
(If we didn't use this script in our documentation I'd just drop it.)
> Fix miral-run to work without a Mir socket

- src/server/frontend_wayland/layer_shell_v1.cpp
- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/server/frontend_wayland/wl_surface_event_sink.cpp
- src/server/frontend_wayland/xdg_shell_stable.cpp
- src/server/frontend_wayland/xdg_shell_stable.h
- src/server/frontend_wayland/xdg_shell_v6.cpp
- src/server/frontend_xwayland/xwayland_wm_shellsurface.h
- tests/mir_test_framework/test_wlcs_display_server.cpp
Correct layer shell behavior so that it passes the new WLCS tests. On top of #925.
> LayerShellSurface: configure correctly

- src/miral/wayland_extensions.cpp
Track registering miral::WaylandExtensions objects with mir::Servers and error if there is more than one. (Fixes #875)
> Track registering miral::WaylandExtensions objects with mir::Servers and error if there is more than one

- spread.yaml
`ubuntu-os-cloud/ubuntu-1910` [doesn't seem to be a thing](https://travis-ci.org/MirServer/mir/jobs/564109665)
> Remove ubuntu-1810 from spread.yaml

- include/miral/miral/window_specification.h
- include/server/mir/scene/surface_creation_parameters.h
- include/server/mir/shell/surface_specification.h
I prefer `///`. I thought `/** */` was standard in Mir, but I've been seeing more `///` comments and I don't want my relatively recent code to be part of the problem.
> Switch from /** */ comments to /// comments

- src/include/server/mir/scene/null_observer.h
- src/server/input/surface_input_dispatcher.cpp
- src/server/scene/legacy_surface_change_notification.cpp
- src/server/scene/legacy_surface_change_notification.h
- src/server/scene/null_observer.cpp
This makes it easier to add surface properties without changing a bunch of observers that don't care
> Use scene::NullObserver and scene::NullSurfaceObserver where it makes sense

- include/server/mir/scene/observer.h
- src/include/server/mir/scene/legacy_scene_change_notification.h
- src/include/server/mir/scene/null_observer.h
- src/server/input/cursor_controller.cpp
- src/server/input/surface_input_dispatcher.cpp
- src/server/input/surface_input_dispatcher.h
- src/server/scene/legacy_scene_change_notification.cpp
- src/server/scene/null_observer.cpp
- src/server/scene/surface_stack.cpp
- src/server/scene/surface_stack.h
- tests/unit-tests/input/test_cursor_controller.cpp
- tests/unit-tests/input/test_surface_input_dispatcher.cpp
- tests/unit-tests/scene/test_legacy_scene_change_notification.cpp
- tests/unit-tests/scene/test_surface_stack.cpp
We discussed earlier using `weak_ptr` instead of `shared_ptr`, but I decided that would require otherwise unnecessary locks and checks. It would always be safe to assume the given weak pointer would be valid during the notification calls, but then why not indicate that with a shared_ptr? I think its fine to pass share_ptrs around as long as we only store weak pointers.
> Send shared_ptr instead of raw surface pointer from scene::Observer

- include/server/mir/shell/window_management_info.h
- src/server/shell/window_management_info.cpp
- src/server/symbols.map
Which we inexplicably appear to have had in `msh::WindowManagementInfo`?
> Drop unused titlebar-rendering code

- examples/miral-shell/miral-app.sh
- examples/miral-shell/miral-desktop.sh
- examples/miral-shell/miral-run.sh
- examples/miral-shell/miral-xrun.sh
The "wayland" snap interface restricts the wayland endpoint to the form wayland-[0-9].
So replace using miral-wayland in the scripts with a name of that form.
> So replace using miral-wayland in the scripts with a name of the form wayland-[0-9]

- debian/libmiral3.symbols
- include/miral/miral/output.h
- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- src/miral/output.cpp
- src/miral/symbols.map
- tests/miral/window_placement_attached.cpp
Fixes the following issues:
* Fixes #953: Makes new fullscreen windows ignore exclusive zones
* Places windows correctly when they are fullscreened
* Adjusts maximized windows when an exclusive window becomes not attached
* Tests everything mentioned
> Exclusive zone fixes

- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wlshmbuffer.cpp
- src/server/frontend_wayland/wlshmbuffer.h
Appears to fix a longstanding crash. The Wayland debug feature I built to detect thread errors tells me this was the only instance of such a problem in Mir (at least in the standard features I've tested with). Fixes #951
> Send wl_buffer.release on the Wayland thread

- .travis.yml
We're seeing "GPG check FAILED" errors in CI.
Temporarily ignore the failing builds.
> Allow Fedora rawhides builds to fail

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wayland_utils.h
- src/server/frontend_wayland/wl_keyboard.cpp
- src/server/frontend_wayland/wl_keyboard.h
- src/server/frontend_wayland/wl_pointer.cpp
- src/server/frontend_wayland/wl_pointer.h
- src/server/frontend_wayland/wl_surface_event_sink.cpp
- src/server/frontend_wayland/wl_surface_event_sink.h
- src/server/frontend_wayland/wl_touch.cpp
- src/server/frontend_wayland/wl_touch.h
This probably wasn't really required, but I started fiddling with things and one thing lead to another. This moves all the code to unpack Mir events into `WlSurfaceEventSink` and out of the Wayland objects. It also generally breaks up the code into more logical chunks with better names and more type safety (ints are replaced by geometry types and chrono types where possible). I've tested the keyboard and mouse portions, but not touch. The WLCS touch tests pass even when I know it's broken (I should probably work on them at some point), so manual testing is needed. I'll comment when I've got it done building and tested on my under-powered touch machine.
My next PR will be changing the surface event sink to a surface observer, which cuts out large pieces of the Mir event system from the …
> Move wayland event unpacking to event sink

- src/server/frontend_wayland/CMakeLists.txt
- src/server/frontend_wayland/wayland_surface_observer.cpp
- src/server/frontend_wayland/wayland_surface_observer.h
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_xwayland/xwayland_wm_shellsurface.cpp
- src/server/scene/surface_event_source.cpp
Built on top of #966 
Replaces the event sink used for surfaces managed by the Wayland frontend with a surface observer.  The event system was presumably helpful in days gone by, but it doesn't provide any value for Wayland. Specifically I got rid of it now because it requires using surface IDs, which I'm removing from the Wayland frontend.
> Wayland use surface observers

- debian/control
- debian/libmirwayland-bin.install
- debian/libmirwayland-dev.install
This makes the PPA packaging match the Ubuntu archive packaging, and is necessary should anyone actually want to install `libmirwayland-dev` for multiple architectures (eg: using a cross-compiler)
> Split arch-specific part of libmirwayland-dev into a -bin package 

- src/miral/window_specification.cpp
- src/server/frontend_wayland/layer_shell_v1.cpp
This is a shot at #980 
While I know way to little to know if a lot of things are missing, it at least fixes the case described in #980
> Set output_id for LayerShell surfaces

- include/server/mir/observer_registrar.h
- src/include/server/mir/observer_multiplexer.h
- tests/unit-tests/test_observer_multiplexer.cpp
It would be very convenient when reasoning about code if `unregister_interest()`
guaranteed that once it returned no further calls to the observer would be
made.
This comes at the cost of preventing multiple observations to be made in parallel. This shouldn't be too much of a problem, as our existing `Executor`s - `GLibMainLoop` and `WaylandExecutor` - are single-threaded and so can't have multiple observations executing at once anyway.
> ObserverMultiplexer: Make unregister_interest deterministic

- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- tests/miral/CMakeLists.txt
- tests/miral/depth_layer.cpp
- tests/miral/display_reconfiguration.cpp
- tests/miral/drag_active_window.cpp
- tests/miral/initial_window_placement.cpp
- tests/miral/modify_window_specification.cpp
- tests/miral/modify_window_state.cpp
- tests/miral/popup_window_placement.cpp
- tests/miral/raise_tree.cpp
- tests/miral/select_active_window.cpp
- tests/miral/test_window_manager_tools.cpp
- tests/miral/window_placement_anchors_to_parent.cpp
- tests/miral/window_placement_attached.cpp
- tests/miral/window_placement_fullscreen.cpp
This fixes and tests a bunch of subtle bugs related to attached and fullscreen windows on specific outputs. Fixes problems with #982.
> Clean up and test attached windows on outputs

- src/server/report/lttng/lttng_report_factory.cpp
```
Fix these errors with boost 1.71.0:
/home/pmos/build/src/mir-1.1.2/src/server/report/lttng/lttng_report_factory.cpp:67:5:
error: use of undeclared identifier 'BOOST_THROW_EXCEPTION'
BOOST_THROW_EXCEPTION(std::logic_error("Not implemented"));
^
/home/pmos/build/src/mir-1.1.2/src/server/report/lttng/lttng_report_factory.cpp:77:5:
error: use of undeclared identifier 'BOOST_THROW_EXCEPTION'
BOOST_THROW_EXCEPTION(std::logic_error("Not implemented"));
```
This patch was written against mir-1.1.2 (as one can see in the commit message). However, the header is still missing in master.
> Add missing throw_exception.hpp include

- include/miral/miral/runner.h
- include/test/miral/test_display_server.h
- src/miral/runner.cpp
- src/miral/symbols.map
- tests/mir_test_framework/test_display_server.cpp
- tests/miral/runner.cpp
[miral] Make it possible for servers to set up the environment for launching clients
Add MirRunner properties to retrieve the WAYLAND_DISPLAY and DISPLAY supported by the server.
> [miral] Make it possible for servers to set up the environment for launching clients

- src/miral/regenerate-miral-symbols-map.py
- src/miral/symbols.map
The glob syntax treats '[' as the start of a character range, so lld is
pretty reasonable in rejecting a single '[' in the symbol name.
'[[]' (a character range containing only '[') is the correct way to match
a '[' in glob syntax.
Closes: #990
> miral: Fix glob syntax in symbols.map

- src/server/scene/basic_surface.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
Don't try to draw cursor buffers that are not ready. (Fixes #1009)
This results from the MultiMonitorArbiter state machine being in a condition that was not anticipated for streams passed to `set_cursor_stream()`. (I don't think it was possible with the mirclient API.)
Specifically, although the stream has buffers posted, they have been consumed and the `current_buffer` is no longer ready.
> Don't try to draw cursor buffers that are not ready

- src/server/scene/basic_surface.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
This reverts commit 391da119d1e0965f1b7c59b1a3cfbb64701332fa, reversing
changes made to d965d6af1afed7251ec3ef77b6a4d9aa52819dba.
The logic here is wrong - we want to draw the cursor even if this
particular cursor image has already been displayed on the current output
(ie: buffers_ready_for_compositor(this) == 0)
> Revert "Merge #1010"

- src/server/frontend_wayland/wlshmbuffer.cpp
PixelSource::read() should execute the supplied block. (Fixes: #1009)
The WlShmBuffer::read() implementation failed to execute the do_with_pixels block when the underlying wl_buffer has been destroyed.
As the most recent buffer remains in the bufferstream until another buffer is submitted client code (e.g. CursorImageFromBuffer) cannot know that the PixelSource is no longer supported by an underlying wl_buffer.
I've removed the log that this is a logic_error as I don't see how the calling code can know.
> PixelSource::read() should execute the supplied block

- src/renderers/gl/renderer.cpp
As it was, the Renderer would try and acquire *both* a Texture and
a TextureSource, and then preferentially use one in some parts of
the code and the other in other parts of the code.
Fortunately, for platforms where it matters we only expose one
or the other interface, not both, and for platforms where we
*do* expose both they're accidentally interchangable.
> renderer: Use only one of Texture or TextureSource

- src/server/graphics/software_cursor.cpp
- src/server/input/touchspot_controller.cpp
- tests/unit-tests/graphics/test_software_cursor.cpp
- tests/unit-tests/input/test_touchspot_controller.cpp
Platforms which don't support mirclient won't support the
`alloc_buffer(BufferProperties const&)` method; switch the last two
remaining uses to `alloc_software_buffer()`.
> Drop the last uses of deprecated alloc_buffer

- src/client/display_configuration.h
- src/client/display_configuration_api.cpp
- src/client/mir_blob.cpp
- src/client/rpc/mir_basic_rpc_channel.cpp
- src/include/common/mir/protobuf/display_server.h
- src/include/common/mir/protobuf/display_server_debug.h
We had a version check, but it appears it wasn't checking the right version. Also, some protobuf types have become `final`, so we can't inherit from them. `MirDisplayConfig` becomes a wrapper struct instead of a child struct, and `MirOutput` becomes an opaque struct that's typedef and casted to but never declared.
> Fixes for new Protobuf on Arch

- include/server/mir/scene/surface.h
- include/test/mir/test/doubles/stub_surface.h
- src/server/frontend_wayland/wayland_surface_observer.cpp
- src/server/frontend_wayland/wayland_surface_observer.h
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/scene/basic_surface.cpp
- src/server/scene/basic_surface.h
- src/server/shell/abstract_shell.cpp
- tests/include/mir/test/doubles/stub_scene_surface.h
- tests/mir_test_framework/stub_surface.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
The focus state property is currently only exposed by the old attribute system via `mir_window_attrib_focus`. This PR exposes it with a setter/getter (like other properties). The observer does not need to be changed since for better or for worse, that still uses attributes. This removes the need to cache the current focus state in `WindowWlSurfaceRole`s observer, and is required for the implementation of `wlr-foreign-toplevel-management`.
> scene::Surface: Add setters and getters for focus state

- src/renderers/gl/renderer.cpp
This is handy for checking that the platform really does support
the things that you think it does.
> renderer: Also log supported EGL and GL extensions

- debian/libmiral3.symbols
- include/miral/miral/window_info.h
- include/miral/miral/window_specification.h
- include/server/mir/scene/null_surface_observer.h
- include/server/mir/scene/surface.h
- include/server/mir/scene/surface_creation_parameters.h
- include/server/mir/scene/surface_observer.h
- include/server/mir/shell/surface_specification.h
- include/test/mir/test/doubles/stub_surface.h
- src/include/server/mir/scene/surface_observers.h
- src/miral/basic_window_manager.cpp
- src/miral/symbols.map
- src/miral/window_info.cpp
- src/miral/window_specification.cpp
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_stable.cpp
- src/server/frontend_wayland/xdg_shell_v6.cpp
- src/server/scene/application_session.cpp
- src/server/scene/basic_surface.cpp
- src/server/scene/basic_surface.h
- src/server/scene/null_surface_observer.cpp
- src/server/scene/surface_creation_parameters.cpp
- src/server/shell/surface_specification.cpp
- src/server/symbols.map
- tests/acceptance-tests/test_client_cursor_api.cpp
- tests/include/mir/test/doubles/stub_scene_surface.h
- tests/mir_test_framework/stub_surface.cpp
This will be something like `org.gnome.gedit`. Generally the same for all toplevels of a given application, but XDG shell allows setting it on a per-surface bases so so do we. It will be needed for foreign toplevel control, but also I though would be useful to MirAL.
> Add application_id surface property

- include/server/mir/frontend/surface.h
- include/server/mir/shell/surface_specification.h
- src/server/frontend_wayland/wl_pointer.cpp
- src/server/scene/basic_surface.h
Fixes #1000
Unfortunately, the old paths are still used by mirclient so I can't get rid of them, but once we drop that `basic_surface` should no longer deal with stream cursors.
> Convert buffer stream to cursor images in wl_pointer

- src/server/frontend_wayland/wl_pointer.cpp
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
Stacked on #1033
Makes `WlSurface` throw if a surface role is set without the previous one being cleared (not sure why it didn't already). This allows a surface to loose one role and gain a different one, which isn't *technically* allowed by Wayland, but it's an improvement.
Makes the wl_pointer cursor set a null surface role, so the surface can't be given a different role or be used by a different wl_pointer (this would have exposed the bug in #1033).
> More wl_pointer improvements

- src/server/frontend_wayland/xdg_output_v1.cpp
- src/wayland/generated/xdg-output-unstable-v1_wrapper.cpp
- src/wayland/generated/xdg-output-unstable-v1_wrapper.h
- src/wayland/protocol/xdg-output-unstable-v1.xml
Note that this is not a breaking protocol change. I'm bumping the backwards compatible version from 2 to 3. The protocol itself is still `xdg_output_unstable_v1`. No events or requests were added. The only change is that now the `wl_output.done` event is used to commit a change instead of `xdg_output_v1.done`
> Bump xdg output to v3

- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
GTK loves to set max and min win size. Previously we were calling all the way through to the window management policy every time this was set (even if there was no change). This PR prevents that
> Don't call modify_window if size bounds have been set to the same value

- include/platform/mir/graphics/egl_wayland_allocator.h
- src/platform/graphics/CMakeLists.txt
- src/platform/graphics/egl_wayland_allocator.cpp
- src/platform/symbols.map
- src/platforms/mesa/server/buffer_allocator.cpp
There's a generic EGL way to handle the Wayland buffer consumption,
so provide helpers which do the common thing.
> platform: Provide a generic Wayland EGL helper

- cmake/FindGtestGmock.cmake
- tests/include/gmock_set_arg.h
- tests/include/mir/test/gmock_fixes.h
- tests/include/mir/test/input_config_matchers.h
- tests/unit-tests/graphics/offscreen/test_offscreen_display.cpp
There's a 1.9 snapshot in focal-proposed, and Mir fails to build against it.
This fixes the build.
> Fix build against GMock/GTest ≥ 1.9

- examples/miral-shell/miral-app.sh
- examples/miral-shell/miral-desktop.sh
- src/include/platform/mir/options/configuration.h
- src/platform/options/default_configuration.cpp
- src/platform/symbols.map
- src/server/frontend_wayland/wayland_default_configuration.cpp
- tests/mir_test_framework/test_wlcs_display_server.cpp
- tests/performance-tests/test_glmark2-es2-mir.cpp
- tools/mir-smoke-test-runner.sh
Drop the --wayland-socket-name configuration option: It duplicates what WAYLAND_DISPLAY means to a server, so use that instead.
> Drop the --wayland-socket-name configuration option

- CMakeLists.txt
- debian/control
- debian/mir-platform-graphics-wayland16.install
- examples/miral-shell/CMakeLists.txt
- examples/miral-shell/spinner.cpp
- src/platforms/CMakeLists.txt
- src/platforms/wayland/CMakeLists.txt
- src/platforms/wayland/buffer_allocator.cpp
- src/platforms/wayland/buffer_allocator.h
- src/platforms/wayland/cursor.cpp
- src/platforms/wayland/cursor.h
- src/platforms/wayland/display.cpp
- src/platforms/wayland/display.h
- src/platforms/wayland/display_input.h
- src/platforms/wayland/displayclient.cpp
- src/platforms/wayland/displayclient.h
- src/platforms/wayland/input.cpp
- src/platforms/wayland/input_device.cpp
- src/platforms/wayland/input_device.h
- src/platforms/wayland/input_platform.cpp
- src/platforms/wayland/input_platform.h
- src/platforms/wayland/platform.cpp
- src/platforms/wayland/platform.h
- src/platforms/wayland/platform_symbols.cpp
- src/platforms/wayland/symbols.map.in
- src/platforms/wayland/wayland_display.cpp
- src/platforms/wayland/wayland_display.h
- src/server/input/input_probe.cpp
- tools/update_package_abis.sh
Assuming there's an existing Wayland server at `wayland-0`, enable connecting to it with:
`--wayland-host wayland-0`
This works well enough as a first cut. The main issue I know of is that the modifier key state gets out of sync when switching between this window and others on a desktop. It's still usable though as toggling the key resynchronises.
Still no tests, but there's not a lot to meaningfully test for platforms beyond "Mir lives". Will look at that after the sprint.
> Wayland platform

- include/core/mir/fatal.h
Make fatal_error() doc comment match the code.
> Make fatal_error() doc comment match the code

- debian/rules
Add wayland platform to debian/rules. (Fixes: #1073)
> Add wayland platform to debian/rules

- debian/mir-test-tools.install
This should fix the package builds.
> Debian packaging: Include platform test harness in mir-test-tools

- src/server/scene/basic_surface.cpp
- src/server/scene/basic_surface.h
It just so happens that the private version of `BasicSurface::visible()` only needs to be called from functions that hold a `std::lock_guard` and not a `std::unique_lock`. However, another private function will need to be called when both types of locks are held, so I'm introducing `BasicSurface::ProofOfMutexLock` which can be created from either. The system isn't full proof, but it does give a clear indication that functions that take it are intended to be called when the mutex is locked, and gives some level of compile-time checking.
> BasicSurface: add ProofOfMutexLock

- debian/mir-test-tools.install
- examples/miral-shell/CMakeLists.txt
This is the last bit of uninstalled stuff; packages now build locally, so *should* also build in the PPA!
> Add mir-spinner to mir-test-tools

- include/platform/mir/graphics/texture.h
- src/platform/graphics/texture.cpp
- src/platform/symbols.map
I *think* egl_wayland_allocator.cpp instantiates Texture::Texture() and toolchain bugs on 16.04/armhf that leads to LTO (incorrectly) complaining about a duplicate vtable.
This ought to stop that, but I don't have armhf kit to test locally.
> Trying to blindly fix 1080

- include/server/mir/scene/session.h
- include/server/mir/scene/surface.h
- include/server/mir/scene/surface_factory.h
- include/test/mir/test/doubles/stub_session.h
- include/test/mir/test/doubles/stub_surface.h
- src/server/scene/application_session.cpp
- src/server/scene/application_session.h
- src/server/scene/basic_surface.cpp
- src/server/scene/basic_surface.h
- src/server/scene/surface_allocator.cpp
- src/server/scene/surface_allocator.h
- src/server/shell/abstract_shell.cpp
- tests/include/mir/test/doubles/mock_scene_session.h
- tests/include/mir/test/doubles/mock_surface.h
- tests/include/mir/test/doubles/stub_scene_surface.h
- tests/include/mir/test/doubles/stub_surface_factory.h
- tests/integration-tests/test_error_reporting.cpp
- tests/integration-tests/test_session.cpp
- tests/integration-tests/test_surface_stack_with_compositor.cpp
- tests/mir_test_framework/stub_session.cpp
- tests/mir_test_framework/stub_surface.cpp
- tests/miral/test_window_manager_tools.cpp
- tests/unit-tests/scene/test_abstract_shell.cpp
- tests/unit-tests/scene/test_application_session.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
- tests/unit-tests/scene/test_session_manager.cpp
- tests/unit-tests/scene/test_surface.cpp
- tests/unit-tests/scene/test_surface_impl.cpp
- tests/unit-tests/scene/test_surface_stack.cpp
Adds and tests an immutable session property to surfaces. Alternative to #1041
> Add Immutable session property to surfaces

- debian/mir-test-tools.install
- examples/miral-shell/CMakeLists.txt
Make `mir-spinner` a `mir_demo_client` that will be picked up by `mir-smoke-test-runner`.
> Make `mir-spinner` a `mir_demo_client`

- tests/CMakeLists.txt
The regex in tests/CMakeLists.txt didn't account for two digits and failed for 1.10.0.
> Adjust regex to fix build with googletest 1.10.0

- .travis.yml
We're seeing intermittent failures to set up ubuntu-devel, ignore them for now.
> Ignore devel failures

- CMakeLists.txt
Only tested on Arch so far. I don't know how long `EGL_NO_X11` has been around. If this fails on older distros, I'll just use both defines.
Fixes #1086
> Use EGL_NO_X11 as well as MESA_EGL_NO_X11_HEADERS

- include/test/mir/test/doubles/mock_egl.h
Not sure what broke here, but the fix is harmless enough I'm not motivated to dig into it
> Forward declare wl types to fix build on Arch

- src/platforms/wayland/display.cpp
- src/platforms/wayland/display.h
Handle touch_up() and touch_cancel() correctly.
De-duplicated almost-correct logic for applying shape and orientation.
> Fix wayland platform touch handling

- debian/control
- debian/libmirserver51.install
- debian/libmirserver52.install
- include/server/mir/scene/null_surface_observer.h
- include/server/mir/scene/surface_observer.h
- src/include/server/mir/scene/surface_event_source.h
- src/include/server/mir/scene/surface_observers.h
- src/server/CMakeLists.txt
- src/server/frontend_wayland/wayland_surface_observer.cpp
- src/server/frontend_wayland/wayland_surface_observer.h
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/input/cursor_controller.cpp
- src/server/input/surface_input_dispatcher.cpp
- src/server/scene/basic_surface.cpp
- src/server/scene/legacy_surface_change_notification.cpp
- src/server/scene/legacy_surface_change_notification.h
- src/server/scene/null_surface_observer.cpp
- src/server/scene/surface_event_source.cpp
- src/server/shell/abstract_shell.cpp
- src/server/symbols.map
- tests/acceptance-tests/test_client_cursor_api.cpp
- tests/acceptance-tests/test_confined_pointer.cpp
- tests/acceptance-tests/test_surface_modifications.cpp
- tests/acceptance-tests/test_surface_specification.cpp
> SurfaceObserver: split resized_to() into window_resized_to() and content_resized_to()

- src/server/frontend_wayland/wayland_connector.cpp
- tests/mir_test_framework/test_wlcs_display_server.cpp
If wl_display_add_socket() fails, report an error instead of silently carrying on.
This happens, for example, under GNOME/Wayland as WAYLAND_DISPLAY points to the GNOME socket.
> Report wl_display_add_socket() errors

- cmake/MirCommon.cmake
Ensure XDG_RUNTIME_DIR is set when running tests. (Fixes: #1096)
> Ensure XDG_RUNTIME_DIR is set when running tests

- src/server/shell/system_compositor_window_manager.cpp
Clear input regions when they should not be set. (Fixes #1091)
This is a workaround for dubious logic documented in #1094 and discussed in comments to #1093.
> Clear input regions when they should not be set

- src/platforms/wayland/displayclient.cpp
[wayland-platform] respect the display output scale.
> [wayland-platform] respect the display output scale

- src/server/scene/basic_surface.cpp
- src/server/scene/basic_surface.h
Fix thread-unsafe code. (Fixes: #1106)
The "frame posted" callback set in BasicSurface::set_streams() can be invoked (e.g. by WlSurface::commit()) after BasicSurface::observers had been destroyed (with the surface). Switch to a shared pointer to ensures that the SurfaceObservers are not destroyed while they are in use.
> Fix thread-unsafe code

- debian/mir-demos.install
- examples/CMakeLists.txt
- examples/miral-system-compositor/CMakeLists.txt
- examples/miral-system-compositor/system_compositor_main.cpp
- include/server/mir/shell/system_compositor_window_manager.h
- src/miral/window_management_options.cpp
- src/server/shell/default_configuration.cpp
- src/server/shell/system_compositor_window_manager.cpp
Because miral-shell incorporates too much keyboard handling it is a poor host to other compositors.
Extract the example system-compositor code from miral-shell and create a new miral-system-compositor example.
Usage:
```
miral-system-compositor
miral-shell --wayland-host wayland-0
egmde-confined-desktop --wayland-host wayland-0
```
Switch between hosted sessions using Ctrl-Alt-PgUp/Ctrl-Alt-PgDn
(The session switching behavior is in a new class to avoid changes that might break unity-system-compositor as used by UBPorts.)
> miral-system-compositor

- examples/miral-shell/spinner.cpp
Close mir_demo_client_wayland_egl_spinner on SIGTERM. (Fixes: #1112)
> Close mir_demo_client_wayland_egl_spinner on SIGTERM

- src/platforms/common/server/shm_buffer.cpp
- src/platforms/common/server/shm_buffer.h
- tests/unit-tests/graphics/test_shm_buffer.cpp
We no longer need to support `renderer::gl::TextureSource`, as our renderer can use the `mg::gl::Texture` interface (as can QtMir, our only other known renderer implementation).
`renderer::gl::TextureSource` is only used by the Screencast interface, which is mirclient only.
This lets us drop the funky disambiguating classes required to let ShmBuffer implement both `mg::gl::Texture` and `renderer::gl::TextureSource`.
> mg::common::ShmBuffer: Drop legacy interfaces.

- include/core/mir/geometry/displacement.h
- include/server/mir/frontend/surface.h
- include/server/mir/scene/surface.h
- include/test/mir/test/doubles/stub_surface.h
- src/server/scene/basic_surface.cpp
- src/server/scene/basic_surface.h
- src/server/shell/abstract_shell.cpp
- tests/include/mir/test/doubles/stub_scene_surface.h
- tests/mir_test_framework/stub_surface.cpp
- tests/unit-tests/scene/test_abstract_shell.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
This allows setting a surface's "window margins" (the padding around a surface that makes room for decorations). There are alternative ways we could have done this, each with its advantages and disadvantages. We settled on this approach several weeks ago because it's easy to implement with minimum code churn, and appears to be similar to what whoever was here last intended to do. In the future (especially if we split up the `scene::Surface` interface) we may want to refactor this, but it has proven to be sufficient for usable SSDs.
> Add Surface::set_window_margins() for SSD

- src/miral/window_info.cpp
Any code surrounding MirAL title bars probably needs to be removed, but this function is part of the ABI so for now just fix it. This PR fixes positioning of my new SSD titlebars.
> decoration type doesn't need a titlebar

- include/server/mir/scene/surface_creation_parameters.h
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_xwayland/xwayland_wm_shellsurface.cpp
- src/server/scene/surface_creation_parameters.cpp
- src/server/shell/abstract_shell.cpp
This lets the XWayland frontend mark its windows as server-side-decorated and causes the shell to decorate them.
> SSD surface creation param

- src/server/scene/basic_surface.cpp
Fixes small mistake in implementation of `BasicSurface::content_size()` that may have caused some SSD crashes.
EDIT: doesn't look like the old behavior was causing any problem in practice, but this doesn't hurt.
> BasicSurface: don't allow zero content size

- src/miral/basic_window_manager.cpp
- src/miral/window_info.cpp
- tests/miral/CMakeLists.txt
- tests/miral/resize_window.cpp
Max and min window size were only being respected when first set. This PR constrains the window size whenever the window is resized. Tests included.
EDIT: note that this PR alone will not fix SSD size constraints, but it will fix the visible problem of windows moving weirdly when you resize them too small.
> Correctly constrain window size

- src/client/display_configuration.h
- src/client/mir_blob.cpp
- src/client/rpc/mir_basic_rpc_channel.cpp
- src/client/rpc/mir_protobuf_rpc_channel.cpp
- src/platforms/wayland/display.cpp
- src/server/frontend/event_sender.cpp
- src/server/frontend/protobuf_responder.cpp
Fixes #1127 
I've also included a patch which fixes another warning with the musl libc (sys/poll.h -> poll.h).
The build seems to be warning-free now except for
```
/home/pmos/build/src/mir-1.6.0/tests/mir_test_framework/test_wlcs_display_server.cpp: In function 'void {anonymous}::wlcs_pointer_move_relative(WlcsPointer*, wl_fixed_t, wl_fixed_t)':
/home/pmos/build/src/mir-1.6.0/tests/mir_test_framework/test_wlcs_display_server.cpp:659:10: warning: '*((void*)& event +16)' may be used uninitialized in this function [-Wmaybe-uninitialized]
659 |     auto event = mir::input::synthesis::a_pointer_event()
|          ^~~~~
```
> Use ByteSizeLong instead of deprecated ByteSize

- src/platforms/wayland/cursor.cpp
- src/platforms/wayland/cursor.h
- src/platforms/wayland/display.cpp
- src/platforms/wayland/displayclient.cpp
- src/platforms/wayland/displayclient.h
Apply output scale. (Fixes: #1133)
Mir uses unscaled coordinates, so we need to mark buffers as pre-scaled and scale some input values.
> [wayland-platform] Apply output scale

- .travis.yml
We're no longer seeing intermittent failures to set up ubuntu-devel. Reinstate in CI.
This reverts commit a9a7bd592c7996d98ffd7d54d63f06deb6cd7fcd, reversing
changes made to 5fdc44755a982374b1723ee0308eb4e76920b9e0.
> Revert "Merge #1089"

- src/miral/minimal_window_manager.cpp
...instead of whatever is under the cursor (fixes #1135)
I believe this is correct implementation because it mirrors what's already in `apply_resize_by()` and `handle_touch_event()`. This should fix a variety of edge cases I've been stumbling on for a while (such as dragging a window under a panel).
> MinimalWindowManager: drag the requested window

- src/server/shell/decoration/basic_decoration.cpp
- src/server/shell/decoration/basic_decoration.h
- src/server/shell/decoration/input.cpp
- src/server/shell/decoration/input.h
- src/server/shell/decoration/renderer.cpp
- src/server/shell/decoration/renderer.h
- src/server/shell/decoration/window.cpp
- src/server/shell/decoration/window.h
- tests/unit-tests/shell/test_decoration_basic_decoration.cpp
* Add a few properties to the `StaticGeometry` struct that were previously magic numbers strewn about the code
* Make `static_geometry` a shared pointer and give all decoration components that need it a copy (instead of having to request it from a `WindowState`
* Give `Renderer` a new `Theme` struct that can be changed when switching between the focused and unfocused look
A PR adding title text rendering is to come after this is merged.
> Refactor decoration

- src/server/CMakeLists.txt
- src/server/shell/decoration/renderer.cpp
- src/server/shell/decoration/renderer.h
Uses FreeType to render window titles on server side decorations. It appears the current XWayland implementation does not update the window title after it is initially set, but this will handle title updates when it happens.
> Draw window titles on SSDs

- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
Previously, `XWaylandServer::spawn()` forked, and handled both forks in a large switch statement. This splits the two branches into `XWaylandServer::execl_xwayland()` and `XWaylandServer::connect_to_xwayland()`. Also runs `wl_client_create()` on the Wayland thread to fix #1147. It may be helpful to look over the commits individually.
> XWayland refactor and fix

- src/server/shell/decoration/basic_decoration.cpp
- src/server/shell/decoration/basic_decoration.h
TLDR this cleans up logic and prevents a flicker. You don't need to fully understand the problem unless you really care.
A call to `window_state_updated()` would trigger creating multiple `WindowState`s, which could be different if a change to the window was in-progress. The end result would be correct once all the callbacks had fired, but it would render one frame where the `WindowState` the `InputState` was generated from was different from the one being rendered. This would cause a flicker of button positions.
> SSD: improve how BasicDecoration states are updated

- tools/process_snaps.py
We want to update "edge" channels when master has a different version. E.g.
>>> "1.6.0+dev73".startswith("1.6.0")
True
>>> "1.6.0+dev73" =="1.6.0"
False
> Fix process snap version check

- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
Make Wayland calls on the correct thread. (Fixes: #1153)
> [X11 frontend] Make Wayland calls on the correct thread

- src/server/input/basic_seat.cpp
This changes the map of outputs from a unordered map to a sorted map, as
mir takes the first output as default for touch screens if not otherwise
is provided. it makes no sense for this to give a different result
depending on whats first in the unordered_map bucket.
> [server/input] Use a sorted map for outputs

- src/include/server/mir/frontend/connections.h
- tests/miral/resize_window.cpp
Clang 10 picks up a couple of extra warnings, which have picked up some incorrect Mir code.
> Fix clang found clangers

- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/shell/abstract_shell.cpp
Don't restart Xwayland if we killed it deliberately. (Fixes: #1169)
This whole area is a mess, as the reason we kill Xwayland is that it is waiting for clients to exit before closing. And if we ensured they were closed, we wouldn't be deleting windows that no longer exist and crashing after this. I'll have a look at that (fixed, second commit).
We still fail to give clients a chance to close nicely, c.f. #1171.
> Don't restart Xwayland if we killed it deliberately

- src/server/frontend_wayland/wl_pointer.cpp
Wayland: (cursor code) don't assume PixelSource::read() will execute the do_with_pixels functor. (Fixes: #1180)
> Wayland: don't assume PixelSource::read() will execute the do_with_pixels functor

- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_xwayland/xwayland_wm_surface.cpp
XWayland: create scene surface only when needed. (Fixes: #1172)
> XWayland: create scene surface only when needed

- src/server/frontend_xwayland/xwayland_connector.cpp
- src/server/frontend_xwayland/xwayland_connector.h
- src/server/frontend_xwayland/xwayland_default_configuration.cpp
- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
- src/server/frontend_xwayland/xwayland_wm_shell.h
- src/server/frontend_xwayland/xwayland_wm_surface.cpp
- src/server/frontend_xwayland/xwayland_wm_surface.h
Also moves some logic from `XWaylandWMSurface` into `XWaylandWM` that removes the need for a few getters.
> XWayland: make names more verbose

- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
- src/server/frontend_xwayland/xwayland_wm_shell.cpp
- src/server/frontend_xwayland/xwayland_wm_shell.h
- src/server/frontend_xwayland/xwayland_wm_shellsurface.cpp
- src/server/frontend_xwayland/xwayland_wm_shellsurface.h
- src/server/frontend_xwayland/xwayland_wm_surface.cpp
- src/server/frontend_xwayland/xwayland_wm_surface.h
Make Wayland calls on the Wayland thread and lock everything else behind a mutext
> Make XWaylandWMSurface thread safe

- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- tests/miral/CMakeLists.txt
- tests/miral/ignored_requests.cpp
- tests/miral/invalid_requests.cpp
It is impossible for one subsystem in Mir to know if another subsystem on another thread is in the process of destroying a surface. It is also impossible to externally lock the window manager. Therefore, a surface may be destroyed twice in quick succession, or the window manager may get a `modify_surface` after the surface has been destroyed.
The current behavior is to `fatal_error()` if a surface is destroyed twice, and throw `std::out_of_range` or do nothing in other cases.
This PR implements, documents and tests: Requests on unknown windows warn and noop.
> BasicWindowManager requests on unknown windows should noop

- src/server/display_server.cpp
We don't need to stop Xwayland when pausing the Mir server. (Fixes: #1188)
> X11: Don't stop Xwayland when pausing the Mir server

- src/server/scene/surface_creation_parameters.cpp
Previously, C++ was helpfully casting the optional into a bool, then a char, then "\x1".
> SurfaceCreationParameters::update_from(): correctly access name

- include/server/mir/shell/surface_specification.h
- src/miral/window_specification.cpp
- src/server/scene/surface_creation_parameters.cpp
- src/server/shell/surface_specification.cpp
It appears this was never added because no mirclient or Wayland protocols needed it. XWayland will.
> Add top_left to shell::SurfaceSpecification

- examples/miral-shell/miral-app.sh
- examples/miral-shell/shell_main.cpp
Simplify miral-app script and make terminal logic more robust.
1. Adds a --shell-terminal-emulator option to miral-shell
2. Uses that (and Ctrl-Alt-T) instead of a separate "launcher" process in miral-app
3. Renames the miral-app "-launcher" option "-terminal"
4. Tries to detect a usable default terminal on the system
> Simplify miral-app script and make terminal logic more robust

- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
More code left over from Thursday. Adds a new `XWaylandWM::get_wm_surface()` method. This makes converting from XCB windows to wm surfaces more convenient and publicly accessible (the latter will be important when shell surfaces want to look up their parent windows). This also fixes the issue of accidentally creating null shell surfaces in the surfaces map via careless usage of the '[]` map operator.
> XWaylandWM::get_wm_surface()

- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
Notably moves processing of a single event into its own function and catches exceptions while processing X11 events. Wrote code last Thursday, but required PRs hadn't landed yet
> More minor XWayland improvements

- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
Introduces and uses a `mutex` and inlines `create()` and `destroy()` into the constructor and destructor (they were only being called from there anyway).
> XWaylandWM: make threadsafe

- src/server/frontend_xwayland/xcb_atoms.cpp
- src/server/frontend_xwayland/xcb_atoms.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
- src/server/frontend_xwayland/xwayland_wm_shellsurface.cpp
- src/server/frontend_xwayland/xwayland_wm_shellsurface.h
- src/server/frontend_xwayland/xwayland_wm_surface.cpp
- src/server/frontend_xwayland/xwayland_wm_surface.h
Fixes #1210. Also alerts windows to their current state (for example, Gedit draws slightly differently when it knows it's maximized).
> XWayland: manage window state correctly

- src/server/frontend_wayland/CMakeLists.txt
- src/server/frontend_wayland/wayland_input_dispatcher.cpp
- src/server/frontend_wayland/wayland_input_dispatcher.h
- src/server/frontend_wayland/wayland_surface_observer.cpp
- src/server/frontend_wayland/wayland_surface_observer.h
- src/server/frontend_wayland/window_wl_surface_role.cpp
Splits input event dispatching out from the rest of the Wayland surface observer. This will allow more easily writing an `XWaylandSurfaceObserver`.
> Split WaylandInputDispatcher out from WaylandSurfaceObserver

- examples/miral-shell/miral-app.sh
Only consider using `--disable-factory` with gnome-terminal when launched from the script.
This workaround is broken and not needed with miral-shell.
> Only use `--disable-factory` with gnome-terminal when launched from the script.

- src/miral/launch_app.cpp
Exec errors after forking need to be fatal. (Fixes: #1218)
> Exec errors after forking need to be fatal

- debian/changelog
Correction: mirplatform ABI unchanged at 17
Copy & pasted in error from 1.6.0
> Correction: mirplatform ABI unchanged at 17

- examples/miral-shell/miral-app.sh
Add `xdg-terminal` to the list of possible terminal commands.
It isn't earlier in the list as it isn't clear that it "does the right thing" for a specific user any more than `x-terminal-emulator` does. But it does exist on a different range of systems.
> [miral-app] Add `xdg-terminal` to the list of possible terminal commands

- src/server/frontend_xwayland/CMakeLists.txt
- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_surface.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
The new `XCBConnection` class holds atoms as the `XCBAtoms` class used to. It also now manages the lifetime and gives access to the `xcb_connection_t`. It is passed to each surface, which reduces dependence of the surfaces on the window manager. In the future, XCB helper methods such as setting properties on windows could be implemented on the `XCBConnection`.
> Repurpose XCBAtoms into XCBConnection

- src/server/frontend_xwayland/xwayland_wm.cpp
Fixes #1235. Looks like it was just an oversight when moving ownership of the `xcb_connection_t` into `XCBConnection`.
> XWayland: fix double free of XCB connection

- debian/libmiral3.symbols
Drop broken entry in libmiral3.symbols. (Fixes: #1242)
> Drop broken entry in libmiral3.symbols

- tests/CMakeLists.txt
- tests/acceptance-tests/server_signal_handling.cpp
- tests/acceptance-tests/test_client_scaling.cpp
- tests/acceptance-tests/test_client_surface_events.cpp
- tests/acceptance-tests/test_client_surfaces.cpp
- tests/acceptance-tests/test_new_display_configuration.cpp
- tests/acceptance-tests/test_server_shutdown.cpp
- tests/acceptance-tests/test_surface_modifications.cpp
- tests/acceptance-tests/test_surface_morphing.cpp
- tests/acceptance-tests/test_surface_placement.cpp
- tests/acceptance-tests/test_surface_specification.cpp
- tests/miral/CMakeLists.txt
- tests/miral/depth_layer.cpp
- tests/miral/drag_active_window.cpp
- tests/miral/ignored_requests.cpp
- tests/miral/modify_window_state.cpp
- tests/miral/window_placement_attached.cpp
- tests/unit-tests/graphics/test_shm_buffer.cpp
- tests/unit-tests/input/evdev/test_evdev_device_detection.cpp
- tests/unit-tests/input/evdev/test_evdev_input_platform.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
- tests/unit-tests/shell/test_decoration_basic_decoration.cpp
GTest conveniently renamed `INSTANTIATE_TEST_CASE_P` to `INSTANTATE_TEST_SUITE_P` and deprecated the old name. This breaks the build on Focal.
Switch to the new name, providing the old name on older GTests via a compatibility `#define`.
> Fix GTest deprecation

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
Adds helper methods to `XCBConnection` for getting and setting window properties.
The new property setters are wrappers around the XCB calls that also catch various type and format issues at compile time.
The getters request a property and return a function. When called, the function waits for the property and processes it. This way a number of properties can be queued up, then all read at once (which is more efficient than requiring a round-trip for each one). The old code *was* doing this, but the way it worked was error-prone and required the property request and property processing logic to be split up.
> XCBConnection helpers

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_surface.h
- src/server/frontend_xwayland/xwayland_surface_observer.cpp
- src/server/frontend_xwayland/xwayland_surface_observer.h
- src/server/frontend_xwayland/xwayland_surface_observer_surface.h
- src/server/frontend_xwayland/xwayland_surface_role.cpp
- src/server/frontend_xwayland/xwayland_surface_role_surface.h
- src/server/frontend_xwayland/xwayland_wm.cpp
In addition to general cleanup, this changes the flow of configure requests to go though the Mir window manager, so they should no longer be ignored.
> XWayland: more refactoring

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_surface.h
- src/server/frontend_xwayland/xwayland_wm.cpp
Improve property reading system and place popups correctly. Popups tested with PCManFM (GTK2), gedit (GTK3) and Kate (Qt, see known issues). XTerm and XEyes also tested.
Known issues:
* Tooltips are only sometimes placed correctly on all toolkits
* Specific Kate menus aren't place correctly
> XWayland: popups!

- debian/mir-utils.install
We dropped miral-screencast. don't package it! (Fixes: #1257)
> We dropped miral-screencast. don't package it

- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_surface.h
- src/server/frontend_xwayland/xwayland_surface_observer.cpp
- src/server/frontend_xwayland/xwayland_surface_observer_surface.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
Fixes #1206 and other issues related to window focus. Also organizes properties from the X server into a `cached` struct.
> Focus state

- src/miral/launch_app.cpp
Tell Java toolkits that we're a non-reparenting window manager.
This, for example, gets CLion painting correctly under X11.
> Tell Java toolkits that we're a non-reparenting window manager

- src/server/frontend_xwayland/xwayland_server.cpp
[X11] Once we've got the lockfile, check for an existing socket before trying to use it. (Fixes: #1265)
> [X11] Once we've got the lockfile, check for an existing socket

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wayland_connector.h
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_surface_role.cpp
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
Fixes #1269. See that issue for more info on the problem. This allows XWayland to register a callback when a surface with a particular ID is created. It is admittedly a lot of new code, and may not be worth it. It's probably not worth the complexity just to fix Mir under wayland-debug, but hypothetically we could hit the same race condition on a very slow machine, or in some other situation where the Wayland thread was bogged down. I'm open to alternative ideas on how to solve this.
> Wait for wl_surface to appear before attaching it to XWayland surface

- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_surface.h
- src/server/frontend_xwayland/xwayland_surface_role.cpp
- src/server/frontend_xwayland/xwayland_surface_role_surface.h
Fixes #1249 and simplifies `XWaylandSurface` logic. `attach_wl_surface()` can now create a `scene::Surface`, even if the `wl_surface` hasn't committed yet. Presumably there used to be a problem with this course of action, but it doesn't seem to be an issue any more (I've tested with gedit, pcmanfm, xxeyes, xterm, kate, blender and steam).
Edit: #1249 was caused by `attach_wl_surface()` caching a pre-commit input area, and the commit not updating the area correctly because there wasn't yet a surface to update. This fixes it because there is no gap between reading the initial input area and creating a scene surface (which allows updates to the input area)
> Create scene surface in attach_wl_surface()

- src/server/scene/basic_surface.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
Reading through the code, it looks like setting all buffer stream callbacks to `[](){}` is allowed (that's what we already do in `BasicSurface::set_streams()`, and why shouldn't it be?). If an noop callback is allowed, a conditionally noop callback should also be allowed. I see no reason to throw this error, as it is perfectly reasonable for a surface to be destroyed before its buffer streams.
Fixes #1272
> BasicSurface: allow frame to be posted after surface destroyed

- src/server/frontend_xwayland/xwayland_surface.cpp
We need to fully process properties before consuming the pending spec, and should be reading properties even when we do not have a scene surface.
> Fix XWaylandSurface::property_notify()

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
Fixes a potential thread safety issue in the resolving of `XCBConnection::Atom` and starts caching atom names for faster lookup.
> Improve XCBConnection atom lookup

- src/server/scene/basic_surface.cpp
- tests/integration-tests/test_surface_stack_with_compositor.cpp
- tests/unit-tests/scene/test_basic_surface.cpp
See discussion in #1273. This prevents observers being sent pointers to dead surfaces.
> BasicSurface: clear all frame posted callbacks in the destructor

- src/server/symbols.map
[mirserver] symbols stanza for mir::Server::x11_display should be 1.7.1
> [mirserver] symbols stanza for mir::Server::x11_display should be 1.7.1

- examples/miral-shell/miral-app.sh
Fix `miral-app -demo-server`.
Export DISPLAY correctly when starting mir_demo_server.
> Fix `miral-app -demo-server`

- examples/miral-shell/miral-app.sh
- examples/miral-shell/shell_main.cpp
Provide a usable default configuration for Xenial era toolkits.
Also fixes up the `gnome-terminal` launch command so that it works on Ubuntu and similar distros, including Xenial.
> Provide a usable default configuration for Xenial era toolkits

- src/server/frontend_xwayland/xwayland_wm.cpp
Fixes #1278. Input focus should now be correctly switched between apps. Due to the workaround for #1295, when a Wayland app is focused the last X app is not told it is unfocused, but it **does** stop receiving any input until it is refocused.
> Fix XWaylandWM::set_focus()

- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
When `TRANSIENT_FOR` is set to a window without a scene surface, use the currently focused window as the fallback popup parent. This happens, for example, when opening Kate's `Bookmarks` menu. This PR works somewhat on its own, and better in conjunction with #1296
> Use focused window as default popup parent

- src/server/frontend_wayland/wayland_input_dispatcher.cpp
- src/server/frontend_wayland/wl_keyboard.cpp
- src/server/frontend_wayland/wl_keyboard.h
- src/server/frontend_wayland/wl_seat.cpp
- src/server/frontend_wayland/wl_seat.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/shell/abstract_shell.cpp
Reverts #825 and fixes #1274. This does not fix #1295, but in my opinion it is an improvement on the status quo.
With the PR, Mir and Wayland/X keyboard focus state is allowed to fall out of sync, but the issue is detected and fixed before sending key events. The only visible symptom of the problem is in some cases (such as after closing a popup) a window appears to not have keyboard focus, but will gain it as soon as you start typing.
None of the new code need be removed when a proper fix is implemented. The fallback of setting keyboard focus before sending keys is reasonable, and will mitigate against potential future bugs.
> Improve keyboard focus situation

- src/server/frontend_xwayland/xwayland_surface.cpp
*Some* toolkits (\*cough\* Java \*cough\*) like to spam changes to window properties. No need to propagate that all the way through Mir.
> Only modify surface if something changed

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xwayland_wm.cpp
Makes remembering window names when debugging much easier. I threw up a generic form of this function here: https://github.com/wmww/name-of/.
> Give windows human readable names

- examples/miral-shell/miral-app.sh
Fix miral-shell command-line when options are provided. (Fixes: #1310)
> Fix miral-shell command-line when options are provided. (Fixes: #1310)

- src/miral/launch_app.cpp
Don't interleave iterating over environ with unsetting environment variables
> Don't interleave iterating over environ with unsetting environment variables

- README.md
http://mirserver.io appears to be dead, whereas https://mir-server.io/ directs to the Mir website and development resources.
> Update link to Mir website

- examples/miral-shell/shell_main.cpp
Fix launching gnome-terminal from "Mir Shell".
We should not supply both --disable-factory and --app-id, as that spawns multiple terminal servers. (Which eventually leads to madness.).
> Fix launching gnome-terminal from "Mir Shell"

- src/platforms/mesa/server/kms/display.cpp
Previous approach seems convoluted and error-prone to me, and was causing CRTC related failures when scale set to anything other than 1.
> Use correct physical output size in mgm::Display::configure_locked()

- src/platforms/mesa/server/x11/graphics/display.cpp
- src/platforms/mesa/server/x11/graphics/display.h
- src/platforms/mesa/server/x11/graphics/graphics.cpp
- src/platforms/mesa/server/x11/graphics/platform.cpp
- src/platforms/mesa/server/x11/graphics/platform.h
- tests/unit-tests/platforms/mesa/x11/test_display.cpp
- tests/unit-tests/platforms/mesa/x11/test_display_generic.cpp
- tests/unit-tests/platforms/mesa/x11/test_graphics_platform.cpp
- tests/unit-tests/platforms/mesa/x11/test_platform.cpp
We already have an option that allows creating multiple X11 windows that act as outputs of different sizes. This adds the additional functionality of optionally specifying a scale for each output with the syntax `^SCALE`.
For example, `--x11-output 640x480:1020x720^2.5` would result in two "outputs", a 640x480 one with a scale of 1 and a 1020x720 one with a scale of 2.5.
This aims to make testing HiDPI much easier.
> X11 platform: scale option for "fake" output

- examples/miral-shell/spinner/miregl.cpp
- src/miral/internal_client.cpp
[miral-shell] Avoid unnecessary blocking call in Spinner setup. (Fixes: #1327)
> [miral-shell] Avoid unnecessary blocking call in Spinner setup

- .travis.yml
Fedora 30 has been failing consistently throught the day. Ignore it. (For now.)
> Allow Fedora 30 to fail

- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- tests/miral/active_window.cpp
When setting the active window to a null window, mru_active_windows
won't be updated. This commit add the `allow_active_window` flag which
will be false when a null window is set, disabling the active window.
This is used by Lomiri during spreads and other effects and animations.
Co-authored-by: Alan Griffiths <alan@octopull.co.uk>
> [MirAL] Implement a "no active window" state

- include/platform/mir/graphics/program_factory.h
- src/platform/graphics/egl_wayland_allocator.cpp
- src/platforms/common/server/shm_buffer.cpp
- src/platforms/eglstream-kms/server/buffer_allocator.cpp
- src/platforms/mesa/server/gbm_buffer.cpp
- src/platforms/rpi-dispmanx/buffer_allocator.cpp
- src/renderers/gl/renderer.cpp
The GL uniforms (such as, for example, screen position) are per Program state, *not*
per context state, so when there were multiple rendering threads they would race.
Fix this by generating a `Program` per `ProgramFactory`; we already had a `ProgramFactory`
per thread.
Fixes: #1332, #1317
> platform: Ensure each rendering thread has a separate gl::Program.

- src/platforms/wayland/display.cpp
- src/platforms/wayland/display.h
- src/platforms/wayland/displayclient.cpp
- src/platforms/wayland/displayclient.h
- src/platforms/wayland/platform.cpp
Apply the display configuration to the Wayland platform.
This enables, for example, setting clone mode for a hosted shell.
> Wayland platform display config

- src/server/frontend_wayland/layer_shell_v1.cpp
- src/server/frontend_wayland/output_manager.cpp
- src/server/frontend_wayland/output_manager.h
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/xdg_output_v1.cpp
Improve the interface to the output and output manager classes. `OutputManager::output_for()` will be needed by upcoming HiDPI code.
> Refactor Wayland output interface

- src/platform/graphics/egl_wayland_allocator.cpp
Fix WaylandTexBuffer.
Buffers may be consumed by multiple compositors. We must protect mutable state.
> Fix WaylandTexBuffer

- src/platforms/common/server/buffer_from_wl_shm.cpp
- src/platforms/common/server/shm_buffer.cpp
- src/platforms/common/server/shm_buffer.h
- src/platforms/mesa/server/gbm_buffer.cpp
- src/platforms/mesa/server/gbm_buffer.h
Make various texture bind() functions threadsafe. (Fixes: #1332)
The one that was actually causing #1332 was re-uploading a texture on multiple threads.
> Make various texture bind() functions threadsafe

- src/platforms/mesa/server/x11/graphics/display.cpp
- src/platforms/mesa/server/x11/graphics/display.h
- src/platforms/mesa/server/x11/graphics/platform.cpp
- tests/unit-tests/platforms/mesa/x11/test_display.cpp
Enable `--display-config` for Mir-on-X. (Fixes: #1326)
Note: if you test, using "--display config clone" with this exposes the race that #1354 addresses.
> Enable `--display-config` for Mir-on-X

- src/platforms/mesa/server/x11/CMakeLists.txt
- src/platforms/mesa/server/x11/input/input_platform.cpp
- tests/include/mir/test/doubles/mock_x11.h
- tests/mir_test_doubles/mock_x11.cpp
- tests/unit-tests/input/test_x11_platform.cpp
[Mir-on-X] hide the X11 cursor when over the Mir window. (Fixes: #1352)
> [Mir-on-X] hide the X11 cursor when over the Mir window

- src/platforms/wayland/cursor.cpp
- src/platforms/wayland/cursor.h
- src/platforms/wayland/display.cpp
- src/platforms/wayland/displayclient.cpp
- src/platforms/wayland/displayclient.h
This reverts commit 42fb1856461e8eda37f2f57f6b7e1a784bbb4f58, reversing
changes made to 023546b26da34d2ce3fc25626c7261181a63fec0.
We no longer need to work around Mir not understanding scaling
> Revert "Merge #1134"

- src/platform/graphics/display_configuration.cpp
- src/platforms/mesa/server/kms/real_kms_display_configuration.cpp
- src/platforms/mesa/server/x11/graphics/display_configuration.cpp
- src/platforms/mesa/server/x11/graphics/display_configuration.h
- src/platforms/wayland/cursor.cpp
- src/platforms/wayland/cursor.h
- src/platforms/wayland/display.cpp
- src/platforms/wayland/displayclient.cpp
- src/platforms/wayland/displayclient.h
- tests/unit-tests/graphics/test_display_configuration.cpp
Make `DisplayConfiguration::extents_of()` return the scaled logical size, instead of the pixel size of the mode
> DisplayConfiguration respect scale

- examples/example-server-lib/decoration_provider.cpp
- examples/example-server-lib/sw_splash.cpp
- examples/example-server-lib/wayland_helpers.cpp
- examples/example-server-lib/wayland_helpers.h
- examples/miral-shell/spinner/miregl.cpp
- examples/miral-shell/spinner/miregl.h
__problem:__ When rendering example clients (such as the spinner, splash and background), we previously used the size from the current output mode for each output. This is not a robust system, as raw output size is not necessarily the size the surface should be to fill the screen (for example, raw output size does not reflect transforms including scaling).
Some of these transforms can be detected and compensated for, but this results in a complicated and fragile system. Others, such as fractional scaling, can not be compensated for in this way as the protocol does not supply enough information.
__Alternative Solution:__ The `xdg_output_unstable_v1` protocol (which we implement) has a `.logical_size` event. This would work, but would have added the complication of generating/updating a …
> Example clients: use configured size instead of output size

- src/server/frontend_wayland/output_manager.cpp
We can not yet deal with client supplied buffers (see #1361). Sending output transform is currently not a problem because surfaces do not enter outputs, but as soon as they do some clients will be attaching buffers with transforms and everything will fall apart. If we don't claim any outputs have a transform, no sane clients should send transformed buffers.
This will break example backgrounds and splashes on transformed outputs until #1360 lands.
> mf::Output: don't send output transform

- src/server/frontend_wayland/window_wl_surface_role.cpp
Is not a full fix of #342, but accomplishes 80% of the functionality that would with 20% of the work. Sends `wl_surface.enter` for every output when a surface is created. This allows surfaces to scale to the highest scale output.
Will cause the buffers of some clients (such as weston-terminal) to have an incorrect transform on transformed outputs until #1362 lands
> Have wl_surfaces enter all outputs

- src/platform/graphics/display_configuration.cpp
- tests/unit-tests/graphics/test_display_configuration.cpp
`user_display_configuration_output_extents_are_scaled_fractionally` was failing due to a floating point error
> Fix DisplayConfiguration tests

- src/platforms/mesa/server/x11/graphics/display.cpp
- src/platforms/mesa/server/x11/graphics/display.h
- src/platforms/mesa/server/x11/graphics/platform.cpp
- tests/unit-tests/platforms/mesa/x11/test_display.cpp
This reverts commit cd4ca37d05518ed1947d76916f6f20329a531036. (Fixes: #1338)
I'm not convinced that "Enable `--display-config` for Mir-on-X" is the real problem, but let's first fix the issue it introduced.
> Revert "Enable `--display-config` for Mir-on-X"

- src/platforms/mesa/server/kms/cursor.cpp
- src/platforms/mesa/server/kms/cursor.h
- tests/unit-tests/platforms/mesa/kms/test_cursor.cpp
This correctly applies output transform and scale when positioning the hardware cursor
> Mesa/KMS: position cursor correctly when output scaled

- examples/miral-system-compositor/system_compositor_main.cpp
- src/platforms/mesa/server/x11/graphics/display.cpp
- src/platforms/mesa/server/x11/graphics/display.h
- src/platforms/mesa/server/x11/graphics/platform.cpp
- tests/unit-tests/platforms/mesa/x11/test_display.cpp
[Mir-on-X11] Reinstate  --display-config
The previous attempt left the miral-system-compositor outputs in "clone" mode. This has them "sidebyside" (by default).
There's still a problem (c.f. #1338) with clone mode, but not with default options.
> [Mir-on-X11] Reinstate  --display-config

- src/gl/tessellation_helpers.cpp
- src/include/server/mir/compositor/buffer_stream.h
- src/server/compositor/stream.cpp
- src/server/compositor/stream.h
- src/server/frontend_wayland/output_manager.cpp
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
Renders scaled buffers at correct size, and sends correct output scales so clients know to render scaled buffers. Clients will not start sending scaled buffers until #1363 has also landed, as they do not know they're on a scaled output.
> Support scaled buffers

- examples/example-server-lib/wallpaper_config.cpp
Add a font & location for the "wallpaper" that works on Fedora "rawhide".
We really need a mor flexible approach to choosing a typeface. But this works for now.
> Add a font & location for the "wallpaper" that works on Fedora "rawhide"

- src/platforms/wayland/display.cpp
- src/platforms/wayland/display.h
- src/platforms/wayland/displayclient.cpp
- src/platforms/wayland/displayclient.h
- src/platforms/wayland/platform.cpp
This reverts commit b248f5282eaba79f639a82eca42962337941aadf, reversing
changes made to 2fb3523b6e2285527a55c52e4a8ee53ee7c1a4a2. (Fixes: #1376)
The reverted changes were simplistic: Display configuration changes cannot ignore the host configuration.
> Disable display configuration on Wayland platform

- examples/miral-shell/miral-app.sh
Don't launch Mir shells in separate dbus sessions for testing. (Fixes: #1392)
Running a temporary dbus session separates our test shell from the host desktop.
But it causes problems for gnome-terminal, so we stop doing it. What could go wrong?
> Don't launch Mir shells in separate dbus sessions for testing

- examples/miral-shell/miral-app.sh
Tidy miral-app.
Drop some legacy features from the miral-app script and clean up the remaining logic.
N.B. this shouldn't be cherry-picked to 1.x
> Tidy miral-app

- src/platforms/wayland/platform_symbols.cpp
If the `wayland-host` is not configured do not try connecting to a Wayland server, and do not return `PlatformPriority::supported` if that succeeds. (Fixes: #1395)
Note: if `WAYLAND_DISPLAY` is set and provided by an existing server Mir will fail to start anyway (as it cannot provide `WAYLAND_DISPLAY`). Only if both `WAYLAND_DISPLAY` is unset and the default wayland-0 socket is provided by an existing server could Mir start with with Mir-on-Wayland.
> If the `wayland-host` is not configured do not try connecting

- include/platform/mir/graphics/display_configuration.h
1.0 is a much more reasonable default output scale than 0.0. Normal code paths do not rely on the default scale, but some tests do.
> Set default DisplayConfigurationOutput.scale

- debian/control
- debian/libmirplatform17.install
- debian/libmirplatform18.install
- src/CMakeLists.txt
- src/platform/symbols.map
Bump libmirplatform soname.
We changed ProgramFactory::compile_fragment_shader(). This will conflict with "master", as that already used `MIRPLATFORM_ABI 18` for a different ABI break. I'll deal with that when we get there.
> Bump libmirplatform soname

- examples/miral-shell/miral-terminal.sh
[miral-terminal] use gdbus to detect and wait for the gnome-terminal-server
> [miral-terminal] use gdbus to detect and wait for the gnome-terminal-server

- src/client/mir_connection.cpp
- src/miral/launch_app.cpp
- src/server/run_mir.cpp
- tests/acceptance-tests/test_client_focus_notification.cpp
- tests/acceptance-tests/test_client_surface_events.cpp
- tests/acceptance-tests/test_custom_window_management.cpp
[mirclient] Do not send events to windows after they are released. (And update tests to match.)
> Do not send events to windows after they are released

- doc/getting_involved_in_mir.md
- spread/build/fedora/task.yaml
- tests/acceptance-tests/test_server_startup.cpp
- tests/mir_test_framework/async_server_runner.cpp
- tests/mir_test_framework/main.cpp
- tests/mir_test_framework/server_runner.cpp
- tests/mir_test_framework/test_display_server.cpp
- tests/miral/external_client.cpp
- tests/unit-tests/test_mir_cookie.cpp
Partial fix for Fedora rawhide build in CI. (Fixes: #1400, fixes: #1399)
1. Drop dependency that's unsatisfiable on Fedora rawhide (I think it's redundant)
2. Add a missing dependency
3. Clear WAYLAND_DISPLAY from the test environment
4. Disable a couple of tests that try to frig with /dev/random
That leaves us with a build, but hanging tests (#1405) but that can be fixed later.
> Fix Fedora rawhide build in CI

- include/miral/miral/window_manager_tools.h
It's also deprecated. Both of these things should be reflected in its documentation.
This produces the following documentation:
It also adds force_close to the list of deprecations at 'deprecated.html'.
> WindowManagerTools::force_close is unsafe, document it

- src/common/dispatch/threaded_dispatcher.cpp
> Use const where possible

- src/server/frontend_wayland/wl_surface.cpp
https://github.com/MirServer/wlcs/pull/156 caught this bug. This is one of the many things that will get fixed right when we rethink how windows, surfaces and buffer streams work together, but this is a relatively harmless workaround for now.
> Correctly handle empty input region on toplevel

- examples/miral-shell/shell_main.cpp
[miral-shell] Use a better default for --shell-terminal-emulator
(It is *possible* that miral-terminal isn't installed, but weston-terminal is even less likely to be found!)
> [miral-shell] Use a better default terminal emulator

- src/wayland/generated/wayland_wrapper.cpp
- src/wayland/generated/wayland_wrapper.h
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.cpp
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.h
- src/wayland/generated/xdg-output-unstable-v1_wrapper.cpp
- src/wayland/generated/xdg-output-unstable-v1_wrapper.h
- src/wayland/generated/xdg-shell-unstable-v6_wrapper.cpp
- src/wayland/generated/xdg-shell-unstable-v6_wrapper.h
- src/wayland/generated/xdg-shell_wrapper.cpp
- src/wayland/generated/xdg-shell_wrapper.h
- src/wayland/generator/interface.cpp
- src/wayland/generator/interface.h
Fixes #1438 (see that for description of the problem). The fix is to unlink the `wl_resource` from the object when the object is destroyed. This should eliminate this and potential future bugs involving wayland objects getting destroyed early.
I've looked at libwayland to verify that:
-  `wl_resource_set_implementation()` is  extremely low cost (just 3 assignments)
- libwayland doesn't assume these values are non-null
> Clear wl_resource implementation on destroy

- src/wayland/generated/wayland_wrapper.cpp
- src/wayland/generated/wayland_wrapper.h
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.cpp
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.h
- src/wayland/generated/xdg-output-unstable-v1_wrapper.cpp
- src/wayland/generated/xdg-output-unstable-v1_wrapper.h
- src/wayland/generated/xdg-shell-unstable-v6_wrapper.cpp
- src/wayland/generated/xdg-shell-unstable-v6_wrapper.h
- src/wayland/generated/xdg-shell_wrapper.cpp
- src/wayland/generated/xdg-shell_wrapper.h
- src/wayland/generator/emitter.cpp
- src/wayland/generator/interface.cpp
- src/wayland/generator/interface.h
- tests/miral/generated/server-decoration_wrapper.cpp
- tests/miral/generated/server-decoration_wrapper.h
Fixes #1438. The sequel to #1439 because it was broken (#1445) and had to be reverted (#1446). The problem was callbacks were not getting handled correctly, which I have now fixed. The root cause is tied up with messiness around our Wayland object destruction paths as better explained in #1447.
> Lets try again: clear wl_resource implementation on destroy

- src/platforms/rpi-dispmanx/CMakeLists.txt
- src/platforms/rpi-dispmanx/buffer_allocator.cpp
- src/platforms/rpi-dispmanx/buffer_allocator.h
- src/platforms/rpi-dispmanx/display_buffer.cpp
- src/platforms/rpi-dispmanx/display_buffer.h
- src/platforms/rpi-dispmanx/helpers.cpp
- src/platforms/rpi-dispmanx/helpers.h
This provides an immense performance improvement, so Mir is actually useable.
> rpi-dispmanx: Use DispmanX overlays when possible

- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
Handle failure to open both abstract and ordinary X11 sockets. (Fixes: #1449)
In confined environments we may not be able to open both sockets. We don't need to fail unless neither opens: we can continue with the working socket.
Specifically, in a confined snap we can't bind to the abstract socket. It looks as though the abstract socket was added to handle some selinux confined environments. Either way Mir should "just work".
> Handle failure to open both abstract and ordinary X11 sockets

- debian/rules
These were missed in the MirAL 3.0 merge, causing the packages to fail to build.
> debian/rules: Update missed references to libmiral3 to libmiral4

- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
Dead code red code
It appears we inherited this from Weston, which apparently uses X11 to draw window frames. We do no such thing, and have no need of this code.
> Remove unused visual and color map

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
All these methods can be `const`, not sure why they weren't.
> XCBConnection: make methods const

- src/include/server/mir/frontend/surface_stack.h
- src/include/server/mir/shell/surface_stack.h
- src/include/server/mir/shell/surface_stack_wrapper.h
- src/server/scene/surface_stack.cpp
- src/server/scene/surface_stack.h
- src/server/shell/surface_stack_wrapper.cpp
- tests/include/mir/test/doubles/mock_surface_stack.h
- tests/integration-tests/session_management.cpp
- tests/unit-tests/scene/test_application_session.cpp
- tests/unit-tests/scene/test_surface_stack.cpp
This allows a user of the fronted surface to query the stacking order of a specific set of surfaces. This API will be used by the X11 window manager to inform the X server of the correct window stacking order (which is necessary for correct input dispatch).
> frontend::SurfaceStack: add stacking_order_of()

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
We're supposed to check if the XCB connection has errors immediately after creating it, but instead we were initializing the rest of the wm before making the check. If the check failed, the wm was left in-tact with an invalid connection.
With this PR the connection checks itself before doing anything, and throws if there's an error. The exception is caught by `XWaylandServer::connect_wm_to_xwayland()` and treated like other XWayland errors. The logic for retrying a few times and then giving up is already implemented (change `connect_to_fd()` to always throw if you want to test this out).
> Handle XCB startup errors better

- src/miral/basic_window_manager.cpp
- src/server/frontend_wayland/window_wl_surface_role.cpp
Activates a surface immediately if is has a buffer on first commit. Fixes #936. Tested by https://github.com/MirServer/wlcs/pull/160.
> immediately activate surface with a buffer

- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_wayland/wl_subcompositor.cpp
- src/server/frontend_wayland/wl_subcompositor.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/server/frontend_wayland/wl_surface_role.h
- src/server/frontend_xwayland/xwayland_surface_role.cpp
- src/server/frontend_xwayland/xwayland_surface_role.h
This fixes some problems with subsurfaces mapping and unmapping, and removes the now-unneeded `visibility()` function from the window role interface. This should get simpler once we sort out buffer streams.
> Wayland: move visibility() logic into commit()

- src/server/frontend_wayland/wayland_input_dispatcher.cpp
- src/server/frontend_wayland/wl_pointer.cpp
- src/server/frontend_wayland/wl_pointer.h
- src/server/frontend_wayland/wl_subcompositor.cpp
- src/server/frontend_wayland/wl_subcompositor.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/server/frontend_wayland/wl_touch.cpp
- src/server/frontend_wayland/wl_touch.h
First of all, once we make each buffer stream an input surface, all of this nonsense will go away. What we have now is a whole input dispatch system separate from the main input dispatch system just for giving input events to the right subsurface. That being said, we might as well do it right. When combined with #1462, all tests added in https://github.com/MirServer/wlcs/pull/156 should now pass.
> Wayland: dispatch pointer and touch input more correctly

- src/include/server/mir/scene/legacy_scene_change_notification.h
- src/include/server/mir/scene/null_observer.h
- src/include/server/mir/scene/observer.h
- src/include/server/mir/shell/surface_stack.h
- src/include/server/mir/shell/surface_stack_wrapper.h
- src/server/input/cursor_controller.cpp
- src/server/scene/legacy_scene_change_notification.cpp
- src/server/scene/null_observer.cpp
- src/server/scene/surface_stack.cpp
- src/server/scene/surface_stack.h
- src/server/shell/surface_stack_wrapper.cpp
- tests/include/mir/test/doubles/mock_surface_stack.h
- tests/integration-tests/session_management.cpp
- tests/unit-tests/compositor/test_multi_threaded_compositor.cpp
- tests/unit-tests/scene/test_application_session.cpp
- tests/unit-tests/scene/test_legacy_scene_change_notification.cpp
- tests/unit-tests/scene/test_surface_stack.cpp
Gives a scene observer the set of surfaces a reorder affected. This will improve performance in some cases (for example, the XWayland window manager can ignore notifications about Wayland surfaces being raised)
> Report affected surfaces in the surfaces_reordered() call

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wayland_connector.h
- src/server/frontend_wayland/wayland_default_configuration.cpp
- We have to pass the display, shell, seat, output manager through a number of functions to create Wayland extensions
- When an extension requires a new global, all these signatures have to be updated
- `mf::get_supported_extensions()` can fall out of sync with actual supported extensions
- Creating the right extensions if the correct names are enabled is manual
- Somewhat convoluted code structure with a class inside a function
- Add a `WaylandExtensions::Context` that can be more easily passed around and added to
- Add `internal_extension_builders`. This is used both to build extensions and to return the list of supported extensions
- Flatten and clean up the code
> Clean up Wayland extension building

- src/server/frontend_xwayland/CMakeLists.txt
- src/server/frontend_xwayland/xwayland_cursors.cpp
- src/server/frontend_xwayland/xwayland_cursors.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
We were loading a number of cursors with xcursor but only using the default pointer. We need to load the pointer and set it as the cursor for the root window or else an ugly X will appear as the cursor in some apps (such as GTK apps). This splits the cursor loading logic into its own file, and only loads the default cursor that we need. If we need additional cursors in the future for whatever reason extending it to do more would be easy.
> Split out and refactor xcursor loading

- debian/rules
Nothing outside Mir should link to libmirclient directly. So drop the libmirclient.so symlink. (Fixes PPA builds)
> Drop the libmirclient.so symlink

- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wayland_connector.h
- src/server/frontend_wayland/wayland_default_configuration.cpp
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
- src/server/frontend_xwayland/xwayland_wm_shell.cpp
- src/server/frontend_xwayland/xwayland_wm_shell.h
If the XWayland server is not told the correct surface stacking order, the desktop will look correct but input will go to the wrong surfaces. Our current solution is to raise a surface when it gains focus, but this is  a bug waiting to happen when someone uses X apps on a desktop that, for example, has focus follow pointer.
To get the correct stacking order we need to plumb the `frontend::SurfaceStack` all the way through to the XWayland window manager, so it can add a scene observer. The wm also has to maintain a map of scene surfaces to XCB windows, and methods are added to allow XWayland surfaces to update that mapping when scene surfaces are created or destroyed. A set of scene surfaces is also added, which is not strictly necessary but prevents us from having to build and destroy it …
> Stack X11 surfaces correctly on the XWayland server

- src/platforms/mesa/server/kms/display.cpp
- src/platforms/mesa/server/kms/real_kms_output_container.cpp
- tests/unit-tests/platforms/mesa/kms/test_display.cpp
DRM will return `EOPNOTSUPP` when attempting to access the KMS APIs on a device
node which does not support KMS.
We can hit this if `drmCheckModesettingSupported` is inconclusve (because, for example,
we're on an ARM device where the GPU has no PCI address).
This is the case on the Raspberry Pi 4. `drmCheckModesettingSupported` is inconclusive,
because of course it is, but the V3D DRM node does not support modesetting.
> mesa-kms: Handle EOPNOTSUPP from drmModeGetResources.

- examples/client/spinner.cpp
For some reason nothing complained that we didn't have a `return` statement
in a function declared as returning an int?!
> mir_demo_client_wayland_egl_spinner: Return a value from main()

- debian/control
- tools/mir-smoke-test-runner.sh
For the moment we don't use the return value to PASS/FAIL the test, as
eglinfo doesn't support selecting the platform to test.
There's an upstream branch which supports dumping the info for a specific
platform; should that land we can then gate on the Wayland and X11 EGL
platforms being supported.
Even before that, the output can be helpful for understanding the rest of
the mir-smoke-test-runner output.
> mir-smoke-test-runner: Start with Mir's eglinfo

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
Please note that I remove a `MultiplexingDispatchable` that we don't appear to need. If there is any purpose for the indirection, let me know.
> More XWayland cleanup

- cmake/MirCommon.cmake
- tests/unit-tests/graphics/test_display_configuration.cpp
[LTTNG documentation](https://lttng.org/man/3/lttng-ust/v2.12/#doc-_using_lttng_ust_with_daemons) makes it clear that using `fork()` without `exec()` in applications linked to `liblttng-ust` is unsafe unless you preload `liblttng-ust-fork.so`. Do so! (Fixes #1405)
This fixes a test failure where running `ThreadedDispatcherSignalTest` immediately after the `Logind` tests would fail.
> Tests: Make LTTNG fork()-safe

- .travis.yml
- spread.yaml
Fedora 30 builds are passing, and Fedora 32 is out
> Update Fedora builds

- cmake/MirCommon.cmake
We *were* stringifying command + arguments and passing that as the command
to execute. For example, "wlcs --gtest_filter=foo" was being treated
as a single argument, resulting in the test failing to find a binary called
`wlcs --gtest_filter=foo` rather than finding a `wlcs` binary and passing
`--gtest_filter=foo` as an argument.
> cmake: Fix mir_discover_external_gtests.

- tests/mir_test_framework/process.cpp
- tests/unit-tests/console/test_logind_console_services.cpp
* Log when mtf::Process fails to terminate the process, rather than silently leave a process hanging around
* Capture `dbusmock`'s stderr in `LogindConsoleServices` tests
* Provide a more complete mock environment in some `LogindConsoleServices` tests so the code doesn't needlessly spew errors to the log
> A few minor test cleanups

- cmake/MirCommon.cmake
- tools/discover_gtests.sh
The umockdev tests work by LD_PRELOADing libumockdev-preload.so.0. Unfortunately, the
LD_PRELOAD of liblttng-ust-fork.so overrides this, causing the tests to fail.
Instead coalesce all the LD_PRELOADs in the environment into a single call, so
both libumockdev-preload.so.0 and liblttng-ust-fork.so get loaded.
> cmake: Handle tests which also set LD_PRELOAD in their environment.

- src/server/frontend_xwayland/xwayland_default_configuration.cpp
- tests/performance-tests/test_glmark2-es2-mir.cpp
Fix performance tests.
Drop MIR_SOCKET legacy, use integrated X11 support
> Fix performance tests

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_wm.cpp
Handling fatal XCB errors is trickier because we don't have the infrastructure to stop the X server. Both the current code and this PR will result in fatal Mir errors, but at least here the problem is made obvious.
> XWaylandWM::handle_events(): make sure there is no XCB error

- src/server/frontend_wayland/wayland_input_dispatcher.cpp
- src/server/frontend_wayland/wayland_input_dispatcher.h
- src/server/frontend_wayland/wayland_surface_observer.cpp
- src/server/frontend_xwayland/xwayland_surface_observer.cpp
Finally got around to fixing the useless `non-input event type 11` warnings
> Make WaylandInputDispatcher only take input events (fixes #1047)

- include/wayland/mir/wayland/wayland_base.h
- src/server/frontend_wayland/wl_subcompositor.cpp
- src/server/frontend_wayland/wl_subcompositor.h
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/wl_surface.h
- src/wayland/wayland_base.cpp
Stacked on #1512 
Alternative to #1513 
Makes the destroyed flag part of `wayland::Resource` and adds a `wayland::Weak` class which uses it to allow objects to hold a weak reference to a Wayland object.
`std::shared_ptr<bool>`s are kept around so that `wayland::Resource` can manage them. If instead they were replaced by some sort of strongly typed pointer, the implementation would be messier and every derived class would need to be modified. With this system, new code should only use the destroyed flag indirectly via `wayland::Weak`.
This PR has one of two possible interfaces for `wayland::Weak`. This one has an optional-like interface. The other one has `.with()` and `.with_opt()` methods to access the underlying class. I think this one is cleaner, but I'm not going to put up a fight …
> Add wayland::Weak (optional-like interface)

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
Error logging is hidden behind the verbose X11 flag because there are a number of errors in normal use and showing them isn't particularly useful. Still something we should have for debugging purposes.
> (when verbose logging) warn on X11 errors

- src/server/frontend_xwayland/xwayland_connector.cpp
- src/server/frontend_xwayland/xwayland_connector.h
I don't see any reason for a lambda to be used here, so I'm going to assume it was a historical artifact
> Refactor XWaylandConnector

- examples/miral-shell/desktop/mir-shell.sh
- src/platform/options/default_configuration.cpp
- tests/mir_test_framework/async_server_runner.cpp
- tests/mir_test_framework/stubbed_server_configuration.cpp
- tests/mir_test_framework/test_display_server.cpp
- tools/mir-smoke-test-runner.sh
Remove the mirclient related configuration options from the standard configuration and add them to the test configurations.
(We can't yet remove them for the tests, as we still use the mirclient API for a lot of end-end tests.)
> Remove the mirclient related configuration options

- CMakeLists.txt
Default to ld linker. (Fixes: #1525)
There's no longer a big speed advantage over ld to gold, and the latter is failing on several targets.
Let's see if this works in the PPA
> Default to ld linker

- debian/rules
Disable LTO which is failing for armhf and ppc64el in PPA builds. (Fixes: #1525)
Hopefully this won't be needed medium term.
> Disable LTO which is failing for armhf and ppc64el in PPA builds

- CMakeLists.txt
- debian/rules
- include/core/mir_toolkit/deprecations.h
- spread/build/ubuntu/task.yaml
- src/server/console/CMakeLists.txt
- src/server/console/minimal_console_services.cpp
- tests/mir_test_doubles/CMakeLists.txt
- tests/mir_test_doubles/mock_drm.cpp
- tests/unit-tests/CMakeLists.txt
- tests/unit-tests/console/test_minimal_console_services.cpp
We're no longer trying to build for Xenial, so drop a bunch of workarounds.
> Forget Xenial

- examples/miral-kiosk/kiosk_main.cpp
- examples/miral-shell/shell_main.cpp
- src/miral/external_client.cpp
- src/miral/launch_app.cpp
- src/miral/launch_app.h
- src/miral/runner.cpp
[MirAL] Drop the --startup-apps configuration option from MirRunner. (Fixes: #1531)
This isn't needed as a feature of MirRunner, as it can be done better using other MirAL features.
In case anyone is using it in miral-kiosk or miral-shell, and to demonstrate, it is re-implemented for these.
> [MirAL] Drop --startup-apps

- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_cursors.h
- src/server/frontend_xwayland/xwayland_server.h
- src/server/frontend_xwayland/xwayland_surface.h
- src/server/frontend_xwayland/xwayland_surface_observer_surface.h
- src/server/frontend_xwayland/xwayland_surface_role_surface.h
- src/server/frontend_xwayland/xwayland_wm.h
This wasn't causing any problems, but I noticed we weren't doing it. I also removed the explicit delete of some move constructors, as I believe they are deleted by default when the copy constructor is.
> Delete copy constructors and asignment operators for XWayland classes

- debian/libmiral4.symbols
- include/miral/miral/toolkit_event.h
- src/miral/toolkit_event.cpp
Don't use size_t in an ABI checked by a symbols file. (Fixes: #1539)
> Don't use size_t in an ABI checked by a symbols file

- debian/rules
No LTO on arm64.
More wallpaper over cracks: The LTO build failures seen in Launchpad are now happening on arm64. This keeps the PPA building, but it would be good to figure out the root cause.
> No LTO on arm64

- src/server/frontend_xwayland/CMakeLists.txt
- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
- src/server/frontend_xwayland/xwayland_spawner.cpp
- src/server/frontend_xwayland/xwayland_spawner.h
This new class is responsible for waiting for X11 clients to connect, and calling a callback when they do which starts the server. This simplifies logic in `XWaylandServer`. For now the spawner is owned by the server, but later ownership of it will get moved to the connector.
> Add XWaylandSpawner class

- debian/libmiral4.symbols
- examples/example-server-lib/floating_window_manager.cpp
- include/miral/miral/window_manager_tools.h
- src/miral/basic_window_manager.cpp
- src/miral/basic_window_manager.h
- src/miral/symbols.map
- src/miral/window_management_trace.cpp
- src/miral/window_management_trace.h
- src/miral/window_manager_tools.cpp
- src/miral/window_manager_tools_implementation.h
Add WindowManagerTools::active_application_zone(). (Fixes: #1530)
Also uses it in the miral-shell "floating" window manager.
> Add WindowManagerTools::active_application_zone()

- debian/control
Ensure that libmirclient-dev gets removed. (Fixes: #1518)
> Ensure that libmirclient-dev gets removed

- debian/libmiral4.symbols
Fix libmiral4.symbols
Causes FTBFS in LP
> Fix libmiral4.symbols

- include/platform/mir/options/configuration.h
- src/platform/options/default_configuration.cpp
- src/platform/symbols.map
Drop --name option that's been unused since we removed the "Nested Mir" quasi-platform
> Drop --name option

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
[X11] Treat COMPOUND_TEXT as a string type. (Fixes: #1552)
> [X11] Treat COMPOUND_TEXT as a string type

- src/server/frontend_xwayland/xwayland_connector.cpp
- src/server/frontend_xwayland/xwayland_connector.h
- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
Moves ownership of the `XWaylandSpawner` out of the `XWaylandServer` and into the `XWaylandConnector` which owns it. Some logic is added to make this all thread safe (I don't believe it was entirely thread safe before). Where this is going is the `XWaylandServer` will fork the server process on construction, kill it on destruction and have no other responsibilities.
> Move XWayland spawner into connector

- src/server/frontend_xwayland/xwayland_connector.cpp
- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
The `XWaylandServer` should fork off the XWayland process on construction and kill it on destruction, rather than the 2-step initialization we were doing. In the process, the spawn thread and logic that waits for the XWayland server to quit is removed.
> XWaylandServer: fork on construction

- include/platform/mir/graphics/platform.h
- src/platforms/eglstream-kms/server/platform_symbols.cpp
- src/platforms/x11/graphics/graphics.cpp
Add a `PlatformPriority::hosted` probe value, so we can select a hardware-accelerated X11 platform over a software-rasterised `mesa-kms` platform, and check whether or not there is any output hardware before calling the `eglstream-kms` platform appropriate.
Partially fixes: #1543. The only thing now left is that it can select `eglstream-kms`, which will work until trying to load the *input* platform, which will fail. Fixing that requires a more significant rework of platform probing, tying input & graphics platforms together.
> Minor platform probing improvements

- src/platforms/eglstream-kms/server/platform_symbols.cpp
We need to capture the `EGLContext` by reference if we want it to be valid when we come to tear it down!
> eglstream-kms: Actually clean up context in probe

- src/server/frontend_xwayland/xwayland_wm.cpp
This allows the X server to exit gracefully (no more "did not close, killing it" messages)
> XWaylandWM: close all clients when shutting down

- src/server/frontend_xwayland/xwayland_connector.cpp
- src/server/frontend_xwayland/xwayland_connector.h
- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
We are going to want to be able to gracefully shut down the server on a window manager error. This will be easier to do when the server does not own the window manager.
> Move wm ownership from server to connector

- debian/libmiral4.symbols
- include/miral/miral/external_client.h
- src/miral/CMakeLists.txt
- src/miral/external_client.cpp
- src/miral/open_desktop_entry.cpp
- src/miral/open_desktop_entry.h
- src/miral/symbols.map
[MirAL] Add ExternalClientLauncher::snapcraft_launch().
This introduces support for launching other snaps via the proposed desktop-launch interface. While that interface has yet to land in snapd the client-side code needed is unlikely to change.
> [MirAL] Add ExternalClientLauncher::snapcraft_launch()

- debian/libmiral4.symbols
- include/miral/miral/wayland_extensions.h
- src/miral/symbols.map
- src/miral/wayland_extensions.cpp
- tests/miral/wayland_extensions.cpp
[MirAL] Drop deprecated functions from WaylandExtensions. (Fixes: #1559)
> [MirAL] Drop deprecated functions from WaylandExtensions

- src/server/frontend_wayland/wayland_input_dispatcher.cpp
Since these lamdas do not outlive the calling scope there is no reason to specify exactly what and how they capture. Remove the noise.
> WaylandInputDispatcher: simplify lambda captures

- include/wayland/mir/wayland/wayland_base.h
Allow a `wayland::Weak` to be explicitly created null, and handle the case where it is created with a null pointer to a resource
> Allow wayland::Weak to be created null

- src/server/frontend_xwayland/xwayland_connector.cpp
- src/server/frontend_xwayland/xwayland_connector.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
This moves ownership of the `ThreadedDispatcher` that dispatches X11 events into the XWayland connector. `XWaylandWM::handle_events()` is made public and called by the connector. This allows handling fatal X11 errors (such as the XWayland server crashing) without bringing down Mir and any non-X11 windows.
> Move X11 dispatcher to connector

- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
Previously we made `XWaylandServer` fork on construction and removed the window manager logic from it. This cleans up the mess that was left over. It transitions from methods that set mutable class members to standalone initialization functions that are used to initialize const members. If the diff is confusing going through commit by commit might help.
> More cleanup of XWaylandServer

- src/server/frontend_xwayland/xwayland_connector.cpp
- src/server/frontend_xwayland/xwayland_connector.h
There's thread safety issues if this ever happens. Lets make sure it doesn't.
> XWaylandConnector: error if destroyed without being stopped

- debian/control
- debian/libmirwayland0.install
- debian/libmirwayland1.install
- include/wayland/mir/wayland/wayland_base.h
- src/wayland/CMakeLists.txt
- src/wayland/symbols.map
- src/wayland/wayland_base.cpp
Break out management of the destoryed flag into a new `LifetimeTracker` class so non-resource objects can inherit from it as well. Future PR will make `WindowWlSurfaceRole` use it.
> wayland::LifetimeTracker

- include/wayland/mir/wayland/wayland_base.h
This is useful to easily compare the contained resource with another, or in if assignments:
```c++
if (auto const surface = wl_surface.or_null())
{
use(surface);
}
```
EDIT: changed example slightly to reflect how things are actually commonly named in the code
> wayland::Weak: add .nullable_ptr() method

- include/wayland/mir/wayland/wayland_base.h
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/wayland/wayland_base.cpp
Classes that inherit from `WindowWlSurfaceRole` often also get a `LifetimeTracker` from inheriting from a Wayland resource, but virtual inheritance is used to make sure there's only ever one. `LifetimeTracker::mark_destroyed()` is added to allow classes to mark themselves as destroyed at the beginning of their destructors. Without it the calls to `shell->destroy_surface(session, scene_surface);` result in crashes.
> Use LifetimeTracker for WindowWlSurfaceRole

- src/server/frontend_xwayland/xwayland_server.cpp
I have no idea why this environment variable is set. @RAOF noted previously that it was a bit odd. Unless there are any objections, I say we take it out, and put it back in with a comment if that causes any problems.
> Do not force XWayland EGL to use DRM

- src/server/frontend_wayland/xdg_shell_stable.cpp
- src/server/frontend_wayland/xdg_shell_v6.cpp
Replace the complicated and error prone direct usage of destroyed flags with `wayland::Weak`
> Use wayland::Weak in XDG shell implementations

- src/client/input/xkb_mapper.cpp
[input] Use xkb scan code to identify modifier keys. (Instead of unreliable key_sym). (Fixes: #1515)
I've not been able to figure out why `xkb_state_key_get_one_sym()` sometimes identifes an Alt key release as `XKB_Meta_L` but using the scan code to identify the modifier keys is reliable.
> [input] Use xkb scan code to identify modifier keys

- include/wayland/mir/wayland/wayland_base.h
- tests/unit-tests/wayland/CMakeLists.txt
- tests/unit-tests/wayland/test_wayland_weak.cpp
- Add tests for `wayland::Weak`
- Makes`LifetimeTracker::mark_destroyed()` protected
- Fix (and tests) `Weak == Weak` in the case of an old and new resource with the same address
- Add `Weak == Resource` operator (unlike previously discussed, it compares with a reference to a resource, not a nullable pointer)
- Add a `!=` operator (without it, != seems to implicitly cast both sides to bools?)
- Move `as_nullable_ptr()` to be a standalone function as Alan previously suggested
I'm not planning any more changes to `wayland::Weak` in the immediate future (but you never know what will come up)
> Improve and test wayland::Weak

- src/server/input/key_repeat_dispatcher.cpp
- src/server/input/key_repeat_dispatcher.h
[input] Don't lock the repeat dispatcher while repeating events. (Fixes: #1617,  #1607)
> [input] Don't lock the repeat dispatcher while repeating events

- src/server/input/key_repeat_dispatcher.cpp
- src/server/input/key_repeat_dispatcher.h
- tests/unit-tests/input/test_key_repeat_dispatcher.cpp
Prevents future issues like #1617
A bit unrelated but also adds a test for key repeats not getting fired for meta keys.
> Minimize locking in KeyRepeatDispatcher

- src/server/graphics/offscreen/display.cpp
It turns out we check for EGL version strictly equal to 1.4,
but Mesa has returned 1.5 for a while (and NVIDIA has returned
1.5 for*ever*).
There's no reason we won't work with newer minor EGL versions,
so don't fail if we find them.
I'm not sure how valuable this is, given that it's been broken
for *some time* and no-one has noticed, but we might as well
do the easy fix.
> Unbreak offscreen renderer.

- examples/miral-shell/shell_main.cpp
- include/miral/miral/toolkit_event.h
[miral-shell] Use key codes, not scan codes to identify keys. (Fixes: #1627)
> [miral-shell] Use key codes, not scan codes to identify keys

- debian/control
[mir_performance_tests] Do not recommend glmark2-es2-mir.
We don't use it, drop it from depends.
> [mir_performance_tests] Do not recommend glmark2-es2-mir

- tests/performance-tests/system_performance_test.cpp
- tests/performance-tests/system_performance_test.h
[mir_performance_tests] Kill clients started in regression_test_1563287. (Fixes: #1637)
> [mir_performance_tests] Kill clients started in regression_test_1563287

- src/server/console/logind_console_services.cpp
- src/server/console/logind_console_services.h
LogindConsoleServices should release control on destruction. (Fixes: #1635)
Also fixes at least part of #1631 and #1632.
> LogindConsoleServices should release control on destruction

- src/platforms/wayland/displayclient.cpp
- src/server/frontend_wayland/output_manager.cpp
Report rotated output sizes (a workaround until we correctly support transforms for outputs and surfaces)
Some clients (such as i3/Xwayland) legitimately think they have control of an output and get confused when we report inconsistent size and orientation.
We should support transforms, but until then, make the size consistent with the reported orientation.
Fixes: #1629, https://forum.snapcraft.io/t/mir-kiosk-problem-with-rotation/18239
> [Wayland] Report rotated output sizes

- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_stable.cpp
- src/server/frontend_wayland/xdg_shell_v6.cpp
[Wayland] Fix focus issues with popups. (Fixes: #1625)
A popup ought to be handled as either a `mir_window_type_gloss` or a `mir_window_type_menu` depending upon whether it is configured with a `grab`.
This avoids unexpectedly shifting the focus to an ungrabbed popup.
> [Wayland] Fix focus issues with popups

- src/platforms/eglstream-kms/server/platform.cpp
- src/platforms/eglstream-kms/server/platform.h
- src/server/frontend_xwayland/xwayland_server.cpp
Provide a way for platforms to tweak the Xwayland options and use it for eglstream-kms. (Fixes: #1634)
We don't have a good way for platforms to pass config options to the front end, using an environment variable is a bad way but it works.
> Provide a way for platforms to tweak the Xwayland options and use it for eglstream-kms

- tests/mir_test_framework/async_server_runner.cpp
- tests/mir_test_framework/headless_test.cpp
Don't frig with the shutdown sequence in AsyncServerRunner. (Fixes: #1642)
Moves a workaround for a problem with stubbed graphics that can cause issues with real graphics.
> Don't frig with the shutdown sequence in AsyncServerRunner

- examples/miral-shell/miral-app.sh
- src/miral/external_client.cpp
- tests/miral/external_client.cpp
Allow GDK to try x11 if wayland fails. (Fixes: #1621)
Some apps need GDK to fall back to X11. (Which is the default, but firefox doesn't follow the GDK default unless MOZ_ENABLE_WAYLAND is set and there might be others.
> Allow GDK to try x11 if wayland fails

- debian/rules
Disable acceptance_tests on arm64 PPA builds. (Fixes: #1505)
Some of these tests appear to fail only because arm64 builders are too slow for hardcoded realtime waits.
> Disable acceptance_tests on arm64

- include/platform/mir/graphics/display.h
- include/test/mir/test/doubles/null_display.h
- include/test/mir_test_framework/headless_test.h
- include/test/mir_test_framework/stub_server_platform_factory.h
- src/platforms/eglstream-kms/server/display.cpp
- src/platforms/eglstream-kms/server/display.h
- src/platforms/gbm-kms/server/kms/display.cpp
- src/platforms/gbm-kms/server/kms/display.h
- src/platforms/rpi-dispmanx/display.cpp
- src/platforms/rpi-dispmanx/display.h
- src/platforms/wayland/display.cpp
- src/platforms/wayland/display.h
- src/platforms/x11/graphics/display.cpp
- src/platforms/x11/graphics/display.h
- src/server/graphics/offscreen/display.cpp
- src/server/graphics/offscreen/display.h
- src/server/scene/default_configuration.cpp
- tests/acceptance-tests/test_new_display_configuration.cpp
- tests/include/mir/test/doubles/mock_display.h
- tests/mir_test_framework/headless_in_process_server.cpp
- tests/mir_test_framework/headless_test.cpp
- tests/mir_test_framework/stub_server_platform_factory.cpp
- tests/mir_test_framework/stubbed_graphics_platform.cpp
- tests/miral/active_outputs.cpp
- tests/platform_test_harness/graphics_platform_test_harness.cpp
- tests/unit-tests/platforms/test_display.h
This is only used to get a `gl::ContextSource` out of a `Display`, which we can just do a direct `dynamic_cast<>` for now.
In the near future this will be moved to the `RenderingPlatform` instead, as a part of allowing multiple display platforms to load, but for now leave it where it is.
> platform: Drop the NativeDisplay interface

- tests/acceptance-tests/test_client_input.cpp
Extend the timeout for TestClientInput setup. (This was one of the failures on arm64 and appears intermittently on amd64)
This is just a timeout that prevents the test hanging, so a large value has no effect on normal execution.
> Extend the timeout for TestClientInput setup

- src/platforms/evdev/fd_store.cpp
- src/platforms/evdev/fd_store.h
Keep the touchpad FD during suspend/resume. (Fixes: #1612)
Less a fix than a workaround. (I haven't tracked down the root cause of weirdness.)
> Keep the touchpad FD during suspend/resume

- src/miral/wayland_extensions.cpp
> Don't give the supplied Wayland extension filter the choice of supporting extensions that are not optionally supported

- src/include/server/mir/input/cursor_listener.h
- src/platforms/evdev/platform.cpp
- src/platforms/evdev/platform.h
- src/server/input/basic_seat.cpp
- src/server/input/cursor_controller.cpp
- src/server/input/cursor_controller.h
- src/server/input/seat_input_device_tracker.cpp
- src/server/input/seat_input_device_tracker.h
- tests/acceptance-tests/server_configuration_wrapping.cpp
- tests/include/mir/test/doubles/mock_cursor_listener.h
- tests/integration-tests/input/test_cursor_listener.cpp
- tests/mir_test_framework/test_wlcs_display_server.cpp
- tests/unit-tests/input/evdev/test_evdev_input_platform.cpp
- tests/unit-tests/input/test_cursor_controller.cpp
Track whether there's a usable pointing device and hide/show cursor accordingly. (Fixes #594, fixes #1660)
> Track whether there's a usable pointing device and hide/show cursor accordingly. (Fixes #594)

- include/platform/mir/graphics/platform.h
- include/test/mir/test/doubles/null_platform.h
- src/platforms/eglstream-kms/server/platform.cpp
- src/platforms/eglstream-kms/server/platform.h
- src/platforms/gbm-kms/server/drm_native_platform.h
- src/platforms/gbm-kms/server/kms/platform.cpp
- src/platforms/gbm-kms/server/kms/platform.h
- src/platforms/rpi-dispmanx/display_platform.cpp
- src/platforms/rpi-dispmanx/display_platform.h
- src/platforms/rpi-dispmanx/platform.cpp
- src/platforms/rpi-dispmanx/platform.h
- src/platforms/wayland/platform.cpp
- src/platforms/wayland/platform.h
- src/platforms/x11/graphics/platform.cpp
- src/platforms/x11/graphics/platform.h
- tests/mir_test_framework/platform_graphics_throw.cpp
- tests/mir_test_framework/stubbed_graphics_platform.cpp
There are apparently still bits of the platform interface that can be hewn away!
> platform: Drop the entirely-unused NativeDisplayPlatform interface

- tests/performance-tests/test_compositor.cpp
- tests/performance-tests/test_glmark2-es2.cpp
Use GTest's annotation support to record the GLMark2
score and compositor performance test's FPS.
Test runners can use the `--gtest_output` flag to get
a JSON or XML file with the results in a location of
their choice.
> performance tests: Record detailed results

- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
I've found this to be a more reliable way to check if the process is running than `kill(pid, 0) == 0`. It also results in the process being reaped, so we don't end up with a bunch of zombies. It's not safe to call `waitpid()` after it has returned that the process exited (the PID may be reused) so we only call it if the process is still marked as `running`.
> Add XWaylandServer::is_running()

- include/platform/mir/graphics/egl_extensions.h
- include/platform/mir/graphics/egl_logger.h
- src/platform/graphics/CMakeLists.txt
- src/platform/graphics/egl_extensions.cpp
- src/platform/graphics/egl_logger.cpp
- src/platform/symbols.map
- src/platforms/eglstream-kms/server/platform_symbols.cpp
- src/platforms/gbm-kms/server/kms/platform_symbols.cpp
- src/platforms/x11/graphics/graphics.cpp
This is a fairly minimal implementation using `EGL_KHR_debug`. Followup work can improve the debug messages printed by tagging objects like “this is the rendering thread”, “this is the EGL context used for buffer allocation”, “this is the EGL context used for a `DisplayBuffer`” and so on.
> Enable EGL_KHR_debug extension on --debug

- src/server/shell/abstract_shell.cpp
This was both obviously wrong, and obviously lacking tests.
This fixes the former problem, the latter should fall out of implementing pointer-constraints-unstable-v1.
> Fix the confine-pointer logic in AbstractShell

- tests/performance-tests/test_compositor.cpp
- tests/performance-tests/test_glmark2-es2.cpp
Because it's very hardware specific, there's no point failing the performance tests here.
> performance: do not fail performance tests

- debian/control
- debian/mir-test-tools.install
- debian/mir-wlcs-integration.install
- tests/mir_test_framework/CMakeLists.txt
Split the wlcs related libraries out of mir-test-tools and into a new mir-wlcs-integration package
> New mir-wlcs-integration package

- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_xwayland/xwayland_surface_role.cpp
There's all sorts of pre-existing questionableness around here. One of these days someone is going to straighten it all out, but not today.
It's unclear if restoring mapped windows when they were previously hidden is a good idea, but I'm pretty sure we should **not** restore windows in any other state. Specifically, this is required for Mir to pass the foreign toplevel tests.
> Don't restore mapped window unless it was hidden

- include/common/mir/log.h
- src/client/handle_event_exception.h
- src/miral/window_management_trace.cpp
- src/platforms/x11/graphics/display.cpp
- src/platforms/x11/input/input_platform.cpp
- src/server/frontend_wayland/layer_shell_v1.cpp
- src/server/frontend_wayland/wayland_connector.cpp
- src/server/frontend_wayland/wl_surface.cpp
- src/server/frontend_wayland/xdg_shell_stable.cpp
- src/server/frontend_wayland/xdg_shell_v6.cpp
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/shell/decoration/renderer.cpp
And then fix all the places where we were accidentally invoking nasal daemons.
> log: Annotate log functions with [[gnu::format]] attributes

- src/server/frontend_wayland/layer_shell_v1.cpp
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.cpp
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.h
- src/wayland/protocol/wlr-layer-shell-unstable-v1.xml
Note that the major unstable version of layer shell is still 1, so all the changes are backwards compatible. The important change is the addition of a `.set_layer()` request. Tested in https://github.com/MirServer/wlcs/pull/173. Fixes https://github.com/MirServer/mir/issues/1589.
> Implement zwlr_layer_shell_v1 version 3

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_wm.cpp
Open for discussion.
Pros:
- No possibility of accidentally initializing an atom with the wrong name
- IMO all caps distinguish atoms in the code better and match the atom constants provided by XCB
- Obvious exactly which atoms are being used/you can copy paste from the code into google to look up an atom
Cons:
- Technically a style guide violation
- Not the most important thing for me to be doing right now (but it's already done)
(NOTE: I'm not currently working and won't respond to reviews until Friday, Posting now because I just noticed the per-rec PR merged)
> Rename XCBConnection atoms to match X11 atom names

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_surface.h
- src/server/frontend_xwayland/xwayland_wm.cpp
X11 window type [can be a list of types](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46035372549728). We were assuming there was only one type. When there was more we were gracefully handling the error, but the type was not getting set. This looks through the list of types and uses the first we know of (they are in order of preference, so this should be correct).
Fixes #1250, based on #1560
> Handle windows that specify multiple window types

- src/include/server/mir/glib_main_loop_sources.h
- src/server/glib_main_loop_sources.cpp
- src/server/run_mir.cpp
Some deployments are sending Mir a SIGHUP that was causing us to exit untidily.
Explicitly handle SIGHUP and log all signal.
> Log SIGHUP and other signals

- src/server/frontend_wayland/wl_keyboard.cpp
- src/server/frontend_wayland/wl_touch.cpp
- src/server/frontend_wayland/wl_touch.h
We already send a `wl_pointer.leave()` event using this same method, but we were not sending `wl_touch.up()` and `wl_keyboard.leave()`. The former is tested by https://github.com/MirServer/wlcs/pull/177. The latter fixes #1236.
> Send wl_touch.up() and wl_keyboard.leave() events when surface destroyed

- examples/example-server-lib/sw_splash.cpp
- examples/example-server-lib/sw_splash.h
- examples/miral-kiosk/kiosk_main.cpp
Default is to display splash. --show-splash=false suppresses it. (Fixes ~ #830)
> Add --show-splash command line option to control whether splash displays

- src/server/frontend_xwayland/CMakeLists.txt
- src/server/frontend_xwayland/xwayland_client_manager.cpp
- src/server/frontend_xwayland/xwayland_client_manager.h
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_surface.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
- src/server/scene/session_manager.cpp
- tests/unit-tests/CMakeLists.txt
- tests/unit-tests/frontend_xwayland/CMakeLists.txt
- tests/unit-tests/frontend_xwayland/test_xwayland_client_manager.cpp
Alternative to #1698, fixes #479. Allows for better switching between different windows on the same apps, and I believe may help Unity8. This version adds a `XWaylandClientManager::Session` class and uses `shared_ptr`s to that to determine when to destroy a session.
Advantages:
- Less likely to leak sessions (although it should be noted the other approach has a check in place to leaks are not silent) 
- Slightly less code
Disadvantages:
- This is (IMO) a little more complicated and less obvious to fresh eyes
- Prone to a different type of bug. If a `XWaylandClientManager::Session` outlives the manager, it will call into the manager and crash. This could be mitigated a couple ways, but that would add additional complexity.
Either is fine with me.
> [shared_ptr version] Give each XWayland app it's own session

- include/wayland/mir/wayland/wayland_base.h
- src/wayland/generated/wayland_wrapper.cpp
- src/wayland/generated/wlr-foreign-toplevel-management-unstable-v1_wrapper.cpp
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.cpp
- src/wayland/generated/xdg-output-unstable-v1_wrapper.cpp
- src/wayland/generated/xdg-shell-unstable-v6_wrapper.cpp
- src/wayland/generated/xdg-shell_wrapper.cpp
- src/wayland/generator/request.cpp
- src/wayland/symbols.map
- src/wayland/wayland_base.cpp
- tests/miral/generated/server-decoration_wrapper.cpp
This adds `mir::wayland::ProtocolError`, an exception that request handlers can throw which will result in a Wayland protocol error being sent to the client.
This is more convenient than bubbling early-returns up the call stack.
> Add an exception for Wayland protocol errors

- src/platforms/wayland/displayclient.cpp
[Wayland-platform] Compositing shouldn't block in eglSwapBuffers(). (Fixes: #1100)
> [Wayland-platform] Compositing shouldn't block in eglSwapBuffers()

- src/server/frontend_xwayland/xwayland_connector.cpp
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_surface.h
- src/server/frontend_xwayland/xwayland_wm.cpp
Including not creating a spawner if it already exists and constructing `XWaylandSurface` with actual properties instead of an event pointer. Nothing super important, but cleans the boring commits out of my xwayland-master branch.
> Minor XWayland cleanup

- src/server/frontend_xwayland/xwayland_connector.cpp
- src/server/frontend_xwayland/xwayland_server.cpp
- src/server/frontend_xwayland/xwayland_server.h
Related to #1722 and #1723. In combination with #1725, I think this fixes the race condition (though I haven't tested in a confined snap yet). This moves socket pair creation out of the `XWaylandServer` constructor, and creates the event dispatcher before creating the window manager or spawning the server. Because `XWaylandConnector`'s mutex is locked, any events will be blocked on the window manager being created and wont be dropped.
> Create event dispatcher before running server

- src/server/frontend_xwayland/xwayland_server.cpp
Don't wait for Xwayland to init before starting WM. (Fixes: #1722)
There is a race between the X11 client connecting (which triggers launching Xwayland) and the WM connecting. Something about the confined environment makes it likely the client wins the race.
If the client wins the race, our WM never processes the client window and nothing gets displayed.
There's no need to wait on SIGUSR1 before starting the WM, it will block awaiting events anyway. And, empirically, not waiting for SIGUSR1 means the WM wins the race even in the confined environment.
(This PR doesn't actually resolve the race, just fixes the outcome.)
> Don't wait for Xwayland to init before starting WM

- src/wayland/generated/wayland_wrapper.cpp
- src/wayland/generated/wlr-foreign-toplevel-management-unstable-v1_wrapper.cpp
- src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.cpp
- src/wayland/generated/xdg-output-unstable-v1_wrapper.cpp
- src/wayland/generated/xdg-shell-unstable-v6_wrapper.cpp
- src/wayland/generated/xdg-shell_wrapper.cpp
- src/wayland/generator/interface.cpp
A `static_cast` from `void*` obviously has no safety rails. But we can do better!
`wl_resource_instance_of` will tell us whether `resource` has the same implementation
as our wrapper class - basically a discount `dynamic_cast`.
We can only use it where the `wl_resource` *has* an implementation (so objects without
requests can't use this safety rail), but that covers most objects.
This is needed for the linux-dmabuf branch, as that deals with `wl_resource* buffer` which
*may* be instances of `mw::Buffer`, or may not, and the `static_cast` results in a subsequent
invalid memory access.
> Safer wayland::Foo::from(wl_resource*)

- src/include/common/mir/c_memory.h
- src/server/frontend_xwayland/xwayland_wm.cpp
- src/server/frontend_xwayland/xwayland_wm.h
Related to #1722 and #1723. It's a lot of code because XCB is messy, but all it's doing is going through the list of windows, getting their properties and setting up a `XWaylandSurface` for them the same way we do on newly created windows. This alone is not enough to fix the race condition because we don't get the `WL_SURFACE_ID` client message. See next PR for fixing that.
> Manage X11 windows that existed before window manager started

- include/platform/mir/graphics/egl_extensions.h
- spread/build/ubuntu/task.yaml
- src/platform/graphics/egl_extensions.cpp
- src/platform/symbols.map
- src/platforms/gbm-kms/server/CMakeLists.txt
- src/platforms/gbm-kms/server/buffer_allocator.cpp
- src/platforms/gbm-kms/server/buffer_allocator.h
- src/platforms/gbm-kms/server/kms/CMakeLists.txt
- src/platforms/gbm-kms/server/linux_dmabuf.cpp
- src/platforms/gbm-kms/server/linux_dmabuf.h
- src/platforms/gbm-kms/server/protocol/linux-dmabuf-unstable-v1.xml
- src/wayland/symbols.map
This is the new, improved way to do client buffer submission. Notably,
it features DRM modifier support, allowing clients to allocate fancy
driver-specific high-performance buffer formats.
Closes: #1663
> gbm-kms: Support zwp_linux_dmabuf_unstable_v1

- src/server/frontend_xwayland/xcb_connection.cpp
Use `unique_ptr` for memory management where possible and simplify error handling into one try/catch block
> Refactor XCBConnection::read_property()

- include/core/mir/geometry/dimensions.h
- include/core/mir/geometry/displacement.h
- src/server/frontend_wayland/layer_shell_v1.cpp
- src/server/frontend_wayland/window_wl_surface_role.cpp
- src/server/frontend_wayland/window_wl_surface_role.h
- src/server/frontend_wayland/xdg_shell_stable.cpp
- src/server/frontend_wayland/xdg_shell_stable.h
The immediate reason to support margin is so MATE notifications look right. This implementation creates a large `scene::Surface` uses `WindowWlSurfaceRole::set_pending_offset()` to place the `WlSurface` in the correct position. Input dispatching just works (because that's already implemented for offset surfaces), but popups need further adjustment. It might be preferable to do this a different way (such as adding a margin surface property specifically for this use case?) or we might want to merge this and see what design makes sense after the surface/window abstraction split.
Extensive refactoring of the layer shell implementation was required. I also added some protocol errors that we weren't catching before (this will probably make it fail any version of WLCS before …
> Support Layer Shell margin

- src/platforms/gbm-kms/server/buffer_allocator.cpp
- src/platforms/gbm-kms/server/buffer_allocator.h
> gbm-kms: Destroy linux-dmabuf global from Wayland mainloop.

- src/server/frontend_xwayland/xcb_connection.cpp
- src/server/frontend_xwayland/xcb_connection.h
- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_wm.cpp
Stacked on #1728. This simplifies passing around `on_success`/`on_error` callbacks. Starting to look similar to a future but I think it's still fine to have an XCB-specific concept here.
> Add XCBConnection::Handler

- src/platforms/wayland/displayclient.cpp
[wayland-platform] Report host refresh rate correctly. (Fixes: #1741)
> [wayland-platform] Report host refresh rate correctly

- benchmarks/frame-uniformity/CMakeLists.txt
- src/client/lttng/CMakeLists.txt
- src/server/report/lttng/CMakeLists.txt
This fixes the build for Mir in Fedora with our [LTO-by-default setup for package builds](https://fedoraproject.org/wiki/LTOByDefault).
> Fixes for building with LTO-by-default in Fedora

- src/server/frontend_xwayland/xwayland_surface.cpp
- src/server/frontend_xwayland/xwayland_surface.h
This allows a window to request to be undecorated by setting the decorations element of the `_MOTIF_WM_HINTS` property to 0. This fixes #1758, as well as well as removing the double-decorations seen on gedit.
> Respect motif decoration hint

- src/core/geometry/rectangles.cpp
- src/platform/graphics/gamma_curves.cpp
This is from an effort in Fedora to prepare for the GCC 11 rebase for Fedora 34.
> Fix missing #includes for GCC 11

- src/miral/static_display_config.cpp
- src/miral/static_display_config.h
- tests/miral/static_display_config.cpp
This allows mir-kiosk and other servers that use the YAML display config system to put outputs in logical groups (aka display walls). I can change the option name to `wall`, `display-wall` or something else if preferable, but IMO `group` is the most obvious.
> Add 'group' option to display config yaml

- examples/miral-kiosk/kiosk_main.cpp
Answers the question "Why does `WAYLAND_DISPLAY=wayland-mir ./bin/miral-kiosk --startup-apps weston-terminal` (built from master) fail with "Cannot launch apps when server has not started?""
> [mir-kiosk] `run_with` the `ExternalClientLauncher`

- include/miral/miral/wayland_extensions.h
- include/platform/mir/options/configuration.h
- src/miral/wayland_extensions.cpp
- src/platform/options/default_configuration.cpp
- src/platform/symbols.map
- tests/miral/wayland_extensions.cpp
This adds `--add-extensions` and `--drop-extension` options, which allow controlling enabled extensions without specifying an exhaustive list. Fixes #1757
> Allow adding and dropping Wayland extensions

- tests/performance-tests/test_glmark2-es2.cpp
This makes more sense as a performance test, as very few windows
are going to want to blend their EGL rendering with what's behind them.
Also, this makes GLMark2 eligible for composite-bypass, when that is implemented,
and that's a very interesting optimisation to be able to see when it
works (and doesn't).
> performance-tests: Use a EGL visual with no alpha channel.

- src/platforms/gbm-kms/server/linux_dmabuf.cpp
It is never correct to pass `DRM_FORMAT_MOD_INVALID` to any external API, so we don't need to be able to distinguish between “no modifier set” and “modifier set to `DRM_FORMAT_MOD_INVALID`”.
The exception here is that if the EGL driver claims support for `EGL_EXT_image_dma_buf_import_modifiers` but *also* does not list any acceptable modifiers for a format then that implies that the driver will perform dark magics on our behalf, and we should publish that format to the client with a `DRM_FORMAT_MOD_INVALID` modifier.
Allows `zwp_linux_dmabuf_unstable_v1` support to be enabled on drivers which don't support modifiers, like amdgpu.
> linux-dmabuf: More correct handling of DRM_FORMAT_MOD_INVALID

- src/platforms/gbm-kms/server/linux_dmabuf.cpp
When iteration over nested containers it's important to use the correct
iteration variable. Otherwise you might accidentally read uninitialised
memory and send that as a modifier to the client!
Fixes the weird “invalid modifier” client errors we've recently seen.
> linux-dmabuf: Fix sending invalid modifiers.

- src/platforms/wayland/display.cpp
- src/platforms/wayland/displayclient.cpp
Same reasoning as #1777 applied correctly
> wl_display_roundtrip() should be called before starting the Wayland thread

- debian/control
Makes it possible, for example, to install just the "wayland" or "X" platform without hard coding the current version.
Fixes: #1750
> [debian] Add metapackages for each of the graphics platforms

- include/platform/mir/graphics/dmabuf_buffer.h
- src/platform/graphics/CMakeLists.txt
- src/platforms/gbm-kms/server/kms/display_buffer.cpp
- src/platforms/gbm-kms/server/kms/display_buffer.h
- src/platforms/gbm-kms/server/kms/kms_output.h
- src/platforms/gbm-kms/server/kms/real_kms_output.cpp
- src/platforms/gbm-kms/server/kms/real_kms_output.h
- src/platforms/gbm-kms/server/linux_dmabuf.cpp
- tests/include/mir/test/doubles/mock_drm.h
- tests/mir_test_doubles/mock_drm.cpp
- tests/unit-tests/platforms/gbm-kms/kms/mock_kms_output.h
- tests/unit-tests/platforms/gbm-kms/kms/test_display_buffer.cpp
Client buffers submitted with the `zwp_linux_dmabuf_unstable_v1` are now possible candidates for composite-bypass.
This comes with a number of significant caveats.
Most significantly: there's no way for the compositor to suggest to the client that it should allocate buffers that are compatible with scanout (this requires [dmabuf-hints](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/8)), so whether or not a client *can* be bypassed is a function of whether or not the display hardware can cope with whatever buffer format the EGL driver chooses.
Furthermore, until we switch to the Atomic KMS API there's no way for us to usefully *query* the set of buffer formats the display hardware can scan out of, either.
> gbm-kms: Implement composite-bypass for Wayland clients

- include/platform/mir/graphics/egl_extensions.h
- src/platform/graphics/egl_extensions.cpp
- src/platform/graphics/egl_wayland_allocator.cpp
- src/platform/symbols.map
- src/platforms/eglstream-kms/server/buffer_allocator.cpp
- src/platforms/eglstream-kms/server/buffer_allocator.h
- src/platforms/eglstream-kms/server/display.cpp
- src/platforms/gbm-kms/server/buffer_allocator.cpp
- src/platforms/gbm-kms/server/linux_dmabuf.cpp
- src/platforms/rpi-dispmanx/buffer_allocator.cpp
- tests/mir_test_doubles/mock_egl.cpp
- tests/unit-tests/graphics/test_egl_extensions.cpp
I've taken a number of stabs at this. Unfortunately the variadic template function pointer variant didn't work out so well so we're left with this. It solves the problem reasonably well in a relatively small diff, so good enough. Related to #914 and improved alternative to #1804.
> Check EGL extensions before using them

- src/platforms/gbm-kms/server/buffer_allocator.cpp
- src/platforms/gbm-kms/server/buffer_allocator.h
- src/platforms/wayland/buffer_allocator.cpp
- src/platforms/wayland/buffer_allocator.h
- src/platforms/x11/graphics/buffer_allocator.cpp
- src/platforms/x11/graphics/buffer_allocator.h
Allow Mir to start without the Wayland EGL extensions on X11, Wayland and GBM/KMS. Only works in conjunction with #1806. Fixes #914.
miral-shell crashes shortly after startup (probably due to the spinner) but that can be addressed in another PR in another release. mir_demo_server works in a non-virgil VM with this and #1806.
> Support software buffers on X11, Wayland and GBM/KMS

- src/platforms/gbm-kms/server/kms/platform_symbols.cpp
This triggers a GPU OOM (issue #1801) on the Pi3 when used with default settings.
There may be due to us hanging on to buffers longer than they need to be, but
it's not clear yet.
Users who want the performance boost and are running on known hardware can
set `--bypass=true`, but by default use the safe option of `false`.
> gbm-kms: Disable bypass by default.

- src/server/frontend_wayland/wl_keyboard.cpp
This solves a minor annoyance I've had for a while. Both Weston and Sway use these values by default. GNOME-on-Wayland, on the other hand uses 33 and 500, which I would also be open to. Mostly, the delay just needs to go up.
Of course this will eventually need be configurable for accessability reasons and general preference, but building an input configuration system is a job for another day,
> Use standard key repeat values

- src/miral/external_client.cpp
- src/miral/open_desktop_entry.cpp
- src/miral/open_desktop_entry.h
Update `ExternalClientLauncher::snapcraft_launch` to reflect changes to the draft desktop-launch interface.
(This matches the current state of https://github.com/snapcore/snapd/pull/8699)
> Reflect changes to the draft desktop-launch interface
