canonical/mir

.github/workflows/spread.yml

`.clang-format` didn't get the needed love over the years.

[gha] do not require Lint to pass

---

examples/example-server-lib/tiling_window_manager.cpp
include/miral/miral/window_info.h
include/miral/miral/window_specification.h
src/miral/basic_window_manager.cpp
src/miral/window_info.cpp
tests/miral/CMakeLists.txt
tests/miral/resize_and_move.cpp

Fixes #1821. Since interactive resize and programmatic policy resize looks the same to the window manager, both are clamped. The policy can, however, change the min/max size to whatever it wants. It's documented that that is required and the tiling window manager has been updated to do that.
There was previously logic to prevent maximized windows from being moved or resized. This was untested, and it seems to be unnecessary. It has been dropped because it was breaking the tiling window manager after I made my changes. Manually moving maximized windows is still impossible in both window managers.

Clamp window resize to min/max

---

src/miral/basic_window_manager.cpp

Minor change to prevent an extra call. `update_attached_and_fullscreen_sets()` is slightly expensive and no need to call it if nothing has changed.

Only call update_attached_and_fullscreen_sets() on state change

---

.github/workflows/spread.yml
include/platform/mir/graphics/program_factory.h
src/platform/graphics/CMakeLists.txt
src/platform/graphics/linux_dmabuf.cpp
src/renderers/gl/renderer.cpp

Some of the formats¹ exposed by `EGL_EXT_image_dma_buf_import_modifiers` are
available only as `GL_OES_EGL_image_external` targets, which require some
different code in GL rendering.
We were filtering these formats out in the first cut of dmabuf support.
This implements the GL necessary to render out of external images,
so we can now expose all the formats the driver supports through to clients.
¹: Notably, multi-planar (eg: YUV) are often only supported with external images.

linux-dmabuf: Support the full range of driver-exposed formats

---

.github/workflows/spread.yml

Stop ignoring the build results for RPi stack

Restore RPi build

---

examples/client/spinner.cpp

Replace `exit()` with a signal-safe function.
See, for example, https://man7.org/linux/man-pages/man7/signal-safety.7.html

Replace `exit()` with a signal-safe function.

---

spread/build/fedora/task.yaml
src/platforms/evdev/libinput_device.cpp
src/platforms/x11/input/input_platform.cpp
src/server/frontend_wayland/wayland_input_dispatcher.cpp
tests/mir_test_doubles/mock_libinput.cpp
tests/unit-tests/input/evdev/test_libinput_device.cpp

Fixes #1813. This stops flipping vertical scroll direction on the X11 and libinput platforms. It was already unflipped on the Wayland platform.
On X11 I think this is an easy decision. I believe it's currently *always* the inverse of the host X11 environment. If that's correct, I think that's obviously wrong. IMO even when we have input settings they should not effect Mir running nested. Instead, we should respect the configuration of the host system.
For libinput, This just changes the default behavior. Normal (as opposed to natural) scrolling is the default on most Linux systems, so I think that is reasonable.

Disable natural scrolling

---

tests/acceptance-tests/test_new_display_configuration.cpp

The Launchpad builders inconsistently, but fairly regularly, fail these
tests. When this happens it looks like the tests have taken a long time,
so I suspect that they're timing out due to the builders being slow.
Just wait for up to 60s *everywhere*, to give the poor overworked builders
time to hit the deadlines!

DisplayConfigurationTest: Standardise on 60s timeouts.

---

include/wayland/mir/wayland/wayland_base.h
src/server/frontend_wayland/wl_keyboard.cpp
src/server/frontend_wayland/wl_keyboard.h
src/server/frontend_wayland/wl_pointer.cpp
src/server/frontend_wayland/wl_pointer.h
src/server/frontend_wayland/wl_seat.cpp
src/server/frontend_wayland/wl_surface.cpp
src/server/frontend_wayland/wl_surface.h
src/server/frontend_wayland/wl_touch.cpp
src/server/frontend_wayland/wl_touch.h
src/wayland/wayland_base.cpp
tests/unit-tests/wayland/CMakeLists.txt
tests/unit-tests/wayland/test_lifetime_tracker.cpp

Previously we had a mix of ways to be notified when a Wayland object was destroyed including a destroy listener system on `WlSurface` and a callback argument to the constructor of input device objects. This standardizes the process of adding and removing destroy listeners and makes it available to any wayland object or other `LifetimeTracker` subclass. This also fixes a dirty hack where we were generating bad pointers to use as IDs in `WlTouch`.

Move destroy listener functionality to LifetimeTracker

---

src/platform/graphics/linux_dmabuf.cpp
src/server/input/default_input_manager.cpp
tests/unit-tests/input/test_default_input_manager.cpp

This is from an effort in Fedora to prepare for the GCC 11 rebase for Fedora 34.
Followup to #1771.

Fix more missing #includes for GCC 11

---

examples/miral-kiosk/kiosk_main.cpp

[miral-kiosk] Allow wayland extensions to be configured in kiosks (and enable pointer confinement by default).
Allowing Wayland extensions to be configured is not very important for kiosks but "nice to have".
However, the incomplete "pointer confinement" extension works well for games in kiosk mode and is worth enabling by default.
Try, for example, mir-kiosk-neverputt.

[miral-kiosk] Allow wayland extensions to be configured in kiosks

---

src/server/frontend_wayland/wayland_default_configuration.cpp

In looking at XWayland HiDPI I was surprised to discover we don't enable the XDG output protocol by default. XDG Output helps XWayland handle scaled outputs, and fixes who knows what other usecases.
I see no potential drawbacks or security concerns to for enabling it. It doesn't allow clients to *do* anything or give any information about other clients, it just [gives additional information about outputs](https://github.com/MirServer/mir/blob/master/src/wayland/protocol/xdg-output-unstable-v1.xml).
The only reason I can think of a compositor wouldn't want to use it is to work around some client specific bug, or if the compositor didn't lay out outputs in a global coordinate space. Since Mir always has a global coordinate space and I know of no client bugs to work around, defaulting it on …

Enable xdg_output_unstable_v1 by default

---

src/server/frontend_wayland/layer_shell_v1.cpp
src/server/frontend_wayland/layer_shell_v1.h
src/server/frontend_wayland/pointer_constraints_unstable_v1.cpp
src/server/frontend_wayland/pointer_constraints_unstable_v1.h
src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h
src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/frontend_wayland/wayland_surface_observer.cpp
src/server/frontend_wayland/wayland_surface_observer.h
src/server/frontend_wayland/window_wl_surface_role.cpp
src/server/frontend_wayland/window_wl_surface_role.h
src/server/frontend_wayland/wl_seat.cpp
src/server/frontend_wayland/wl_seat.h
src/server/frontend_wayland/xdg_shell_stable.cpp
src/server/frontend_wayland/xdg_shell_stable.h
src/server/frontend_wayland/xdg_shell_v6.cpp
src/server/frontend_wayland/xdg_shell_v6.h
src/server/frontend_xwayland/xwayland_connector.h
src/server/frontend_xwayland/xwayland_surface.cpp
src/server/frontend_xwayland/xwayland_surface.h
src/server/frontend_xwayland/xwayland_surface_observer.cpp
src/server/frontend_xwayland/xwayland_surface_observer.h
src/server/frontend_xwayland/xwayland_surface_observer_surface.h
src/server/frontend_xwayland/xwayland_wm.cpp
src/server/frontend_xwayland/xwayland_wm.h
src/server/frontend_xwayland/xwayland_wm_shell.h

This removes `WlSeat::spawn()` and switches all of its users over to using the Wayland executor directly. There was never any reason for running on the Wayland thread to be tied to the seat. In fact, that's the only thing the seat even had an executor for. It also switches around the XWayland frontend a bit to use executors directly where it makes sense.

Use the Wayland executor directly in more places

---

src/server/frontend_wayland/CMakeLists.txt
src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wl_client.cpp
src/server/frontend_wayland/wl_client.h

This breaks `ClientPrivate` in `wayland_connector.cpp` into its own files. The immediate benefits are simplifying `wayland_connector.cpp` and improving and documenting the logic around creating clients. 
The main motivation for doing this now is to help with #1896. Outputs for the XWayland client will sometimes need to report different dimensions than outputs for Wayland clients. I could try to pipe the output manager and XDG output manager through to XWayland, add a map of clients, etc etc but the probably easier and IMO cleaner solution is to add a property to clients which XWayland sets the the outputs use. Creating a client class is the prerequisite for adding a property to a client.

Add WlClient class

---

src/platforms/x11/X11_resources.cpp
src/platforms/x11/X11_resources.h
src/platforms/x11/graphics/display.cpp
src/platforms/x11/graphics/display.h
src/platforms/x11/graphics/graphics.cpp
src/platforms/x11/input/input_platform.cpp

The X11 input platform (which gets events, like window resize) needs talk to the graphics platform (which can apply output configuration changes). The previous method for doing this only shared display configs and only from the graphics platform to the input platform. This PR adds an interface to add flexibility.

Refactor X11Resources to prepare for X11 platform improvements

---

include/client/mir/events/event_builders.h
include/platform/mir/options/configuration.h
src/client/events/event_builders.cpp
src/client/symbols.map
src/miral/x11_support.cpp
src/platform/options/default_configuration.cpp
src/platform/symbols.map
src/platforms/x11/graphics/platform.cpp
src/server/frontend_wayland/wl_client.h
src/server/frontend_wayland/xdg_output_v1.cpp
src/server/frontend_xwayland/CMakeLists.txt
src/server/frontend_xwayland/scaled_buffer_stream.cpp
src/server/frontend_xwayland/scaled_buffer_stream.h
src/server/frontend_xwayland/xwayland_connector.cpp
src/server/frontend_xwayland/xwayland_connector.h
src/server/frontend_xwayland/xwayland_default_configuration.cpp
src/server/frontend_xwayland/xwayland_server.cpp
src/server/frontend_xwayland/xwayland_server.h
src/server/frontend_xwayland/xwayland_surface.cpp
src/server/frontend_xwayland/xwayland_surface.h
src/server/frontend_xwayland/xwayland_surface_observer.cpp
src/server/frontend_xwayland/xwayland_surface_observer.h
src/server/frontend_xwayland/xwayland_surface_role.cpp
src/server/frontend_xwayland/xwayland_surface_role.h
src/server/frontend_xwayland/xwayland_wm.cpp
src/server/frontend_xwayland/xwayland_wm.h

NOTE: there is still a rather serious problem where the window frame is too big and input comes in in the wrong place, thus the draftness of the PR.
Until the X11 PRs noted in #1367 get merged, the whole stack is inherently a little jank. There is no standard way to ask X11 apps to scale, and there is no way to know which apps are scaling. The only way to make sure everything's the right size is to turn scaling off for everything and let Mir stretch apps, but that's obviously not preferable.
Most modern apps and toolkits do support scaling one way or another (the [Arch Wiki page](https://wiki.archlinux.org/index.php/HiDPI#IntelliJ_IDEA) is the best resource for getting them all working), so it makes sense to allow the user to set up app scaling for themselves and then tell Mir to assume …

Improve HiDPI support for XWayland

---

src/miral/x11_support.cpp
src/server/frontend_xwayland/xwayland_default_configuration.cpp
src/server/frontend_xwayland/xwayland_server.cpp

Update the `--x11-scale` option to:
1. Suggest configuring GDK_SCALE in `--app-args-x11`
2. Use GDK_SCALE as the default setting
3. Give an error if `--x11-scale` value cannot be parsed

Update the `--x11-scale` option

---

include/client/mir_toolkit/events/input/input_event.h
src/client/input/input_event.cpp
src/client/symbols.map
src/server/frontend_wayland/wayland_input_dispatcher.cpp
src/server/frontend_wayland/wayland_input_dispatcher.h
src/server/frontend_wayland/wl_keyboard.cpp
src/server/frontend_wayland/wl_keyboard.h
src/server/frontend_wayland/wl_pointer.cpp
src/server/frontend_wayland/wl_pointer.h
src/server/frontend_wayland/wl_seat.cpp
src/server/frontend_wayland/wl_seat.h
src/server/frontend_wayland/wl_touch.cpp
src/server/frontend_wayland/wl_touch.h

Lot of code churn, but the logic stays roughly the same. This sends the Mir events into `WlKeyboard`/`WlPointer`/`WlTouch` instead of extracting information from them. This is step in the direction of addressing #1792. We want to attach serials to input events, and this moves the events to where we'll need them to do that.

Process events in device classes

---

src/server/frontend_xwayland/xwayland_clipboard_provider.cpp
src/server/frontend_xwayland/xwayland_clipboard_provider.h
src/server/frontend_xwayland/xwayland_clipboard_source.cpp
src/server/frontend_xwayland/xwayland_clipboard_source.h
src/server/frontend_xwayland/xwayland_connector.cpp
src/server/frontend_xwayland/xwayland_wm.cpp
src/server/frontend_xwayland/xwayland_wm.h

Pipes the X11 event dispatcher through to the clipboard provider and source, and adds pending operations to it so they do not block.  Clipboard provider's connection needed to be changed from a ref to a `shared_ptr` so `SelectionSender` wouldn't outlive it, and this adds a bit of noise to the diff.

Async XWayland copy paste

---

tests/acceptance-tests/test_new_display_configuration.cpp

Extend preview timeouts to allow for flaky real-time tests on SLOW builders.
Fixes: #1907 (hopefully)

Extend preview timeouts in DisplayConfigurationTest

---

src/platforms/x11/graphics/display.cpp
src/platforms/x11/graphics/display.h
src/platforms/x11/graphics/display_buffer.cpp
src/platforms/x11/graphics/display_buffer.h
src/platforms/x11/graphics/egl_helper.cpp
src/platforms/x11/graphics/egl_helper.h

This changes `EGLHelper` from two stage to one stage initialization, which allows it to be const. Also makes some other things const.

X11 platform: make things const

---

tests/acceptance-tests/test_new_display_configuration.cpp

[DisplayConfigurationTest.preview_base_display_configuration_reverts_after_timeout] Don't use sleep for test timing

---

examples/example-server-lib/decoration_provider.cpp

The idea here is that if anything is updated, only redraw once after all events are dispatched. This keeps updates from stacking up if they come in faster then we can software render the background. In practice this didn't seem to fix any of the issues I'm seeing, but it's still a good idea.

Decoration provider: reduce redraws

---

tools/process_snaps.py

This is to support a change to our workflow that allows an extra verification step.
* edge: automatically built from /dev. (Same as now)
* beta: automatically built from /rc. (As candidate is now)
* candidate: promoted by us from beta. (Typically when we copy /rc to /release)
* stable: promoted from candidate. (After CfT etc.)

Snap beta (not candidate) from mir-team/rc

---

tools/process_snaps.py

Rather than depending on the recipe's configuration.
`channels` isn't required, so can skip altogether.

[snaps] use PPA as defined for the snap/channel

---

src/server/frontend_xwayland/xcb_connection.cpp
src/server/frontend_xwayland/xcb_connection.h
src/server/frontend_xwayland/xwayland_clipboard_provider.cpp
src/server/frontend_xwayland/xwayland_clipboard_provider.h
src/server/frontend_xwayland/xwayland_clipboard_source.cpp
src/server/frontend_xwayland/xwayland_clipboard_source.h
src/server/frontend_xwayland/xwayland_wm.cpp

This enables large copy-pastes between X11 and Wayland.
The X11 protocol this implements can be found [here](https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#incr_properties). Basically, first the property is set to type `INCR`, once the receiver deletes that chunks of data start being sent (a new one after the previous is deleted). The last chunk has a length of zero, and then the receiver knows it's done.
How large a data transfer is needed to make this PR relevant? Unclear. For Wayland -> X11 we have it hard-coded to 64kb (same as Weston). Somewhere I read the real cutoff was 256kb. X11 Kate seems to allow copying out much bigger buffers without incremental transfers. In any case, There is no longer a limit with this PR.

XWayland incremental data transfers

---

examples/example-server-lib/decoration_provider.cpp
examples/example-server-lib/sw_splash.cpp
examples/example-server-lib/wayland_app.cpp
examples/example-server-lib/wayland_app.h
examples/example-server-lib/wayland_shm.cpp
examples/example-server-lib/wayland_shm.h
examples/example-server-lib/wayland_surface.cpp
examples/example-server-lib/wayland_surface.h
examples/miral-shell/spinner/miregl.h

In practice this doesn't currently matter because with only one buffer, buffers are never re-used (which is I guess ok for a static background, where updates are infrequent). However, it was technically incorrect to allow buffers with different geometry than requested to be returned. This PR guarantees a new buffer is created if different geometry is requested.
EDIT: this PR now also ports `SwSplash` to the new classes, which fixes some sketchy buffer management it was doing.

Example WaylandShm: don't allow incorrectly sized buffers

---

debian/libmiroil1.symbols
include/miroil/miroil/eventdispatch.h
include/miroil/miroil/persist_display_config.h
src/miroil/CMakeLists.txt
src/miroil/eventdispatch.cpp
src/miroil/persist_display_config.cpp
src/miroil/symbols.map

Adding DisplayConfigurationPolicy back as a parameter to DisplayConfigurationPolicyWrapper (The qtmir version had this).
This is need by MirDisplayConfigurationPolicy in 
qtmir/src/platforms/mirserver/mirdisplayconfigurationpolicy.cpp

Adding DisplayConfigurationPolicy back as a parameter

---

spread/build/sbuild/task.yaml

Sometimes the build needs packages (or package versions) not available in the main archive. Add the mir-team/dev PPA to the build environment so we have somewhere the build can grab such packages from.

spread: Add mir-team/dev PPA to Ubuntu build environment

---

examples/miral-shell/miral-terminal.sh

When we start gnome-terminal-server, we also need to wait for it to exit.
(Fixes: #1616)

[miral-terminal] wait for gnome-terminal-server to exit

---

src/platform/mirplatform.pc.in

This fixes mirplatform.pc include dirs, correct dirs is mirplatform and mircommon.
Error got introduced in https://github.com/MirServer/mir/commit/270fea2994eb9fd5e086fe95013811772386fea8

Fix mirplatform.pc include dirs

---

src/include/server/mir/shell/abstract_shell.h
src/miral/minimal_window_manager.cpp
src/server/shell/abstract_shell.cpp

The spec is not super clear to me on where keyboard focus should go with regards to popups, but other compositors including Weston do **not** give keyboard focus to popups. GTK handles both fine, but Qt has issues in edge cases when popups get input focus (#1941). Draft because it does not yet play nice with the proposed popup WLCS in https://github.com/MirServer/wlcs/pull/190 (specifically, it doesn't dismiss popups when new surfaces are created). I'm also not sure if this is the correct place to put this code.
Fixes #1941, Fixes #1818. Better alternative to #1942

Don't give keyboard focus to popups

---

tests/include/mir/test/doubles/stub_buffer_allocator.h

Valgrind reports a spurious "Invalid write of size 8" beyond the end of `dummy_destination`, extending the test buffer avoids this.

Workaround spurious valgrind error

---

debian/libmiroil1.symbols
include/miroil/miroil/prompt_session_listener.h
include/miroil/miroil/prompt_session_manager.h
src/miroil/CMakeLists.txt
src/miroil/prompt_session_listener.cpp
src/miroil/prompt_session_manager.cpp
src/miroil/symbols.map

Qtmir uses mir::scene::PromptSessionManager which is no long available, so I've created a wrapper for this class. This is used many places in QtMir.
In addition qtmir listens to mir::scene::PromptSessionListener (also not available)... so I've created an abstract class for that.
This is used in:
https://github.com/ubports/qtmir/blob/xenial/src/platforms/mirserver/mirserverhooks.cpp
class PromptSessionListenerImpl
Which can't be solved in this way because it contains both internal mir stuff and qt stuff. So it has to be split into a mir part(miroil) and Qt part(Qtmir).

adding PromptSessionListener & PromptSessionManager

---

src/protobuf/symbols.map

Build broke on Arch. This fixes it.

Fix protobuf symbols for Arch

---

src/server/frontend_wayland/wl_pointer.cpp
src/server/frontend_wayland/wl_surface.cpp
src/server/frontend_wayland/wl_surface.h

The changes in #1960 led to clients getting spurious pointer movement events (e.g. mir-kiosk-neverputt ends up with jitters). We shouldn't be sending those if the pointer is locked.

Check for locked cursor before sending pointer movement

---

src/server/frontend_xwayland/xwayland_connector.cpp
src/server/frontend_xwayland/xwayland_connector.h
src/server/frontend_xwayland/xwayland_default_configuration.cpp
src/server/frontend_xwayland/xwayland_server.cpp
src/server/frontend_xwayland/xwayland_server.h

Our logic for launching XWayland has long been good but not great. #1969 is a symptom of this, and while looking into it I found other symptoms (notably when XWayland fails to start apps *also* hang for a similar but unrelated reason). This PR attempts to clean it up, show errors when needed and prevent deadlocks. Fixes #1969.
Notable changes:
- Pull in the main loop so `ThreadedDispatcher`s can be destroyed inside their own calls. The previous method of creating and joining a new thread was heavy, looked weird and didn't seem to even work in all cases.
- Use `std::enable_shared_from_this` with `XWaylandConnector`--this is because we need a `weak_ptr` when punting to the main loop in case the object dies.
- Move creation of socket pairs to `XWaylandServer`. This prevents them from being …

Gracefully handle XWayland errors

---

src/platforms/gbm-kms/server/buffer_allocator.cpp
src/platforms/wayland/buffer_allocator.cpp
src/platforms/x11/graphics/buffer_allocator.cpp

My understanding of rvalue references is still a little shaky so maybe I'm wrong, but this looks like a bug to me. In each case we're moving an rvalue reference, only to then potentially use it later. I have not observed any symptoms.

Do not move on_consumed callback in buffer allocators

---

src/server/frontend_wayland/wl_surface.cpp

Noticed this looking into #1967. This doesn't appear to help, but it is more correct then before.

Send timestamps with frame done event

---

src/miral/basic_window_manager.cpp
src/miral/basic_window_manager.h

Only when the parent window spans outputs does this change the behaviour.
In these cases, child window is constrained to the output that contains the anchor rectangle, not the one that contains the parent rectangle. This seems right to me.
Fixes: #1408

Place popups on output their anchor is on

---

src/server/compositor/stream.cpp
src/server/compositor/stream.h

Should fix #1337 (though I don't know how to test that). The only potential issue is that now while the first buffer is being submitted, `has_submitted_buffer()` returns `false` whereas it used to block and the return `true`. By my understanding any code that cares about this would have been a race anyway, and it's unclear that either is behavior is more correct than the other. I haven't observed any changes in behavior.

Fix potential deadlock in BasicSurface::visible()

---

CMakeLists.txt
cmake/MirCommon.cmake
debian/rules
spread/build/sbuild/task.yaml
spread/build/ubuntu/task.yaml
tests/acceptance-tests/wayland/CMakeLists.txt
tools/discover_gtests.sh

This fixes running the WLCS tests under ptest, rather than silently(!) failing to run them and reporting success.
It also implements the ptest support for checking that the XFAIL tests actually fail.

cmake: Fix running WLCS tests under ptest

---

src/miral/basic_window_manager.cpp

Long ago I wrote 10761d2 which doesn't play nice with the more recent logic for attached windows.
Alternative to #1990

Only minimized windows should be restored to get focus

---

src/server/frontend_xwayland/xcb_connection.cpp

This was cute and fairly useful in the early stages of developing XWayland support, but I don't think it's needed any more.

XWayland: drop human-readable window names in debug output

---

src/miral/basic_window_manager.cpp

This way the `place_attached_to_zone()` can `fatal_error()` if it's preconditions aren't met (meaning there's an obvious logic error), but we get a non-fatal error when the state is wrong (indicating there is an error, but an easier one to slip into the code).

Add error message for window manager inconsistancy

---

include/core/mir/geometry/dimensions_generic.h
include/core/mir/geometry/displacement_generic.h
include/core/mir/geometry/point_generic.h
include/core/mir/geometry/size_generic.h
src/platforms/wayland/display.cpp
src/platforms/wayland/display.h
src/platforms/wayland/display_input.h
src/platforms/wayland/input_device.cpp
src/platforms/wayland/input_device.h
tests/unit-tests/geometry/test-displacement.cpp
tests/unit-tests/geometry/test-point.cpp
tests/unit-tests/geometry/test-size.cpp

This adds support for floating point pointer motion and scrolling to the Wayland platform. It appears touches were already precise. Fixes #1852. There's still a notable problem, where scrolling events don't *appear* to be precise because they are arbitrarily multiplied by 10 by the Wayland frontend. This will be fixed in a different PR.

Precise pointer events for Wayland platform

---

src/include/common/mir/unwind_helpers.h
src/server/compositor/multi_threaded_compositor.cpp

This was fixed in GCC/libstdc++ v5.3. Ubuntu 16.04 has v5.4 in -updates,
so none of our currently supported platforms suffer from this bug.

Drop workaround for broken std::uncaught_exception()

---

src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h
src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/frontend_wayland/wl_keyboard.cpp
src/server/frontend_wayland/wl_keyboard.h
src/server/frontend_wayland/wl_seat.cpp
src/server/frontend_wayland/wl_seat.h

Uses the existing configuration option to configure clients to disable key repeat.
Mitigates: #1471

Respect `--enable-key-repeat` with Wayland

---

tests/acceptance-tests/wayland/test_wlcs_display_server.cpp

Using a recursive mutex and doing `work()` under lock was causing the deadlock observed in #1881. I'm unsure of if that exposed a bug that was already there, or if changes there created a new bug, but either way it's dependent on the wayland executor jobs being run under lock.
I don't think there's any reason to do that or to use a recursive mutex. The "real" Wayland executor doesn't execute arbitrary work under lock (as far as I can tell), so the WLCS one shouldn't need to either.

WLCS WaylandExecutor: don't do work under lock

---

.github/workflows/snap.yml
snap/snapcraft.yaml

---
Rather than:
```plain
$ snapcraft revisions mir-core20 | head
Rev.    Uploaded              Arches    Version                 Channels
26      2021-04-30T16:25:52Z  amd64     v2.3.3-220-g1b943e361d  latest/edge/pr2015*
$ snapcraft revisions mir-kiosk | grep head
Rev.    Uploaded              Arches    Version                   Channels
6808    2021-05-02T09:18:52Z  amd64     v2.3.3-snap123            latest/edge/mir-pr2017*
6807    2021-05-02T07:26:17Z  armhf     2.3.3+dev198-snap122      latest/edge
```
Be consistent with deb-based:
```plain
$ snapcraft revisions mir-core20 | head
Rev.    Uploaded              Arches    Version                   Channels
31      2021-05-02T09:51:19Z  amd64     2.3.3+dev239-g670e7226de  latest/edge/pr2016*
$ snapcraft revisions mir-kiosk | head …
```

[snap] fix snap version string

---

cmake/MirCommon.cmake
tests/acceptance-tests/wayland/CMakeLists.txt

We already dropped a test upstream: https://github.com/MirServer/wlcs/pull/196
But until wlcs is released we need a way to skip it

Add mechanism to skip "broken" wlcs tests

---

.github/workflows/ppa-upload.yml

The Launchpad PPAs for mir no longer provide up-to-date builds of mir for Ubuntu 21.04 (see https://launchpad.net/~mir-team/+archive/ubuntu/dev/+packages ) - this change in behaviour coincides with the opening of the impish archive in launchpad which causes 'devel' to refer to impish rather than hirsute. This pull request should hopefully restore the availability of debs for hirsute.

Continue building debs for Ubuntu 21.04

---

src/platforms/x11/input/input_platform.cpp
src/platforms/x11/input/input_platform.h
src/platforms/x11/x11_resources.cpp
src/platforms/x11/x11_resources.h
tests/include/mir/test/doubles/mock_x11_resources.h
tests/mir_test_doubles/mock_xkb.cpp

Fixes #2029. There are a couple pieces to this.
1. Use the XKB extension to track the modifier state. This gives us more correct symcodes (which we send on to Mir but don't seem to care much about) as well as the ability to know the state of the modifiers when the window is focused. 
2. Cache pressed keys. For a number of reasons key ups and key downs may not be perfectly paired up (XKB events duplicating normal events in some cases, keys that are pressed when the window is unfocused and released when the window is focused, etc). The `pressed_keys` set allows us to make sure the events we send on to Mir are more coherent.
3. Synthesize key up events for all non-modifiers when the window looses focus. This keeps us from getting endlessly repeating keys. Modifiers are any key that an XKB …

X11 platform: handle key state changes when window is not focused

---

include/core/mir/geometry/displacement_generic.h
include/core/mir/geometry/rectangle_generic.h
include/core/mir/geometry/size_generic.h
src/platforms/x11/input/input_device.cpp
src/platforms/x11/input/input_device.h
src/platforms/x11/input/input_platform.cpp

Fixes #2034. Also introduces floating point geometry into the X11 platform, and removes the usage of `as_int()` from generic geometry calculations.

X11 platform: fix cursor position on scaled outputs

---

cmake/MirCommon.cmake

We're still seeing "broken" tests failing in CI, this is another attempt to fix this.
(Last time around I didn't quite grok how ptest actually works)

Fix broken tests better

---

src/platforms/x11/input/input_platform.h

This is now needed on Arch for some reason, guess a system header changed or something

Add missing include

---

include/wayland/mir/wayland/wayland_base.h

New message shows if the value is destroyed or set to null explicitly, and the type. typeid produces mangled type, but still readable and certainly better than nothing.

Improve wayland::Weak error message

---

tests/acceptance-tests/wayland/CMakeLists.txt

tests/wlcs: XFail XdgToplevelStableTest.touch_can_not_steal_pointer_based_move

---

src/server/frontend_wayland/wayland_connector.cpp
src/wayland/wayland_base.cpp
tests/miral/wayland_extensions.cpp

The oldest series we need to support is focal (which has 1.18)
bionic-security & bionic-updates have 1.16. (For info pure bionic has 1.14)

Remove backward compatibility for stuff that predates focal

---

.github/workflows/spread.yml
CMakeLists.txt
spread.yaml
spread/build/alpine/task.yaml

Based on #1949 , thanks for the "template"!
Commit f4d0dd5979cc36c64c76ae7f8ac7eebb7c6a7c53 can be upstreamed as-is imo.
A couple of problems:
* https://github.com/MirServer/mir/commit/e3d9b53512fdd73d81254b219af5cea71e471431
* The tests fail
* Alpine 3.13 won't really be possible (at the moment) because some of the dependencies are only in the testing repo and that repo is only available on the edge version and not on the stable version. I'll see that all dependencies will be included in the Alpine 3.14 release

Add Alpine Linux CI

---

src/server/frontend_wayland/wl_pointer.cpp
src/server/frontend_wayland/wl_pointer.h

There was a logic error in WlPointer::set_cursor() that compared a pointer with an optional (both of which, unfortunately, convert to bool).
We also needed to hook into the "commit" on the corresponding surface to detect an attempt to unmap by sending a null buffer. It looks a bit messy, but fixes #2073.
(Alternative to #2078)

Make GTK's approach to hiding cursors work on Mir

---

examples/mir_demo_server/server_example_input_filter.cpp
include/client/mir/events/event_builders.h
include/client/mir_toolkit/events/input/keyboard_event.h
include/miral/miral/toolkit_event.h
include/platform/mir/input/event_builder.h
include/test/mir/test/event_matchers.h
src/client/event_printer.cpp
src/client/events/event_builders.cpp
src/client/input/input_event.cpp
src/client/input/xkb_mapper.cpp
src/client/symbols.map
src/common/events/keyboard_event.cpp
src/common/symbols.map
src/include/common/mir/events/keyboard_event.h
src/miral/toolkit_event.cpp
src/miral/window_management_trace.cpp
src/platforms/wayland/display_input.h
src/platforms/wayland/input_device.cpp
src/platforms/wayland/input_device.h
src/platforms/x11/input/input_device.cpp
src/platforms/x11/input/input_device.h
src/platforms/x11/input/input_platform.cpp
src/server/input/default_event_builder.cpp
src/server/input/default_event_builder.h
src/server/input/key_repeat_dispatcher.cpp
tests/mir_test_framework/fake_input_device_impl.cpp
tests/unit-tests/input/test_event_builders.cpp
tests/unit-tests/input/test_input_event.cpp
tests/unit-tests/scene/test_abstract_shell.cpp

Previously `key_code` was a badly overloaded name, referring to keysyms in some contexts and scan codes in other contexts. This PR standardizes the names across Mir to completely avoid the use of `key_code` (with the exception of the MirAL API, which keeps it in it's "keysym" meaning in order to remain stable).

Standardize on keysym/key_code names

---

src/include/platform/mir/udev/wrapper.h
src/platform/udev/udev_wrapper.cpp

If a udev device is removed between the time we scan and the time
we try and iterate through it then the `device_from_syspath` call
will fail with a `std::runtime_error`.
We catch that on `++iterator` and `iterator++` but *not* if the
very first udev device has disappeared; in that case we crash
with an unhandled exception.
Extend the `increment()` handling to also handle the inital case,
and then use it to handle the case where the first udev device
has disappeared.

udev: Handle the first entry of an udev iterator being invalid

---

src/platforms/evdev/platform.cpp

By design, the event dispatcher does not expect exceptions to propagate. Fix a dispatchee that allows events to propagate.
Maybe fixes https://github.com/MirServer/mir-kiosk/issues/60

[input] Handle exceptions while handling udev events

---

debian/libmiral4.symbols
examples/miral-shell/shell_main.cpp
include/miral/miral/toolkit_event.h
src/miral/symbols.map
src/miral/toolkit_event.cpp

Deprecate mir_keyboard_event_key_code()

---

src/miral/internal_client.cpp
src/platforms/eglstream-kms/server/egl_output.cpp
src/platforms/evdev/platform.cpp
src/server/input/vt_filter.cpp

We were slicing the exception being reported by copying to the runtime type.
Before:
```
...Dynamic exception type: std::exception
std::exception::what: std::exception
```
After:
```
... /home/alan/CLionProjects/mir/src/platform/udev/udev_wrapper.cpp(60): Throw in function {anonymous}::DeviceImpl::DeviceImpl(udev_device*)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: Udev device does not exist
```

Fix a log error message

---

src/miral/keymap.cpp

This mitigates #2098, but a real fix would also detect and report setting an invalid keymap.

Prevent exceptions propagating where they are not expected

---

src/server/input/default_input_device_hub.cpp
src/server/input/default_input_device_hub.h

Reading through this code, I saw what appeared to be a number of threadsafety issues. I'm not sure if these were mistakes or it was determined that nothing would be using these classes in ways that cause race conditions. Either way, doing stuff from the Wayland thread for OSK support may introduce problems, so better get everything straight first.
A potential downside is that now some observer methods are called while under lock, which is generally not advisable. I don't *think* there's any case in which we need to change input devices from an observer call. Not calling the observer under lock would be nontrivial (and slightly less performant).

Fix InputDeviceHub threadsafety

---

include/common/mir/input/mir_keyboard_config.h
src/common/input/mir_keyboard_config.cpp
src/common/input/xkb_mapper.cpp
src/include/common/mir/input/key_mapper.h
src/include/common/mir/input/xkb_mapper.h
src/miral/keymap.cpp
src/server/frontend_wayland/wl_seat.cpp
src/server/input/default_device.cpp
tests/include/mir/test/doubles/mock_key_mapper.h

In order to property manage and move around keymaps more things will need to hold on to them, so making them available as a shared pointer makes sense. Part of #2111.

Use shared pointers to move around keymaps

---

src/common/events/keyboard_event.cpp
src/common/symbols.map
src/include/common/mir/events/keyboard_event.h

Allow setting the keymap for a key event. In a subsequent PR the `KeyMapper` will set this property and the Wayland frontend will use it to determine if a new keymap needs to be sent.

MirKeyboardEvent: add keymap property

---

src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h
src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/frontend_wayland/wl_seat.cpp
src/server/frontend_wayland/wl_seat.h
src/server/frontend_wayland/wl_touch.cpp
src/server/frontend_wayland/wl_touch.h

Instead of the old, hacky system of using `steady_clock` with an offset. Most of the code is getting the clock to the `WlTouch`. May not produce correct behavior until #2117 lands, as it assumes event timestamps have the same base as the Mir clock.

WlTouch: use Clock to synthisize timestamps

---

include/common/mir/input/buffer_keymap.h
src/common/CMakeLists.txt
src/common/input/buffer_keymap.cpp
src/common/symbols.map
tests/unit-tests/input/CMakeLists.txt
tests/unit-tests/input/test_buffer_keymap.cpp

Adds a new keymap implementation based on a character buffer of data. Used for keymaps provided through the Wayland protocol, such as for OSKs. Part of #2111.

Add BufferKeymap

---

src/common/input/xkb_mapper.cpp
src/include/common/mir/input/xkb_mapper.h
src/server/frontend_wayland/wl_keyboard.cpp
src/server/frontend_wayland/wl_keyboard.h
src/server/frontend_wayland/wl_seat.cpp

When a key event comes through with a different keymap, send the keymap event to Wayland clients before sending the key. Based on #2114 and #2113. Part of #2111.

Send keymaps as needed

---

include/platform/mir/input/input_device_registry.h
src/server/input/default_input_device_hub.cpp
src/server/input/default_input_device_hub.h
tests/include/mir/test/doubles/mock_input_device_registry.h
tests/unit-tests/input/evdev/test_evdev_input_platform.cpp
tests/unit-tests/input/evdev/test_libinput_device.cpp
tests/unit-tests/input/test_x11_platform.cpp

This will allow the thing that created a device to set it's config (specifically, allow for keymaps to be set). Part of #2111.

InputDeviceRegistry: return device handle when adding device

---

include/platform/mir/input/event_builder.h
src/server/input/default_configuration.cpp
src/server/input/default_event_builder.cpp
src/server/input/default_event_builder.h
src/server/input/default_input_device_hub.cpp
src/server/input/default_input_device_hub.h
tests/integration-tests/input/test_single_seat_setup.cpp
tests/mir_test_framework/fake_input_device_impl.cpp
tests/unit-tests/input/evdev/test_libinput_device.cpp
tests/unit-tests/input/test_default_input_device_hub.cpp
tests/unit-tests/input/test_seat_input_device_tracker.cpp
tests/unit-tests/input/test_x11_platform.cpp

With this PR, `DefaultEventBuilder` holds a `time::Clock`, which is uses to calibrate incoming events with. This way events coming from multiple sources (each with an undefined timestamp base) and events generated inside Mir will all have correct timestamps relative to each other. The `EventBuilder` interface is not changed, and no changes are needed for users of it.

Calibrate event timestamps

---

include/platform/mir/input/event_builder.h
src/platforms/x11/input/input_device.cpp
src/platforms/x11/input/input_device.h
src/platforms/x11/input/input_platform.cpp
src/platforms/x11/input/input_platform.h
src/server/input/default_event_builder.cpp
src/server/input/default_event_builder.h
tests/unit-tests/input/evdev/test_libinput_device.cpp

This changes the `EventBuilder` interface to take optional timestamps, and to synthesize a timestamp from current time if none is given. It also uses that in the X11 platform where before we were using the last timestamp we saw. Stacked on top of #2117.

X11 platform: use synthisized timestamps instead of last timestamp

---

tests/include/mir/test/doubles/mock_drm.h
tests/include/mir_test_framework/open_wrapper.h
tests/mir_test_doubles/mock_drm.cpp
tests/mir_test_framework/open_wrapper.cpp
tests/unit-tests/console/test_minimal_console_services.cpp
tests/unit-tests/platforms/eglstream-kms/server/test_threaded_drm_event_handler.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_drm_helper.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_platform.cpp

So, `open()` is actually a varargs function, taking an optional `mode_t` third parameter.
We've always interposed this with a `open(char const*, int, mode_t)` function, which is
a) Obviously not varargs, and so any calls to `open()` were being handled by a function with incompatible signature, but
b) We never hit the UB this introduced… until now.
Fixes the build on ppc64el. Tested on ppc64el and x86-64.

Fix open() interposer

---

tests/mir_test_doubles/mock_drm.cpp
tests/unit-tests/console/test_minimal_console_services.cpp

Changes incantation to return a null optional that "may be used uninitialized" (at least according to gcc).

Fixes: #2125

---

src/server/frontend_wayland/wayland_input_dispatcher.cpp
src/server/frontend_wayland/wl_data_device.cpp
src/server/frontend_wayland/wl_data_device.h
src/server/frontend_wayland/wl_seat.cpp
src/server/frontend_wayland/wl_seat.h

This renames and refactors `WlSeat::ListenerTracker` to `WlSeat::FocusListener`. Focus listeners are tied to a single client and only get notifications relevant to that client, and they are told what surface is focused. These things will help implement `zwp_text_input_v3`, as it needs to respond to changing focus.

WlSeat: improve focus listeners

---

tests/unit-tests/platforms/gbm-kms/kms/test_display.cpp
tests/unit-tests/test_mir_cookie.cpp

Remove or reinstate DISABLED tests.
There remain some conditionally DISABLED tests, but these are still running in most configurations.
Fixes: #209

Clean up our DISABLED tests

---

include/wayland/mir/wayland/wayland_base.h
src/server/frontend_wayland/wl_keyboard.cpp
src/server/frontend_wayland/wl_seat.cpp
tests/unit-tests/wayland/test_wayland_weak.cpp

If we got a key event to the surface that the keyboard isn't currently on, we used to send the event then refocus the keyboard. This corrects that order.
1. Open LXTerminal
2. Go to Tabs -> Name Tab
3. Click Cancel
4. Type key
__master:__ first letter typed doesn't appear in main window
__this PR:__ first letter does appear

WlKeyboard: if refocus is needed, send key event after it completes

---

src/server/frontend_wayland/wl_seat.cpp
src/server/frontend_wayland/wl_seat.h

Currently the only `FocusObserver` is the data device. The effect of this PR is that when the focused surface is destroyed `has_focus` will be set to false for that client and future data offers will not be given to it. In practice this behavior causing problems is unlikely, but the new behavior is more correct for data device and useful for text input.

WlSeat: notify focus observers when focused surface is destroyed

---

src/server/frontend_wayland/layer_shell_v1.cpp
src/server/frontend_wayland/window_wl_surface_role.cpp
src/server/frontend_wayland/window_wl_surface_role.h

As noted in my old bug report [here](https://gitlab.gnome.org/World/Phosh/squeekboard/-/issues/285), Squeekboard violates the protocol when it closes it's layer surface. Currently on Mir, this causes it to be disconnected. With several days to a week of time investment I could probably solve this, which may or may not get merged upstream in a timely manor. In possibly a little less time I could make a patch for wlroots which would force all clients to do the right thing, which again may or may not be merged.
In the short term we need Squeekboard to work. This PR allows the protocol violation in Mir. In `WindowWlSurfaceRole`, `surface` had to be changed to a `wayland::Weak` to make these changes safe.
Part of #2139

Layer shell: allow destroying surface before the role object

---

src/platforms/wayland/displayclient.cpp

When the display turns off on a Mesa system, the mir_frontend's swap_buffers will hang after one successful frame. This is because Mesa throttles Wayland frame callbacks to no more than one per vsync, and the vsync has stopped when the display is off.
This causes Mir servers using the Wayland platform to hang from the time the display turns off until it turns back on. This was a particular problem for Lomiri since the Qt main thread has to sync with the render thread. So blocking the render thread also blocks the main thread. [1]
If we just don't wait *forever* for frame callbacks, we don't end up hanging the rendering thread indefinitely.
This probably isn't 100% of the correct solution. See the discussion in [2] for more information on the whole right solution.
[1] …

[Wayland-platform] Don't block forever in swap_buffers

---

tests/performance-tests/test_glmark2-es2.cpp

Fixes "windowed" tests broken by #2143

[mir_performance_tests] Use a window management policy that supports windowing

---

tests/mir_test_framework/open_wrapper.cpp
tests/mir_test_framework/symbols-server.map.in

GoogleTest *very conveniently* uses at least one global with a non-trivial
destructor. Due to the vagaries of static linking, these globals are
exported in the symbol table unless you explicitly hide them.
This interacts badly with `dlopen()`. The object will get constructed during
the initial loading process, along with the other globals, and then will
be constructed *again* when the ELF-module-constructor machinery runs
to load the `dlopen`ed DSO.
Even better, during process teardown the DSO's ELF-destructor will run
the destructor for the global. *Then* the executable's ELF-destructor will
run the destructor for the global *again*. This is rarely what you want,
and in *this* case it results in GoogleTest hitting an `abort()` when it
tries to destroy a `pthread_key_t` a second time. …

test/graphics-dummy: Guard against unwanted symbol export.

---

include/core/mir_toolkit/events/enums.h
include/test/mir/test/event_matchers.h
src/common/events/CMakeLists.txt
src/common/events/keyboard_resync_event.cpp
src/common/input/input_event.cpp
src/common/symbols.map
src/include/common/mir/events/keyboard_resync_event.h
src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_executor.cpp
src/server/frontend_wayland/wayland_input_dispatcher.cpp
src/server/frontend_wayland/wl_seat.cpp
src/server/frontend_wayland/wl_seat.h
src/server/input/CMakeLists.txt
src/server/input/default_configuration.cpp
src/server/input/keyboard_resync_dispatcher.cpp
src/server/input/keyboard_resync_dispatcher.h
src/server/input/surface_input_dispatcher.cpp
src/server/shell/abstract_shell.cpp
src/server/shell/decoration/input.cpp
src/server/symbols.map
tests/unit-tests/input/CMakeLists.txt
tests/unit-tests/input/test_keyboard_resync_dispatcher.cpp
tests/unit-tests/wayland/test_wayland_executor.cpp

Reverts the revert and ensures WaylandConnector initializes in a timely manner.

Reinstate #2146

---

src/platforms/eglstream-kms/server/platform.cpp
src/platforms/eglstream-kms/server/platform.h
src/platforms/eglstream-kms/server/platform_symbols.cpp

This was an artefact from before the Dispaly/Rendering split.

eglstream-kms: Drop superfluous mge::Platform

---

src/server/frontend_xwayland/xwayland_surface.cpp
src/server/frontend_xwayland/xwayland_surface.h

Fixes #2037. I hope this refactor moderately improves some of the convoluted logic. Now window parent and type are set in one place, so we always have the information to set them correctly. Draft PR for now because I've seen occasional segfaults, so I think this introduces a memory issue somewhere.

XWayland: improve popup window types and positioning

---

tests/performance-tests/CMakeLists.txt
tools/mir-smoke-test-runner.sh

This provides new MIR_RUN_SMOKE_TESTS and MIR_RUN_PERFORMANCE_TESTS options to cmake.
These options are enabled (and default to ON) when xvfb-run exists (and also glmark2-es2-wayland for mir_performance_tests).
(The end goal of getting these test to run in CI is for a future PR.)

Enable running smoke tests and performance tests in CMake

---

include/core/mir/proof_of_mutex_lock.h
src/server/frontend_xwayland/xwayland_surface.h
src/server/scene/basic_surface.cpp
src/server/scene/basic_surface.h

We now use `ProofOfMutexLock` in two places, and it stands to reason it will be useful in more. This moves it to it's own header `core/mir/proof_of_mutex_lock.h`.

Consolidate ProofOfMutexLock

---

include/miral/miral/wayland_extensions.h
src/server/frontend_wayland/CMakeLists.txt
src/server/frontend_wayland/keyboard_helper.cpp
src/server/frontend_wayland/keyboard_helper.h
src/server/frontend_wayland/wayland_input_dispatcher.cpp
src/server/frontend_wayland/wl_keyboard.cpp
src/server/frontend_wayland/wl_keyboard.h
src/server/frontend_wayland/wl_seat.cpp
src/server/frontend_wayland/wl_seat.h

One of the initially unimplemented components of the input method protocol is keyboard grabs. Squeekboard doesn't grab the keybaord, but CJK input methods (such as [wlanthy](https://github.com/st3r4g/wlanthy) do need to. `zwp_input_method_keyboard_grab_v2` is a separate interface than `wl_keyboard` and will need a separate implementation, but requires much of the same functionality.
After several attempts involving inheritance, I settled on a more composition-oriented approach. `KeybaordHelper` implements the common keyboard logic, and calls into `KeyboardImpl` to send events. In this PR `WlKeyboard` is the only `KeyboardImpl`, but an upcoming PR will add a new grab keybaord implementation.

Refactor KeyboardHelper out of WlKeyboard

---

src/include/server/mir/scene/surface_state_tracker.h
src/server/frontend_xwayland/xwayland_surface.cpp
src/server/frontend_xwayland/xwayland_surface.h
src/server/scene/surface_state_tracker.cpp

Not too long ago we introduced `SurfaceStateTracker` to store multiple surface states at once. Previously the XWayland frontend was using it's own class to do this. With this PR, it uses the common one. Fixes #1217.

Use SurfaceStateTracker to track X11 window state

---

src/server/frontend_wayland/foreign_toplevel_manager_v1.cpp
tests/acceptance-tests/wayland/CMakeLists.txt

Makes our foreign toplevel implementation simpler and more robust by not keeping track of surface state in the frontend. This does cause one WLCS test to fail, which is explained in #2164. I do not consider changing non-active state to be particularly important, and if it is doing it by keeping a cache in the frontend is not the way to go about it.

Use state tracker for foreign toplevel control

---

src/miral/basic_window_manager.cpp

I noticed this code looked out of place in `BasicWindowManager::add_surface()`. Where it was before it couldn't be overridden by the shell. No pressing reason for this change, but ability to customize these things could be useful later.

MirAL: move depth layer and focus mode setup to place_new_surface()

---

src/server/frontend_wayland/window_wl_surface_role.cpp
src/server/frontend_wayland/window_wl_surface_role.h

Simplifies `WindowWlSurfaceRole` by transitioning it to only creating surface creation parameters when needed. Part of the project to transition away from surface creation parameters entirely.

WindowWlSurfaceRole use surface spec instead of creation params

---

src/platform/graphics/linux_dmabuf.cpp

Some clients make this technically invalid request.
Fixes: #2177

Allow zwp_linux_buffer_params_v1.add() with DRM_FORMAT_MOD_INVALID

---

include/test/mir_test_framework/async_server_runner.h
tests/mir_test_framework/async_server_runner.cpp

Release builds on 21.04 segfault in mir_performance_tests
That happens because the callback passed to `add_init_callback()` executes with an invalid context.
I don't see how this could happen as the `std::functor` that contains it is built before the thread that executes it is started. (So that should be  sequenced-before.)
Anyway, moving the call to `add_init_callback()` onto the "AsyncServer" seems to avoid this and is otherwise harmless.

Sequence AsyncServerRunner::start_server() setup on one thread

---

include/wayland/mir/wayland/wayland_base.h
src/server/frontend_wayland/xdg_shell_stable.cpp
src/server/frontend_wayland/xdg_shell_v6.cpp

I ran into this trying neverball on Arch.
I use `mw::ProtocolError` even though there is not valid error code, because that makes the client show the error. If I threw a `std::runtime_error` it only shows up in the Mir log, which a client dev may not check (I haven't checked if this is true for all clients or just SDL). In any case, I think this is more correct, and it's what wlroots does.

Error on invalid xdg_surface size

---

src/miral/CMakeLists.txt
src/miral/check-and-update-debian-symbols.py

Renames it to `regenerate-miral-debian-symbols` and makes it always enabled (but off by default on unsupported systems). This allows playing with it everywhere.

Improve check-miral-symbols target

---

debian/libmiral4.symbols
include/miral/miral/wayland_extensions.h
src/miral/symbols.map
src/miral/wayland_extensions.cpp
src/server/frontend_wayland/foreign_toplevel_manager_v1.cpp
src/server/frontend_wayland/foreign_toplevel_manager_v1.h
src/server/frontend_wayland/input_method_v2.cpp
src/server/frontend_wayland/input_method_v2.h
src/server/frontend_wayland/pointer_constraints_unstable_v1.cpp
src/server/frontend_wayland/pointer_constraints_unstable_v1.h
src/server/frontend_wayland/relative_pointer_unstable_v1.cpp
src/server/frontend_wayland/relative_pointer_unstable_v1.h
src/server/frontend_wayland/text_input_v3.cpp
src/server/frontend_wayland/text_input_v3.h
src/server/frontend_wayland/virtual_keyboard_v1.cpp
src/server/frontend_wayland/virtual_keyboard_v1.h
src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h
src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/frontend_wayland/xdg_output_v1.cpp
src/server/frontend_wayland/xdg_output_v1.h
tests/miral/wayland_extensions.cpp

Fixes #2208. Extension names are now automatically deduced for built-in extensions, and if a bespoke extension with an invalid name is enabled, a fatal error is raised at startup.

Change extension names to always match global names

---

src/include/server/mir/graphics/default_display_configuration_policy.h
src/miral/display_configuration_option.cpp
src/server/graphics/default_display_configuration_policy.cpp
tests/unit-tests/graphics/test_default_display_configuration_policy.cpp

This may be useful in all sorts of contexts. It only allows specifying one scale for all outputs, but in many cases that's all you need.

Add display-scale option

---

examples/example-server-lib/wallpaper_config.cpp
src/server/shell/decoration/renderer.cpp

As discussed in chat, code duplication is the correct dependency management tool for this situation. This PR fully duplicates the logic, which fixes Miral shell text on Arch (has always been broken)

Use same font search logic in Mir and example server lib

---

include/core/mir_toolkit/common.h
src/include/server/mir/shell/abstract_shell.h
src/server/frontend_wayland/pointer_constraints_unstable_v1.cpp
src/server/frontend_wayland/wayland_surface_observer.cpp
src/server/frontend_wayland/window_wl_surface_role.cpp
src/server/frontend_xwayland/xwayland_surface_observer.cpp
src/server/scene/basic_surface.cpp
src/server/shell/abstract_shell.cpp
src/server/shell/decoration/renderer.cpp
tests/unit-tests/scene/test_basic_surface.cpp

Fixes #1626, fixes #2189. Adds a new `mir_window_focus_state_active` focus state, which is used for surfaces that are in the active stack but do not have keyboard focus. We did not previously have a way to represent this state properly, which caused us a number of problems.

Differentiate between active surfaces and surfaces with keyboard input

---

include/miral/miral/wayland_extensions.h
src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h

Fixes #2227. We lose a diagnostic, but I don't see a good way of keeping it.

Allow globals with unknown names

---

include/test/mir/test/doubles/mock_egl.h
src/platforms/gbm-kms/server/display_helpers.cpp
src/platforms/gbm-kms/server/display_helpers.h
src/platforms/gbm-kms/server/kms/display.cpp
src/platforms/gbm-kms/server/kms/display_buffer.cpp
src/platforms/gbm-kms/server/kms/egl_helper.cpp
src/platforms/gbm-kms/server/kms/egl_helper.h
tests/unit-tests/platforms/gbm-kms/kms/test_buffer_allocator.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display_generic.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display_multi_monitor.cpp

Some drivers (*cough* Mali) don't support rendering to `RGBX` GBM buffers. We don't care about the difference between `RGBX` and `RGBA` for framebuffers, so check whether `RGBX` will work and try to fall back to `RGBA` if it doesn't.
There are some obvious points of further work here - checking what formats the *display* hardware supports and using that to populate the `MirDisplayConfiguration`, respecting the pixel format specified in the `MirDisplayConfiguration`, and so on - but that should be deferred until we make the switch to Atomic KMS.
Closes: #2226

gbm-kms: Try harder to pick a working GBM framebuffer format

---

src/platforms/gbm-kms/server/kms/platform_symbols.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_platform.cpp

The libmali EGL implementation requires that the `gbm_device` passed in to
`eglGetPlatformDisplay` be created from a DRM master fd.
We can't guarantee this in the rendering probe, as the display platform may
have already claimed DRM master.
Instead, assume that an EGL platform which claims to support the GBM platform
will be at least minimally usable with GBM.

gbm-kms: Be more relaxed in the rendering probe.

---

src/server/shell/abstract_shell.cpp
tests/acceptance-tests/wayland/CMakeLists.txt

According to XDG Shell, grabbing popups should be given keyboard focus and non-grabbing ones should not. This PR brings our keyboard focus logic in line with that.
Fixes #2241. Tested by the recently-updated https://github.com/MirServer/wlcs/pull/216.

Give keyboard focus to menus (grabbing popups)

---

src/include/server/mir/shell/abstract_shell.h
src/server/shell/abstract_shell.cpp

The window manager already has logic that prevents `gloss` and `tip` windows from getting focus, so that doesn't need to be duplicated here.
The problem that this was solving is that sometimes the topmost active surface and the keyboard input surface are different, however this is not the case. XDG popups never need to become active (their active state is not reported to the client), so the only XDG popups we make active are those that also have keyboard focus (grabbing popups, aka `mir_window_type_menu`). This is handled in the window manager, so the shell does not need to worry about window types at all.

Simplify keyboard focus targeting

---

src/server/frontend_wayland/wayland_input_dispatcher.cpp
src/server/frontend_wayland/wl_keyboard.cpp
src/server/frontend_wayland/wl_keyboard.h

It seems at some point we made `WlSeat` expose a generic focus tracking API, but never ported `WlKeyboard` to use it. This PR removes that code duplication, and because `WlSeat::FocusListener` gets notified of the focus state when initially added, it fixes #2272 for free.

WlKeyboard: use WlSeat::FocusListener for focus tracking

---

src/server/frontend_wayland/text_input_v3.cpp

That was easy.
Fixes #2269.
Tested by https://github.com/MirServer/wlcs/pull/217.

Deactivate text input when the Wayland object is deleted

---

CMakeLists.txt

```
This isn't available on Alpine (and other distros)
/usr/include/lttng/tracepoint.h:39:10: fatal error: sys/sdt.h: No such file or directory
39 | #include <sys/sdt.h>
|          ^~~~~~~~~~~
(cherry picked from commit 77920fb7ac5b734b696769fb25acb9e25206060d)
```
Original pull request: #1957

release/1.8: Stop forcing systemtap integration

---

src/platforms/mesa/server/x11/graphics/egl_helper.h
src/platforms/mesa/server/x11/graphics/platform.h
src/platforms/mesa/server/x11/input/input_platform.h
tests/include/mir/test/doubles/mock_x11.h

For some reason including capnproto before X11 header makes the compiler
happy.
See https://github.com/capnproto/capnproto/issues/1393
---
Capnproto is gone with Mir 2.x so it's not a problem there fortunately.

release/1.8: Work around capnproto incompatibility

---

include/common/mir/events/event_builders.h
include/common/mir_toolkit/events/input/pointer_event.h
include/platform/mir/input/event_builder.h
src/common/events/event_builders.cpp
src/common/events/pointer_event.cpp
src/common/input/input_event.cpp
src/common/symbols.map
src/include/common/mir/events/pointer_event.h
src/platforms/evdev/libinput_device.cpp
src/server/frontend_wayland/wl_pointer.cpp
src/server/input/default_event_builder.cpp
src/server/input/default_event_builder.h
tests/include/mir/test/doubles/mock_libinput.h
tests/mir_test_doubles/mock_libinput.cpp
tests/unit-tests/input/evdev/test_libinput_device.cpp

This sends a `wl_pointer.axis_stop` event when we get a libinput scroll event that has an axis with value 0. Reading the llibinput and Wayland docs it seems to be correct behavior, is consistent with both Weston and wlroots and works with Firefox.
I've quite possibly screwed up the symbols, so double check them.
Fixes #2247, fixes #2276

Send wl_pointer.axis_stop

---

tests/mir_test_framework/CMakeLists.txt
tests/umock-acceptance-tests/CMakeLists.txt
tests/unit-tests/CMakeLists.txt

This was required for Mir to use a umockdev built from source.

Include ldflags for umockdev

---

.github/workflows/spread.yml
debian/rules

Filed an Ubuntu bug at:
https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1958984

[debian] disable LTO on jammy, and in dpkg, too

---

include/common/mir/system_executor.h
src/common/symbols.map
src/common/system_executor.cpp
src/server/run_mir.cpp
tests/unit-tests/test_system_executor.cpp

Global destruction order is not specified (or specifiable), *and* code
we use may register its own global destructors. In an ideal world we
could ensure the SystemExecutor gets destroyed before any other global,
and hence guarantee that none of its threads access state which may
have already been destroyed. Sadly, attempting that is *at best*
non-portable and fragile, at worst impossible.
Do the next best thing by explicitly waiting in `run_mir()` for
work to finish.
Fixes: #2313 - double free on shutdown.
Mesa EGL registers some thread-local storage and frees it during
global teardown. If this teardown is done before all threads which
access that storage have exited then a double-free will occur when
thread termination triggers deallocation of the TLS object.

SystemExecutor: Quiesce before exiting `run_mir()`

---

include/common/mir/linearising_executor.h
src/common/CMakeLists.txt
src/common/linearising_executor.cpp
src/common/symbols.map
tests/unit-tests/CMakeLists.txt
tests/unit-tests/test_linearising_executor.cpp

This can be used to ensure work is executed in the order it is `spawn()`ed.

Add a mir::linearising_executor

---

src/include/server/mir/shell/abstract_shell.h
src/server/shell/abstract_shell.cpp
tests/acceptance-tests/wayland/CMakeLists.txt
tests/include/mir/test/doubles/mock_surface.h
tests/unit-tests/scene/test_abstract_shell.cpp

Fixes #2324, and refactors `AbstractShell::notify_focus_locked()` in an attempt to make future changes easier to understand.

Do not give menus keyboard focus (again)

---

src/include/server/mir/server.h
src/miral/external_client.cpp
src/server/server.cpp

This makes it easier to apply both packaging related options (e.g. variables used by snap) and user options.

Allow --app-env-amend to be supplied multiple times

---

src/server/shell/abstract_shell.cpp
tests/unit-tests/scene/test_abstract_shell.cpp

This PR corrects a behavior where Mir would fail to set the requested surface as focused if it was already active. Instead of adding additional error-prone logic I simply gave up on our previous strategy of only notifying surfaces when necessary.
`BasicSurface` already returns immediately if `focus_state` is set to the same value multiple times. The only additional performance cost is that of locking all surfaces that were active both before and after, which will never be never be the majority of the cost of changing focus because we already lock all surfaces in the new focus tree once anyway to get their parent.
Fixes #2338

Further simplify and correct keyboard focus setting

---

src/platforms/x11/graphics/display.cpp
src/platforms/x11/graphics/display.h
src/platforms/x11/graphics/graphics.cpp
src/platforms/x11/graphics/platform.cpp
src/platforms/x11/graphics/platform.h
tests/unit-tests/platforms/x11/test_display.cpp
tests/unit-tests/platforms/x11/test_display_generic.cpp
tests/unit-tests/platforms/x11/test_platform.cpp

Fixes #2219 by making the initialized title an argument in X11Window, and if the argument is an empty string, sets it to the previous default, "Mir on X".

[x11-platform] Make window title a configuration option

---

src/server/frontend_wayland/wayland_connector.cpp

Fixes #2191 by adding a `fatal_error` if WaylandConnector cannot bind Wayland socket.

Add fatal_error if unable to bind Wayland socket

---

tests/CMakeLists.txt

g++-12 is not a fan of the GoogleMock headers:
```
/usr/src/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:296:10: error: infinite recursion detected [-Werror=infinite-recursion]
296 | inline T Invalid() {
|          ^~~~~~~
/usr/src/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:301:20: note: recursive call
301 |   return Invalid<T>();
|          ~~~~~~~~~~^~
```
This is not *actually* infinite-recursion, because `Invalid()` calls `Abort()` before reaching the return. `Abort()` will *eventually* end up calling a `[[noreturn]]` function, but conditionally, and it seems g++-12's program flow analysis doesn't trace down far enough to notice.

cmake: Fix the build with g++-12

---

src/server/frontend_wayland/wl_keyboard.cpp

While we're not ready for release with this, it has been useful identifying and fixing genuine problems in development.

Restore the "fatal_error" when focus is screwed

---

include/platform/mir/graphics/drm_formats.h
src/platform/CMakeLists.txt
src/platform/graphics/CMakeLists.txt
src/platform/graphics/drm_formats.cpp
src/platform/graphics/linux_dmabuf.cpp
src/platform/symbols.map
src/platforms/gbm-kms/server/kms/display.cpp
tests/CMakeLists.txt

Various parts of Mir code want to know various things about
pixel formats. The DRM fourcc format specifiers are reasonably
well described, in common use through Linux subsystems,
both kernel and userspace, and we already need to use them
in various parts of the codebase.
This adds some infrastructure for describing DRM formats.

platform: Add DRMFormat descriptor

---

tests/include/mir/test/input_config_matchers.h

(cherry picked from commit 08671a33714b6dc196d093e962a473730bd8bb5a)

release/1.8: Fix Alpine/edge (by not using internal GTEST macros for trivial stuff)

---

src/miroil/mir_server_hooks.cpp

This fixes a bunch of errors like the following while building against musl libc:
```
../src/miroil/mir_server_hooks.cpp: In member function 'std::shared_ptr<mir::scene::PromptSessionManager> miroil::MirServerHooks::the_prompt_session_manager() const':
../src/miroil/mir_server_hooks.cpp:164:16: error: 'logic_error' is not a member of 'std'
164 |     throw std::logic_error("No prompt session manager available. Server not running?");
|                ^~~~~~~~~~~
```

Add missing stdexcept include to mirserverhooks

---

src/include/server/mir/observer_multiplexer.h
src/server/graphics/default_configuration.cpp
src/server/scene/default_configuration.cpp
tests/unit-tests/test_observer_multiplexer.cpp

This PR adds three multiplexer tests (all of which previously deadlocked) and fixes all of them.
The core issue was that spawning an observation required locking the same mutex that remained locked while observations were being processed. The use of `recursive_mutex` mitigated that if everything was on the same thread, but if the receiving-observation thread was blocked on some other thread, which was blocked on sending an observation there was trouble.
This PR uses separate mutexes for spawning and running observations. Both are locked when an observer is unregistered, but unregister does not lock them simultaneously.
This fixes some of the deadlocks I've encountered in #2371, and assuming it's correct is an overall improvement.

Prevent deadlocks in ObserverMultiplexer

---

tests/acceptance-tests/wayland/CMakeLists.txt

With WLCS CI now publishing into Mir CI we've got a new WLCS, and that has fixed a couple of tests we XFAILed.

Update WLCS XFAIL list

---

tests/acceptance-tests/wayland/CMakeLists.txt
tests/acceptance-tests/wayland/print_missing_wlcs_tests.cmake

You can run the `list_missing_wlcs_xfail_tests` to get a list of the tests that we mark as expected failures that don't exist in the installed version of WLCS.
We don't want to *fail* XFAIL tests which don't exist, because we want to be able to mark a test that is *going* to land in WLCS as XFAIL.
However, where we've added tests to the expected failure list because the *test* is incorrect we should periodically run this target and remove any XFAILs that are now removed in WLCS.

wlcs: Add target to list XFAIL tests which don't exist

---

tests/unit-tests/dispatch/test_threaded_dispatcher.cpp

Don't try to cleanup child process on exit.
There can be "random" cleanup left by other tests that we don't care about.
Fixes #2377

Fix ThreadedDispatcherSignalTest.keeps_dispatching_after_signal_interruption

---

examples/client/wayland_client.c
tests/unit-tests/dispatch/test_threaded_dispatcher.cpp

Use `sigaction() throughout as `signal()` has unspecified behaviour in multithreaded programs.

Stop using `signal()` has unspecified behaviour in multithreaded programs

---

src/common/linearising_executor.cpp
src/common/system_executor.cpp
src/common/thread/recursive_read_write_mutex.cpp
src/platforms/common/server/egl_context_executor.cpp
src/platforms/eglstream-kms/server/threaded_drm_event_handler.cpp
src/platforms/wayland/displayclient.cpp
src/server/compositor/multi_threaded_compositor.cpp
src/server/frontend_xwayland/xwayland_server.cpp
src/server/glib_main_loop.cpp
src/server/input/default_input_device_hub.cpp
tests/include/mir/test/barrier.h
tests/integration-tests/compositor/multithread_harness.h
tests/integration-tests/test_surface_stack_with_compositor.cpp
tests/mir_test/signal.cpp
tests/mir_test_framework/async_server_runner.cpp
tests/mir_test_framework/passthrough_tracker.cpp
tests/mir_test_framework/server_runner.cpp
tests/mir_test_framework/test_display_server.cpp
tests/miral/wayland_extensions.cpp
tests/unit-tests/test_glib_main_loop.cpp
tests/unit-tests/test_observer_multiplexer.cpp

1. Do not call `condition_variable::notify_*` under lock: The woken thread cannot get lock the mutex.
2. Call `condition_variable::notify_one()` when only one thread will be able to proceed.

Don't wake threads that can't run

---

tests/performance-tests/CMakeLists.txt

This test more that doubles the time taken by `make ptest`. That's not worth it as it is very unlikely to detect problems during normal development activities.

Change default MIR_RUN_PERFORMANCE_TESTS option to OFF

---

debian/rules

[debian] run RISC-V tests across Launchpad builds

---

tests/include/mir/test/doubles/explicit_executor.h
tests/unit-tests/graphics/test_software_cursor.cpp

Makes some tests work in my better surface observer branch, and seems to be a general improvement to me.

ExplicitExecutor: repeat execute until queue is drained

---

debian/control
debian/libmircommon8.install
debian/libmircommon9.install
include/common/mir/thread_pool_executor.h
src/common/CMakeLists.txt
src/common/linearising_executor.cpp
src/common/symbols.map
src/common/thread_pool_executor.cpp
src/server/compositor/default_configuration.cpp
src/server/compositor/multi_threaded_compositor.cpp
src/server/run_mir.cpp
tests/unit-tests/CMakeLists.txt
tests/unit-tests/test_thread_pool_executor.cpp

I've previously discussed this with @RAOF. I think thread pool is a more obvious name. I don't think external code is using `SystemExecutor` but might be a no-go because of ABI stability?

Rename SystemExecutor to ThreadPoolExecutor

---

debian/rules

Unit tests are hanging on riscv64+jammy|kinetic, so don't run them. (Yes, I know!)
Also changed to _build_ the miral tests. So, in principle, we can install from the PPA to investigate.

Don't run failing tests on riscv64 PPA builds

---

examples/client/wayland_client.c

Clang now reports a `-Wstrict-prototypes` error:
```
wayland_client.c:371:9: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
```
So use the full prototype of `int main(int, char**)`.

wayland_client: Fix build error with recent clang

---

src/platforms/eglstream-kms/server/platform_symbols.cpp

It seems that Mesa is now exposing rendernodes as EGLDevices, but using the EGL query to find the device node of such devices fails.
Handle those exceptions by assuming the device is unsuitable.
Fixes: #2426

eglstream-kms: Handle EGL errors in `devnum_for_device`

---

src/platform/udev/udev_wrapper.cpp
tests/unit-tests/CMakeLists.txt
tests/unit-tests/test_udev_wrapper.cpp

Fixes: https://github.com/MirServer/mir-test-tools/issues/50

udev: Test (and fix) Context::char_device_from_devnum

---

src/platforms/eglstream-kms/server/platform_symbols.cpp

Oops. While fixing up #2426 I changed the scope of `device_holder`, so that
it would almost immediately go out of scope. This broke probing on the VT
console provider, as the VT console provider, and *only* the VT console
provider, drops DRM master when you release the `mir::Device`.
Fixes: #2431.

eglstream-kms: Retain DRM device access for whole probe.

---

tools/mir-smoke-test-runner.sh

Inspired by https://github.com/MirServer/mir/pull/2423#issuecomment-1129215985
Wayland support on desktop is becoming common and we ought to be able to run our smoke tests without reliance on X11.
This still retains the existing default of running on the X11 platform, but if that isn't available then we should try working on Wayland. If neither X11 nor Wayland support is available, the "hardware" platforms are still selectable.
This will allow, for example, the following to work:
```
miral-app -kiosk -terminal mir-smoke-test-runner
```

[mir-smoke-test-runner] Enable working in a Wayland only environment

---

src/platforms/wayland/platform.cpp
src/platforms/wayland/wayland_display.cpp

This was giving me an "EGL_SUCCESS" error in the common case that the Wayland host is set to a display that does not currently exist. I see no reason why this would ever be an EGL error, or why the exception should be thrown so far from were the error can initially be detected. This PR drops gives the relevant context of the display name it tried to connect to.

Wayland platform: improve failed to connect error

---

.gitattributes

There's no need for our release tarballs to contain a `debian/`
directory, or the GitHub CI metadata.
I'm *pretty* sure that GitHub will respect the git attributes when
generating the tarball.

[build]: Remove unnecessary files from release tarballs.

---

include/platform/mir/graphics/display.h

It seems that not everyone can psychically intuit the invariant that the `DisplayBuffer`s
provided by a `Display` must remain vaild at all times, and are only invalidated by a call
to `Display::configure`.
This should really go in some higher-level narrative documentation, but making the call's
documentation more explicit is a cheap way to make things better.

platform: Document Display::configure harder.

---

src/platforms/wayland/display.cpp
src/platforms/wayland/display.h
src/platforms/wayland/displayclient.cpp
src/platforms/wayland/displayclient.h

Fixes #2450 by making `DisplayClient` an executor and running the frame request on it

Wayland platform threadsafe swap_buffers()

---

src/renderers/gl/renderer.cpp
tests/unit-tests/renderers/gl/test_gl_renderer.cpp

The fully-transparent `glClearColor` was introduced in 2015 in commit dabbc2bc1f
titled “merge mir” (it is not a merge commit).
Since the practical result of a fully-transparent framebuffer is expensive black
on all hardware platforms (at least until transparent displays become a thing),
switch the behaviour *back* to clearing the framebuffer to black.
Fixes: #2427

renderers/gl: Clear framebuffer to opaque black, not fully-transparent.

---

src/server/frontend_wayland/wlr_screencopy_v1.cpp

The `.copy_with_damage` request still isn't implemented fully (it does not wait for there to be damage or report the damaged area of the screen), but with this change it works well enough for wayvnc to work (albeit with higher than needed CPU load)

wlr-screencopy-v1: send .damage event when required

---

include/core/mir/mutex.h
src/server/scene/basic_surface.cpp

Simplifies the syntax for dropping a mutex guard, and makes sure the program crashes if a mutex guard is used after being dropped (we could change this to a fatal error or exception at the cost of a single conditional branch based on a non-atomic bool each time the guard is accessed).

Add .drop method to mutex

---

src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/frontend_wayland/wlr_screencopy_v1.cpp
src/server/frontend_wayland/wlr_screencopy_v1.h
tests/include/mir/test/doubles/mock_frontend_surface_stack.h
tests/unit-tests/frontend_wayland/CMakeLists.txt
tests/unit-tests/frontend_wayland/test_screencopy_v1_damage_tracker.cpp

Waits until the copy area has been damaged in `.copy_with_damage` request.
The protocol isn't designed very well and is not super clear in how this is supposed to be implemented. The naive way would be to start waiting for damage when the request comes in, but that would allow a client to miss frames. Instead the way this is built is to dynamically create `CaptureArea`s for each area the client captures and track damage to those areas. That way a frame can be captured immediately with the correct damage if the damage happened between one frame being captured and the following frame being requested.
It would be nice to have this tested, but we need the screenshoter to work in WLCS for that and it currently does not.

Screencopy: wait for damage before copying frame

---

include/test/mir/test/doubles/stub_surface.h
src/include/server/mir/input/surface.h
src/include/server/mir/scene/null_surface_observer.h
src/include/server/mir/scene/surface_event_source.h
src/include/server/mir/scene/surface_observer.h
src/include/server/mir/scene/surface_observers.h
src/miroil/eventdispatch.cpp
src/miroil/surface.cpp
src/server/frontend_wayland/foreign_toplevel_manager_v1.cpp
src/server/frontend_wayland/wayland_surface_observer.cpp
src/server/frontend_wayland/wayland_surface_observer.h
src/server/frontend_xwayland/xwayland_surface_observer.cpp
src/server/frontend_xwayland/xwayland_surface_observer.h
src/server/input/cursor_controller.cpp
src/server/input/surface_input_dispatcher.cpp
src/server/scene/basic_surface.cpp
src/server/scene/basic_surface.h
src/server/scene/null_surface_observer.cpp
src/server/scene/surface_change_notification.cpp
src/server/scene/surface_change_notification.h
src/server/scene/surface_event_source.cpp
src/server/shell/abstract_shell.cpp
src/server/shell/decoration/input.cpp
src/server/shell/decoration/window.cpp
tests/include/mir/test/doubles/mock_surface.h
tests/unit-tests/input/test_cursor_controller.cpp
tests/unit-tests/scene/test_basic_surface.cpp
tests/unit-tests/scene/test_surface.cpp
tests/unit-tests/shell/test_decoration_basic_decoration.cpp

Because the modern observer system does not always send notifications on the same thread, it needs to be given types it can hold ownership of. This PR changes types used by SurfaceObserver to work. All methods still take a raw surface pointer, which is generally not used and should be removed, but that is out of scope here.

Refactor SurfaceObserver types to be compatible with new observer system

---

src/miral/wayland_extensions.cpp

Alternative to #2468, does not introduce a new command line option, instead allowing `--add-wayland-extensions all`. While I was in this part of the code, I improved our help and error messages relating to extensions. Now we only print the extension list once in help, and each extensions is on a different line so they're easier to read and copy/paste.
Before:
```
--wayland-extensions arg              Exhaustive list of all Wayland 
extensions to enable. 
[wl_shell:xdg_wm_base:zwlr_foreign_topl
evel_manager_v1:zwlr_layer_shell_v1:zwl
r_screencopy_manager_v1:zwp_idle_inhibi
t_manager_v1:zwp_input_method_manager_v
2:zwp_pointer_constraints_v1:zwp_relati
ve_pointer_manager_v1:zwp_text_input_ma
nager_v1:zwp_text_input_manager_v2:zwp_
text_input_manager_v3:zwp_virtual_keybo …
```

Allow --add-wayland-extenions all and clean up help message

---

include/platform/mir/graphics/display_configuration.h
include/test/mir/test/doubles/mock_display_configuration.h
include/test/mir/test/doubles/null_display_configuration.h
include/test/mir/test/doubles/stub_display_configuration.h
src/platform/graphics/display_configuration.cpp
src/platforms/eglstream-kms/server/kms_display_configuration.cpp
src/platforms/eglstream-kms/server/kms_display_configuration.h
src/platforms/gbm-kms/server/kms/real_kms_display_configuration.cpp
src/platforms/gbm-kms/server/kms/real_kms_display_configuration.h
src/platforms/rpi-dispmanx/display.cpp
src/platforms/wayland/displayclient.cpp
src/platforms/x11/graphics/display_configuration.cpp
src/platforms/x11/graphics/display_configuration.h
tests/mir_test_doubles/stub_display_configuration.cpp
tests/miral/test_window_manager_tools.cpp
tests/unit-tests/graphics/test_overlapping_output_grouping.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_cursor.cpp

Nothing has ever used this information, and in the new platform interface
we have one `DisplayPlatform` per card anyway.

platform/graphics: Drop `DisplayConfiguration::for_each_card`

---

tools/scan_symbols.py

Given the path to a .so file, this script will compare the symbols in the library with the symbols in the debian symbols file and show the symbols only present in one or the other. Not perfect, but makes manually editing symbols easier.

Add tools/scan_symbols.py script

---

src/miral/regenerate-miral-symbols-map.py

...so it regenerates symbols.map correctly. (We accidentally broke it in #2516)

Fix regenerate-miral-symbols-map.py

---

src/server/frontend_wayland/wl_keyboard.cpp
src/server/frontend_wayland/wl_keyboard.h

Possibly a naive implementation (as I've not read the protocol requirements)
Fixes: #2535
Fixes: #2025

Send keyboard modifiers after keyboard enter

---

src/server/frontend_wayland/keyboard_helper.cpp
src/server/frontend_wayland/virtual_keyboard_v1.cpp

Fixes #2533. I haven't observed any bugs related to this, but it is technically required by the latest wayland.xml (my impression is that in previous versions it was ambiguous but the new behavior was always generally expected, so changing behavior for all versions should be most correct).

Include null terminator in keymap

---

src/server/frontend_wayland/virtual_keyboard_v1.cpp
tests/mir_test_framework/mmap_wrapper.cpp

This and #2508 are the final two pieces required to make input work with wayvnc. I don't completely understand why reading from the fd works for squeekboard and not wayvnc, but mmap works for both and it's what wlroots does.

mmap keymap fd instead of reading from it

---

src/miral/symbols.map

Not sure how that slipped through, at least on LLD it prevents Mir from building.

Drop (accidental?) extern "C++" in miaral symbols

---

src/platforms/gbm-kms/server/display_helpers.cpp
src/platforms/gbm-kms/server/kms/platform_symbols.cpp
src/platforms/gbm-kms/server/kms/quirks.cpp
src/platforms/gbm-kms/server/kms/quirks.h
tests/unit-tests/platforms/gbm-kms/kms/test_quirks.cpp

With an implicit `display-quirks=disable-kms-probe:virtio_gpu` as we need it for virtio

Add a new driver quirk to disable KMS modeset probe

---

debian/libmiral5.symbols
include/miral/miral/zone.h
src/miral/symbols.map
src/miral/zone.cpp

Not having this has been a recurring annoyance in writing shells. With the ID a shell can have a hashmap of zones, store an associated zone with a window, etc. Without it identifying zones is much less convenient and efficient.

Expose miral::Zone::id()

---

src/miral/basic_window_manager.cpp
src/platforms/gbm-kms/server/display_helpers.cpp
src/platforms/gbm-kms/server/kms/platform_symbols.cpp
tests/unit-tests/scene/test_surface_state_tracker.cpp

It exists, is standardised, so why not. Compilers might not continue to treat a `//fallthrough` or `//falls through` comment equivalently!

trivial: Use C++17 [[fallthrough]] attribute

---

doc/Doxyfile.in

Mostly this makes little difference.
But there are places (like many of the source listings) where the output improves.

Use Clang parser for generating docs

---

src/platforms/gbm-kms/server/kms/quirks.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_quirks.cpp

Mir's gbm-kms support isn't (yet) working with nvidia or evdi.
Better to disable drivers here than in Ubuntu Frame configuration: When we have them working we just need update one project. 
See: https://github.com/MirServer/ubuntu-frame/blob/a6ba2e1d84a2d6edd3b7e5c439a3c06d78998f96/snap/hooks/configure#L81

Add more defaults to driver-quirks

---

src/platforms/gbm-kms/server/kms/quirks.cpp

We're already skipping the modesetting check in Frame and mir-kiosk, just consolidating these as defaults:
* RPi3b: vc4-drm
* RPi4: vc4-drm & v3d

More default quirks

---

src/platforms/evdev/libinput_device.cpp
src/platforms/evdev/libinput_device.h
tests/include/mir/test/doubles/mock_libinput.h
tests/mir_test_doubles/mock_libinput.cpp
tests/unit-tests/input/evdev/test_libinput_device.cpp

Do not conflate `LIBINPUT_EVENT_POINTER_AXIS` with `LIBINPUT_EVENT_POINTER_SCROLL_WHEEL` etc.
Fixes: #2565

Handle the new libinput events

---

tests/mir_test_doubles/mock_x11.cpp

Only call global_mock->XInitThreads() if global mock exists

---

src/server/input/default_event_builder.cpp
src/server/input/default_event_builder.h
src/server/input/default_input_device_hub.cpp
tests/include/mir/test/doubles/advanceable_clock.h
tests/unit-tests/input/CMakeLists.txt
tests/unit-tests/input/evdev/test_libinput_device.cpp
tests/unit-tests/input/test_default_event_builder.cpp
tests/unit-tests/input/test_seat_input_device_tracker.cpp
tests/unit-tests/input/test_x11_platform.cpp

Fixes #2577
Prevent timestamps in the future ever being sent, and use unmodified timestamps if they're close to Mir's internal timestamps.

Fix timestamp calibration 

---

debian/rules
tests/integration-tests/test_display_server_main_loop_events.cpp
tests/mir_test_framework/async_server_runner.cpp
tests/mir_test_framework/server_runner.cpp
tests/mir_test_framework/test_display_server.cpp
tests/performance-tests/system_performance_test.cpp

---
I left this one be:
https://github.com/MirServer/mir/blob/3661378e54ffd9fc96c72442b6c51cbf6e830e5c/tests/miral/external_client.cpp#L72-L73
It may still be I need something extra for CI, let's see.

tests: fix XDG_RUNTIME_DIR handling

---

debian/rules

We run into [LP#1983852](https://bugs.launchpad.net/ubuntu/+source/gcc-12/+bug/1983852) otherwise.

debian: disable pre-compiled headers on gcc-12

---

src/miral/minimal_window_manager.cpp
src/server/frontend_wayland/wl_pointer.cpp

Fixes #2584
Pretty quick, can definitely be improved later.
EDIT: I fixed the most pressing problem, which was the window not always staying under the cursor. This branch also now moves closer to fixing #1793 (although we still need to plumb through proper serial handling and input event remembering for that to matter)

MinimalWindowManager: allow moving window from the maximized state

---

src/server/compositor/multi_monitor_arbiter.cpp

The compositor ID should not be added repeatedly when there is no new buffer available

[MultiMonitorArbiter] track buffer users better

---

include/common/mir/events/event_builders.h
include/common/mir/events/touch_contact.h
include/platform/mir/input/event_builder.h
src/common/events/event_builders.cpp
src/common/events/touch_event.cpp
src/common/input/input_event.cpp
src/common/symbols.map
src/include/common/mir/events/touch_event.h
src/include/server/mir/input/validator.h
src/platforms/evdev/libinput_device.cpp
src/platforms/wayland/display.cpp
src/platforms/wayland/display.h
src/platforms/wayland/display_input.h
src/platforms/wayland/input_device.cpp
src/platforms/wayland/input_device.h
src/server/input/default_event_builder.cpp
src/server/input/default_event_builder.h
src/server/input/validator.cpp
tests/integration-tests/input/test_single_seat_setup.cpp
tests/mir_test_framework/fake_input_device_impl.cpp
tests/unit-tests/input/evdev/test_libinput_device.cpp
tests/unit-tests/input/test_idle_poking_dispatcher.cpp
tests/unit-tests/input/test_input_event.cpp
tests/unit-tests/input/test_seat_input_device_tracker.cpp

This renames `ContactState` to `TouchContact`, and versions it similar to how scroll axis is versioned. The old `ContactState` struct is kept around for ABI stability, and is aliased to `TouchContactV1`
The motivation for this is that I want to add local position to touch events (and pointer events) as part of my work on #1792, but to do that without breaking ABI I need more flexibility in the touch contact struct.

Modernize touch events

---

src/server/input/default_event_builder.cpp
src/server/input/default_event_builder.h
tests/unit-tests/input/test_default_event_builder.cpp

Use the timestamp if it is reasonable, and use the measured current time otherwise. As discussed in #2591.

Simplify timestamp calibration

---

CMakeLists.txt
tests/CMakeLists.txt

Fat LTO objects slow down the build. We don't *need* fat LTO objects, as we don't ship any LTO'd static archives.

CMake: Use non-fat LTO

---

src/platforms/common/server/buffer_from_wl_shm.cpp

Fixes #2620
This would be better synchronised using an egl fence, but Chris has volunteered to fix that later.

Bind shm textures when we create the buffers

---

CMakeLists.txt
debian/rules
tests/mir_test_framework/CMakeLists.txt
tests/unit-tests/CMakeLists.txt

We semi-regularly run into toolchain bugs where a warning false-positives on our test code¹. Add the minimal infrastructure to let us disable `-Werror` on the smallest easily-accessible code unit, and quirk off `Werror` on the current set of gcc-12 false-positives.
¹: GTest is apparently a compiler fuzzing suite

Add quirks for false-positive compiler warnings

---

src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h

The libwayland global filter is called during wl_global_remove (sensibly, as it needs to know whether or not the client knows about the global that's being removed).
This means that the filter will be called from the destructor of any extension object that publishes a global (ie: all of them).
Ensure it lives long enough to avoid UAF.

WaylandConnector: Fix use-after-free

---

src/miral/basic_window_manager.cpp
src/miral/basic_window_manager.h
tests/miral/application_zone.cpp
tests/miral/window_placement_attached.cpp

Fixes #2580. Before we always removed application zones when they had no associated outputs. We still do that now if *any* zones have associated outputs, but if all outputs are removed we keep zones as-is. When at least one output is added again we reevaluate and delete any zones that are no longer needed. `DisplayArea::output_id` is added so that a re-added output can be matched with the zone that was originally created for it.

Preserve application zones when all outputs removed

---

src/server/frontend_wayland/text_input_v1.cpp
src/server/frontend_wayland/text_input_v2.cpp

~~Fixes #2651,~~ should have been included in #2270

Deactivate text input in destructor for v1 and v2 protocols

---

src/server/run_mir.cpp

Our fatal signal handler is (necessarily!) signal-unsafe, so we can deadlock while trying to run it.
At least document this, and dump a message using a known-safe method before proceeding into the swamp.

Server/run_mir: Fatal signal handling is the worst.

---

CMakeLists.txt

Attempting to run this on non-Debian systems building from the release tarballs breaks running tests due to non-existent debian dir.
Fixes #2596.

CMake: Only run package-abis test if toplevel debian dir exists

---

src/server/run_mir.cpp

*Of course* there exist compilers for which `static_cast<void>(foo)` does not disable the “must-use return value” warning for `write()`…
Fixes: #2663

Server/run_mir: Fix build failure.

---

tests/include/mir/test/doubles/mock_input_surface.h

This was apparently missed in the recent Event refactor.
Fixes: #2659

mtd::MockInputSurface: Fix `consume` method signature 

---

src/server/run_mir.cpp

Oops. We should probably add a newline after our “it's all going to hell” warning.

Server/run_mir: Improve warning message.

---

include/platform/mir/renderer/sw/pixel_source.h
include/renderers/gl/mir/renderer/gl/basic_buffer_render_target.h
include/renderers/gl/mir/renderer/gl/buffer_render_target.h
include/renderers/gl/mir/renderer/gl/render_target.h
src/platform/graphics/cpu_buffers.cpp
src/platforms/common/server/buffer_from_wl_shm.cpp
src/platforms/common/server/shm_buffer.h
src/platforms/eglstream-kms/server/display.cpp
src/platforms/gbm-kms/server/kms/display_buffer.cpp
src/platforms/gbm-kms/server/kms/display_buffer.h
src/platforms/rpi-dispmanx/display_buffer.cpp
src/platforms/rpi-dispmanx/display_buffer.h
src/platforms/wayland/displayclient.cpp
src/platforms/x11/graphics/display.cpp
src/platforms/x11/graphics/display_buffer.cpp
src/platforms/x11/graphics/display_buffer.h
src/renderers/gl/basic_buffer_render_target.cpp
src/renderers/gl/renderer.cpp
src/renderers/gl/renderer.h
src/server/compositor/basic_screen_shooter.cpp
src/server/frontend_wayland/wlr_screencopy_v1.cpp
src/server/frontend_wayland/wlr_screencopy_v1.h
tests/include/mir/test/doubles/mock_gl_display_buffer.h
tests/include/mir/test/doubles/stub_buffer.h
tests/include/mir/test/doubles/stub_gl_display_buffer.h
tests/unit-tests/compositor/test_basic_screen_shooter.cpp
tests/unit-tests/frontend_wayland/test_screencopy_v1_damage_tracker.cpp
tests/unit-tests/renderers/gl/test_basic_buffer_render_target.cpp
tests/unit-tests/renderers/gl/test_gl_renderer.cpp

Fixes #2653, a few systems needed to be refactored. With this PR software buffers now expose their properties without being mapped, render targets expose their size so the renderer doesn't have to query the current EGL surface (something that never worked for screenshots), and our wlr-screencopy implementation requests clients use buffers of the full output resolution rather than the logical size.

Support scaled screenshots

---

src/platforms/gbm-kms/server/kms/quirks.cpp

These are basic 2D output devices built into motherboards (particularly server MBs). They have no 3D hardware, and they have no DRI drivers. Unfortunately, bug #2678 means that this causes Mir to fail to come up on a system with AST hardware.
Like evdi, this hardware *should* be supportable in the New Platform API™, but for now quirking it off is the appropriate response.

gbm-kms/quirks: Quirk off AST devices

---

src/server/frontend_xwayland/xwayland_clipboard_source.cpp

Fixes #2677? I'm not quite sure the cause of the originally described bug (copying up to the last `\n`, nor have I observed that behavior specifically. However this does seem to fix the CLion/Intellij copy/paste bugs I'm seeing.
The problem is that when we got a new paste source we cleared the old one, but since setting up an X11 paste is a multi-step process and paste source observations are non-blocking, both the clearing and new source setup were happening at an arbitrary time and racing. With this PR the old paste source is invalidated (so nothing can paste from it), but it's not cleared. It will instead be replaced by the future paste source that will be created. If something goes wrong in the setup process, the worst that can happen is apps see an expired paste source, but trying to …

XWaylandClipboardSource: do not clear source just before a new one is set

---

src/server/terminate_with_current_exception.cpp

We've encountered a few issues recently where we think we're trying to terminate, but don't have clear diagnostic information.
This ensures we log the "current exception" before trying to terminate.

Add some logging to terminate_with_current_exception()

---

src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h

By closing clients explicitly instead of waiting for the destruction of the display to do it, clients do not see all globals disappear (which they may not be designed to handle)

Close all Wayland clients on server stop

---

src/client/rpc/mir_protobuf_rpc_channel.cpp
src/renderers/gl/renderer.h
src/server/glib_main_loop_sources.cpp
tests/acceptance-tests/test_presentation_chain.cpp
tests/acceptance-tests/test_prompt_session_client_api.cpp
tests/unit-tests/compositor/test_multi_monitor_arbiter.cpp
tests/unit-tests/scene/test_application_session.cpp
tests/unit-tests/scene/test_basic_surface.cpp
tests/unit-tests/test_glib_main_loop.cpp
tests/unit-tests/test_posix_rw_mutex.cpp

Adding missing headers, needed for compilation with GCC-12.

Fix compilation failure with GCC-12 (missing headers)

---

src/platform/options/default_configuration.cpp

Since `--wayland-host` is an option only provided by the Wayland platform, it makes more sense to present an example option that is existent on all platforms. This uses `--wayland-extensions` instead as an example. Fixes #2687

Don't use "wayland-host" as command line option example

---

.github/workflows/ppa-upload.yml
.github/workflows/snap.yml
.github/workflows/spread.yml

Because Node.js 12 actions are getting deprecated:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

ci: bump actions/checkout version

---

src/server/frontend_wayland/wl_data_device.cpp

Before we were sending multiple null sections in a row, and may have been allowing clients to paste after they were unfocused. This PR cleans up that logic so that clients can only paste from the currently active offer and events are sent only as necessary.

Clean up copy/paste messages

---

src/platforms/gbm-kms/server/kms/real_kms_output.cpp

In #2690, we're segfaulting trying to access the size of an output. Maybe this "fixes" it?
Marked as "draft" as it is experimental

Disconnected hardware has no modes: invent a size

---

src/include/server/mir/default_server_configuration.h
src/include/server/mir/server_configuration.h
src/server/frontend_wayland/CMakeLists.txt
src/server/frontend_wayland/primary_selection_v1.cpp
src/server/frontend_wayland/primary_selection_v1.h
src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h
src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/frontend_wayland/wl_keyboard.cpp
src/server/frontend_wayland/wl_keyboard.h
src/server/frontend_wayland/wl_seat.cpp
src/server/scene/default_configuration.cpp
src/server/symbols.map
src/wayland/CMakeLists.txt
src/wayland/protocol/primary-selection-unstable-v1.xml
src/wayland/symbols.map
tests/acceptance-tests/wayland/CMakeLists.txt

Needs to be enabled with `--add-wayland-extensions zwp_primary_selection_device_manager_v1`. GTK doesn't seem to consistently work outside of one app, possibly due to environment variable/settings problem? Qt works. Without a check that the receiving client has a focused surface it passes WLCS, but with that check it needs https://github.com/MirServer/wlcs/pull/245 (so I disabled the relevant tests until that's resolved).
Fixes #2699 
Fixes #2583.

Implement wp_primary_selection_unstable_v1

---

src/platforms/gbm-kms/server/kms/platform_symbols.cpp

Ensure that a candidate device has the hardware to support at least one physical display. It's not a very useful `DisplayPlatform` without at least one display :grin:
Also ensure that the device supports hardware EGL; this is (currently) a requirement for the gbm-kms `DisplayPlatform`.
Fixes: #2258

gbm-kms: Improve Display platform probing

---

include/core/mir_toolkit/events/enums.h
src/common/events/keyboard_event.cpp
src/common/input/xkb_mapper.cpp
src/common/symbols.map
src/include/common/mir/events/keyboard_event.h
src/include/common/mir/events/xkb_modifiers.h
src/include/common/mir/input/key_mapper.h
src/include/common/mir/input/xkb_mapper.h
src/include/server/mir/input/seat.h
src/server/frontend_wayland/input_method_grab_keyboard_v2.cpp
src/server/frontend_wayland/input_method_grab_keyboard_v2.h
src/server/frontend_wayland/keyboard_helper.cpp
src/server/frontend_wayland/keyboard_helper.h
src/server/frontend_wayland/virtual_keyboard_v1.cpp
src/server/frontend_wayland/wl_keyboard.cpp
src/server/frontend_wayland/wl_keyboard.h
src/server/input/basic_seat.cpp
src/server/input/basic_seat.h
src/server/input/key_repeat_dispatcher.cpp
src/server/input/seat_input_device_tracker.cpp
src/server/input/seat_input_device_tracker.h
tests/include/mir/test/doubles/mock_input_seat.h
tests/include/mir/test/doubles/mock_key_mapper.h

Instead of the long-standing hacky solution of maintaining an XKB state in the Wayland frontend, this PR uses the state already maintained in the KeyMapper. XKB modifiers are now passes as part of key events so they are available for the frontend to send to clients. With these changes in place it was possible to add support for virtual keyboard modifiers.
Fixes #2720
Fixes #2145

Move XKB modifier tracking from Wayland frontend to KeyMapper

---

.github/workflows/ppa-upload.yml

Hello :) This should allow for kinetic ppa debs to continue now that kinetic is no longer 'devel'. I have also taken the liberty to stop using 'devel' in this context and explicitly name lunar (=23.04) as it would seem much better for any debs which are being built to continue being built (and then adding the latest development release when needed), rather than the latest release debs stopping as soon as there is a new development release. I appreciate there might be a good reason to use 'devel', but (with my limited knowledge) I couldn't see anything immediately obvious. Thanks a lot!

Continue building ppa debs for kinetic

---

CMakeLists.txt
cmake/MirCommon.cmake
spread/build/sbuild/task.yaml
tools/discover_gtests.sh

We've been accidentally misusing `tools/discover-gtests.sh` by trying to pass `--gtest_filter` through. Due to the way GTest parses `--gtest_filter` (specifically, that it only respects the *last* `--gtest_filter` on the command line, ignoring any others), this results in any filter we were *trying* to pass in being ignored.
Instead, add a `--gtest-includes` option to `tools/discover-gtests.sh`, error out if the command contains `--gtest_filter`, use this in test discovery infrastructure, and explicitly pass tests we don't expect to run as `--gtest-excludes`.

cmake: Fix ptest target

---

include/platform/mir/graphics/drm_formats.h
src/platform/graphics/drm_formats.cpp
src/platform/symbols.map

Ideally we would migrate to a world where `DRMFormat` is the canonical type for pixel formats; there are more of them, and the descriptor contains more useful information that code using `MirPixelFormat` has had to ad-hoc.
Make it possible to start doing this by adding a conversion from `DRMFormat` to `MirPixelFormat`. This is necessarily lossy, as there are a lot of `DRMFormat`s that have no corresponding `MirPixelFormat`, but that implies that *current* code couldn't have properly handled them, so it's OK.

platform/DRMFormat: Add as_mir_format converter

---

src/server/frontend_wayland/primary_selection_v1.cpp
src/server/frontend_wayland/virtual_keyboard_v1.cpp
src/server/frontend_wayland/wl_client.cpp

Clang warns about calling `std::move` as an unqualified call to `move`, and is reasonable to do so because Argument Dependent Lookup *could* cause the compiler to resolve `bar::T baz; move(baz)` to some other `bar::move(baz)` if there happens to be a `bar::move(T)` implementation in the same namespace as `T` is defined.
Closes: #2742

Fixup unqualified `std::move` warnings

---

spread.yaml
spread/build/sbuild/task.yaml
spread/build/ubuntu/task.yaml

This is both a (tiny) CI optimisation - we're running sbuild inside an ephemeral LXD container, so there's no point in spending time cleaning up the schroot - and also makes for easier debugging, as you can run `spread -debug` to stop after sbuild fails and still have the build available in the preserved schroot session.

spread/sbuild: Don't purge the schroot session, more for local runs

---

src/include/server/mir/display_changer.h
src/server/display_server.cpp
src/server/scene/mediating_display_changer.cpp
src/server/scene/mediating_display_changer.h
tests/unit-tests/scene/test_mediating_display_changer.cpp

The MediatingDisplayChanger will in many scenarios revert to the base_configuration which means this must be kept up to date.
Fixes: #2695
Fixes: #2757
It may be worth revisiting  #2632, but I am entirely unclear how to reproduce or test that.

Fix MediatingDisplayChanger::set_power_mode()

---

src/server/frontend_xwayland/xwayland_surface.cpp

We need to ensure that no further callbacks occur after `~XWaylandSurfaceObserverManager()` executes, and this is guaranteed by `ObserverRegistrar::unregister_interest()`:
* It is guaranteed that once unregister_interest() returns that no
* other thread is in, or will receive, observations from this
* ObserverRegistrar. If the thread calling unregister_interest()
* is currently in an Observer call that call will complete, but
* no further ones will be dispatched.
What is not guaranteed though is that there will be no remaining `shared_ptr` to `observer`.
In practice, that is not so as `WeakObserver::spawn()` may still hold `live_observer` after `WeakObserver::invoke()` has returned.
As the check is both redundant and wrong remove it.
Fixes: #2790

Do not abort when nothing is wrong

---

include/miroil/miroil/edid.h
include/platform/mir/graphics/egl_extensions.h

- `<stdexcept>` for `std::logic_error`
- `<cstdint>` for `uint*_t`
Fixes failure to compile with GCC 13.

Add missing #include statements

---

tests/unit-tests/test_shm_backing.cpp

So, `mmap` will provide a mapping *of pages*, which means its going to be a multiple of `PAGE_SIZE`, even if the backing file is not a-multiple-of-`PAGE_SIZE` big. It zero-pads the end up to the next page, *and accesses to this zero-initialised region do not fault*.
Now, it turns out I picked `4000` as the backing size, which is close enough to the `PAGE_SIZE` of `4096` on *most* kernels Ubuntu builds that doubling it puts you in a separate page, so these tests pass on all systems with a 4K `PAGE_SIZE`.
ppc64el has a 64K `PAGE_SIZE` 😠
Fix this by querying `sysconf(_SC_PAGE_SIZE)` and making our backing file *exactly* one page in size. Combined with `mmap` being specified to map on a page-aligned address (which is really the only thing it could do), that guarantees that *any* access …

tests/ShmBacking: Improve invalid access tests.

---

src/miral/static_display_config.cpp
src/miral/static_display_config.h

This method contained a lambda over 100 lines long with multiple responsibilities.
This splits the responsibilities between an 11 line lambda and two new methods each with a single responsibility.
Note to reviewers: This is a pure refactoring with no functional changes

[miral] refactor YamlFileDisplayConfig::apply_to()

---

cmake/Doxygen.cmake

`rm -f dir` doesn't do.
Fixes: #2800

doc: better removal of existing docs

---

include/platform/mir/graphics/display.h
src/include/server/mir/default_server_configuration.h
src/include/server/mir/server_configuration.h
src/platforms/eglstream-kms/server/display.cpp
src/platforms/eglstream-kms/server/display.h
src/platforms/gbm-kms/server/kms/display.cpp
src/platforms/gbm-kms/server/kms/display.h
src/platforms/gbm-kms/server/kms/platform.cpp
src/platforms/gbm-kms/server/kms/platform.h
src/platforms/gbm-kms/server/kms/platform_symbols.cpp
src/platforms/rpi-dispmanx/display.cpp
src/platforms/rpi-dispmanx/display.h
src/platforms/wayland/display.cpp
src/platforms/wayland/display.h
src/platforms/x11/graphics/display.cpp
src/platforms/x11/graphics/display.h
src/server/display_server.cpp
tests/include/mir/test/doubles/mock_console_services.h
tests/include/mir/test/doubles/mock_display.h
tests/include/mir/test/doubles/null_display.h
tests/integration-tests/test_display_server_main_loop_events.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_buffer_allocator.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display_configuration.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display_generic.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display_multi_monitor.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_platform.cpp

The `ConsoleServices` is a singleton, and which the `DisplayPlatform` only needs
to interact with during construction (in order to `acquire_device`).
There's no need to force the `Display` to keep a reference to the `ConsoleServices`
purely so that it can forward `register_pause_resume_handlers` to it.

platform/Display: Remove register_pause_resume_handlers

---

include/wayland/mir/wayland/protocol_error.h

This fixes building for Fedora Linux 38, which ships GCC 13.

wayland: Add missing cstdint includes

---

src/miral/static_display_config.cpp
src/miral/static_display_config.h
src/platforms/gbm-kms/server/kms/real_kms_display_configuration.cpp
tests/miral/static_display_config.cpp

* Refactor YamlFileDisplayConfig::apply_to() more
* use the unique output name as an identifier (instead of a weird tuple)
* Some drive-by tidy up

More refactoring of display configuration

---

src/miral/static_display_config.cpp
src/miral/static_display_config.h

When creating a .display configuration include multiple layouts (`all_at_00` and `side_by_side`)

Add a side-by-side layout to the .display configuration

---

src/miral/static_display_config.cpp

This makes it easier to add display configuration strategies and applies these strategies when a `display-layout` option is not found in the configuration file (or the file isn't found).

More tweaking of the display configuration code

---

src/miral/static_display_config.cpp
src/miral/static_display_config.h
tests/miral/static_display_config.cpp

* Roll the "default" layout into the `layout_strategies` table
* Write the .display configuration file before applying the selected layout to preserve the default settings
* If an output "appears" after the .display configuration is written apply the named strategy (if found) and use those values by default

More tidy-up of the display configuration

---

include/miral/miral/display_configuration.h
src/miral/display_configuration.cpp
src/miral/static_display_config.cpp
src/miral/static_display_config.h

In cases where a .display configuration fle is used add an additional .display-layout configuration file.
Creating or updating this file will update the active display layout.

Add a .display-layout configuration file

---

src/server/frontend_wayland/idle_inhibit_v1.cpp
src/server/frontend_wayland/idle_inhibit_v1.h
src/server/frontend_wayland/wl_surface.cpp
src/server/frontend_wayland/wl_surface.h

Based on and alternative to #2839. I put the visibility observer in idle_inhibit_v1.cpp to avoid cluttering wl_surface.cpp. Draft since there's still some issues I've observed and want to sort out. Not yet clear if they're also in our current implementation and/or Alan's implementation.
Fixes #2838
Fixes #2836

(Sophie's) reimplementation of idle_inhibit_unstable_v1

---

src/server/frontend_wayland/layer_shell_v1.cpp
src/server/frontend_wayland/window_wl_surface_role.cpp
src/server/frontend_wayland/window_wl_surface_role.h
src/server/frontend_wayland/wl_shell.cpp
src/server/frontend_wayland/xdg_shell_stable.cpp
src/server/frontend_wayland/xdg_shell_stable.h
src/server/frontend_wayland/xdg_shell_v6.cpp

Some toolkits & clients are not deleting the surface role before deleting the surface. 
Killing the connection when they do this is too harsh: Wayland servers are not conformance test suites, and can be flexible in what they expect.
There is text in wl-shell that directs that, despite the client not being allowed to do this, the server should delete the role object. And we already handled that case this way. Mutter does the same with xdg-shell, so there is prior art for what is proposed here.
We have a different workaround in layer-shell, as squeekboard doesn't delete the surface role before the surface, but also crashes if the role object is destroyed by the server.

[Wayland] Don't kill bad clients

---

debian/libmiral5.symbols
include/miral/miral/output.h
src/miral/output.cpp
src/miral/regenerate-miral-symbols-map.py
src/miral/symbols.map

These are useful for compositors (e.g. Frame) that want to do lexical matching (e.g. HDMI-1: "Kodi")

[miral] Provide output names

---

src/include/server/mir/input/scene.h
src/server/input/cursor_controller.cpp
src/server/input/surface_input_dispatcher.cpp
src/server/input/surface_input_dispatcher.h
src/server/scene/surface_stack.cpp
src/server/scene/surface_stack.h
tests/include/mir/test/doubles/stub_input_scene.h
tests/unit-tests/input/test_cursor_controller.cpp
tests/unit-tests/input/test_surface_input_dispatcher.cpp
tests/unit-tests/scene/test_surface_stack.cpp

`for_each()` was only being used to implement finding the topmost input surface. Our `input::Scene` implementation already has a more performant function to find the topmost surface.

Replace input::Scene::for_each() with input_surface_at()

---

include/platform/mir/graphics/egl_extensions.h

The Wayland extensions aren't MESA-exclusive anymore (and haven't been for *some time*)

Drop redundant eglmesaext.h include

---

debian/libmiral5.symbols
include/miral/miral/display_configuration.h
include/miral/miral/output.h
include/platform/mir/graphics/display_configuration.h
src/miral/display_configuration.cpp
src/miral/display_configuration_listeners.cpp
src/miral/display_configuration_listeners.h
src/miral/output.cpp
src/miral/static_display_config.cpp
src/miral/static_display_config.h
src/miral/symbols.map
src/platform/graphics/display_configuration.cpp
tests/mir_test_doubles/stub_display_configuration.cpp
tests/miral/static_display_config.cpp

This is motivated by Frame needing a way to assign apps to outputs

Add an API for adding custom attributes to outputs

---

src/server/frontend_wayland/xdg_shell_stable.cpp
src/server/frontend_wayland/xdg_shell_stable.h
src/server/frontend_wayland/xdg_shell_v6.cpp

While poking around in WLCS I noticed that we have some potential for use-after-free in XDG surfaces. This clears those issues up.

Use wayland::Weak in place of raw pointers in XDG surfaces

---

src/miral/basic_window_manager.cpp

Required to pass the new WLCS tests added by https://github.com/MirServer/wlcs/pull/277

Detect cyclic parent-child relationships

---

debian/control
debian/libmirplatform24.install
debian/libmirplatform25.install
src/CMakeLists.txt

We've introduced members to mir::graphics::Display, DisplayConfigurationOutput and UserDisplayConfigurationOutput that break ABI

Bump mirplatform soname

---

.github/workflows/snap.yml
.github/workflows/spread.yml

Ref.:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
This will cancel any pending runs for a PR, avoiding wasted work and speeding up results when we get throttled down.

ci: cancel previous PR runs

---

include/platform/mir/graphics/display.h
src/server/graphics/CMakeLists.txt
src/server/graphics/multiplexing_display.cpp
src/server/graphics/multiplexing_display.h
src/server/scene/mediating_display_changer.cpp
tests/include/mir/test/doubles/mock_display.h
tests/unit-tests/graphics/CMakeLists.txt
tests/unit-tests/graphics/test_multiplexing_display.cpp
tests/unit-tests/scene/test_mediating_display_changer.cpp

In the brave New Platform API™ world, each `DisplayPlatform` drives
a single set of display hardware.
This means, for multi-GPU cases, Mir needs to aggregate multiple
`Display`s into a single, combined configuration.
`MultiplexingDisplay` does this.

Multiplexing display

---

.github/workflows/snap.yml

The mir-libs-build branches now contain the track and risk. Just add the branch
Fixes: #2877

[snaps workflow] Fix Frame build

---

src/miral/minimal_window_manager.cpp

We introduced "attached" windows to support layer-shell. But the window manager can use them to support docked applications. But docked applications should be dragged into a restored state. (See https://github.com/Miriway/Miriway/pull/28 for an example of this)
I don't think this affects the layer-shell support as these windows won't initiate a drag gesture.

Allow "attached" windows to be "restored" by drag gesture

---

include/miroil/miroil/event_builder.h
src/miroil/input_device.cpp
src/miroil/mir_server_hooks.cpp

There's no longer any point in keeping miroil source-compatibile between 1.x and 2.x. It has been introduced and used in both places

Drive-by cleanup

---

.github/workflows/snap.yml

I've seen this "cancelled after 30 minutes" a few times.
Bumping the timeout

[mir-libs] bump timeout

---

src/include/server/mir/default_server_configuration.h
src/include/server/mir/frontend/drag_icon_controller.h
src/server/input/cursor_controller.cpp
src/server/input/cursor_controller.h
src/server/scene/default_configuration.cpp
src/server/symbols.map
tests/include/mir/test/doubles/mock_surface.h
tests/unit-tests/input/test_cursor_controller.cpp

This is a prerequisite for drag & drop support. (It isn't connected up to anything yet, so doesn't impact visible behaviour.)
Fixes: #640

Add support for cursor drag icons

---

src/include/server/mir/scene/clipboard.h
src/include/server/mir/scene/data_exchange.h
src/server/frontend_wayland/primary_selection_v1.cpp
src/server/frontend_wayland/wl_data_device.cpp
src/server/frontend_wayland/wl_data_device.h
src/server/frontend_wayland/wl_data_source.cpp
src/server/frontend_wayland/wl_data_source.h
src/server/frontend_xwayland/xwayland_clipboard_provider.cpp
src/server/frontend_xwayland/xwayland_clipboard_provider.h
src/server/frontend_xwayland/xwayland_clipboard_source.cpp
src/server/frontend_xwayland/xwayland_clipboard_source.h
src/server/scene/basic_clipboard.cpp
src/server/scene/basic_clipboard.h
tests/unit-tests/scene/test_basic_clipboard.cpp

Extract and rename data exchange interface that is common between cut & paste, select & paste, and drag and drop.

Rename ClipboardSource to DataExchangeSource

---

include/miral/miral/window_manager_tools.h
src/include/server/mir/scene/null_surface_observer.h
src/include/server/mir/scene/surface.h
src/include/server/mir/scene/surface_event_source.h
src/include/server/mir/scene/surface_observer.h
src/include/server/mir/scene/surface_observers.h
src/miral/basic_window_manager.cpp
src/miral/basic_window_manager.h
src/miral/window_management_trace.cpp
src/miral/window_management_trace.h
src/miral/window_manager_tools.cpp
src/miral/window_manager_tools_implementation.h
src/miroil/surface.cpp
src/server/scene/basic_surface.cpp
src/server/scene/basic_surface.h
src/server/scene/null_surface_observer.cpp
src/server/scene/surface_event_source.cpp
tests/include/mir/test/doubles/stub_surface.h

This is not functional without the mirclient API and content-hub, and not useful as a framework for further development.
There are miral and miroil APIs that mention drag and drop. For ABI stability these are retained and deprecated, but do nothing.

Drop legacy drag & drop code

---

src/server/shm_backing.cpp

We `new` a `struct sigaction` each time this gets called, so we need to either stash it somewhere (as `previous_handler`) or `delete` it.

server/ShmBacking: Fix leak in `install_sigbus_handler`

---

src/platforms/wayland/display.cpp

Fixes #2902, alternative to #2901, I've looked into #2903 but that seems a little more complicated (and tricky to test)

Wayland platform: flush display before polling

---

src/platforms/evdev/platform.cpp

When libinput fails to add a device via `libinput_path_add_device` it will already have called the close-fd hook we provide. We should not try to remove it from the `FdStore` ourselves; that will (at best) result in `FdStore` generating a warning, or, if the fatal stars align *just right*, will result in us closing a newly-acquired FD to an unrelated input device.
Fixes log warnings of the form:
```
[2023-05-15 10:43:48.442256] < -warning- > evdev-input: Attempted to remove unmanaged fd 73
```

platforms/evdev: Handle libinput device rejections better.

---

include/common/mir/events/event_builders.h
include/common/mir/events/touch_contact.h
src/common/events/CMakeLists.txt
src/common/events/event_helpers.cpp
src/common/events/pointer_event.cpp
src/common/events/touch_event.cpp
src/common/symbols.map
src/include/common/mir/events/event_helpers.h
src/include/common/mir/events/pointer_event.h
src/include/common/mir/events/touch_event.h
src/miroil/eventdispatch.cpp
src/server/frontend_wayland/wl_pointer.cpp
src/server/frontend_wayland/wl_pointer.h
src/server/frontend_wayland/wl_touch.cpp
src/server/frontend_wayland/wl_touch.h
src/server/frontend_xwayland/xwayland_surface_observer.cpp
src/server/input/surface_input_dispatcher.cpp
tests/unit-tests/input/test_surface_input_dispatcher.cpp

For #1792 we'll want to pass events from the frontend to the window manager. In order to meaningfully use them events will need to preserve global position in addition to local position.

Add local position property to touch and pointer events

---

src/include/server/mir/shell/abstract_shell.h
src/include/server/mir/shell/shell.h
src/include/server/mir/shell/shell_wrapper.h
src/include/server/mir/shell/system_compositor_window_manager.h
src/include/server/mir/shell/window_manager.h
src/miral/basic_window_manager.cpp
src/miral/basic_window_manager.h
src/server/frontend_wayland/window_wl_surface_role.cpp
src/server/frontend_xwayland/xwayland_surface.cpp
src/server/shell/abstract_shell.cpp
src/server/shell/decoration/basic_decoration.cpp
src/server/shell/decoration/basic_decoration.h
src/server/shell/decoration/input.cpp
src/server/shell/decoration/input.h
src/server/shell/shell_wrapper.cpp
src/server/shell/system_compositor_window_manager.cpp
tests/include/mir/test/doubles/mock_window_manager.h
tests/include/mir/test/doubles/stub_shell.h
tests/miral/ignored_requests.cpp
tests/unit-tests/shell/test_decoration_basic_decoration.cpp

Fixes #1792 the way I've planned to for some time

Pass event instead of timestamp to move/resize requests

---

include/common/mir/events/event_builders.h
include/miral/miral/window_management_policy.h
src/common/events/event_builders.cpp
src/common/events/pointer_event.cpp
src/common/events/window_event.cpp
src/include/common/mir/events/pointer_event.h
src/include/common/mir/events/window_event.h
src/include/server/mir/shell/abstract_shell.h
src/include/server/mir/shell/focus_controller.h
src/include/server/mir/shell/input_targeter.h
src/include/server/mir/shell/shell.h
src/include/server/mir/shell/shell_wrapper.h
src/include/server/mir/shell/system_compositor_window_manager.h
src/include/server/mir/shell/window_manager.h
src/miral/basic_window_manager.cpp
src/miral/basic_window_manager.h
src/miral/window_management_trace.cpp
src/server/input/null_input_targeter.h
src/server/input/surface_input_dispatcher.cpp
src/server/input/surface_input_dispatcher.h
src/server/shell/abstract_shell.cpp
src/server/shell/shell_wrapper.cpp
src/server/shell/system_compositor_window_manager.cpp
tests/include/mir/test/doubles/mock_window_manager.h
tests/include/mir/test/doubles/stub_input_targeter.h
tests/include/mir/test/doubles/stub_shell.h
tests/miral/ignored_requests.cpp
tests/miral/test_window_manager_tools.cpp

It is now clear we don't need this at all for implementing drag and drop in Wayland.
So delete the implementation and explicitly deprecate the APIs

Clean out legacy of mirclient drag-and-drop support

---

src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h
src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/frontend_xwayland/xwayland_client_manager.cpp
src/server/frontend_xwayland/xwayland_client_manager.h
src/server/frontend_xwayland/xwayland_surface.cpp
src/server/frontend_xwayland/xwayland_wm.cpp
src/server/frontend_xwayland/xwayland_wm_shell.h
tests/unit-tests/frontend_xwayland/test_xwayland_client_manager.cpp

As xwayland/x11 has no way of telling us gid and uid so we try to get this from running stat on /proc/(pid)
Same as https://github.com/MirServer/mir/pull/2835 but fixed issues pointed out by @AlanGriffiths 
Part of fix for: https://github.com/MirServer/mir/issues/2830

Make sure to call connection_is_allowed on xwayland sessions

---

.github/workflows/spread.yml
spread.yaml

We've Alpine 3.18 now, and F36 is EOL:
https://docs.fedoraproject.org/en-US/releases/eol/

spread: drop Alpine 3.17, Fedora 36

---

src/server/input/surface_input_dispatcher.cpp
src/server/input/surface_input_dispatcher.h

This removes some broken (and untested) support for multiple pointers.
The code removed incorrectly treated each input device as driving a separate pointer. That isn't true in general (a touchpad and associated buttons drive a single pointer) or specifically (multiple pointer input devices drive a single pointer in Mir).
The problem this code caused was that using a different device causes spurious leave/enter transitions.
After clicking on surface A...
1. Using the trackpad to move the pointer from surface A to surface B causes A.leave/B.enter (that's correct).
2. Subsequently pressing a button causes A.leave/B.enter (that's *incorrect*).
3. Subsequently using a newly attached mouse to move the pointer within surface B causes yet another B.enter (that's *incorrect*).
These spurious …

Simplify SurfaceInputDispatcher

---

tests/acceptance-tests/wayland/CMakeLists.txt

Mir has actually been sending correct (or, at least, not wildly incorrect) timestamps on frame events for quite some time, but the test itself was broken.
Now that the test is not broken (and was then fixed *again*), remove it from the XFAIL list so CI will pass again.

tests/wlcs: Drop frame_timestamp_increases from expected failures

---

doc/Doxyfile.in
include/core/mir/anonymous_shm_file.h

- Removed an empty namespace reference
- Added a bunch of `mir::` namespaces to our ignored list of namespaces. AFAIK, this is the best solution (see [here](https://sourceforge.net/p/doxygen/mailman/message/32202449/) for more details)
- I did not remove the `namespace wallpaper` document, as that is rightly being exported because we export docs for all of `example-server-lib`. My suggestion would be for all of the example code to be in an `namespace example` so as not to confused doc-readers with the rest of the documentation. I think that is outside of the scope of this PR though

(#2365) Updated Doxyfile.in to ignore namespaces that we do not want exported

---

CMakeLists.txt
src/platforms/evdev/CMakeLists.txt
src/platforms/evdev/libinput_device.cpp
tests/mir_test_doubles/mock_libinput.cpp
tests/unit-tests/input/evdev/test_libinput_device.cpp

- Removed all instances of `MIR_LIBINPUT_HAS_VALUE120`

(#2974) Removal of MIR_LIBINPUT_HAS_VALUE120 and now-dead code surrounding it

---

.github/workflows/snap.yml

Ref.:
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures

ci: don't fail-fast on snaps

---

src/server/frontend_wayland/wl_keyboard.cpp

We need to re-sync modifier state after `wl_keyboard.enter()`, so we need `WlKeyboard::send_modifiers()` to send the modifiers unconditionally.
Fixes: #2985
Note that this condition originates in #2537 which "fixed" #2535 and #2025.
Alternative to #2988

 Send modifiers after keyboard enter

---

HACKING.md
README.md
doc/getting_and_using_mir.md
doc/getting_involved_in_mir.md
doc/mainpage.md

- Fixed a weird issue where we were rendering html tags in our pages as plain text
- Moved around and grouped some paragraphs so that they made more sense to me (let me know if I am mistaken though)
- Using plain markdown links instead of Doxygen `\ref`s so that everything works on Github as well

Suggestion: Fixing a few broken links in the markdown version of the files and some light reorganization

---

src/server/graphics/multiplexing_display.cpp
tests/unit-tests/graphics/test_multiplexing_display.cpp

This ensures that output names in a `MultiplexingDisplay` configuration match the existing names.

Fix MultiplexingDisplay names

---

tests/mir_test_framework/mmap_wrapper.cpp

Alpine/edge has dropped the mmap64 symbol that previously existed "everywhere"

Fix the Alpine/edge FTBFS

---

tests/unit-tests/input/test_touchspot_controller.cpp

Don't pass temporaries via initializer_list

---

.github/workflows/snap.yml

armhf has consistently been *slightly* too slow to hit the 4hr(!) timeout we currently have.
Since this doesn't gate merging, bump it up to 6hrs to ensure people can test PR builds. Eventually.

CI/snaps: Bump timeout for building mir-libs.

---

spread.yaml
spread/build/ubuntu/task.yaml
tests/acceptance-tests/wayland/CMakeLists.txt

ci: run tests in ubsan

---

tests/include/mir/test/doubles/mock_drm.h
tests/mir_test_doubles/mock_drm.cpp

Ensure the signatures of our drm intercept functions are correct

---

src/platforms/wayland/displayclient.cpp

Fix locking in mgw::DisplayClient()

---

src/platforms/wayland/display.cpp
src/platforms/wayland/displayclient.cpp
src/platforms/wayland/displayclient.h

Don't confuse scaling of host environment with internal scaling of outputs.
Fixes: #3036
Note: this fixes the display and cursor positioning and so is generally an improvement. However, there are remaining oddities with the cursor image. These are arguably pre-existing, and don't make things unusable

[wayland platform] Less broken display on scaled hosts

---

src/platforms/gbm-kms/server/kms/quirks.cpp

Empirically, the platform API branch works with evdi (modulo some display config tracking that should be fixed).
So this is a reminder to change the defaults

Allow evdi

---

src/server/frontend_wayland/wl_shell.cpp
src/server/frontend_wayland/xdg_shell_stable.cpp
src/server/frontend_wayland/xdg_shell_v6.cpp
src/server/frontend_xwayland/xwayland_surface.cpp

We've failed to distinguished "Gloss" and "Tip" in our window management implementation, and that's led us to labelling "Tips" `mir_window_type_gloss`.
Label "Tips" `mir_window_type_tip` correctly. (Issue about the incorrect "Gloss" implementation: #3045.)

Reduce scope for confusion between Tips and Gloss

---

src/server/frontend_xwayland/xwayland_surface.cpp

Clamp size related rescaling correctly.
Fixes: ##2509
Alternative to #3049

[Xwayland] Fix broken rescaling

---

debian/control

It's a new package, prefer it
https://packages.ubuntu.com/search?keywords=glmark2-es2-x11 https://packages.debian.org/search?keywords=glmark2-es2-x11

debian: prefer glmark-es2-x11

---

src/platforms/wayland/displayclient.cpp

It's important to actually *name* your RAII lock object, so it doesn't immediately go out of scope and unlock the mutex!

platforms/wayland: Fix a lock in DisplayClient

---

src/common/input/xkb_mapper.cpp
src/include/common/mir/input/xkb_mapper.h

We don't guarantee that `XKBMapper::map_event()` sets `last_device_id` before we use it in `XKBMapper::update_modifier()` and valgrind complains.

Avoid undefined behavior

---

examples/client/wayland_client.c

Clang's `-Wstrict-prototypes` complains about this.

examples/wayland_client.c: Fix pedantic compile error.

---

src/miral/display_configuration_option.cpp

This adds an autoscaling option to miral's display configuration options.
So to scale to emulate, for example, 1080p use `--display-autoscale=1080`
The scaling is quantized to the nearest quarter pixel

Add display-autoscale option to miral::display_configuration_options()

---

.mailmap

Hi!
My old name is all over Mir git history. I don't care that much so I never proposed filter-branching it out, but I recently found out with a simple .mailmap you can get a lot of the same benefits without changing history. If this is merged my new name will be displayed on my old commits and on git blame, both locally and on github.

Add .mailmap file to map old commits to Sophie's new name and email

---

cmake/FindGtestGmock.cmake

For some reason now there's some issue when passing the version string to pkg_check_modules with spaces inbetween which breaks setting a bunch of used variables.
pkg_check_modules(GTEST "gtest >= 1.8.0")
-- Checking for module 'gtest >= 1.8.0'
--   Found gtest , version
vs.
pkg_check_modules(GTEST "gtest>=1.8.0")
-- Checking for module 'gtest>=1.8.0'
--   Found gtest, version 1.14.0
---
Saw this issue on Alpine Linux when building v1.8.2, but patch applies the same to main so I don't see why it shouldn't be correct for main also.

Fix gtest pkg-config detection

---

src/platform/graphics/linux_dmabuf.cpp

Rather than naked eglDestroyImage.
https://registry.khronos.org/EGL/sdk/docs/man/html/eglDestroyImage.xhtml

linux_dmabuf: use eglDestroyImageKHR extension

---

CMakeLists.txt
src/server/graphics/default_configuration.cpp

The intent is to allows us to merge without exposing functionality we are still polishing.
This uses an environment variable (`MIR_EXPERIMENTAL_HYBRID_GRAPHICS`), not a configuration option, as that is easy to drop seamlessly later.

Add a feature flag to hide hybrid capability

---

src/miral/runner.cpp

We were trying to shut down the server on whatever thread was calling MirRunner::stop(). That worked fine for the input thread (for example), but if it were the Wayland thread the server became unresponsive and internal clients couldn't close.
Fixes: #3070

Fix MirRunner::stop()

---

include/platform/mir/graphics/display_configuration_policy.h
src/include/server/mir/graphics/default_display_configuration_policy.h
src/miral/display_configuration_option.cpp
src/miral/static_display_config.cpp
src/miral/static_display_config.h
src/miroil/persist_display_config.cpp
src/server/graphics/default_display_configuration_policy.cpp
src/server/graphics/multiplexing_display.cpp
tests/include/mir/test/doubles/null_display_configuration_policy.h
tests/unit-tests/graphics/test_multiplexing_display.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display_multi_monitor.cpp
tests/unit-tests/scene/test_mediating_display_changer.cpp

- Added a `confirm` to the `DisplayConfigurationPolicy` to handle writing the config to file

Decoupling writing the display configuration from processing it

---

src/platforms/eglstream-kms/server/display.cpp
src/platforms/eglstream-kms/server/platform.cpp
src/platforms/eglstream-kms/server/platform.h

- On an nvidia + intel platform, run:
```sh
sudo MIR_EXPERIMENTAL_HYBRID_GRAPHICS=1 MIR_SERVER_PLATFORM_RENDERING_LIBS=mir:eglstream-kms XDG_RUNTIME_DIR=/run/ ./bin/mir_performance_tests --gtest_filter=GLMark2Wayland.*
```
```
LD_LIBRARY_PATH=./bin/../lib/
MIR_SERVER_PLATFORM_PATH=./bin/../lib/server-modules/
exec=./bin/mir_performance_tests.bin
Running main() from main.cpp
Note: Google Test filter = GLMark2Wayland.*
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from GLMark2Wayland
[ RUN      ] GLMark2Wayland.fullscreen
Saving server logs to: /tmp/GLMark2Wayland_fullscreen_server.log
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create …
```

Fix for mir_performance_tests failure due to not cleaning up our displays

---

src/server/graphics/default_configuration.cpp

Make the choice of buffer allocator determanistic and prefer "eglstream" over "gbm".
I think this resolves the problem as I understand it, but I don't have easy access to hardware to verify my understanding.

Hold the rendering platforms in description->name order

---

src/server/graphics/default_configuration.cpp

Fix processing of `--platform-*-libs`

---

src/platforms/common/server/CMakeLists.txt
src/platforms/common/server/basic_cpu_addressable_display_provider.cpp
src/platforms/common/server/basic_cpu_addressable_display_provider.h
src/platforms/common/server/cpu_addressable_fb.cpp
src/platforms/common/server/cpu_addressable_fb.h
src/platforms/common/server/kms_cpu_addressable_display_provider.cpp
src/platforms/common/server/kms_cpu_addressable_display_provider.h
src/platforms/common/server/kms_framebuffer.h
src/platforms/eglstream-kms/server/display.cpp
src/platforms/eglstream-kms/server/drm_event_handler.h
src/platforms/eglstream-kms/server/egl_output.cpp
src/platforms/eglstream-kms/server/egl_output.h
src/platforms/eglstream-kms/server/eglstream_interface_provider.cpp
src/platforms/eglstream-kms/server/kms_display_configuration.cpp
src/platforms/eglstream-kms/server/kms_display_configuration.h
src/platforms/eglstream-kms/server/platform.cpp
src/platforms/eglstream-kms/server/threaded_drm_event_handler.cpp
src/platforms/eglstream-kms/server/threaded_drm_event_handler.h
src/platforms/gbm-kms/server/kms/CMakeLists.txt
src/platforms/gbm-kms/server/kms/display.cpp
src/platforms/gbm-kms/server/kms/display.h
src/platforms/gbm-kms/server/kms/display_buffer.cpp
src/platforms/gbm-kms/server/kms/display_buffer.h
src/platforms/gbm-kms/server/kms/kms_output.h
src/platforms/gbm-kms/server/kms/platform.cpp
tests/unit-tests/platforms/gbm-kms/kms/mock_kms_output.h
tests/unit-tests/platforms/gbm-kms/kms/test_display_multi_monitor.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_real_kms_output.cpp

- The EglStreams platform now has a `CPUAddressableDisplayProvider` so that it works in this specific hybrid situation
- Moved some classes to be shared between GBM and EGLStreams
```
sudo XDG_RUNTIME_DIR=/run ./bin/mir_demo_server --platform-rendering-libs mir:gbm-kms
```
It still SIGABRTs after, but it gets through the selection part.

Sharing CpuAdressableDisplayProvider between eglstreams and gbm platforms

---

src/include/server/mir/compositor/display_buffer_compositor.h
src/server/compositor/default_display_buffer_compositor.cpp
src/server/compositor/default_display_buffer_compositor.h
src/server/compositor/multi_threaded_compositor.cpp
tests/include/mir/test/doubles/null_display_buffer_compositor_factory.h
tests/integration-tests/test_surface_stack_with_compositor.cpp
tests/mir_test_framework/headless_display_buffer_compositor_factory.cpp
tests/unit-tests/compositor/test_default_display_buffer_compositor.cpp
tests/unit-tests/compositor/test_multi_threaded_compositor.cpp

1. Checkout https://github.com/MirServer/mir/pull/3086 and run `sudo make install`
2. Checkout https://github.com/MirServer/ubuntu-frame/pull/157 and build it
3. From a VT, run plymouth
```sh
sudo plymouthd
sudo plymouth show-splash
sudo plymouth deactivate
```
The splash should still be on the screen
4. Run frame:
```
./frame --wallpaper=false
```
5. Wait however long you like and note that you still see the splash
6. Run some other app (e.g. gedit) and note that the splash disappears
- `DefaultDisplayBufferCompositor::composite` now returns a boolean telling the caller if any compositing happened or not
- If the `MultithreadedCompositor` needs compositing, a `post` will happen, otherwise nothing will happen

Support for not compositing until at least one renderable has been sent to the compositor

---

src/platforms/virtual/platform.cpp
tests/unit-tests/platforms/virtual/test_platform.cpp

[mir:virtual] drop GenericEGLDisplayProvider

---

include/platform/mir/graphics/display_buffer.h
src/platforms/eglstream-kms/server/display.cpp
src/platforms/gbm-kms/server/kms/display_buffer.cpp
src/platforms/gbm-kms/server/kms/display_buffer.h
src/platforms/wayland/displayclient.cpp
src/platforms/x11/graphics/display.cpp
src/platforms/x11/graphics/display_buffer.cpp
src/platforms/x11/graphics/display_buffer.h
src/server/compositor/default_display_buffer_compositor_factory.cpp
tests/include/mir/test/doubles/mock_display_buffer.h
tests/include/mir/test/doubles/null_display_buffer.h
tests/mir_test_framework/headless_display_buffer_compositor_factory.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display_multi_monitor.cpp

We need this when allocating `Framebuffer`s.
Fixes: #3103

platform/DisplayBuffer: Add pixel_size() accessor.

---

examples/client/wayland_client.c
src/server/graphics/default_configuration.cpp
tests/performance-tests/CMakeLists.txt

- Fixes https://github.com/MirServer/mir/issues/3102
- Rendering in the same manner as ubuntu-frame does it so that everything works with the virtual platform
Run this and see that we don't block any longer:
```sh
WAYLAND_DISPLAY=wayland-99 MIR_SERVER_PLATFORM_DISPLAY_LIBS=mir:virtual MIR_SERVER_VIRTUAL_OUTPUT=1280x1024 ./bin/mir_demo_server --test-timeout=3 --test-client ./bin/mir_demo_client_wayland
```

Refactored wayland_client.c to support the virtual platform

---

debian/control
include/platform/mir/graphics/platform.h
src/platforms/renderer-generic-egl/platform_symbols.cpp
src/platforms/virtual/graphics.cpp
src/platforms/wayland/platform_symbols.cpp
src/platforms/x11/graphics/graphics.cpp
src/server/graphics/default_configuration.cpp
src/server/graphics/platform_probe.cpp
tests/mir_test_framework/platform_graphics_dummy.cpp
tests/mir_test_framework/platform_graphics_throw.cpp
tests/platform_test_harness/graphics_platform_test_harness.cpp
tests/unit-tests/graphics/test_platform_prober.cpp
tests/unit-tests/platforms/x11/test_platform.cpp

We use these packages in the headers, so include them in the `-dev` dependencies.

Packaging: Add new -dev dependencies to the relevant packages

---

tests/miral/external_client.cpp

Thanks @hbatagelo who mentioned this in #3133

Fix skipping of ExternalClient tests when environment doesn't support X11

---

src/platform/options/default_configuration.cpp

Tested with miral-shell built from within this repo and with my own compositor linking against this version.
I also looked in unit tests to see if I could add it there, but the existing test for options uses test data rather than real responses from built artifacts. Please let me know if there's another one that I've missed that would be suitable for this.

Add --mir-version command line option. solves MirServer/mir#3058

---

CMakeLists.txt
debian/control
snap/snapcraft.yaml
src/platforms/x11/CMakeLists.txt
src/platforms/x11/graphics/display.cpp
src/platforms/x11/graphics/display_configuration.cpp
src/platforms/x11/graphics/display_configuration.h
src/platforms/x11/x11_resources.cpp
src/platforms/x11/x11_resources.h
src/server/CMakeLists.txt
tests/include/mir/test/doubles/mock_x11_resources.h

There's a few sticky things here:
- First of all, I'm adding a new dependency. However, xcb-randr should already exist anywhere xcb is installed, as far as I know. On my distribution this is not even a separate package. I've added the relevant stanza for debian/ubuntu in the control file (commented out for now), but, if I remember debian packaging correctly, this won't apply until the version is bumped in the changelog. 
- I'm following the general trend of ignoring xcb errors. They're usually non-fatal.
- If the randr extension version of the host X11 is <1.2, this will probably either not work or return nonsense. OTOH, if someone is doing development or testing of Mir-on-X on an Xorg that doesn't support 1.2+, they're probably doing it deliberately.
- More importantly, should I also …

Remove TODO from 2015 to detect host refresh rate/max fps for Mir-on-X client.

---

include/platform/mir/graphics/display_sink.h
include/platform/mir/graphics/platform.h
src/platforms/common/server/cpu_copy_output_surface.cpp
src/platforms/common/server/cpu_copy_output_surface.h
src/platforms/common/server/kms_cpu_addressable_display_provider.cpp
src/platforms/common/server/kms_cpu_addressable_display_provider.h
src/platforms/eglstream-kms/server/buffer_allocator.cpp
src/platforms/eglstream-kms/server/buffer_allocator.h
src/platforms/eglstream-kms/server/display.cpp
src/platforms/gbm-kms/server/buffer_allocator.cpp
src/platforms/gbm-kms/server/buffer_allocator.h
src/platforms/gbm-kms/server/gbm_display_allocator.cpp
src/platforms/gbm-kms/server/gbm_display_allocator.h
src/platforms/gbm-kms/server/kms/display_buffer.cpp
src/platforms/gbm-kms/server/kms/display_sink.h
src/platforms/renderer-generic-egl/buffer_allocator.cpp
src/platforms/renderer-generic-egl/buffer_allocator.h
src/platforms/wayland/displayclient.cpp
src/platforms/x11/graphics/display.cpp
src/platforms/x11/graphics/display_sink.cpp
src/platforms/x11/graphics/display_sink.h
src/server/compositor/basic_screen_shooter.cpp
src/server/compositor/basic_screen_shooter.h
src/server/compositor/default_display_buffer_compositor_factory.cpp
tests/include/mir/test/doubles/mock_gl_rendering_provider.h
tests/include/mir/test/doubles/null_display_sink.h
tests/include/mir/test/doubles/stub_gl_rendering_provider.h
tests/mir_test_framework/headless_display_buffer_compositor_factory.cpp
tests/unit-tests/compositor/test_basic_screen_shooter.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_display_multi_monitor.cpp

Because each `DisplaySink` knows how big the buffers it needs, and each `DisplayAllocator` is easily associated with a single `DisplaySink`, we can let the `DisplayAllocator` allocate buffers of the correct size.

platform/DisplaySink: Remove pixel_size() accessor

---

src/platforms/evdev/platform.cpp

Not all `ConsoleProvider`s will send a `removed` event on the `DeviceObserver` (in fact, only logind will), so we can't rely on that to clean up the handle in `device_watchers`.
Furthermore, libinput itself will notice a device going away (by monitoring the fd) and generate `LIBINPUT_EVENT_DEVICE_REMOVED`, which we might process *before* the udev `REMOVED` event, and in *that* case, `device_removed` will have already deleted the `LibInputDevice` and so the udev event handler will *also* not clean up `device_watchers`.
Resolve this by cleaning up `device_watchers` *only* in `device_removed`, and rely on the `DeviceObserver::removed` codepath triggering a libinput removal event.
Fixes: #3149

platforms/evdev: Clean up mir::Device handle on device remove

---

src/server/frontend_wayland/CMakeLists.txt
src/server/frontend_wayland/desktop_file_manager.cpp
src/server/frontend_wayland/desktop_file_manager.h
src/server/frontend_wayland/foreign_toplevel_manager_v1.cpp
tests/include/mir/test/doubles/mock_surface.h
tests/unit-tests/frontend_wayland/CMakeLists.txt
tests/unit-tests/frontend_wayland/test_desktop_file_manager.cpp

- Fixed a bug where `gnome-disks` wasn't showing up (we needed a `NoDisplay` check)
- Wrote tests for everything except fileystem-specific stuff

tests: updated the desktop file manager so that we can more easily write tests for it

---

src/miral/minimal_window_manager.cpp

I'm not sure why we were checking that refocusing on the window selected for the gesture activated it. It seems both pointless and wrong. So dropped that code.
There are not a lot of apps to illustrate the issues, but gimp (with floating toolboxes) is one: without this it isn't possible to move the toolboxes.

Fix dragging and resizing satellite windows

---

src/include/server/mir/glib_main_loop.h

`result_of_t` was deprecated in C++17, and removed in C++20, which we claim to use. Replace it with the equivalent `invoke_result_t` templates.
Fixes the Ubuntu 24.04 build with modern Clang.

mir::GLibMainLoop: Fix deprecated `std::result_of_t` usage.

---

src/common/symbols.map
src/platform/symbols.map
src/platforms/eglstream-kms/server/symbols.map.in
src/platforms/virtual/symbols.map.in
src/platforms/x11/symbols.map.in
tests/mir_test_framework/symbols-server.map.in

`mold` likes to complain about these; newer `lld`s make this a hard error

various: Drop nonexistent symbols from symbols.map

---

src/miral/basic_window_manager.cpp

fixes https://github.com/MirServer/mir/issues/3128
- Before we place a surface in its zone, we sort the list such that surfaces which span east-to-west (e.g. top and bottom panels) are at the end and therefore "push" all other surfaces out of their zones.
- Should we demand that any other types of surfaces take precedence over any other type?

(#3128) bugfix: east/west attached surfaces always push north/south attached out of the way

---

src/server/graphics/multiplexing_display.cpp

We missed copying the `scale` field from the copy of the configuration handed out to be mutated during configuration changes.
We also missed a couple of other fields. They're less interesting, but also copy them while we're here.
Fixes: #3165

mg::MultiplexingDisplay: Copy *all* mutable fields on user configuration update

---

src/server/shell/decoration/basic_decoration.cpp
src/server/shell/decoration/basic_decoration.h
src/server/shell/decoration/basic_manager.cpp
src/server/shell/decoration/basic_manager.h
src/server/shell/decoration/decoration.h
src/server/shell/decoration/renderer.cpp
src/server/shell/decoration/renderer.h
src/server/shell/decoration/window.cpp
src/server/shell/decoration/window.h
src/server/shell/default_configuration.cpp
tests/unit-tests/shell/test_decoration_basic_decoration.cpp
tests/unit-tests/shell/test_decoration_basic_manager.cpp

Fixes #1369.
The decoration builder now selects the maximum scale factor among all display outputs, passing it to `msd::BasicDecoration` and `msd::Renderer` to create buffers with a resolution that ensures sharp-looking decorations on all outputs.

Make server-side decorations scale aware

---

src/miral/basic_window_manager.cpp

Fixes #3175 using a combination of cascading and random positioning.
Rather than replacing the original algorithm, it has been extended. If the new optically centered window shares the same top-left position as an existing window within a margin of tolerance, the new window is cascaded both vertically and horizontally. Following cascading, if any part of the window extends beyond the display area, it is randomly placed within a "feasible placement region" defined as the morphological erosion of the display region by the window region. If this region is empty, the window is resized horizontally and/or vertically to fit the display area and is also moved to the top and/or left of the display area.

Change placement of new floating windows

---

src/renderers/gl/renderer.cpp

Fix transformation for Layout::TopRowFirst

---

debian/libmiroil5.symbols.armhf

Launchpad builds are failing because of size_t (for example) is a different type on 32bit builds.
This provides a POC fix

Fix armhf symbols

---

examples/client/wayland_client.c
src/platform/graphics/egl_buffer_copy.cpp
src/server/frontend_xwayland/xcb_connection.cpp

```
/spread/mir/examples/client/wayland_client.c:533:39: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
533 |     draw_context* ctx = calloc(sizeof *ctx, 1);
|                                       ^
/spread/mir/examples/client/wayland_client.c:533:39: note: earlier argument should specify number of elements, later size of each element
cc1: all warnings being treated as errors
```

Fix rawhide FTBFS

---

src/server/frontend_xwayland/xwayland_surface.cpp

Note that Mir will hide the window anyway. It simply can't request the client delete it too.
Fixes: #3177

Do not kill X11 apps whose pop-ups don't support WM_DELETE_WINDOW

---

src/platforms/evdev/libinput_device.cpp
src/platforms/evdev/libinput_device.h
src/platforms/evdev/platform.cpp
src/server/input/default_device.cpp
tests/unit-tests/input/evdev/test_libinput_device.cpp

Tidying input code that should be clearer. Mostly simplifying `mie::LibInputDevice` which is confuses about whether it represents l`ibinput_device*` or `libinput_device_group*`.
Before:
`mie::LibInputDevice` has a data member `devices` that is populated via `add_device_of_group()` that would appear to be intended to reflect the `libinput_device_group`.
However `add_device_of_group()` will only be called with the same `libinput_device` (and no code makes reference to `libinput_device_group`).
Further, most of the class is implemented based on `mie::LibInputDevice::device()` which returns the first element of `devices`.
After:
`mie::LibInputDevice` represents a single device.
Some tests of the "multiple devices in one `mie::LibInputDevice`" code dropped

Drive-by tidy up of libinput use

---

src/server/graphics/default_configuration.cpp

We load one `RenderingPlatform` for each hardware device detected, and then select the best one to drive each display. If we don't keep all the `RenderingPlatform`s then we might not keep the one capable of direct-output, requiring a CPU copy to the display.
Fixes: #3205

platform/graphics: Allow for multiple RenderingPlatforms of each type 

---

debian/libmiral7.symbols
include/miral/miral/minimal_window_manager.h
include/miral/miral/window_manager_tools.h
src/miral/application_selector.cpp
src/miral/application_selector.h
src/miral/basic_window_manager.cpp
src/miral/basic_window_manager.h
src/miral/minimal_window_manager.cpp
src/miral/symbols.map
src/miral/window_management_trace.cpp
src/miral/window_management_trace.h
src/miral/window_manager_tools.cpp
src/miral/window_manager_tools_implementation.h
tests/miral/application_selector.cpp
tests/miral/test_window_manager_tools.cpp
tests/miral/test_window_manager_tools.h

- I realized that the last PR was going to be messy, as we would have to maintain a tab order for every application _and_ every window.
- However, I realized that this list was one in the same. Basically, we just keep the order of Windows, and we choose whether or not we are jumping from App to App or from Window to Window within an app
- So much simpler, less data to keep track of, and easier to read :magic_wand:

feature: alt + grave behavior now implemented alongside alt + tick

---

src/server/graphics/CMakeLists.txt
src/server/graphics/multiplexing_display.cpp
src/server/graphics/multiplexing_hw_cursor.cpp
src/server/graphics/multiplexing_hw_cursor.h

Create a HW cursor on each `Display`; if any `Display` cannot support a HW cursor, bail.
Our existing HW cursor implementations already handle setting the position outside of their display area, so we can just directly delegate to all multiplexed `Cursor` implementations without needing to track which platform(s) should actually be handling the event.
Fixes: #3198

graphics/MultiplexingDisplay: Add HW cursor support.

---

src/wayland/generator/request.cpp
tests/acceptance-tests/wayland-generator/expected.cpp
tests/acceptance-tests/wayland-generator/expected.h

fixes https://github.com/canonical/mir/issues/3241
- We now generate a virtual stub method with destructors so that you can do something like this:
```c++
void mf::SessionLockV1::unlock_and_destroy()
{
printf("Being unlocked and destroyed\n");
}
```
This is called right before destruction happens. By default, the method is a stub.

(#3241) Wayland wrapper generator now generates a virtual stub function for destructors

---

src/include/server/mir/frontend/buffer_stream.h
src/server/compositor/stream.cpp
src/server/compositor/stream.h
src/server/frontend_xwayland/scaled_buffer_stream.cpp
src/server/frontend_xwayland/scaled_buffer_stream.h
tests/include/mir/test/doubles/mock_buffer_stream.h
tests/include/mir/test/doubles/stub_buffer_stream.h

This is unused (and untested!)

mf::BufferStream: Remove with_most_recent_buffer_do

---

src/platforms/gbm-kms/server/kms/real_kms_output.cpp

After a wake we might see an invalid Gamma curve.  Ignore it.
Fixes: #3238
It fixes the problem because `ensure_crtc()` might allocate a new `current_crtc` but the `drmModeCrtcSetGamma()` will fail leaving it unused - but still associated with the output.

Ignore zero length gamma curves

---

src/wayland/generator/request.cpp
tests/acceptance-tests/wayland-generator/expected.cpp
tests/acceptance-tests/wayland-generator/expected.h

This reverts commit 8346ca9ac88341ef81fb0294f205504dd434368f, reversing changes made to 120d2ccfb744d6f43fd32df806936e6b92c4b3a8.
It turns out that sometimes the userdata is set to nullptr, leading `me->destroy()` to attempt to jump to null.

Revert "Merge pull request #3243 from canonical/feature/3241"

---

src/include/server/mir/shell/surface_specification.h
src/server/shell/surface_specification.cpp
src/server/symbols.map

We no longer use this class, and it never had any symbols to map

Drop dead code

---

include/core/mir/geometry/dimensions.h
include/core/mir/geometry/displacement.h
include/core/mir/geometry/point.h
include/core/mir/geometry/rectangle.h
include/core/mir/geometry/size.h
include/core/mir/int_wrapper.h

Hand crafting leads to mistakes and/or omissions (as noticed by @hbatagelo in #3244)

Use the compiler generated default comparison operators

---

src/platforms/common/server/cpu_copy_output_surface.cpp
src/renderers/gl/renderer.cpp

fixes https://github.com/canonical/mir/issues/3236
Am I right to think this @RAOF ? It looks like `CPUCopyOutputSurface`  is trying to have a `GL` layout. I could be wrong, but this makes my screenshots work.

(#3236) `CPUCopyOutputSurface` now used a GL output layout

---

include/platform/mir/graphics/drm_formats.h
src/platform/graphics/drm_formats.cpp
src/platform/graphics/linux_dmabuf.cpp
src/platform/symbols.map

Some EGL implementations (*cough* NVIDIA) return formats from `eglQueryDmaBufFormatsEXT` that generate
`EGL_BAD_PARAMETER` errors when querying for the associated modifiers with `eglQueryDmaBufModifiersEXT`.
This doesn't need to be fatal, as long as there are *some* formats for which we can successfully query
the modifiers, so make it non-fatal.
Fixes: #3278

platform/linux-dmabuf: Be more lenient with EGL implementations

---

debian/libmiral7.symbols
include/miral/miral/window_info.h
include/miral/miral/window_specification.h
src/include/server/mir/shell/surface_specification.h
src/miral/basic_window_manager.cpp
src/miral/symbols.map
src/miral/window_info.cpp
src/miral/window_info_internal.cpp
src/miral/window_info_internal.h
src/miral/window_specification.cpp
src/miral/window_specification_internal.h
src/server/frontend_wayland/layer_shell_v1.cpp
src/server/frontend_wayland/session_lock_v1.cpp
src/server/shell/surface_specification.cpp
tests/miral/window_placement_attached.cpp

fixes #1992 (and maybe #3125?)
- If we have an attached window with `ignore_exclusion_zones` set to `true`, then the surface will attach to its edges without regard for other exclusion zones
- When we're locked, we shouldn't calculate exclusion zones that are _not_ visible on the lockscreen
- Run `waybar`
- Run `swaybg -i /path/to/jpg`
- Note that `swaybg` will appear _underneath_ `waybar`, as it should!

feature: support for `zwlr_layer_surface_v1::set_exclusive_zone(-1)`

---

tests/mir_test_framework/open_wrapper.cpp

We're *mostly* insulated from this, but our tests need to intercept calls to `open`, which means that we're exposed to some glibc internals that change under `_TIME_BITS=64`.
Fortunately umockdev in the archive has already hit this, so adapt that fix to our use.
Fixes: #3285

tests/open_wrapper: Handle the Ubuntu 64-bit time_t apocalypse

---

src/server/frontend_wayland/wlr_screencopy_v1.cpp

(#3259) buffer size should be the possibly-inverted extents size so that the final image is correct

---

doc/sphinx/Doxyfile.in

We started using C++23 features. Doxygen needs to tell clang

Fix regenerate-miral-symbols-map

---

examples/example-server-lib/floating_window_manager.cpp
include/miral/miral/window_info.h
src/miral/window_info.cpp

When a satellite window is positioned, an extra vertical offset is added to its top-left position, making the vertical anchoring incorrect. The offset is added because `WindowInfo::needs_titlebar()` returns `true` when called from the floating window policy manager. This PR fixes that.

Fix positioning of satellite windows

---

debian/libmiroil5.symbols
debian/libmiroil5.symbols.armhf
include/miroil/miroil/surface.h
src/include/server/mir/compositor/buffer_stream.h
src/include/server/mir/scene/surface.h
src/miroil/surface.cpp
src/miroil/symbols.map
src/server/compositor/stream.cpp
src/server/compositor/stream.h
src/server/frontend_xwayland/scaled_buffer_stream.cpp
src/server/frontend_xwayland/scaled_buffer_stream.h
src/server/scene/basic_surface.cpp
src/server/scene/basic_surface.h
tests/include/mir/test/doubles/mock_buffer_stream.h
tests/include/mir/test/doubles/stub_buffer_stream.h
tests/include/mir/test/doubles/stub_surface.h
tests/unit-tests/compositor/test_stream.cpp
tests/unit-tests/scene/test_basic_surface.cpp

The only internal user of this has been removed. QtMir is an *external* user of this, but:
* Doesn't actually *need* this behaviour, and
* Needs significant work in this area anyway to update for 2.16's Platform changes

compositor/Stream: Remove `buffers_ready_for_compositor`

---

src/include/server/mir/server.h
src/server/server.cpp

We already have some floating point "input configuration" options in our examples. This provides a little more support internally that I used in hacking that code about.

Add floating point options

---

src/server/shell/decoration/renderer.cpp

Clang has started (correctly) identifying that we're not using the error variable we're declaring. We might as well!

msd::Renderer: Use freetype error return value

---

include/common/mir/signal.h
src/common/CMakeLists.txt
src/common/signal.cpp
src/common/symbols.map
src/common/thread_pool_executor.cpp
src/server/compositor/multi_threaded_compositor.cpp
tests/unit-tests/CMakeLists.txt
tests/unit-tests/test_signal.cpp

This is *very* much like `std::binary_semaphore`, but doesn't have the preconditon that the signal must not be raised before attempting to raise it.
Use it to fix the UB (on shutdown) in `mir::ThreadPoolExecutor`

common/Signal: New worker-thread synchronisaton primitive.

---

debian/control
debian/libmirserver60.install
debian/libmirserver61.install
src/server/CMakeLists.txt

In 2.16 mirserver was 59, in 2.17 it should be 60

Revert spurious bump to mirserver soname

---

debian/control
debian/libmircommon-internal-dev.install

I found this while running CI on `miracle-wm`: https://github.com/mattkae/miracle-wm/actions/runs/8908986732/job/24465567363?pr=116
The error is:
```
Unpacking libmircommon-internal-dev:amd64 (2.16.4+dev380-gf95f846c94-0ubuntu22.04) ...
dpkg: error processing archive /tmp/apt-dpkg-install-meg0dJ/6-libmircommon-internal-dev_2.16.4+dev380-gf95f846c94-0ubuntu22.04_amd64.deb (--unpack):
trying to overwrite '/usr/lib/x86_64-linux-gnu/libmircommon.so', which is also in package libmircommon-dev:amd64 2.16.4+dev380-gf95f846c94-0ubuntu22.04
Errors were encountered while processing:
/tmp/apt-dpkg-install-meg0dJ/6-libmircommon-internal-dev_2.16.4+dev380-gf95f846c94-0ubuntu22.04_amd64.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

bugfix: libmircommon-internal-dev should not attempt to install libmircommon10 because libmircommon-dev will provide that

---

src/common/mircommon-internal.pc.in

My local version of `pkgconfig` doesn't complain about this, but it is most definitely an error!

bugfix: mircommon-internal-dev was erroneously including some libs

---

src/server/frontend_wayland/keyboard_helper.cpp
src/server/frontend_wayland/wl_keyboard.cpp

- This will  give us some logs for when modifiers are sent so that we can compare when we expect them to be sent

Improved debug logging around modifier sends

---

include/platform/mir/graphics/renderable.h
src/server/graphics/software_cursor.cpp
src/server/input/touchspot_controller.cpp
src/server/scene/basic_surface.cpp
src/server/shell/basic_idle_handler.cpp
tests/include/mir/test/doubles/fake_renderable.h
tests/include/mir/test/doubles/mock_renderable.h
tests/include/mir/test/doubles/stub_renderable.h
tests/platform_test_harness/graphics_platform_test_harness.cpp

Alternative to https://github.com/canonical/mir/pull/3349
- Now you can access the `Surface` via the `Renderable`

feature: provide surface access via the Renderable

---

src/server/frontend_wayland/virtual_pointer_v1.cpp

fixes https://github.com/canonical/mir/issues/3300
See [this comment](https://github.com/canonical/mir/issues/3300#issuecomment-2088897189) to understand my rationale here. I think this should fix it, but I don't have a solid repo on my end (and I don't see this in CI anywhere). All other code paths seemed to be fine.

(#3300) bugfix for a race condition in VirtualPointerV1

---

doc/sphinx/how-to/how-to-enable-graphics-core22-on-a-device.md
doc/sphinx/how-to/index.md

- Transferred the Mir bringup guide to a how-to guide in the Mir project
- Rewrote the document with a focus on `graphics-core22`. @RAOF please let me know if any of my assumptions about `graphics-core22` were incorrect here, since the original document was intended for `graphics-core20`
- Published the document on readthedocs
- Open the file in CI

doc: publish the graphics enablement doc on rtd

---

src/platforms/eglstream-kms/server/display.cpp

The `conf_change_handler()` callback comes from external code, and could do anything. In practice, it *now* ends up (eventually) calling `Display::configuration`, which *also* tries to take the configuration mutex, with hilarious consequences!
Drop the lock before invoking the callback.
Fixes: #3375

platforms/eglstream-kms: Don't invoke callback under `configuration_mutex`

---

include/common/mir/log.h
include/miral/miral/application.h
include/platform/mir/graphics/display_configuration.h
include/wayland/mir/wayland/protocol_error.h
src/miral/output.cpp
src/miral/static_display_config.h
src/miral/wayland_extensions.cpp
src/platforms/virtual/display.h
src/server/compositor/multi_monitor_arbiter.cpp
src/server/console/linux_virtual_terminal.cpp
src/server/console/minimal_console_services.cpp
src/server/frontend_wayland/wayland_executor.cpp
src/server/frontend_xwayland/xwayland_client_manager.cpp
src/server/input/cursor_controller.cpp
src/server/scene/rendering_tracker.cpp

This should complete the first part of my journey of running Mir on [Chimera Linux](https://chimera-linux.org) initially reported on #3383.
Now I'm figuring out this runtime failure of `mir_demo_server` (https://paste.c-net.org/umtbetmnnvsn) which I cannot reproduce on Arch with (https://paste.c-net.org/a3azgse7x8en) or without these patches, further opinions welcome :)

Fix building on LLVM libc++

---

.github/workflows/snap.yml
snap/snapcraft.yaml

Revert the frig

---

src/platform/graphics/linux_dmabuf.cpp
src/platforms/gbm-kms/server/kms/platform.cpp

One-half of fixing hybrid on my laptop is to allocate
the bounce buffers necessary to get the client buffer
somewhere the compositing GPU can read it in a *format*
that the compositing GPU can read.
The code *was* trying to do that by matching on supported
modifiers. Unfortunately, due to other constraints, the
code accepts (and must accept, elsewhere) `DRM_FORMAT_MOD_INVALID`.
`MOD_INVALID` means “use a driver-specific side-band to know
what the format is”, and is unlikely to work across GPUs.

linux-dmabuf: Fix cross-GPU imports

---

src/platform/graphics/CMakeLists.txt

, e.g. NixOS.
I hope this still works on other systems.

miniscule fix for building on systems where the hardcoded path to libdrm headers doesn't exist

---

doc/sphinx/how-to/how-to-test-mir-for-a-release.md
doc/sphinx/how-to/index.md

Click https://canonical-mir--3392.com.readthedocs.build/3392/how-to/how-to-test-mir-for-a-release/ to read the content
- Taking https://wiki.ubuntu.com/Process/Merges/TestPlans/Mir as a basis, I have redone the test plan while keeping in mind our goal of automating it in the future
1. Integrate 2.16 findings into this test plan
2. Integrate hybrid wack-a-mole findings into this test plan

docs: re-do the mir test plan

---

.github/workflows/spread.yml
spread.yaml

Alpine 3.20 is out and Alpine 3.18 is old (e.g. doesn't have __cpp_lib_format (std::format))

Refresh the Alpine builds

---

src/miral/application_selector.cpp
src/miral/application_selector.h

fixes #3323 
Note that this does **NOT** fix https://github.com/canonical/mir/issues/3408
- We now remember the restore state of the selected window as we're cycling through it

bugfix: alt+tab no longer restores windows if they don't end up focused

---

src/include/server/mir/default_server_configuration.h
src/server/graphics/default_configuration.cpp
src/server/graphics/platform_probe.cpp
src/server/graphics/platform_probe.h
tests/include/mir/test/doubles/mock_gl_rendering_provider.h
tests/unit-tests/graphics/test_platform_prober.cpp

This implements an actual selection process for the GraphicBufferAllocator:
* First, find the `RenderingPlatform`(s) with *fewest* displays they *can't* drive, then
* Select the `RenderingPlatform` with the highest number of displays probed 'best' for
In the case of ties, the algorithm picks the first `RenderingPlatform` in the list;
due to the selections elsewhere, that will be the first platform in alphabetical order
Fixes: #3400

graphics/PlatformProbe: Implement a more principled `GraphicBufferAllocator` selector

---

debian/libmiral7.symbols
src/miral/symbols.map
src/server/symbols.map
tools/symbols_map_generator/main.py

- The symbols generator script now has a "quirk" check to filter out symbols that we do not want to generate
- Removed a few miral symbols purposefully because they cause us headaches

bugfix: ignoring certain miral symbols purposefully due to inlining

---

src/miral/CMakeLists.txt

This makes it possible to use all miral objects in tests (without risking duplicate definitions)

Provide an intermediate OBJECT library for MirAL's external API

---

src/server/frontend_wayland/output_manager.cpp

Fixes #3414
Removes a duplicate call to `OutputConfigListener::output_config_changed` during the binding of the output object.

(#3414) Don't re-send wl_output.geometry if unchanged

---

include/platform/mir/input/input_report.h
src/miral/input_device_config.cpp
src/platforms/evdev/platform.cpp
src/server/input/default_input_device_hub.cpp
src/server/report/logging/input_report.cpp
src/server/report/logging/input_report.h
src/server/report/lttng/input_report.cpp
src/server/report/lttng/input_report.h
src/server/report/null/input_report.cpp
src/server/report/null/input_report.h

Drops some unused code from the "Input Report", and replaces the optional logging with direct logging.
This now includes logging the actual configuration of the device

Log input devices

---

CMakeLists.txt
debian/control
snap/snapcraft.yaml
spread/build/alpine/task.yaml
src/server/CMakeLists.txt
src/server/frontend_wayland/desktop_file_manager.cpp
src/server/frontend_wayland/desktop_file_manager.h

- AppArmor is now the primary source of snap desktop files in the `DesktopFileManager`

feature: resolving snap desktop files using app armor as the primary source

---

src/platforms/gbm-kms/server/kms/cursor.cpp
tests/unit-tests/platforms/gbm-kms/kms/test_cursor.cpp

Keep hardware cursor planes visible on all outputs intersected by the cursor geometry instead of only its position.
Issue: [#3449](https://github.com/canonical/mir/issues/3449)

gbm-kms: Make cursor transitions across outputs smoother

---

spread/build/ubuntu/task.yaml

We're only cross-building in `sbuild`.

spread: drop cross-build from `ubuntu` task

---

tests/CMakeLists.txt
tests/include/mir_test_framework/window_management_test_harness.h
tests/mir_test_framework/CMakeLists.txt
tests/mir_test_framework/window_management_test_harness.cpp
tests/window_management_tests/CMakeLists.txt
tests/window_management_tests/test_minimal_window_manager.cpp

This PR establishes an initial test harness that is suitable for `MinimalWindowManager`. We might need more harnessing for `FloatingWindowManager`, but that should come as a follow up if we need it. 
- Built out the `WindowManagementTestHarness`
- Wrote some initial integration tests for the `MinimalWindowManager`

feature: a test harness for window managers + tests for the MinimalWindowManager

---

src/platforms/common/server/cpu_copy_output_surface.cpp
src/platforms/common/server/cpu_copy_output_surface.h
src/platforms/eglstream-kms/server/buffer_allocator.cpp
src/platforms/gbm-kms/server/buffer_allocator.cpp
src/platforms/renderer-generic-egl/buffer_allocator.cpp
src/server/compositor/basic_screen_shooter.cpp
src/server/compositor/basic_screen_shooter.h
src/server/compositor/default_configuration.cpp
tests/unit-tests/compositor/test_basic_screen_shooter.cpp

fixes #3438
- `BasicScreenShooter` now respects the `GLConfig`
- When depth and stencil bits are provided, we create a render buffer for them
I was unable to make separate stencil/depth buffers worked, but it is _apparently_ recommended that they are combined. I don't know if this will have any major issues...

bugfix: screenshots now respect the `GLConfig` and contain a depth + stencil buffer when one is required

---

src/platforms/wayland/displayclient.cpp
src/platforms/wayland/wl_egl_display_provider.cpp
src/platforms/wayland/wl_egl_display_provider.h

Fixes: #3427
This is mostly about managing the lifetime of EGL entities correctly, but cleaned up some threading issues along the way

[mir:wayland] Fix handling of display unplug/replug

---

src/server/frontend_wayland/CMakeLists.txt
src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/frontend_wayland/xdg_decoration_unstable_v1.cpp
src/server/frontend_wayland/xdg_decoration_unstable_v1.h
src/server/frontend_wayland/xdg_shell_stable.cpp
src/server/frontend_wayland/xdg_shell_stable.h
src/wayland/CMakeLists.txt
tests/acceptance-tests/wayland/CMakeLists.txt
wayland-protocols/xdg-decoration-unstable-v1.xml

Wayland server side decorations

---

doc/sphinx/tutorial.md

- Reorganized Mir's main tutorial to divide the line between "installing the library" and "installing + running demos" to be more readable
- Removed some sections that I consider to be superfluous and just confuse a first-time reader

docs: update the tutorial to include less unnecessary cruft for newcomers

---

src/server/compositor/basic_screen_shooter.cpp
src/server/compositor/basic_screen_shooter.h
src/server/compositor/default_configuration.cpp
tests/unit-tests/compositor/test_basic_screen_shooter.cpp

bugfix: BasicScreenShooter now selects a GLRenderingProvider based off of its compatibility with the BufferAllocator

---

include/common/mir/input/keyboard_leds.h
include/platform/mir/input/led_observer_registrar.h
src/common/CMakeLists.txt
src/include/server/mir/default_server_configuration.h
src/include/server/mir/input/xkb_mapper_registrar.h
src/platforms/evdev/libinput_device.cpp
src/platforms/evdev/libinput_device.h
src/server/input/CMakeLists.txt
src/server/input/default_configuration.cpp
src/server/input/default_input_device_hub.cpp
src/server/input/default_input_device_hub.h
src/server/input/xkb_mapper_registrar.cpp
src/server/symbols.map
tests/include/mir/test/doubles/mock_led_observer_registrar.h
tests/include/mir/test/doubles/mock_libinput.h
tests/integration-tests/input/test_single_seat_setup.cpp
tests/mir_test_doubles/mock_libinput.cpp
tests/unit-tests/input/evdev/test_evdev_device_detection.cpp
tests/unit-tests/input/test_default_input_device_hub.cpp
tests/unit-tests/input/test_seat_input_device_tracker.cpp

fixes #620 
- `XkbMapper` takes a callback for when the leds need to be updated for a device 
- Whenever a modifier is changed for a device, `XkbMapper` notifies the corresponding device of a possible change to its LEDs using `Device::set_leds`
- In the case if a libinput device,`LibInputDevice::set_leds` calls `libinput_device_led_update` to update the LEDs

(#620) Enabling keyboard LEDs when the modifier state changes

---

debian/control
debian/libmirplatform28.install
debian/libmirplatform29.install
include/platform/mir/graphics/drm_formats.h
src/CMakeLists.txt
src/platform/graphics/drm_formats.cpp
src/platform/graphics/linux_dmabuf.cpp
src/platform/symbols.map
src/platforms/gbm-kms/server/buffer_allocator.cpp
src/server/scene/basic_surface.cpp

We're now using `DRMFormat` in a situation (linux-dmabuf) where:
* We don't actually need to care about many the properties of the format, and
* We're processing formats submitted by cilents.
This means that the existing “throw an exception if we haven't got a `FormatInfo`” approach works badly; we will disconnect clients with a Wayland internal error if they submit buffers in a format we haven't explicitly listed, even though it *would* work if we just treated the format as an opaque identifier.
So, don't do that anymore. Instead, store the fourcc code directly in `DRMFormat`, only look up the `FormatInfo` (now `DRMFormat::Info`) when code asks for it.
Additionally, we log the first time code asks for the `DRMFormat::Info` for a format we haven't got info for; this way we can fill out …

platform/DRMFormat: Don't require a `FormatInfo` for each format.

---

debian/control

These are needed to make it work in a snap environment, so make life easy by adding them here

Add dependencies to mir-x11-kiosk

---

src/platforms/common/server/kms-utils/CMakeLists.txt
src/platforms/common/server/kms-utils/drm_event_handler.h
src/platforms/common/server/kms-utils/threaded_drm_event_handler.cpp
src/platforms/common/server/kms-utils/threaded_drm_event_handler.h
src/platforms/eglstream-kms/server/CMakeLists.txt
src/platforms/eglstream-kms/server/display.cpp
src/platforms/eglstream-kms/server/display.h
tests/unit-tests/platforms/CMakeLists.txt
tests/unit-tests/platforms/eglstream-kms/server/CMakeLists.txt
tests/unit-tests/platforms/test_threaded_drm_event_handler.cpp

This should be useful when transitioning to the Atomic KMS API in gbm-kms.

platforms/common: Move DRMEventHandler in from eglstream-kms.

---

doc/sphinx/explanation/index.md
doc/sphinx/explanation/threat-model.md
doc/sphinx/explanation/ubuntu_frame_threat_model.mmd

To view: https://canonical-mir--3484.com.readthedocs.build/3484/explanation/threat-model/

docs: adding a threat model diagram for Ubuntu Frame

---

include/platform/mir/console_services.h
src/server/console/ioctl_vt_switcher.cpp
src/server/console/ioctl_vt_switcher.h
src/server/console/logind_console_services.cpp
src/server/input/vt_filter.cpp
tests/unit-tests/console/test_logind_console_services.cpp

This was broken as, despite passing an exception around, the exception is never thrown and so `current_exception()` is null and we get a segfault.
It was leaky as we called `new std::function<void(std::exception const&)>{error_handler};` and never delete.
It was over-engineered as there is no need to pass an exception around to log a runtime failure.

Drop overengineered, leaky and broken error reporting on VT switch

---

tests/mir_test_framework/window_management_test_harness.cpp

I can't convince myself that all access to `mir_test_framework::WindowManagementTestHarness::Self` data members is thread safe. So dropping in a mutex to see if it fixes the weird failures we see (mostly on riscv64).

Drop in a mutex to lock around data access

---

debian/control
debian/mir-x11-kiosk.install
examples/CMakeLists.txt
examples/mir-x11-kiosk/CMakeLists.txt
examples/mir-x11-kiosk/mir-x11-kiosk-launch.sh
examples/mir-x11-kiosk/x11_kiosk_main.cpp
examples/mir-x11-kiosk/x11_kiosk_window_manager.cpp
examples/mir-x11-kiosk/x11_kiosk_window_manager.h

> Backport of #3460, #3480, #3486 to 2.16 for release into `core22`
Add a mir-kiosk-x11 package (to replace
https://github.com/MirServer/mir_kiosk_x11.git in IOT snaps)
The intended use is to include this from our release PPA to support
snaps that wrap X11 apps. AFAICS there's no reason to also consider
adding this to the Ubuntu archive.

2.16: add x11-kiosk

---

src/platforms/wayland/displayclient.cpp
src/platforms/wayland/wl_egl_display_provider.cpp
src/platforms/wayland/wl_egl_display_provider.h

> Backport of #3433 to 2.16 for release into core22
Fixes: #3427
This is mostly about managing the lifetime of EGL entities correctly, but cleaned up some threading issues along the way

2.16: [mir:wayland] Fix handling of display unplug/replug (#3433)

---

src/platforms/wayland/displayclient.cpp
src/platforms/wayland/wl_egl_display_provider.cpp
src/platforms/wayland/wl_egl_display_provider.h

> Backport of #3433 to 2.17 for release into core22
Fixes: #3427
This is mostly about managing the lifetime of EGL entities correctly, but cleaned up some threading issues along the way

2.17: [mir:wayland] Fix handling of display unplug/replug (#3433)

---

debian/control
debian/mir-x11-kiosk.install
examples/CMakeLists.txt
examples/mir-x11-kiosk/CMakeLists.txt
examples/mir-x11-kiosk/mir-x11-kiosk-launch.sh
examples/mir-x11-kiosk/x11_kiosk_main.cpp
examples/mir-x11-kiosk/x11_kiosk_window_manager.cpp
examples/mir-x11-kiosk/x11_kiosk_window_manager.h

> Backport of #3460, #3480, #3486 to 2.17 for release into `core22`
Add a mir-kiosk-x11 package (to replace
https://github.com/MirServer/mir_kiosk_x11.git in IOT snaps)
The intended use is to include this from our release PPA to support
snaps that wrap X11 apps. AFAICS there's no reason to also consider
adding this to the Ubuntu archive.

2.17: add x11-kiosk

---

src/miral/static_display_config.cpp
src/server/frontend_wayland/foreign_toplevel_manager_v1.cpp

As [mentioned](https://github.com/canonical/mir/pull/3544#discussion_r1716168734) by @RAOF, we don't want the FD leaking to child processes

inotify_init1(IN_CLOEXEC)

---

include/platform/mir/graphics/platform.h
src/platforms/eglstream-kms/server/platform_symbols.cpp
src/platforms/gbm-kms/server/kms/platform_symbols.cpp
src/platforms/renderer-generic-egl/platform_symbols.cpp
src/platforms/virtual/graphics.cpp
src/platforms/wayland/platform_symbols.cpp
src/platforms/x11/graphics/graphics.cpp
src/server/graphics/default_configuration.cpp
src/server/graphics/platform_probe.cpp
src/server/graphics/platform_probe.h
tests/mir_test_framework/platform_graphics_dummy.cpp
tests/mir_test_framework/platform_graphics_throw.cpp

There's no particular reason these interfaces need the concrete `ProgramOption`, and it's simpler if we don't need to wildly `dynamic_cast<ProgramOption>` everywhere.

platform/graphics: Use interface Option type in interfaces.

---

include/core/mir/optional_value.h
src/include/server/mir/shell/decoration.h
src/miral/window_info_internal.cpp
src/server/frontend_xwayland/xwayland_surface.cpp
src/server/shell/abstract_shell.cpp
src/server/shell/decoration/basic_decoration.cpp
src/server/shell/decoration/window.cpp
src/server/shell/decoration/window.h
src/server/symbols.map

When SSD is applied the client only cares about the content area. So we need to adjust size related requests to reflect whole window 
Fixes #3572

fix-decorated-window-sizing

---

debian/rules

As per:
https://packages.ubuntu.com/source/oracular/binutils

debian: bump broken binutils version

---

src/miral/launch_app.cpp
src/platforms/wayland/cursor.cpp

Do not allocate memory between `fork()` and `exec()`

---

src/server/frontend_wayland/output_manager.cpp

In particular, `WindowWlSurfaceRole::output_global_created()` uses the notification to register as an observer on the global. Without this, it cannot track configuration changes

OutputManager: When listeners are registered, they need to be notified of existing globals

---

src/server/frontend_wayland/output_manager.cpp

In my [previous fix](https://github.com/canonical/mir/pull/3430) for #3414, I accidentally disabled sending `wl_surface.enter` events for surfaces on outputs enabled at runtime. This PR resolves that issue while still addressing #3414.

Fix missing `wl_surface.enter` events for outputs enabled at runtime.

---

src/include/server/mir/scene/null_surface_observer.h
src/include/server/mir/scene/surface_observer.h
src/miroil/surface.cpp
src/server/frontend_wayland/fractional_scale_v1.cpp
src/server/frontend_wayland/fractional_scale_v1.h
src/server/frontend_wayland/wayland_surface_observer.cpp
src/server/frontend_wayland/wayland_surface_observer.h
src/server/frontend_wayland/window_wl_surface_role.cpp
src/server/frontend_wayland/window_wl_surface_role.h
src/server/scene/basic_surface.cpp
src/server/scene/basic_surface.h
src/server/scene/null_surface_observer.cpp
src/server/symbols.map
tests/mir_test_framework/window_management_test_harness.cpp

Surfaces need to track scale changes on outputs they appear on
Fixes: #3552
(Reviewers note: this depends on #3586)

Live scale changes

---

src/miral/launch_app.cpp

Rework `miral::launch_app_env()` to avoid calling functions that are not async-signal-safe after fork()

---

src/server/frontend_wayland/wayland_surface_observer.cpp
src/server/frontend_wayland/wayland_surface_observer.h

Fixes: #3600 
Fixes: #3592 
Fixes: #3573

Revert "Fix toplevel window resize pingpong (#3575)" and fix better

---

src/platforms/wayland/cursor.cpp

Fixes x11-kiosk crash when running on `mir:wayland`
(It looks like any use if the `mir:wayland` platform would fail)

Revert "Fix random leak"

---

src/miral/input_configuration.cpp

Do not extend the `InputDeviceHub` lifetime beyond teardown

---

src/platforms/wayland/display.cpp
src/platforms/wayland/display.h
src/platforms/wayland/displayclient.cpp
src/platforms/wayland/displayclient.h
src/platforms/wayland/platform.cpp
src/platforms/wayland/platform.h
src/platforms/wayland/platform_symbols.cpp

- Added the `--wayland-surface-app-id=<APP_ID>` option for the wayland platform that, when set, will call [xdg_top_level::set_app_id](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id) with the value `APP_ID`
- Added the `--wayland-surface-title=<TITLE>` option for the wayland platform that, when set, will call [xdg_top_level::set_title](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_title) with the value `TITLE`

feature: users can specify an app id for the wayland surface when running on the wayland platform

---

src/platforms/atomic-kms/server/kms/atomic_kms_output.cpp

`DisplayConfigurationOutput.pixel_formats` now contains the list of accepted pixel formats (or, at least, those pixel formats that are representable in the `MirPixelFormats` enum; many aren't).

platforms/atomic-kms: Populate supported pixel formats correctly

---

include/common/mir/shared_library.h
include/platform/mir/options/configuration.h
include/platform/mir/options/default_configuration.h
include/platform/mir/options/program_option.h
src/common/sharedlibrary/shared_library.cpp
src/common/symbols.map
src/include/server/mir/default_server_configuration.h
src/platform/options/default_configuration.cpp
src/platform/options/program_option.cpp
src/server/default_server_configuration.cpp
src/server/graphics/default_configuration.cpp
src/server/graphics/platform_probe.cpp
src/server/graphics/platform_probe.h
src/server/server.cpp
src/server/symbols.map
tests/acceptance-tests/server_configuration_options.cpp
tests/mir_test_framework/command_line_server_configuration.cpp
tests/unit-tests/graphics/test_platform_prober.cpp
tests/unit-tests/options/test_program_option.cpp

This lets each module define its own options, without needing the option names to be unique across all modules.
Also organises the module-specific options into their own sections at the end of the help text.

Configuration: Split options into global and per-module configuration

---

src/server/frontend_xwayland/xwayland_surface.cpp

X11 CONFIGURE events may specify a position, but we will ignore it

[xwayland] Don't try to place X11 windows

---

src/miral/config_file.cpp
tests/miral/config_file.cpp

The `miral::ConfigFile` "Watcher" can be destroyed before the main loop invokes the handler it supports. So add another level of indirection to check it is still there. 
Plus some hygienic improvements to the test fixture.
Fixes: #3612

All problems in computer science can be solved by another level of indirection

---

CMakeLists.txt
doc/sphinx/tutorial/write-your-first-wayland-compositor.md

Another docs review. I've provided a bit more context to the code creation part (at least as well as I myself could understand it).
Do you think the build definition of Cmake requires more explanations? Or will it be a self-evident thing for a regular C++ developer?
Jira: https://warthogs.atlassian.net/browse/DOCPR-852

Review compositor tutorial

---

src/server/CMakeLists.txt

fixes https://github.com/canonical/mir/issues/3571
- This is a dead cmake target

Remove regenerate-mirserver-internal-debian-symbols because it does nothing

---

src/server/frontend_wayland/desktop_file_manager.cpp
src/server/frontend_wayland/foreign_toplevel_manager_v1.cpp
tests/unit-tests/frontend_wayland/test_desktop_file_manager.cpp
tests/unit-tests/frontend_wayland/test_g_desktop_file_cache.cpp

fixes https://github.com/canonical/mir/issues/3608

DesktopFileManager::resolve_app_id no longer returns an app id with a .desktop file suffix

---

.github/workflows/automatic-doc-checks.yml
doc/sphinx/.custom_wordlist.txt
doc/sphinx/.sphinx/build_requirements.py
doc/sphinx/Makefile
doc/sphinx/explanation/mir-graphics-support.md
doc/sphinx/explanation/ok-so-what-is-this-wayland-thing-anyway.md
doc/sphinx/how-to/developing-a-wayland-compositor-using-mir.md
doc/sphinx/how-to/developing-wayland-extension-protocols-for-mir-servers.md
doc/sphinx/how-to/getting_involved_in_mir.md
doc/sphinx/how-to/how-to-use-checkbox-mir.md
doc/sphinx/reference/continuous-integration.md
doc/sphinx/reference/dso_versioning_guide.md
include/core/mir_toolkit/mir_native_buffer.h
include/miral/miral/window_info.h
include/miral/miral/window_specification.h
src/miral/open_desktop_entry.cpp
src/miral/version.h.in

Adds new words to the custom wordlist to fix the spelling check, and fixes (most) URLs .

Fix docs checks

---

src/miral/basic_window_manager.cpp
src/server/frontend_wayland/window_wl_surface_role.cpp
src/server/frontend_wayland/window_wl_surface_role.h
src/server/scene/basic_surface.cpp
src/server/scene/surface_allocator.cpp

Stop pretending (mostly) that windows we don't know the size of are 640x480, 100x100, or 1x1.

Do not default window size

---

src/miral/check-and-update-debian-symbols.py
src/miroil/check-and-update-debian-symbols.py

Fixes an annoying warning spat out by Python

Use raw strings for regex patterns

---

include/platform/mir/options/configuration.h
src/include/server/mir/shell/idle_handler.h
src/platform/options/default_configuration.cpp
src/platform/symbols.map
src/server/shell/basic_idle_handler.cpp
src/server/shell/basic_idle_handler.h
src/server/shell/default_configuration.cpp
tests/unit-tests/shell/test_basic_idle_handler.cpp

Fixes #3306.
This PR adds a new configuration option, `--idle-timeout-when-locked`, that allows the compositor to apply a separate idle timeout when the session is locked. The default value is 0, meaning the display will stay on indefinitely when the session is locked.
Examples showing its interaction with the existing `--idle-timeout` option:
- `--idle-timeout=60 --idle-timeout-when-locked=10`: The display turns off after 60s of idle time when the session is unlocked, and after 10s of idle time when the session is locked.
- `--idle-timeout=0 --idle-timeout-when-locked=10`: The display never turns off when idle, but it turns off after 10s of idle time when the session is locked.
- `--idle-timeout=60 --idle-timeout-when-locked=0`: The display turns off after 60s of idle time but never when …

Add `--idle-timeout-when-locked` for idle timeout when session is locked

---

src/platforms/gbm-kms/server/gbm_display_allocator.cpp

Use smart pointers better and don't leak memory when errors occur

please-no-naked-new

---

src/miral/config_file.cpp
src/miral/static_display_config.cpp

ReloadingYamlFileDisplayConfig::auto_reload() incorrectly triggered on `IN_CREATE`.
The reason for that is that `IN_CREATE` and `IN_CLOSE_WRITE` events can often be read as pairs and we were not handling multiple events correctly.
Note:
This is a backport of the logic in ConfigFile's Watcher::handler(). Ideally, we'd unify the code. But that's awkward as Watcher currently only handles changes to a single file.
It would make sense to rework Watcher to have a single watch on the configuration directory and register multiple files with it.

Fix the inotify event handling in ReloadingYamlFileDisplayConfig::auto_reload()

---

src/server/frontend_wayland/CMakeLists.txt
src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h
src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/frontend_wayland/xdg_activation_v1.cpp
src/server/frontend_wayland/xdg_activation_v1.h
src/wayland/CMakeLists.txt
wayland-protocols/xdg-activation-v1.xml

[Screencast from 2024-10-16 16-21-05.webm](https://github.com/user-attachments/assets/86f9b0bf-181c-4aab-acfd-4ceb1e4e2c38)
- Added the xdg_activation_v1 protocol
- Implemented the xdg_activation_v1 protocol
- Run `miral-shell`
- Open `gnome-terminal`
- Run `gedit`
- Focus `gnome-terminal` again
- Run `gedit` again
- Note that `gedit` gets focus :magic_wand: 
Similarly:
- Open up `emacs`
- Open up `firefox`
- In emacs, write `https://google.com`
- Ctrl + Click the link
- Watch as firefox gets focus!
- The "timeout" is not configurable at the moment, but perhaps it should be. However, I don't think we do per-protocol options AFAICT
- I should probably write some WLCS tests!

feature: implementation of xdg_activation_v1 because I want my auto focuses

---

README.md

Fix the heading of Copyright, which was h1 not h2.

Move the license below the resources, as this is generally less useful to someone reading the README.

---

src/server/frontend_xwayland/xwayland_wm.cpp

For some reason, our code ignored synthetic unmap requests, even though [ICCCM 4.1.4](https://tronche.com/gui/x/icccm/sec-4.html) doesn't mention that it should be ignored. I tried commenting out the couple of lines responsible for ignoring the request and tested with gimp, qtcreator, and imagemagick. All seem to work better, especially gimp and qtcreator where this bug is most apparent.

Fix X11 dropdowns persisting for too long on unfocus

---

src/common/events/CMakeLists.txt
src/platforms/evdev/CMakeLists.txt
tests/unit-tests/CMakeLists.txt

openSUSE puts it's xkbcommon and libinput development headers in a non-standard location, which isn't Mir's problem, but it also doesn't implement PkgConfig properly to find those headers.
This is what I did to get it to package for openSUSE, but this should benefit any distribution that uses PkgConfig to find development files.

Use PkgConfig to find development headers

---

src/miral/window_info_internal.cpp

Aspect ratios shouldn't contain zero

---

src/server/frontend_xwayland/xwayland_surface.cpp

Previously, resizing didn't work at all unless you did a vertical resize followed by a horizontal one (or vice versa). Now, resizes work but only if you shrink the application. Any resizing outside application bounds stops after a couple of pixels.

Fix rendering of resized XWayland applications with client side decorations

---

src/platforms/atomic-kms/server/kms/CMakeLists.txt
src/platforms/atomic-kms/server/kms/atomic_kms_output.cpp
src/platforms/atomic-kms/server/kms/atomic_kms_output.h
src/platforms/atomic-kms/server/kms/cursor.cpp
src/platforms/atomic-kms/server/kms/cursor.h
src/platforms/atomic-kms/server/kms/display.cpp
src/platforms/atomic-kms/server/kms/display.h
src/platforms/atomic-kms/server/kms/kms_output.h
src/platforms/atomic-kms/server/platform_common.h
src/platforms/eglstream-kms/server/egl_output.cpp

This code will act as a placeholder temporarily until we implement damage, at which point, the real atomic KMS cursor  code (#3615) can be updated and merged.

Use old DRM cursor API as a placeholder for the atomic KMS hardware cursor

---

src/server/frontend_wayland/shm.cpp

I encountered this while running `cosmic-bg` on Mir. It still doesn't fix the problems there, but it avoids us blowing up in mmap

feature: throwing an invalid_stride error when the size provided to wl_shm::create_pool is less than or equal to zero

---

src/miral/basic_window_manager.cpp
src/miral/basic_window_manager.h
src/server/frontend_wayland/layer_shell_v1.cpp

New attached windows need to be placed

---

src/include/server/mir/scene/surface.h
src/server/scene/basic_surface.cpp
src/server/scene/basic_surface.h
src/server/shell/abstract_shell.cpp
tests/include/mir/test/doubles/stub_surface.h

- Added a method called `Surface::initial_placement_done` that is called after the surface has been placed properly
- `BasicSurface` sends the output enter event after creation.
This makes `cosmic-bg` work!

bugfix: always sending an initial output enter if we fail to send one otherwise

---

debian/control
debian/libmirplatform29.install
debian/libmirplatform30.install
src/CMakeLists.txt
src/platform/symbols.map
src/server/symbols.map

As noted in https://github.com/canonical/mir/pull/3590#pullrequestreview-2299754528

We broke the platform ABI since 2.18

---

examples/example-server-lib/tiling_window_manager.cpp

Don't assume that window size is specified

---

debian/changelog

2.18 had a mirserver ABI bump to 61

Fix changelog for 2.18.0

---

src/server/frontend_wayland/text_input_v1.cpp

Closes #3580. 
Fixes a few issues:
1. The "Interval" field showing the OSK for a split second
2. The "Interval" field (and similar fields) didn't get input changes as you used the OSK
3. Tabbing from the interval field to the minutes/hours/days field to its right opened the OSK in number mode.
This was due to `reset` being called between the content type being set in the state and the state being actually committed, causing Mir to lose the state and not commit it to the handler, leading to the previous mode (numbers) carrying over to the new field

Fix OSK issues on electron

---

examples/mir_demo_server/server_example_test_client.cpp

Slower devices (RPi3) did not keep up reliably.

smoke: increase the test timeout

---

src/miral/basic_window_manager.cpp

Fixes #3309 
Note that this bug only occurs with apps that can have multiple windows running under the same process (example: gnome-terminal, pluma)

Don't try to refocus on an app of the same client.

---

src/server/frontend_wayland/text_input_v3.cpp

Every time an app supporting text-input-v3 starts we allocate a "virtual-keyboard", we should also deallocate it as appropriate.
This was identified while investigating #3710, and is part of the fix (possibly all the fix - still testing)

Don't leak VirtualInputDevice keyboards

---

src/platforms/atomic-kms/server/kms/quirks.cpp
src/platforms/gbm-kms/server/kms/quirks.cpp

They should never be there in the first place.
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2084046 https://github.com/canonical/mir/issues/3710
Closes #3710

kms: skip `simple-framebuffer` devices

---

src/server/frontend_wayland/input_method_v1.cpp
src/server/frontend_wayland/input_method_v1.h

After an update, clang-20 started marking `InputPanelV1::display` as unused, which is true as there is no need to store it. This still happens with clang-20 (20250112081750+42da12063f49-1\~exp1\~20250112081925.659)

Remove unused `InputPanelV1::display`

---

src/miral/application_selector.cpp
src/miral/basic_window_manager.cpp
src/miral/basic_window_manager.h

Fix minimized windows being focused when a focused window is closed

---

examples/miral-shell/shell_main.cpp

This fixes terminals failing to activate themselves due to the key listener immediately revoking their token in response to the terminal launch shortcut being pressed.

Ctrl+Alt+{t,T,x,X} now prevent other event filters from running.

---

src/server/shell/decoration/basic_decoration.cpp
src/server/shell/decoration/basic_decoration.h
src/server/shell/decoration/basic_manager.cpp
src/server/shell/decoration/decoration_strategy.cpp
src/server/shell/decoration/decoration_strategy.h
src/server/shell/decoration/input.cpp
src/server/shell/decoration/input.h
src/server/shell/decoration/renderer.cpp
src/server/shell/decoration/renderer.h
src/server/shell/decoration/window.cpp

Improves the interface between the decoration strategies and the rest of the subsystem:
1. Encapsulates the StaticGeometry
2. Moves the Button enums into the struct (with a few renames)
3. Adds some documentation
4. Simplifies buffer creation API
5. Make InputState a struct
6. Simplify use of WindowState
Generally, making the decoration strategy simpler and easier to customise

decoration-strategy-rework

---

debian/libmiral7.symbols
examples/mir_demo_server/server_example.cpp
include/miral/miral/input_configuration.h
include/server/mir/shell/keyboard_helper.h
src/include/server/mir/default_server_configuration.h
src/include/server/mir/server.h
src/include/server/mir/shell/accessibility_manager.h
src/miral/input_configuration.cpp
src/miral/input_device_config.cpp
src/miral/input_device_config.h
src/miral/symbols.map
src/server/frontend_wayland/input_method_grab_keyboard_v2.h
src/server/frontend_wayland/keyboard_helper.cpp
src/server/frontend_wayland/keyboard_helper.h
src/server/frontend_wayland/wayland_connector.cpp
src/server/frontend_wayland/wayland_connector.h
src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/frontend_wayland/wl_keyboard.h
src/server/frontend_wayland/wl_seat.cpp
src/server/frontend_wayland/wl_seat.h
src/server/report/default_server_configuration.cpp
src/server/server.cpp
src/server/shell/CMakeLists.txt
src/server/shell/accessibility_manager.cpp
src/server/shell/default_configuration.cpp
src/server/symbols.map

How to test:
- Create a file at `~/.config/mir_demo_server.input` with the following content:
```
repeat_rate=25
repeat_delay=600
```
- Run mir demo server
- Run a wayland compatible text editor or terminal (`kgx`), or and X application (`xterm`)
- press and hold any key
- Change `repeat_rate` to a higher or lower value and watch as the repeat rate speeds or slows down
- Change `repeat_delay` to a higher or lower value and watch as the duration you need to hold the key down increases or decreases.

Make key repeat and delay configurable

---

examples/mir_demo_server/server_example.cpp

Consolidate the data and logic associated with the input configuration file into a class

Extract InputConfigFile

---

src/server/frontend_wayland/wl_surface.cpp
src/server/frontend_wayland/wl_surface.h

We currently queue a `send_frame_events()` 16ms after receiving
a `surface.commit()` with no buffer but that requests a frame
event.
When `send_frame_events()` is triggered it sends *all* the frame
events at the time of trigger; this results in us sending frame
events at a sub-optimal time and breaks the way that WLCS uses
the frame event to determine when a buffer has been used.
Instead, maintain a separate `heartbeat_quirk_frame_events` list
that gets sent by the 16ms timer.

Improve Firefox `surface.frame` event quirk

---

src/platforms/atomic-kms/server/kms/atomic_kms_output.cpp
src/platforms/atomic-kms/server/kms/atomic_kms_output.h
src/platforms/atomic-kms/server/kms/cursor.cpp
src/platforms/atomic-kms/server/kms/kms_output.h

`KMSOutput::has_cursor` was misleadingly named, and so we implemented it incorrectly. It is *used* to tell whether or not a cursor image needs to be set on that particular output before it is visible, *not* whether that output *supports* a cursor.
Rename it to something hopefully more easily understandable, and then fix the implementation.
Fixes: #3677

platforms/atomic-kms: Fix cursors across multiple monitors.

---

src/miral/input_device_config.cpp

Closes #3737 
Wasn't sure whether these changes fit in the cursor scaling PR or not. Nonetheless, they depend on some changes from it, specifically the following chunk which merges changes from the input config and the command line/env/etc:
https://github.com/canonical/mir/pull/3735/files#diff-cab2d87fa32f5bd035e2ffb1ebaf95cb5fdcf4ce79543ea2136af92fee83093eR131-R141

Add options to override key repeat rate and delay

---

src/platforms/gbm-kms/server/kms/display_buffer.cpp
src/platforms/gbm-kms/server/kms/kms_output.h
src/platforms/gbm-kms/server/kms/real_kms_output.cpp
src/platforms/gbm-kms/server/kms/real_kms_output.h
tests/unit-tests/platforms/gbm-kms/kms/mock_kms_output.h

fixes #3729 
If a display sink is associated with a disconnected output, `mgg::RealKMSOutput::size()` returns a 0-size. This size is then used to size a buffer, which causes `eglSwapBuffers` to be upset.
If this `DisplaySink` references a disconnected output, we shouldn't include it when we're iterating over the list of sinks, as it will assuredly lead to the allocation of a 0-sized buffer.
The atomic kms platform does not suffer from the same issue as the non-atomic platform, so I have not made changes there.

(#3729) disconnected display outputs do not show up in DisplaySink::for_each_display_sink

---

examples/mir_demo_server/server_example.cpp
src/server/frontend_wayland/wayland_default_configuration.cpp

Extend the lifetime of the accessibility manager to keep enable-key-repeat

---

examples/example-server-lib/decoration_provider.cpp
src/server/shell/decoration/decoration_strategy.cpp

This is "Appendix D" and slated for removal in C++26, hopefully there will be an obvious replacement by then

std::wstring_convert is deprecated, but there's no obvious replacement. Yet

---

src/server/frontend_wayland/wl_data_device.cpp

I.e.  check we have a buffer size before using it
Fixes: #3765

Do not crash when pcmanfm-qt does DnD 

---

src/server/frontend_wayland/wl_data_device.cpp

We were being too strict by requiring the `origin` to be the surface with input focus. Focus simply needs to belong to the same client
Fixes: #3769

[Drag and Drop] Relax check for "implicit grab"

---

src/server/frontend_wayland/xdg_activation_v1.cpp

The segfault was because of null entries in `pending_tokens`
Fixes: #3771
The prior code left rubbish at the end of the vector, and never erased anything

Do not crash in XdgActivationV1

---

src/server/shell/abstract_shell.cpp

Unmapped windows with size constraints need to adjust them for SSDs

---

include/miral/miral/window_management_policy.h
src/miral/window_management_policy.cpp

Helps fix spurious debian symbol errors in CI.

Move `~WindowManagementPolicy` to its source file.

---

src/server/shell/abstract_shell.cpp

Do not allow max_{width,height} to overflow

---

src/miral/input_configuration.cpp

Keep references to server components by weak pointer so that we do not extend their life beyond the life of the server

Fix shutdown order

---

include/platform/mir/options/configuration.h
src/include/server/mir/default_server_configuration.h
src/include/server/mir/input/input_event_transformer.h
src/include/server/mir/shell/accessibility_manager.h
src/platform/options/default_configuration.cpp
src/platform/symbols.map
src/server/frontend_wayland/wayland_default_configuration.cpp
src/server/input/CMakeLists.txt
src/server/input/default_configuration.cpp
src/server/input/input_event_transformer.cpp
src/server/shell/accessibility_manager.cpp
src/server/shell/default_configuration.cpp
src/server/symbols.map
tests/acceptance-tests/test_input_device_hub.cpp
tests/acceptance-tests/test_seat_report.cpp
tests/unit-tests/input/CMakeLists.txt
tests/unit-tests/input/test_input_event_transformer.cpp

Some notes:
1. The latter half of this PR (the accessibility manager demo) is just for making sure its functionality works properly. ~I will move this commit to the mousekeys  PR after this one is approved.~ Well, since that PR is based on this, it doesn't matter if I leave it here or move it there, so...
2. Currently, there's a segfault when shutting down mir thrown somewhere while destructing `SeatInputDeviceTracker::touch_visualizer`. It's not entirely clear what's the cause, but I have a "workaround" for it. ~I'm still trying to find the root cause~ #3768

Introduce `InputEventTransformer` to read and synthesize input events

---

include/test/mir/test/doubles/mock_gl.h
src/platforms/common/server/shm_buffer.cpp
tests/mir_test_doubles/mock_gl.cpp

Because we're on an `EGLContextExecutor` we're probably on a different
thread to where the GL state is going to be used, *and* we don't
have implicit flushing with `eglMakeCurrent` happening (because
the context just stays current on the `EGLContextExecutor`.
If the GL implementation has per-thread execution queues (for example,
amdgpu by default), this might mean that the texture setup commands
aren't visible to command stream that's actually using the
texture.
Explicitly `glFlush()` after our texture setup, to ensure
these commands are visible to any `EGLContext` that might
need them.
Closes: #3792

mgc::ShmBuffer: Fix texture setup synchronisation

---

src/include/server/mir/scene/session_coordinator.h
src/include/server/mir/shell/shell.h
src/include/server/mir/shell/token_authority.h
src/miral/config_file.cpp
src/platforms/common/server/kms-utils/drm_event_handler.h
src/platforms/wayland/wl_egl_display_provider.cpp
src/server/shell/decoration/decoration_strategy.cpp

Found compile errors such as the following both on v2.19.3 and main (with this PR being verified against the latter):
```
In file included from src/platforms/common/server/kms-utils/threaded_drm_event_handler.cpp:17:
In file included from src/platforms/common/server/kms-utils/threaded_drm_event_handler.h:20:
src/platforms/common/server/kms-utils/drm_event_handler.h:42:14: error: no template named 'function' in namespace 'std'
42 |         std::function<void(unsigned int frame_number, std::chrono::milliseconds frame_time)> on_flip) = 0;
|         ~~~~~^
In file included from src/server/server.cpp:39:
In file included from src/server/frontend_wayland/wayland_connector.h:20:
src/include/server/mir/shell/token_authority.h:72:10: error: no type named 'mutex' in namespace 'std'
72 | …
```

Include missing headers to fix compile under musl/libc++

---

src/platforms/atomic-kms/server/kms/atomic_kms_output.cpp

This fixes a segfault in subsequent code that assumes the connector can be used
Fixes: #3816

AtomicKMSOutput::ensure_crtc() may see an output disconnect

---

include/miral/miral/output.h

* Display output types are enumerated in multiple places across mir. In all of them except for this file, Virtual, DSI, and DPI are enumerated. make miral's output enumeration consistent with rest of mir graphics.

miral: fix missing dsi enumeration

---

tests/include/mir_test_framework/window_management_test_harness.h
tests/mir_test_framework/window_management_test_harness.cpp
tests/window_management_tests/test_minimal_window_manager.cpp

- Adding tests for windows transitioning states when they are moved

testing: adding MinimalWindowManager tests for preparing a movement gesture

---

src/include/server/mir/shell/accessibility_manager.h
src/server/shell/accessibility_manager.cpp

Addresses https://github.com/canonical/mir/pull/3735#discussion_r1999090513
Didn't really fit with either #3735 nor #3830, so I made it into its own PR.

Protect `AccessibilityManager` data member from racy mutations

---

tests/include/mir_test_framework/window_management_test_harness.h
tests/mir_test_framework/window_management_test_harness.cpp
tests/window_management_tests/test_minimal_window_manager.cpp

- No real functionality has changed!
- Use `miral::WindowSpecification` over `msh::SurfaceSpecification`
- Removing windows in a more future-proof way using promises
- Const-ifying things that can be made const
- Generally cleaning up the code, because it was shady-ish in the past
- `focused` now takes a window and returns true if that window is focused

testing: refactor the WindowManagementTestHarness to use miral::WindowSpecification, manage object lifetimes better, and be more const friendly

---

.github/workflows/tics.yml

---
This has a much lower complexity than https://github.com/canonical/mir/compare/main...tics-parallel and slightly better result, even if it is a little slower at first.
A run with this in place: https://github.com/canonical/mir/actions/runs/13925531981

tics: run on the self-hosted runner

---

src/miral/input_configuration.cpp

Fix `Mouse::{v,h}scroll_speed` returning `acceleration_bias`

---

include/miral/miral/window_manager_tools.h
src/miral/window_management_trace.cpp

IMO the `PersistentSurfaceStore` and associated infrastructure are zombie code: Mark the corresponding APIs as deprecated before removal

Deprecate "persistent" surface IDs

---

CMakeLists.txt
debian/rules
tests/unit-tests/CMakeLists.txt

(https://github.com/canonical/mir/pull/3842) disabled `array-bounds` errors in optimized builds, that was the
only remaining quirk.

tests: drop `MIR_COMPILER_QUIRKS`

---

debian/rules

Only see those issues in plucky,oracular/arm64 at the moment.

debian: tighten LTO-disabling rules

---

doc/sphinx/how-to/how-to-specify-startup-apps.md

Removes an extra unmatched closed brace in the "How to Specify Startup Applications" code sample.

docs: remove extra brace

---

src/include/server/mir/shell/accessibility_manager.h
src/server/shell/accessibility_manager.cpp

Split out from https://github.com/canonical/mir/pull/3861#issuecomment-2758295300

Only initialize `AccessibilityManager::transformer` if mousekeys are enabled

---

tests/include/mir_test_framework/window_management_test_harness.h
tests/mir_test_framework/window_management_test_harness.cpp
tests/window_management_tests/CMakeLists.txt
tests/window_management_tests/test_minimal_window_manager.cpp

- Add tests for closing windows and asserting facts about focus order and size
- Prioritizing using `tools()` over anything else to make changes to the underlying system. To accomplish this, I created a proxy object class called `NotifyingWindowManagerToolsImplementation` which mainly delegates changes to the wrapped object, but also has the property that it will notify the underlying system when a change has occurred. This allows us to queue up actions (which - in the normal system - would have happened asynchronously) and execute them before the request returns. This simplifies most events going into the system.
- Removed locks around the `surface_cache`, as they are guaranteed to be accessed synchronously now. The cache is only accessed (1) when we create a window or (2) when we remove …

testing: add tests for closing the active window

---

.github/workflows/symbols-check.yml

Otherwise can't make it required.

ci: rename symbols check job

---

.github/workflows/tics.yml

Gating up for evaluation - not a required check just yet.

tics: run on all `main` pushes and gate on pull requests

---

src/platforms/gbm-kms/server/buffer_allocator.cpp
src/platforms/gbm-kms/server/buffer_allocator.h
src/platforms/renderer-generic-egl/buffer_allocator.cpp
src/platforms/renderer-generic-egl/buffer_allocator.h
src/server/frontend_wayland/wayland_connector.cpp

Fix `mf::WaylandConnector` to always call `GraphicsBufferAllocator::unbind_display`
on the Wayland eventloop (or directly, if the eventloop isn't running), and then
use this to clean up `LinuxDmaBufUnstable` resources synchronously rather than
deferring them to the `WaylandExecutor` which may never execute that work.

Fix leak of `LinuxDmaBufUnstable` resources

---

.gitignore
src/server/graphics/software_cursor.cpp
tests/unit-tests/graphics/test_software_cursor.cpp

We only ever destroy `the_cursor()` during teardown, and
*during* teardown work deferred to the `GLibMainLoop` can
get leaked; in this case resulting in the cursor `Renderable`
being leaked (along with the `Scene`).
Since we don't need to release any *hardware* resources,
just don't try to hide the cursor; we're going to stop
drawing it immediately anyway!

mg::SoftwareCursor: Don't `hide()` on destruction

---

src/platforms/renderer-generic-egl/rendering_platform.cpp
src/platforms/renderer-generic-egl/rendering_platform.h

We want `EGLTerminate` to be called *last*, but there are a bunch of member variables that will try cleaning up EGL resources in *their* destructors.
Move `EGLDisplay` handling into a trivial class with its own destructor so we can rely on member ordering to enforce correct destruction order.

platforms/generic-egl: Correct order of EGL resource destruction

---

debian/libmiral7.symbols
include/miral/miral/display_configuration.h
src/miral/display_configuration.cpp
src/miral/static_display_config.cpp
src/miral/static_display_config.h
src/miral/symbols.map
tests/miral/CMakeLists.txt
tests/miral/display_configuration.cpp
tests/miral/static_display_config.cpp

- Add `DisplayConfiguration::layout_userdata` and `DisplayConfiguration::set_layout_userdata_builder` so that callers can get/set an arbitrary `shared_ptr<void>` user-defined data member on a per layout basis.
- Bumped the minor version of miral from 5.2 to 5.3
- Wrote a test for setting/getting the userdata for a layout
- Added a new stanza to the `symbols.map` file

feature: add the ability to associate a layout with custom user data

---

tests/miral/CMakeLists.txt

Is this evil? I am setting `MIR_EXCLUDE_TESTS`. It is local to the test, and fairly easy to control.

(#3843) Excluding a test from miral-test runs

---

src/include/server/mir/shell/accessibility_manager.h
src/miral/input_configuration.cpp
src/server/shell/basic_accessibility_manager.cpp
src/server/shell/basic_accessibility_manager.h
tests/miral/test_mousekeys_config.cpp
tests/unit-tests/shell/test_basic_accessibility_manager.cpp

The deadlock was caused by the for loop extending the lifetime of the state lock to cover the duration of the whole loop. In the loop, we also locked the state to read some data, which would cause the deadlock.
Why did this decide to come up now? I have no idea, it used to work before (and should've failed in CI), but now it deadlocks...

Fix deadlock in `BasicAccessibilityManager::notify_helpers`

---

examples/tests/test_floating_window_manager.cpp
include/test/mir/test/doubles/fake_display.h
src/include/server/mir/default_server_configuration.h
src/include/server/mir/server.h
src/server/server.cpp
src/server/symbols.map
tests/include/mir_test_framework/window_management_test_harness.h
tests/mir_test_doubles/fake_display.cpp
tests/mir_test_framework/window_management_test_harness.cpp
tests/window_management_tests/test_minimal_window_manager.cpp

- Exposed `the_display_configuration_observer` from the configuration so that we can trigger display updates
- Added `WindowManagementTestHarness::for_each_output` and `WindowManagementTestHarness::update_outputs`
- Refactored `WindowManagementTestHarness::get_output_rectangles` to `WindowManagementTestHarness::get_initial_output_configs`
- Updated `NotifyingWindowManagerToolsImplementation::move_cursor_to` to be linear
- Wrote some new tests for the `MinimalWindowManager` with how surfaces should behave on new outputs

testing: adding tests for output updates

---

src/miral/static_display_config.cpp
src/miral/static_display_config.h
tests/miral/static_display_config.cpp

Adds to the default config:
```yaml
#
#
```

static_display_config: add display properties to output

---

src/include/server/mir/input/input_event_transformer.h
src/server/input/default_configuration.cpp
src/server/input/input_event_transformer.cpp
src/server/shell/basic_accessibility_manager.cpp
src/server/shell/basic_accessibility_manager.h
src/server/shell/default_configuration.cpp
src/server/shell/mouse_keys_transformer.cpp
src/server/shell/mouse_keys_transformer.h
src/server/symbols.map
tests/acceptance-tests/test_input_device_hub.cpp
tests/unit-tests/input/test_input_event_transformer.cpp
tests/unit-tests/shell/test_basic_accessibility_manager.cpp

Reassign some of the responsibilities from `InputEventTransformer`
Alternative to #3861
Fixes: #3854

Introduce mir::shell::BasicAccessibilityManager::MousekeyPointer

---

tests/unit-tests/input/test_input_platform_probing.cpp

Fixes CI failures on Fedora/rawhide

Use a null object, not a null pointer

---

include/platform/mir/graphics/linux_dmabuf.h
src/platform/graphics/linux_dmabuf.cpp
src/platforms/eglstream-kms/server/buffer_allocator.cpp
src/platforms/gbm-kms/server/buffer_allocator.cpp
src/platforms/renderer-generic-egl/buffer_allocator.cpp
tests/include/mir/test/doubles/stub_gl_rendering_provider.h

Users may wish to wrap a `Buffer` in a class with some extra behaviour of their own (notably, tracking when the buffer is no longer used by the rendering pipeline).
In order to allow this wrapping while still having `as_texture` access the *real* buffer type we should be using `NativeBufferBase` so the wrapper can return the underlying buffer.

platforms: Use `NativeBufferBase` in `as_texture`

---

src/platforms/atomic-kms/server/gbm_display_allocator.h

Seems to be a global replace when atomic-kms was copied from gbm-kms.

Fix param name that mismatches cpp source

---

tests/window_management_tests/test_minimal_window_manager.cpp

We have been testing that a behaviour fails when that behaviour happens intermittently (and is probably what we want).
We don't currently understand why the behaviour isn't consistent, but changing the tests to test for the correct behaviour and disabling them seems a good intermediate condition

Simplify MinimalWindowManagerTests

---

src/platforms/common/server/kms-utils/drm_mode_resources.cpp

Seems to be a copy-paste error as it duplicates the exception text for drmModeGetPlane

Update exception text when fail to call drmModeGetProperty

---

src/server/compositor/basic_screen_shooter.cpp
src/server/compositor/basic_screen_shooter.h
src/server/compositor/basic_screen_shooter_factory.cpp
src/server/compositor/basic_screen_shooter_factory.h
src/server/compositor/default_configuration.cpp
tests/unit-tests/compositor/test_basic_screen_shooter.cpp
tests/unit-tests/compositor/test_basic_screen_shooter_factory.cpp

- When doing magnification work, I noticed that the color of the scene was always inverted after pulling latest from `main`
- Looks like we needed to set the filter in the `BasicScreenShooter`
- Run miral-shell
- Run `grimshot save output`. Note that the image is correctly not inverted
- Invert the color using Ctrl + I
- Run `grimshot save output` again. Note that the image is correctly inverted

Account for the OutputFilter in the BasicScreenShooter

---

src/miral/output_filter.cpp

Remove `output-config` from "dead" configuration options

cleanup-output-config-options

---

src/platforms/common/server/shm_buffer.cpp
src/platforms/common/server/shm_buffer.h
src/platforms/eglstream-kms/server/buffer_allocator.cpp
src/platforms/gbm-kms/server/buffer_allocator.cpp
src/platforms/renderer-generic-egl/buffer_allocator.cpp
src/platforms/renderer-generic-egl/buffer_allocator.h
src/platforms/renderer-generic-egl/rendering_platform.cpp
src/platforms/renderer-generic-egl/rendering_platform.h
tests/mir_test_doubles/stub_buffer_allocator.cpp
tests/unit-tests/graphics/test_shm_buffer.cpp

fixes #3933 
- `GLRenderingProvider::as_texture` now checks if we have a `ShmBuffer` and returns a texture for that specific provider instead of a single texture for all providers
- Implemented `ShmBuffer::texture_for_provider` which will return a `gl::Texture` either from a map cache or elsewhere
- Added `ShmBuffer::create_texture` which has a default implementation, but will be overridden for each of the subclasses. These subclasses mostly need to override the `bind()` method
- `ShmBuffer` no longer implements `gl::Texture`
- `ShmBuffer` no longer takes an `EGLContextExecutor` unless it is creating a texture
- Updated the associated unit tests

(#3933) fixing improper texture allocation across cards

---

CMakeLists.txt

This improves the experience for people using editors with LSP support, and file is small relative to a full Mir build tree so there is not much harm in generating it in cases where it won't be used.

Enable generation of compile_commands.json for use by clangd

---

debian/rules

Ref.: https://launchpad.net/ubuntu/+source/binutils

debian: add questing's broken binutils version

---

debian/libmiral7.symbols
examples/mir_demo_server/server_example.cpp
include/miral/miral/cursor_scale.h
include/miral/miral/input_configuration.h
include/miral/miral/live_config.h
include/miral/miral/output_filter.h
src/miral/CMakeLists.txt
src/miral/cursor_scale.cpp
src/miral/input_configuration.cpp
src/miral/live_config.cpp
src/miral/output_filter.cpp
src/miral/symbols.map
tests/miral/CMakeLists.txt
tests/miral/live_config.cpp
tools/symbols_map_generator/main.py

This is the first part of providing a pluggable live configuration mechanism
This PR provides 
1. the `miral::live_config::Store` API to be implemented over a configuration mechanism; and,
2. Constructors for  `OutputFilter`, `CursorScale` and `InputConfiguration` that register for configuration changes
There's also a POC .ini file style implementation in `mir_demo_server`.
Further PRs will provide implementations of `miral::live_config::Store` based on ".ini file" (replacing the POC with something complete and product ready), YAML and gsettings.
Shells will be able to choose between these implementations and rolling their own

live configuration facilities

---

include/platform/mir/graphics/dmabuf_buffer.h
include/platform/mir/graphics/platform.h
src/platform/graphics/linux_dmabuf.cpp
src/platforms/atomic-kms/server/kms/display_buffer.cpp
src/platforms/atomic-kms/server/kms/display_sink.h
src/platforms/gbm-kms/server/buffer_allocator.cpp
src/server/compositor/default_display_buffer_compositor.cpp
src/server/compositor/multi_threaded_compositor.cpp

Apologies for the general suckiness of the code, will improve that once it actually works.
To test:
```sh
./build/bin/miral-kiosk --show-splash=off --platform-display-libs=mir:atomic-kms --platform-rendering-libs=mir:gbm-kms --cursor=null &
sleep 2
glmark2-wayland
```
Note that until hardware cursor support is merged, the cursor must be disabled when testing bypass (current implementation works only with one renderable)

Atomic KMS: enable bypass

---

src/platforms/eglstream-kms/server/buffer_allocator.cpp
src/platforms/eglstream-kms/server/buffer_allocator.h

This is a follow up for #3968, fixing an immediate crash on eglstream-kms.

platforms/eglstream-kms: Update for ShmBuffer interface changes

---

src/include/server/mir/compositor/screen_shooter.h
src/server/compositor/basic_screen_shooter.cpp
src/server/compositor/basic_screen_shooter.h
src/server/compositor/basic_screen_shooter_factory.cpp
src/server/compositor/basic_screen_shooter_factory.h
src/server/compositor/default_configuration.cpp
src/server/compositor/null_screen_shooter.cpp
src/server/compositor/null_screen_shooter.h
src/server/frontend_wayland/wlr_screencopy_v1.cpp
src/server/frontend_wayland/wlr_screencopy_v1.h
tests/unit-tests/compositor/test_basic_screen_shooter.cpp
tests/unit-tests/compositor/test_basic_screen_shooter_factory.cpp
tests/unit-tests/frontend_wayland/test_screencopy_v1_damage_tracker.cpp

- Add `overlay_cursor` parameter to `ScreenShooter::capture` and implement it in the `BasicScreenShooter`
- Pass the flag through wlr screencopy v1
- Wrote a test for the new functionality
1. Run your compositor with wlr screencopy support
2. Run `grimshot --cursor save output`
3. See your cursor on screen
**WARNING**: This does not yet work with the atomic-kms platform, but that will come once #4011 has landed. Neither PR depends on the other.
This is running on gbm-kms with two outputs:

Implement the 'overlay_cursor' flag for WlrScreencopy

---

src/include/server/mir/server.h
src/server/symbols.map

The definition has gone, drop the declaration too

Drop dead function declaration

---

src/platforms/atomic-kms/server/kms/cursor.cpp
src/platforms/atomic-kms/server/kms/cursor.h
tests/unit-tests/platforms/CMakeLists.txt
tests/unit-tests/platforms/atomic-kms/CMakeLists.txt
tests/unit-tests/platforms/atomic-kms/kms/CMakeLists.txt
tests/unit-tests/platforms/atomic-kms/kms/mock_kms_output.h
tests/unit-tests/platforms/atomic-kms/kms/test_cursor.cpp

- Gave the `atomic-kms` cursor the same implementation as the `gbm-kms` cursor
- Added our first `atomic-kms` tests for the new methods

Implement Cursor::renderable for the atomic-kms platform

---

include/core/mir_toolkit/common.h
include/platform/mir/graphics/renderable.h
src/include/server/mir/scene/basic_surface.h
src/platforms/atomic-kms/server/kms/cursor.cpp
src/platforms/gbm-kms/server/kms/cursor.cpp
src/renderers/gl/renderer.cpp
src/server/graphics/software_cursor.cpp
src/server/input/touchspot_controller.cpp
src/server/scene/basic_surface.cpp
src/server/shell/basic_idle_handler.cpp
tests/include/mir/test/doubles/fake_renderable.h
tests/include/mir/test/doubles/mock_renderable.h
tests/include/mir/test/doubles/stub_renderable.h
tests/platform_test_harness/graphics_platform_test_harness.cpp
tests/unit-tests/graphics/test_software_cursor.cpp
tests/unit-tests/platforms/atomic-kms/kms/test_cursor.cpp
tests/unit-tests/renderers/gl/test_gl_renderer.cpp
tests/unit-tests/scene/test_basic_surface.cpp
tests/unit-tests/shell/test_basic_idle_handler.cpp

- To properly support [all of the allowed transforms](https://wayland.app/protocols/wayland#wl_output:enum:transform), we need to support `mirror_mode()` on renderables in addition to orientation
- We apply this mirror mode to the renderable at render time to un-flip the content
- Wrote tests for everything

Use MirMirrorMode on renderables in the renderer

---

src/include/server/mir/input/input_event_transformer.h
src/server/input/input_event_transformer.cpp
src/server/shell/basic_hover_click_transformer.cpp
src/server/shell/basic_hover_click_transformer.h

Whoops! `state->click_dispatcher` is initialized lazily. We should make it more obvious that this is the case :)

Fixing issue where alarm could be scheduled with a null click_dispatcher

---

debian/libmiral7.symbols
doc/sphinx/how-to/how-to-handle-keyboard-input.md
examples/miral-shell/shell_main.cpp
examples/miral-system-compositor/system_compositor_main.cpp
include/miral/miral/append_keyboard_event_filter.h
src/miral/CMakeLists.txt
src/miral/append_keyboard_event_filter.cpp
src/miral/symbols.map

A lot of code adds event filters for keyboard events only; add a helper class to remove this boilerplate code.

Add AppendKeyboardEventFilter helper

---

examples/mir_demo_server/server_example.cpp

Removes unused includes and namespace aliases, and moves the bounce keys include to the correct place with the correct style.

Clean up server example

---

src/server/CMakeLists.txt

GLib 2.85 fixes a looooong-standing bug we were hitting. Unfortunately, the fix interacts badly with the workaround we use. Fortunately, we put the workaround behind a `#ifndef GLIB_IS_FIXED`, so we can now just add that `#define` on sufficiently-new GLibs.
C.f. https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2187
Fixes: #4003

server/GLibMainLoop: Turn off workaround for now-fixed GLib bug

---

src/server/frontend_wayland/output_manager.cpp
src/server/frontend_wayland/output_manager.h
tests/unit-tests/frontend_wayland/test_output_manager.cpp

- Update `OutputInstance::output_config_changed` to send the right transform in the [geometry event](https://wayland.app/protocols/wayland#wl_output:event:geometry)
- Update `OutputInstance::output_config_changed` to send the untransformed width and height in the [mode event](https://wayland.app/protocols/wayland#wl_output:event:mode)
- Wrote a unit test for the new transformation code

Update wl_output::geometry to include the correct transformation

---

debian/libmiral7.symbols
examples/mir_demo_server/server_example.cpp
include/miral/miral/slow_keys.h
src/include/server/mir/shell/accessibility_manager.h
src/include/server/mir/shell/slow_keys_transformer.h
src/miral/CMakeLists.txt
src/miral/slow_keys.cpp
src/miral/symbols.map
src/server/shell/CMakeLists.txt
src/server/shell/basic_accessibility_manager.cpp
src/server/shell/basic_accessibility_manager.h
src/server/shell/basic_slow_keys_transformer.cpp
src/server/shell/basic_slow_keys_transformer.h
src/server/shell/default_configuration.cpp
src/server/symbols.map
tests/miral/test_mousekeys_config.cpp
tests/unit-tests/shell/CMakeLists.txt
tests/unit-tests/shell/test_basic_accessibility_manager.cpp
tests/unit-tests/shell/test_slow_keys_transformer.cpp

Adds slow keys, an accessibility feature which allows users to define how long they have to press a button before it registers as a real press. If the user continues to hold the button down, key repeat activates. If the user taps the button continuously, the no key presses are registered.
At the moment, slow keys is enabled by default for prototyping purposes. To test, you can open any application with text input such as `xterm` or `kgx`. Try tapping a key, holding it until it registers a press, and also holding it further until repeat activates.

Implement slow keys

---

include/common/mir/input/transformer.h
src/include/server/mir/input/input_event_transformer.h
src/include/server/mir/shell/hover_click_transformer.h
src/include/server/mir/shell/simulated_secondary_click_transformer.h
src/include/server/mir/shell/slow_keys_transformer.h
src/include/server/mir/shell/sticky_keys_transformer.h
src/server/shell/basic_accessibility_manager.cpp
src/server/shell/basic_hover_click_transformer.cpp
src/server/shell/basic_hover_click_transformer.h
src/server/shell/basic_simulated_secondary_click_transformer.cpp
src/server/shell/basic_simulated_secondary_click_transformer.h
src/server/shell/basic_slow_keys_transformer.cpp
src/server/shell/basic_slow_keys_transformer.h
src/server/shell/basic_sticky_keys_transformer.cpp
src/server/shell/basic_sticky_keys_transformer.h
src/server/shell/mouse_keys_transformer.cpp
src/server/shell/mouse_keys_transformer.h
src/server/symbols.map
tests/unit-tests/input/test_input_event_transformer.cpp
tests/unit-tests/shell/test_basic_accessibility_manager.cpp
tools/symbols_map_generator/main.py

Prerequisite to test `MouseKeysConfig` properly in #4071. 
In the aforementioned PR, I wanted to add tests for `miral::MouseKeyConfig`, which required that I implement a `MockMouseKeysTransformer`, which requires the definition of `Transformer`. That is defined in `input_event_transformer.h`. Unfortunately, since `InputEventTransformer` inherits from `Seat`, it also includes `seat.h`, which transitively includes headers that can't be included in miral. The solution was to split the definition of `Transformer` so that these headers are not included.

Move `InputEventTransformer::Transformer` into its own header

---

debian/libmiral7.symbols
examples/mir_demo_server/server_example.cpp
examples/miral-shell/shell_main.cpp
include/miral/miral/hover_click.h
src/miral/hover_click.cpp
src/miral/symbols.map
src/server/shell/basic_hover_click_transformer.cpp

1. Removes the old `HoverClick(bool)` constrcutor, replacing it with `enabled()` and `disabled()`
2. Adds a live config constructor, which adds the following options:
- hover_click_enable
- hover_click_hover_duration
- hover_click_cancel_displacement
- hover_click_reclick_displacement
3. Adds a comment that explains to users what hover click is
4. Fixed a bug where hover clicks would continuously be initiated regardless of whether the pointer moved `hover_click_reclick_displacement` pixels away or not
You can add the following options `~/.config/mir_demo_server.live-config`:
```
hover_click_enable=true
hover_click_hover_duration=3000
hover_click_cancel_displacement=100
hover_click_reclick_displacement=100
```
Hover click does not start dispatching clicks until the cursor first moves. …

Hover click cleanup

---

src/include/server/mir/scene/basic_surface.h
src/include/server/mir/scene/surface.h
src/miral/window_info.cpp
src/miral/window_info_internal.cpp
src/miral/window_info_internal.h
src/server/scene/basic_surface.cpp
src/server/symbols.map
tests/include/mir/test/doubles/stub_surface.h
tests/miral/window_info.cpp

The size constraints need to reflect the SSD margins
This was not possible as the Surface was responsible for the margins and the WindowInfo was responsible for the size constraints. So move the latter to the surface and fixup all around
Fixes: #4129

Fix window size constraints with ssd

---

src/include/server/mir/time/alarm_factory.h
src/server/CMakeLists.txt
src/server/input/key_repeat_dispatcher.cpp
src/server/shell/basic_mousekeys_transformer.cpp
src/server/symbols.map
src/server/time/CMakeLists.txt
src/server/time/alarm_factory.cpp

* Moves the repeating alarm code duplicated between `KeyRepeatDispatcher` and `BasicMouseKeysTransformer` to `time::AlarmFactory::create_repeating_alarm`.
* Adds a new module `mirservertime` at `src/server/time/` to house the implementation of `time::AlarmFactory::create_repeating_alarm`

Consolidate repeating alarm code

---

src/miral/window_info.cpp

We might calculate the `restore_rect()` before there is a surface asociated with the WindowInfo

Fix crash in miral-kiosk and Frame

---

doc/sphinx/.custom_wordlist.txt
doc/sphinx/tutorial/getting-started-with-mir.md

Updates `getting_started_with_mir.md` to mention shell component compatibility, nvidia support, and which Mir-related projects users could go to for a quick test.

doc: Update getting started tutorial to mention app compatibility, nvidia support, and other Mir based compositors

---

doc/sphinx/configuring-index.md
doc/sphinx/contributing-index.md
doc/sphinx/explanation/configuring-index.md
doc/sphinx/explanation/contributing-index.md
doc/sphinx/explanation/index.md
doc/sphinx/how-to/configuring-index.md
doc/sphinx/how-to/contributing-index.md
doc/sphinx/how-to/index.md
doc/sphinx/index.md
doc/sphinx/reference/configuring-index.md
doc/sphinx/reference/contributing-index.md
doc/sphinx/reference/index.md
doc/sphinx/tutorial/configuring-index.md
doc/sphinx/tutorial/contributing-index.md
doc/sphinx/tutorial/index.md

Leaves the main landing page for "consumers" of the Mir libraries.
Splits off content for:
1. Configuring compositors based on Mir
2. Contributing to Mir
The former is a handy reference for users of Ubuntu Frame, Miriway, miracle-wm, Lomiri _etc_

Split documentation by audience

---

src/platform/CMakeLists.txt
src/platform/graphics/CMakeLists.txt
tests/mir_test_doubles/CMakeLists.txt
tests/mir_test_framework/CMakeLists.txt

Fix problems reported on #miriway:matrix.org: someone packaging for openSUSE moves the header files for libinput and libdisplay-info

use-pkgconfig-better

---

src/platforms/atomic-kms/server/kms/quirks.cpp
src/platforms/eglstream-kms/server/platform_symbols.cpp
src/platforms/gbm-kms/server/kms/quirks.cpp

Check for `EGL_WL_bind_wayland_display` when probing EGLStream display platform

---

doc/sphinx/Doxyfile.in
include/platform/mir/input/input_sink.h
src/include/common/mir/events/xkb_modifiers.h
src/include/server/mir/default_server_configuration.h

This adds the internal headers to the Doxygen API docs build.
I had looked at trying to build this as a separate build to the public headers, but while the breathe extension supports multiple projects, the exhale extension we're using does not. It also [doesn't support Doxygen's grouping feature](https://exhale.readthedocs.io/en/latest/faq.html#my-documentation-is-setup-using-groups-how-can-i-use-exhale), so that is also not an option.
I also noticed a few errors in the build process that I've corrected too:
* add a bunch of `-I` arguments to help Doxygen parse headers with clang. As is, many files failed to parse on unknown `#include` directives.
* Update a couple of headers that were missing includes.

doc: include internal APIs in documentation

---

doc/sphinx/how-to/getting_involved_in_mir.md

- Uses tabs instead of separate sections for the "Install Dependencies"
- Wait for RTD to build
- Open "Getting Involved in Mir"
- Scroll down to "Getting Mir source and dependencies"
- You should see a tab group instead of three subsections

Use tabs instead of separate sections for "Install Dependencies"

---

spread/build/ubuntu/task.yaml

- #4225 failed to actually make use of the newer Rust
CI to pass the `ubuntu/rust` variant

spread: make Cargo find the right Rust

---

tools/mir-smoke-test-runner.sh

We can "smoke test" across all the platforms (depending on the runtime environment)

more-smoke-tests

---

src/common/mircommon.pc.in

This is needed in practice for building against mircommon, so declare it in the pkgconfig file so it is automatically set up as a dependency.

mircommon: Add xkbcommon to pkgconfig dependency

---

doc/sphinx/.readthedocs.yaml

- RTD should now build with changes inside `include/` and `src/`
- Commits with changes outside the specified directories should cancel RTD builds (they give a 404 page in that case)

Rtd build on src include changes

---

spread/build/fedora/task.yaml

DNF automatically refreshes repositories when repository configuration changes on the next transaction call (e.g. "dnf install"), so this is redundant and slows down the jobs unnecessarily.

spread/build/fedora: Drop unneeded "dnf update" call

---

src/miral/runner.cpp

Closes #???
Related: alternative to #4280
Printing help text isn't treated as an error
Run with `--help` and check return code

Exiting with text output is success

---

src/server/frontend_wayland/window_wl_surface_role.cpp

Fixes #4282
Avoid window management handling window changes if size didn't, actually, change.
Enable `--window-management-trace` and see that `handle_modify_window` doesn't run on every frame.
No testing harness yet.

wayland: avoid modify_window if size didn't change

---

src/miral/input_configuration.cpp

The options on mir_touchpad_scroll_mode match other options (no `_scroll` wart) and prior art (in Miriway)
This is exposed in mir_demo_server.live-config

Fix mir_touchpad_scroll_mode to match Miriway (and other options)

---

doc/sphinx/contributing/reference/continuous-integration.md

We have no way for the public to consume TICS, yet...
Doc builds

doc: drop reference to codecov

---

src/platforms/evdev-rs/platform_factory.cpp

Always return unsupported for the evdev-rs platform while it is in transit.

bugfix: make the evdev-rs platform unsupported for the time being

---

src/platform/options/default_configuration.cpp

This is intended to be used by projects that are built using Mir to generate their own documentation.
For example, if a project has a shell called `my-shell` they would generate this using:
```
$ my-shell --help-markdown > options.md.include
```
And then include that into their own documentation with:
```
Options for my-shell, which can be set on the command line, e.g. `--version`.
{include} options.md.include
```

Add a --help-markdown flag to generate documentation

---

src/platforms/gbm-kms/server/buffer_allocator.cpp
src/platforms/gbm-kms/server/kms/quirks.cpp
src/platforms/gbm-kms/server/kms/quirks.h

`gbm-kms` now also respects `gbm-surface-has-free-buffers` quirk, [like atomic-kms does](https://github.com/canonical/mir/blob/8ef4565d01324e8c5f81f9a14325d41d5e3c6918/src/platforms/atomic-kms/server/kms/quirks.cpp#L91-L95).
Fixes #4319
Run on Mali with `--driver-quirks gbm-surface-has-free-buffers:driver:<driver>:skip`

gbm-kms: bring free-buffers quirk over

---

CMakeLists.txt
examples/mir_demo_server/CMakeLists.txt
src/core/CMakeLists.txt
src/platforms/common/server/CMakeLists.txt
tests/CMakeLists.txt
tests/integration-tests/CMakeLists.txt
tests/mir_test_doubles/CMakeLists.txt
tests/mir_test_framework/CMakeLists.txt
tests/unit-tests/CMakeLists.txt
tests/window_management_tests/CMakeLists.txt

No longer used in Boost > 1.69
Disables Boost::System for Boost > 1.69
See: https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/N5O2U76SQS3VNIFEBCFGLW3IHVFT5Y7K/#Y5F4JM2OPE4KQ5B2EB7VBXKKUXXDS37H

Disable boost_system

---

src/miral/CMakeLists.txt

The cmake rules used to run `wayland-scanner` to generate source and headers for miral listed `${GENERATED_DIR}` as a dependency. As the output of the command is within this directory, it's timestamp will be updated as a side effect of the command.
So by the end of the build all the generate commands will be out of date w.r.t. their dependencies and will be rebuilt on the next run. This causes anything depending on those generated files to be rebuilt again too.
To fix this, I've removed the directory as a dependency and have each command ensure the directory exists before running `wayland-scanner`. I've also adjusted the commands so the final command moves the generated file to the final location.
Configure and build a mir source tree. Run `make` a second time and observe that nothing …

miral: don't make the generated files depend on ${GENERATED_DIR}

---

tools/mir-compositor-smoke-test.bash

If there's a matching file in the current directory shell expansion breaks the find command

Fix mir-compositor-smoke-test

---

tools/mir-smoke-test-runner.sh

If there's a Wayland session open on VT2 and this is run on VT4 the Wayland platform will hang waiting for the "host" to respond.
We detect we're not running on a host desktop
Leave a Wayland session open on VT2 and on VT4 (as the same user) run `mir-smoke-test-runner`

Don't try to run the hosted Wayland platform unless there's a current desktop

---

tests/miral/test_bounce_keys.cpp

Closes #4339 
Uses `std::atomic` to ensure a consistent view of state across threads
[BuildAndTest (lxd:fedora-42:spread/build/fedora:clang)](https://github.com/canonical/mir/actions/runs/18317300354/job/52160975204?pr=4340)

Try using std::atomic for thread synchronization
