canonical/mir

tests/mir_test_framework/async_server_runner.cpp
I'm suspicious that same issue (of potentially using/deleting buffers allocated by a graphics platform after the platform unloads) exists more generally, but this fixes the only known, reproducible, case.
=> Prevent the (stub-graphics) module being unloaded while a test is using it. (LP: #1728931)

examples/miral-shell/miral-desktop.sh
Ensure the user has a login session on the target VT
=> Check that user is logged into the VT before using it (LP: #1728574)

.travis.yml, bors.toml
Tell travis to build staging and trying branches, and tell bors to wait
on travis before pushing to master.
=> Set up bors.tech merge bot

src/protobuf/symbols.map
Export InternalSwap methods from libmirprotobuf (Fixes #39)
=> Export InternalSwap methods from libmirprotobuf (Fixes #39)

examples/server_example.cpp, tools/mir-smoke-test-runner.sh
Also fixes the mir_demo_server return code
=> Grab the "smoke tests" script from old CI

examples/miral-shell/floating_window_manager.cpp, src/miral/basic_window_manager.cpp
Check for titlebars when placing windows. (Fixes #37)
=> Check for titlebars when placing windows. (Fixes #37)

debian/changelog, examples/screencast.cpp, include/renderers/gl/mir/renderer/gl/texture_target.h, src/client/mir_screencast.cpp, src/platforms/common/server/shm_buffer.cpp, src/platforms/common/server/shm_buffer.h, src/platforms/mesa/server/gbm_buffer.cpp, src/platforms/mesa/server/gbm_buffer.h, src/renderers/gl/renderer.cpp, src/server/compositor/screencast_display_buffer.cpp, src/server/graphics/nested/buffer.cpp, tests/include/mir/test/doubles/stub_gl_buffer.h, tests/unit-tests/compositor/test_screencast_display_buffer.cpp
Enable screen capture to SHM buffers. (Fixes #47)
=> screencast

src/server/frontend/wayland/wayland_connector.cpp
Otherwise we might deadlock if the work item code also takes locks.
=> WaylandExecutor: Drop lock before calling work item.

src/miral/basic_window_manager.cpp, tests/miral/CMakeLists.txt, tests/miral/modify_window_specification.cpp
We must allow child windows to be divorced from their parents
=> divorce-from-parent

src/server/frontend/wayland/wayland_connector.cpp
Extracts functionality that is also needed to implement window management extensions such as xdg-shell
=> Extract WlMirSurface interface and WlAbstractMirSurface implementation (to be shared with xdg-shell support)

src/server/frontend/wayland/wayland_connector.cpp, src/server/frontend/wayland/wayland_connector.h
These will be needed for xdg-shell support.
=> Add stubs for DataDeviceManager & DataDevice.

src/server/frontend/wayland/CMakeLists.txt, src/server/frontend/wayland/basic_surface_event_sink.cpp, src/server/frontend/wayland/basic_surface_event_sink.h, src/server/frontend/wayland/null_event_sink.cpp, src/server/frontend/wayland/null_event_sink.h, src/server/frontend/wayland/wayland_connector.cpp, src/server/frontend/wayland/wayland_executor.cpp, src/server/frontend/wayland/wayland_executor.h, src/server/frontend/wayland/wlshmbuffer.cpp
Extract some bits from wayland_connector.cpp in the hope compilers don't choke on it.
=> split-wayland_connector.cpp

src/server/frontend/wayland/wayland_connector.cpp
[Wayland] accumulate window modifications until commit() is called.
(That's what the specification says should happen.)
=> modify-on-commit

src/server/input/surface_input_dispatcher.cpp, src/server/input/surface_input_dispatcher.h
=> Send motion events when the surface under the pointer moves

.travis.yml
Seems the images are back after all.
=> Bring back ubuntu-17.10 based CI

src/server/frontend_wayland/wl_pointer.cpp
(fixes hovering over GTK buttons looking broken)
=> added wl_frame event to pointer

src/server/frontend_wayland/xdg_shell_v6.cpp
We should be doing this (but it doesn't fix any symptoms I've noticed so far)
=> Use wayland calls from the correct thread

src/server/frontend_wayland/xdg_shell_v6.cpp
This incorporates the fix-180 branch, as that's pretty useful for testing this and is still up for review.
=> Fix menu placement in xdg-shell

src/server/frontend_wayland/CMakeLists.txt, src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/wayland_connector.h, src/server/frontend_wayland/wl_subcompositor.cpp, src/server/frontend_wayland/wl_subcompositor.h, src/server/frontend_wayland/wl_surface.h
Subsurfaces still don't appear, but at least they don't crash clients.
=> Subcompositor placeholder

src/include/platform/mir/options/default_configuration.h, src/platform/options/default_configuration.cpp
=> Revert "Merge #229"

src/server/frontend_wayland/CMakeLists.txt, src/server/frontend_wayland/double_buffered.h, src/server/frontend_wayland/wl_pointer.cpp, src/server/frontend_wayland/wl_surface.cpp, src/server/frontend_wayland/wl_surface.h, src/server/frontend_wayland/wl_touch.cpp, src/server/frontend_wayland/xdg_shell_v6.cpp
added DoubleBuffered<T> class and used it for WlSurface::buffer_offset
=> added DoubleBuffered<T>

src/server/frontend_wayland/wl_surface.cpp, src/server/frontend_wayland/wl_surface.h
Fixes a couple of things that were bugging me
=> Tidy WlSurface

debian/rules
Result of experiments to get builds working across 16.04, 17.10 and 18.04
=> debian-hacks-from-0.31

src/server/frontend_wayland/wl_subcompositor.cpp, src/server/frontend_wayland/wl_subcompositor.h, src/server/frontend_wayland/wl_surface.cpp, src/server/frontend_wayland/wl_surface.h, src/server/frontend_wayland/wl_surface_role.cpp, src/server/frontend_wayland/wl_surface_role.h
Fixed subsurface offset issue and sync behavior. Input coming soon!
=> Subcompositor fixes

.travis.yml
I'm Dominic from Travis CI.
Do you think you could merge this to see if we can connect to ppa.launchpad.net using `lftp`?
I'll open a bug report based on the result of this test.
Thanks!
=> Check if we can ftp to ppa.launchpad.net

src/server/frontend_wayland/wl_surface.cpp, src/server/frontend_wayland/wl_surface.h
=> stopped frame.done being called if frame has been destroyed

.travis.yml, spread/build/fedora/task.yaml, spread/build/ubuntu/task.yaml
This should speed us up even more as travis doesn't throttle non-sudo jobs.
=> [travis] don't require sudo and match devel/rawhide correctly

src/include/server/mir/frontend/event_sink.h, src/server/frontend/event_sender.cpp, src/server/frontend/event_sender.h, src/server/frontend_wayland/basic_surface_event_sink.cpp, src/server/frontend_wayland/basic_surface_event_sink.h, src/server/frontend_wayland/null_event_sink.cpp, src/server/frontend_wayland/null_event_sink.h, src/server/scene/application_session.cpp, src/server/scene/global_event_sender.cpp, src/server/scene/global_event_sender.h, src/server/scene/surface_event_source.cpp, tests/include/mir/test/doubles/mock_event_sink.h, tests/include/mir/test/doubles/null_event_sink.h, tests/integration-tests/test_buffer_scheduling.cpp, tests/mir_test_doubles/mock_event_sink_factory.cpp, tests/unit-tests/frontend/test_event_sender.cpp, tests/unit-tests/frontend/test_session_mediator.cpp, tests/unit-tests/scene/test_surface.cpp
This will allow me to simplify of how we handle synchronization of event hadling code.
=> switched event sink to accept unique pointers to events

examples/example-server-lib/decoration_provider.cpp
I accidentally approved a (presumably) accidental submodule change. this fixes that.
=> Submodule fix

src/server/frontend_wayland/wl_subcompositor.cpp, src/server/frontend_wayland/wl_subcompositor.h, src/server/frontend_wayland/wl_surface.cpp
Rare crash, but worth fixing none the less.
=> fixed crash when parents destroyed before children

src/server/frontend_wayland/wl_touch.cpp, src/server/frontend_wayland/wl_touch.h
Pretty simple, but completely untested (don't have a touchscreen running Linux on me). (Fixes #347)
=> implemented subsurface support for touches

src/server/display_server.cpp
Retry drmSetMaster() a few times and if it doesn't work die. (Fixes #373)
=> Retry loop for DRM master

.travis.yml
We have a full green run, let's keep it that way
=> [travis] require all targets to pass again

include/test/mir/test/event_factory.h, tests/mir_test/event_factory.cpp, tests/mir_test_framework/fake_input_device_impl.cpp
=> added *.with_event_time() to button and key events

src/platform/options/program_option.cpp
=> fix for boost 1.67

.travis.yml
It's an infrastructure issue of some kind, ignore failures while we investigate.
=> [travis] skip arm64 failures for now

src/miral/process_doxygen_xml.py, src/miral/symbols.map
The regenerate script got put of step with recent changes
=> Fix regenerate-miral-symbols-map

.travis.yml
=> [travis] drop 17.10 builds

debian/rules, spread.yaml
Also fix LXD systems in `spread.yaml`.
=> [debian] respect "nocheck" in DEB_BUILD_OPTIONS

src/protobuf/symbols.map
=> added MaybeMessage symbol to fix on protobuf v3.6.0

examples/miral-shell/spinner/miregl.cpp, src/miral/runner.cpp, src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/wl_keyboard.cpp, src/server/server.cpp
=> Revert "Merge #527"

src/miral/runner.cpp, src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/wl_keyboard.cpp, src/server/server.cpp
This re-applies those changes from #527 that don't contribute to #540
=> Fix some leaky and unused memory allocations reported by AddressSanitizer

src/platforms/mesa/server/kms/real_kms_output.cpp, tests/unit-tests/platforms/mesa/kms/test_real_kms_output.cpp
Now that we support logind we can lose modesetting rights (ie: DRM master)
asynchronously, should logind decide to revoke our master.
logind may do that while session-switching; in which case, there's something
else to handle the CRTC, and we shouldn't kill Mir (but logging is fine).
=> mesa-kms: EPERM or EACCES in clear_crtc() should be non-fatal.

examples/miral-kiosk/kiosk_main.cpp, examples/miral-shell/miral-app.sh, examples/miral-shell/miral-desktop.sh, examples/miral-shell/shell_main.cpp
Removed obsolete support for running on Unity8 & allow supplied command-line options to override script
=> Cleaner launch scripts for demos

CMakeLists.txt, cmake/MirCommon.cmake
Use the more modern method of specifying standard in CMake
=> Fix C++ std used on Arch

src/platforms/evdev/platform.h, tests/include/mir/test/doubles/stub_console_services.h, tests/mir_test_framework/main.cpp
Is the order of includes important for you?
=> Add missing includes when compiling with Musl

doc/getting_involved_in_mir.md
Add missing packages to Fedora documentation
=> Add missing packages to Fedora documentation

examples/miral-shell/miral-app.sh, examples/miral-shell/miral-desktop.sh, examples/miral-shell/miral-run.sh, examples/miral-shell/miral-screencast.sh, examples/miral-shell/miral-xrun.sh
Bash is not always in /bin, so use env to find it from $PATH
(One of the Musl build issues.)
=> Find bash using env

src/server/frontend_wayland/layer_shell_v1.cpp, src/server/frontend_wayland/xdg_shell_stable.cpp
Not much to see here, should not change any behavior.
=> Minor XDG shell and layer shell cleanup

tests/unit-tests/platforms/eglstream-kms/server/test_threaded_drm_event_handler.cpp
We were interleaving calls to EXPECT_CALL(…, drmHandleEvent) with calls to drmHandleEvent *in a different thread*, which really just makes you wonder how it worked at all.
=> ThreadedDRMEventHandlerTest: Make ThreadSanitizer happy.

tests/unit-tests/shared_library_test.cpp
Update test expectations to work on musl libc
=> musl-tests

guides/cppguide.xml
Document new style function declarations. (Fixes #722)
=> Document new style function declarations

src/server/frontend_wayland/wl_subcompositor.cpp
Related to #345 but does __not__ fix it
=> Warn when getting unsupported subsurface requests

src/common/logging/dumb_console_logger.cpp
Even the length of the severity tags and HIGHLIGHT problems.
=> Tidy up tags in default logger

src/platforms/mesa/server/display_helpers.cpp, src/platforms/mesa/server/kms/platform_symbols.cpp
Setting MIR_MESA_KMS_DISABLE_MODESET_PROBE overrides drmCheckModesettingSupported() ENOSYS result.
Needed to work with the libdrm on pmOS, maybe others.
=> Setting MIR_MESA_KMS_DISABLE_MODESET_PROBE overrides drmCheckModesettingSupported() ENOSYS result

.travis.yml
=> Revert "Workaround rawhide "Error: GPG check FAILED""

src/wayland/generated/wayland_wrapper.cpp, src/wayland/generated/wayland_wrapper.h, src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.cpp, src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.h, src/wayland/generated/xdg-shell-unstable-v6_wrapper.cpp, src/wayland/generated/xdg-shell-unstable-v6_wrapper.h, src/wayland/generated/xdg-shell_wrapper.cpp, src/wayland/generated/xdg-shell_wrapper.h, src/wayland/generator/interface.cpp
=> Expose interface names in generated code

debian/libmiral3.symbols, examples/mir_demo_server/server_example.cpp, include/miral/miral/wayland_extensions.h, src/miral/symbols.map, src/miral/wayland_extensions.cpp, src/platform/options/default_configuration.cpp, tests/miral/wayland_extensions.cpp
Make it easier for servers to set defaults for configuring Wayland extensions
=> Configure Wayland extensions

tests/acceptance-tests/wayland/miral_integration.cpp
Match wlcs API update. (Fixes #781)
=> Match wlcs API update

.travis.yml, spread.yaml, src/server/console/minimal_console_services.cpp
Fix CI failures on Fedora. (Fixes: #809)
=> fix-fedora-builds

include/server/mir/frontend/buffer_stream.h, include/server/mir/frontend/surface.h, src/include/server/mir/compositor/buffer_stream.h, src/server/compositor/multi_monitor_arbiter.cpp, src/server/compositor/multi_monitor_arbiter.h, src/server/frontend_wayland/wl_pointer.cpp, src/server/scene/basic_surface.h
Just some formatting and the removal of an unused function. I've had these things sitting around for a while so I might as well PR them now.
=> Harmless formatting

tests/mir_test_framework/open_wrapper.cpp
With `std::list`, Mir unit tests segfaults with the following stack trace. Don't have enough motivation at the moment (or enough understanding of `std::list`) to figure out why. It seems likely there is a root cause I haven't actually addressed, so if you have ideas on what it may be or how to debug it, I'm all ears.
```
GNU gdb (Ubuntu 8.2.91.20190405-0ubuntu3) 8.2.91.20190405-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug …
```
=> Fix Mir unit tests

CMakeLists.txt, src/server/console/CMakeLists.txt, src/server/console/minimal_console_services.cpp
=> Use drmIsMaster() from libdrm when it is provided

examples/example-server-lib/floating_window_manager.cpp, examples/example-server-lib/floating_window_manager.h
Simplify FloatingWindowManager example using new MinimalWindowManager. (Fixes #816)
=> Simplify FloatingWindowManager example using new MinimalWindowManager

examples/example-server-lib/decoration_provider.cpp
Improve miral shell help text rendering. (Fixes #799)
=> Improve miral shell help text rendering (Fixes #799)

src/server/frontend_wayland/layer_shell_v1.cpp, src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/window_wl_surface_role.cpp, src/server/frontend_wayland/window_wl_surface_role.h, src/server/frontend_wayland/wl_surface_event_sink.cpp, src/server/frontend_wayland/wl_surface_event_sink.h, src/server/frontend_wayland/xdg_shell_stable.cpp, src/server/frontend_wayland/xdg_shell_v6.cpp, src/server/frontend_xwayland/xwayland_wm_shellsurface.h
This whole area has been a mess for quite a while, and this PR does not attempt to fix that mess. I do hope it is seen as an improvement, as well as fixing #836.
=> Better handle window role state changes (fixes #836)

.travis.yml, spread.yaml
Fix publishing to supported series
=> Fix publishing to supported series

src/server/frontend_wayland/wayland_executor.cpp
This would appear to be a fairly minor optimisation, as the Wayland thread
was going to dispatch the Executor (and hence perform this work) before
going to sleep anyway.
However, because Wayland events are processed in-order, getting them
in the stream *now*, rather than after the rest of the events are processed/
sent, can make a reasonable difference in client behaviour.
=> WaylandExecutor: Eagerly execute work when on Wayland thread.

.travis.yml
=> Restore Fedora rawhide to being a required CI target

tools/process_snaps.py
There's new API that's required for new snapcraft behaviour to be available.
=> [tools] fix process_snaps.py requesting builds

src/miral/internal_client.cpp
[miral] Handle exceptions propagating from InternalClient code.
=> [miral] Handle exceptions propagating from InternalClient code

src/server/graphics/nested/buffer.cpp
We're not allowed to destroy the `EGLClientBuffer` until all of the associated images are destroy by `eglDestroyImageKHR()`.
On arm/android the buffer was destroyed before all the images were destroyed, it isn't obvious why but simplifying the code as proposed seems to fix this.
=> [nested] Make sure we destroy eglImage before class gets destructed

src/server/frontend_wayland/output_manager.cpp
All that's added is a release request, which we don't have to respond to.
=> Bump wl_output version 2 -> 3

examples/miral-shell/miral-app.sh, examples/miral-shell/miral-desktop.sh
Automatically enable mirclient if we set configure any toolkit to use it.
Mostly to simplify testing on 16.04
=> [miral-app] Automatically enable mirclient if we configure any toolkit to use it

.travis.yml, spread.yaml
Drop 18.10 it's out of support.
=> Drop 18.10 it's out of support

src/server/frontend_wayland/layer_shell_v1.cpp, src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/window_wl_surface_role.h, src/server/frontend_wayland/wl_surface_event_sink.cpp, src/server/frontend_wayland/xdg_shell_stable.cpp, src/server/frontend_wayland/xdg_shell_stable.h, src/server/frontend_wayland/xdg_shell_v6.cpp, src/server/frontend_xwayland/xwayland_wm_shellsurface.cpp, src/server/frontend_xwayland/xwayland_wm_shellsurface.h, src/server/frontend_xwayland/xwayland_wm_surface.cpp, src/server/frontend_xwayland/xwayland_wm_surface.h
Fixes #946; will be tested by wlr-foreign-toplevel-management WLCS tests once they land
=> Wayland frontend: handle mir_event_type_close_window

src/server/input/surface_input_dispatcher.cpp
Drive-by modernization of code
=> Prefer lambdas to std::bind()

src/server/frontend_wayland/layer_shell_v1.cpp, src/server/frontend_wayland/layer_shell_v1.h, src/server/frontend_wayland/wayland_default_configuration.cpp
Tested using GDB, and appears to work. Fixes #963
=> Add LayerShellV1::get_window()

include/server/mir/shell/surface_specification.h, src/server/scene/surface_creation_parameters.cpp, src/server/shell/surface_specification.cpp
If we're going to have a comparison operator, we might as well do it right
=> Add missing checks to SurfaceCreationParameters' == operator

doc/mainpage.md
Hopefully this, along with some other website changes, will result in fewer people being unable to find a forum to ask us questions! (cf: issue #972)
=> doc: Mention our community resources

examples/example-server-lib/wayland_helpers.cpp, examples/mirclient/wayland_client.c
Confined snaps only have access to "/dev/shm" via the "mir" interface and we want to deprecate that.
Wayland based toolkits typically use $XDG_RUNTIME_DIR to open shm pools, so we try that before "/dev/shm".
A confined snap that frigs with $XDG_RUNTIME_DIR (as we do for servers) will fail there and in "/dev/shm" so we try "/tmp" if both of the above fail.
Another way allocating a shm file can fail is on old kernels (as used on the current UBports phones), so while touching this code I've copied the workaround seen here:
https://github.com/MirServer/mir/blob/master/src/core/anonymous_shm_file.cpp#L54
=> Update shared memory handling to work both in confined snaps and on pre-3.11 kernels

src/server/scene/basic_surface.cpp
We don't need three names for locks in the same file. Follow up PR will fix some potential issues, but this was bothering me.
=> BasicSurface: rename all instances of lg and lk with lock

src/server/scene/basic_surface.cpp, src/server/scene/basic_surface.h
Make mutex locking in `scene::BasicSurface` more consistent and correct
=> BasicSurface safety

src/miral/basic_window_manager.cpp, tests/miral/output_updates.cpp
=> Move maximized windows when output is unplugged

src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/wl_keyboard.cpp, src/server/frontend_wayland/wl_keyboard.h, src/server/frontend_wayland/wl_seat.cpp, src/server/frontend_wayland/wl_seat.h
Resync keyboard state after server is paused. (Fixes: #999)
=> Resync keyboard state after server is paused

include/server/mir/frontend/surface.h, include/server/mir/scene/surface.h, include/test/mir/test/doubles/stub_surface.h, src/server/frontend/session_mediator.cpp, src/server/frontend_wayland/window_wl_surface_role.cpp, src/server/scene/basic_surface.cpp, src/server/scene/basic_surface.h, tests/include/mir/test/doubles/stub_scene_surface.h, tests/mir_test_framework/stub_surface.cpp, tests/unit-tests/scene/test_basic_surface.cpp
=> Rename frontend::Surface::client_size() -> content_size()

include/core/mir/geometry/dimensions.h
More missing geometry operators. More needs to be done (I'm hoping to completely remove displacements, see #1064), but this helps.
=> Add width and height operators

tests/CMakeLists.txt, tests/platform_test_harness/CMakeLists.txt, tests/platform_test_harness/graphics_platform_test_harness.cpp
This is approximately the simplest possible thing, with plenty of scope for cleanup and augmentation, but it's useful enough!
=> tests: Add basic manual platform test harness

CMakeLists.txt, src/platforms/wayland/cursor.cpp, src/platforms/wayland/cursor.h, src/platforms/wayland/displayclient.cpp
Fix failure to build Wayland platform on 16.04
=> Fix failure to build Wayland platform on 16.04

src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/wayland_connector.h, src/server/frontend_wayland/wayland_default_configuration.cpp, tools/mir-smoke-test-runner.sh
=> Fix smoke tests

src/platforms/wayland/platform_symbols.cpp, src/platforms/wayland/wayland_display.cpp, src/platforms/wayland/wayland_display.h, tests/platform_test_harness/graphics_platform_test_harness.cpp
Make the platform test and the wayland platform play nice
=> fix-wayland-platform-test

src/platforms/wayland/display.cpp, src/platforms/wayland/display.h, src/platforms/wayland/input.cpp
[wayland-platform] Only report input supported when it will work. (Fixes: #1104)
=> [wayland-platform] Only report input supported when it will work

include/server/mir/scene/surface.h, include/test/mir/test/doubles/stub_surface.h, src/miral/window.cpp, src/server/frontend/basic_mir_client_session.cpp, src/server/scene/basic_surface.cpp, src/server/scene/basic_surface.h, src/server/scene/surface_event_source.cpp, src/server/shell/system_compositor_window_manager.cpp, src/server/shell/window_management_info.cpp, tests/acceptance-tests/test_surface_placement.cpp, tests/include/mir/test/doubles/stub_scene_surface.h, tests/mir_test_framework/canonical_window_manager.cpp, tests/mir_test_framework/stub_surface.cpp, tests/miral/test_window_manager_tools.cpp, tests/unit-tests/scene/test_basic_surface.cpp, tests/unit-tests/scene/test_surface.cpp, tests/unit-tests/scene/test_surface_impl.cpp
This makes things more explicit as we prepare for server side decorations
=> Rename surface->size() to surface->window_size()

src/server/scene/basic_surface.cpp, src/wayland/wayland_base.cpp
We should stop accepting "commit" and disconnect if a surface has gone.
=> fix-1106-more

src/miral/x11_support.cpp, src/server/frontend_xwayland/xwayland_connector.cpp, src/server/frontend_xwayland/xwayland_connector.h, src/server/frontend_xwayland/xwayland_default_configuration.cpp, src/server/frontend_xwayland/xwayland_server.cpp, src/server/frontend_xwayland/xwayland_server.h
Drop some code used in early testing.
Add a configuration option to specify the Xwayland executable.
=> x11 tweaks

src/server/shell/decoration/renderer.cpp
=> SSD: Redraw titlebar when buttons move

src/server/shell/decoration/basic_decoration.cpp, src/server/shell/decoration/renderer.cpp, src/server/shell/decoration/renderer.h, src/server/shell/decoration/window.h
Programmatically draws close, minimize and maximize icons. They should look like so:
=> Draw SSD titlebar button icons

src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/wayland_connector.h
Remove unused function (that cannot be used safely).
=> Remove unused function

include/server/mir/frontend/surface_stack.h, src/include/server/mir/default_server_configuration.h, src/server/scene/default_configuration.cpp, src/server/scene/surface_stack.h, src/server/symbols.map
=> Add frontend::SurfaceStack

src/server/frontend_xwayland/xwayland_server.cpp, src/server/frontend_xwayland/xwayland_server.h
A pass at tidying XWaylandServer:
o Reducing scope of stuff
o Avoiding indirect recursion
o Simplify threading
o Initialize on creation & make const
=> [X11 frontend] A pass at tidying XWaylandServer

src/server/shell/decoration/input.cpp, src/server/shell/decoration/input.h, tests/unit-tests/shell/test_decoration_basic_decoration.cpp
Fixes #1167 Double click ssd maximize
=> Maximize/restore windows with SSDs on titlebar double click

src/server/frontend_xwayland/xwayland_server.cpp, src/server/frontend_xwayland/xwayland_server.h
Threadsafe XwaylandServer.
Protects the mutable state with a mutex and simplifies formerly racy logic.
=> Threadsafe XwaylandServer

src/server/frontend_xwayland/xwayland_server.cpp, src/server/frontend_xwayland/xwayland_wm.cpp, src/server/frontend_xwayland/xwayland_wm.h
More initialize-on-construction, constification and other tidying
=> X11: Tidy XWaylandWM

src/server/frontend_wayland/wayland_surface_observer.cpp, src/server/frontend_wayland/wayland_surface_observer.h, src/server/frontend_wayland/wl_keyboard.cpp, src/server/frontend_wayland/wl_keyboard.h
I believe this is not related to #997, but it is a possibility
=> Remove dead Wayland keymap code

src/server/frontend_xwayland/xwayland_wm.cpp, src/server/frontend_xwayland/xwayland_wm.h, src/server/frontend_xwayland/xwayland_wm_shellsurface.h, src/server/frontend_xwayland/xwayland_wm_surface.cpp
=> Drop unused headers

include/miral/miral/window_specification.h, src/miral/basic_window_manager.cpp, tests/miral/popup_window_placement.cpp, tests/miral/test_window_manager_tools.cpp
This corrects popup placement for server side decorated surfaces
=> BasicWindowManager: Place popup's relative to content

src/server/frontend_xwayland/xwayland_log.h, src/server/frontend_xwayland/xwayland_server.cpp, src/server/frontend_xwayland/xwayland_wm.cpp, src/server/frontend_xwayland/xwayland_wm.h, src/server/frontend_xwayland/xwayland_wm_shellsurface.cpp, src/server/frontend_xwayland/xwayland_wm_surface.cpp
Improvements to the verbose logs generated by the XWayland frontend. Probably not interesting to anyone but me, but merging will make maintaining my branches simpler.
=> XWayland: improve verbose logging

src/server/frontend_xwayland/xwayland_server.cpp
Better execl arguments when executing Xwayland.
Fixes the results from ps etc.
=> Better execl arguments when executing Xwayland

.travis.yml, spread.yaml
Drop 19.04 builds - it has gone.
=> Drop 19.04 builds

src/miral/launch_app.cpp
Don't advertise mirclient support to GDK
=> Don't advertise mirclient support to GDK

cmake/FindGtestGmock.cmake
Correct logic to locate gmock when gtest has package configuration. (Fixes: #1228)
=> Correct logic to locate gmock when gtest has package configuration

include/miral/miral/application_info.h, include/miral/miral/deprecations.h, include/miral/miral/internal_client.h, include/miral/miral/window_info.h, include/miral/miral/window_manager_tools.h, src/miral/CMakeLists.txt, tests/miral/CMakeLists.txt
=> Deprecate obsolete miral APIs

.travis.yml
[travis] Merge `matrix` into `jobs` (Maybe fixes: #1230)
I'm guessing what the new travis config validation errors mean. If this works, then it's the answer. ;)
=> [travis] Merge `matrix` into `jobs`

src/server/frontend_xwayland/xcb_connection.cpp, src/server/frontend_xwayland/xwayland_wm.cpp
Improves some debugging and error messages, and fixes a bug related to data buffer length. I was assuming `xcb_get_property_value_length()` was in elements, when it is actually in bytes. This bug was exposed as soon as I tried to read a 32-bit window property.
=> XWayland: debug messages and data length bug

src/server/frontend_xwayland/xcb_connection.cpp, src/server/frontend_xwayland/xcb_connection.h, src/server/frontend_xwayland/xwayland_surface.cpp
=> Politely ask XWayland clients to close

src/server/frontend_xwayland/xcb_connection.cpp, src/server/frontend_xwayland/xcb_connection.h, src/server/frontend_xwayland/xwayland_surface.cpp, src/server/frontend_xwayland/xwayland_surface.h, src/server/frontend_xwayland/xwayland_wm.h, src/server/frontend_xwayland/xwayland_wm_shell.cpp, src/server/frontend_xwayland/xwayland_wm_shell.h
Drop some dead code and turn some defines into an enum
=> More cleanup

examples/miral-shell/spinner/miregl.cpp, include/platform/mir/graphics/buffer_id.h, src/client/error_buffer.cpp, src/client/error_buffer.h, src/client/error_render_surface.cpp, src/client/error_render_surface.h, src/client/error_stream.cpp, src/client/error_stream.h, src/common/events/input_event.cpp, src/common/events/touch_event.cpp, src/include/common/mir/client_visible_error.h, src/include/cookie/mir/cookie/blob.h, src/include/server/mir/frontend/connector.h, src/include/server/mir/frontend/shell.h, src/miral/external_client.cpp, src/platform/udev/udev_wrapper.cpp, src/platforms/common/server/kms-utils/drm_mode_resources.h, src/platforms/common/server/kms-utils/kms_connector.cpp, src/platforms/evdev/fd_store.cpp, src/platforms/evdev/fd_store.h, src/server/frontend_xwayland/xcb_connection.h, src/server/shell/decoration/window.h, src/server/shell/persistent_surface_store.cpp, tests/include/mir/test/doubles/stub_buffer.h, tests/mir_test_doubles/stub_display_configuration.cpp
Fix FTBFS with g++-10. (Fixes: #1259)
=> Fix FTBFS with g++-10

examples/mir_demo_server/server_example.cpp, examples/miral-shell/miral-app.sh, src/miral/x11_support.cpp
[X11] add --x11-displayfd option.
File descriptor to write X11 DISPLAY number to when ready to connect.
=> [X11] add --x11-displayfd option

src/server/frontend_xwayland/xwayland_surface.cpp, src/server/frontend_xwayland/xwayland_surface.h, src/server/frontend_xwayland/xwayland_wm.cpp
Also verbose logs all initial window properties
=> Process transient_for property in a function

src/server/frontend_wayland/wayland_connector.cpp
Don't destroy objects we don't own. (Fixes #1276)
=> [Wayland] Don't destroy objects we don't own

examples/miral-shell/miral-app.sh, src/miral/external_client.cpp, src/miral/launch_app.cpp, src/miral/launch_app.h, tests/miral/CMakeLists.txt, tests/miral/external_client.cpp
Make app launch environment configurable. (Fixes: #1268)
=> [miral] Make app launch environment configurable

tests/miral/external_client.cpp
=> Fix for LP builds

tests/miral/external_client.cpp
=> fix-lp-ftbfs

src/server/frontend_xwayland/xwayland_surface.cpp
AFAIK this wasn't causing any problems, but best not to prod complex external components under lock.
=> Don't make shell requests under lock

src/miral/launch_app.cpp
Strip out any MIR_* environment variables when launching apps
These can cause annoyance when launching Mir compositors (such as tests) from a Mir Shell.
=> Strip out any MIR_* environment variables when launching apps

src/server/frontend_xwayland/xcb_connection.cpp, src/server/frontend_xwayland/xcb_connection.h, src/server/frontend_xwayland/xwayland_surface.cpp
=> Tell XWayland about stacking order

include/platform/mir/graphics/cursor.h, include/test/mir/test/doubles/stub_cursor.h, src/platforms/mesa/server/kms/cursor.cpp, src/platforms/mesa/server/kms/cursor.h, src/platforms/wayland/cursor.cpp, src/platforms/wayland/cursor.h, src/server/graphics/default_configuration.cpp, src/server/graphics/null_cursor.h, src/server/graphics/software_cursor.cpp, src/server/graphics/software_cursor.h, tests/unit-tests/graphics/test_software_cursor.cpp, tests/unit-tests/platforms/mesa/kms/test_cursor.cpp
=> Safely show and hide software cursor

src/server/graphics/default_display_configuration_policy.cpp, tests/unit-tests/graphics/test_default_display_configuration_policy.cpp
Fix sidebyside display config for scaled outputs
=> Fix sidebyside display config for scaled outputs

src/platforms/wayland/displayclient.cpp
[Mir-on-Wayland] Tell the host we've scaled our surfaces
=> [Mir-on-Wayland] Tell the host we've scaled our surfaces

doc/getting_involved_in_mir.md
Update Fedora build instructions. (Fixes: #1384)
=> Update Fedora build instructions

cmake/FindGtestGmock.cmake
Fix FTBFS with Fedora packaging of gmock 1.10. (Fixes: #1382)
=> Fix FTBFS with Fedora packaging of gmock 1.10

debian/mir-demos.install, examples/miral-shell/CMakeLists.txt, examples/miral-shell/miral-app.sh, examples/miral-shell/miral-terminal.sh, examples/miral-shell/shell_main.cpp
(Almost) universal terminal launcher. (Fixes: #1387)
=> (Almost) universal terminal launcher

examples/example-server-lib/decoration_provider.cpp, examples/example-server-lib/wayland_helpers.cpp, examples/example-server-lib/wayland_helpers.h
Renders the example background at high resolution on scaled outputs (currently it is correctly scaled but blurry)
=> Example background HiDPI

tests/unit-tests/compositor/test_stream.cpp, tests/unit-tests/gl/CMakeLists.txt, tests/unit-tests/gl/test_tessellation_helpers.cpp
Tests renderable tessellation and stream scaling
=> HiDPI related tests

examples/miral-shell/miral-terminal.sh
Check that gdbus has "wait" before using it. (Fixes: #1413)
=> Check that gdbus has "wait" before using it

tests/miral/external_client.cpp
#1397 broke PPA builds, this should fix it
=> Fix FTBFS in PPA

include/common/mir/dispatch/threaded_dispatcher.h
=> Use const where possible

src/miral/static_display_config.cpp
[miral] Add scale support to DisplayConfiguration. (Fixes: #1423)
=> [miral] Add scale support to DisplayConfiguration

examples/miral-shell/desktop/mir-shell.sh
[mir-shell] Get the user keymap from gsetting.
=> [mir-shell] Get the user keymap from gsetting

src/wayland/generated/wayland_wrapper.cpp, src/wayland/generated/wayland_wrapper.h, src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.cpp, src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.h, src/wayland/generated/xdg-output-unstable-v1_wrapper.cpp, src/wayland/generated/xdg-output-unstable-v1_wrapper.h, src/wayland/generated/xdg-shell-unstable-v6_wrapper.cpp, src/wayland/generated/xdg-shell-unstable-v6_wrapper.h, src/wayland/generated/xdg-shell_wrapper.cpp, src/wayland/generated/xdg-shell_wrapper.h, src/wayland/generator/interface.cpp, src/wayland/generator/interface.h
This reverts commit d7d9ffc65e0d9c8f342f6b027e45f4f0a4266299, reversing
changes made to cc924a3b12e443504ce682d8062824f588df245a.
Fixes #1445
=> Revert "Merge #1439"

.travis.yml, spread.yaml
=> Add 20.04 to PPA uploads

src/server/frontend_xwayland/xwayland_wm.cpp, src/server/frontend_xwayland/xwayland_wm.h
Make things const and all that good stuff. Stacked on #1453
=> More XWaylandWM cleanup

src/server/shell/decoration/basic_decoration.cpp, src/server/shell/decoration/threadsafe_access.h
=> Initialize BasicDecoration in a threadsafe way

src/server/frontend_xwayland/xcb_connection.cpp, src/server/frontend_xwayland/xcb_connection.h, src/server/frontend_xwayland/xwayland_server.cpp, src/server/frontend_xwayland/xwayland_server.h, src/server/frontend_xwayland/xwayland_wm.cpp, src/server/frontend_xwayland/xwayland_wm.h
Stacked on #1474. No rush. Let that merge first. I just don't want to forget that I'm planning to PR this branch.
=> Use Mir fds

tests/unit-tests/graphics/test_display_configuration.cpp
=> Add missing GMock include for EXPECT_THAT

src/miral/cursor_theme.cpp
Add missing include. (Fixes: #1506)
=> Add missing include

src/server/frontend_xwayland/xwayland_server.cpp
This auto-restart functionality is complicated and mostly useless. We can do without it.
=> Don't try to start XWayland multiple times if it fails

src/miral/display_configuration_option.cpp, src/miral/external_client.cpp, src/miral/runner.cpp
Missing headers. (Fixes: #1546)
=> Missing headers

debian/control
Fix package dependencies.
The X11 platform is not Mesa-X11.
=> Fix package dependencies

debian/mir-demos.install, examples/miral-kiosk/CMakeLists.txt, examples/miral-kiosk/fake-mir-kiosk.sh
Add a "fake-mir-kiosk" script to assist snap development.
We'll update the forum docs after this gets released.
=> Add a "fake-mir-kiosk" script to assist snap development

src/server/input/key_repeat_dispatcher.cpp, tests/acceptance-tests/test_client_input.cpp
[input] Don't auto repeat meta keys. (Fixes: #1598)
=> [input] Don't auto repeat meta keys

.travis.yml, spread.yaml
Drop support for 19.10.
It's at EOL
=> Drop support for 19.10

src/server/frontend_xwayland/xwayland_connector.cpp, src/server/frontend_xwayland/xwayland_server.cpp
Better diagnostics when Xwayland can't be found or executed. (Fixes: #1604)
=> Better diagnostics when Xwayland can't be found or executed

src/server/frontend_wayland/wl_keyboard.cpp
[wayland] don't send/apply input events after rebuilding state. (Fixes: #1607)
=> [wayland] don't send/apply input events after rebuilding state

.travis.yml
=> [travis] fix USN checks (Fixes #1622)

src/platforms/eglstream-kms/server/egl_output.cpp
Since we try to restore it on shutdown we should probably save it on startup!
Fixes: #1466
=> eglstream-kms: Actually save CRTC on startup

tests/performance-tests/system_performance_test.cpp
=> performance-tests: Hacky fix for MIR_SERVER_LOGGING

src/server/frontend_xwayland/xwayland_surface.cpp, src/server/frontend_xwayland/xwayland_surface.h
=> Respect initial window state

src/platforms/x11/input/input_platform.cpp, tests/include/mir/test/doubles/mock_x11.h, tests/mir_test_doubles/mock_x11.cpp, tests/unit-tests/input/test_x11_platform.cpp
=> X11 input platform: ignore key repeats

src/server/frontend_xwayland/xwayland_surface.cpp, src/server/frontend_xwayland/xwayland_surface.h, src/server/shell/abstract_shell.cpp
Process some of the X11 window types and rework the logic to identify parents. (Fixes: #1665)
=> [X11] Better handling of popups and menus

include/test/mir_test_framework/main.h, tests/mir_test_framework/command_line_server_configuration.cpp, tests/performance-tests/test_glmark2-es2.cpp
=> Nested performance (again)

benchmarks/frame-uniformity/CMakeLists.txt, tests/unit-tests/CMakeLists.txt
=> Fix FTBFS without gbm-kms

src/platforms/gbm-kms/server/linux_dmabuf.cpp
Fix "error: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘const int’"
=> Fix PPA build

src/server/run_mir.cpp
If Mir is started via `nohup` do not install a SIGHUP handler.
=> Respect `nohup` handing of SIGHUP

include/platform/mir/graphics/egl_extensions.h, src/server/frontend_xwayland/xwayland_surface.cpp
Fix Rawhide FTBFS. (Fixes: #1743, Fixes: #1746)
=> Fix Rawhide FTBFS

src/miral/basic_window_manager.cpp
This is slightly more efficient and removes duplicated logic. Let me know if there's a better way to do this (my STL knowledge is hit-and-miss).
=> advise_output_delete(): better utilize STL

include/platform/mir/graphics/display_configuration.h, src/platform/graphics/display_configuration.cpp, src/platforms/x11/graphics/display_configuration.cpp, src/server/graphics/offscreen/display_configuration.cpp, tests/mir_test/display_config_matchers.cpp, tests/mir_test_doubles/stub_display_configuration.cpp, tests/miral/test_window_manager_tools.cpp, tests/miral/test_window_manager_tools.h, tests/unit-tests/graphics/test_default_display_configuration_policy.cpp, tests/unit-tests/graphics/test_display_configuration.cpp, tests/unit-tests/graphics/test_overlapping_output_grouping.cpp, tests/unit-tests/platforms/gbm-kms/kms/test_cursor.cpp, tests/unit-tests/platforms/gbm-kms/kms/test_display_configuration.cpp
This is the first step towards display walls. Window manager support and tests will come next.
=> Logical output groups

src/platforms/wayland/cursor.cpp, src/platforms/wayland/cursor.h, src/platforms/wayland/display.cpp, src/platforms/wayland/display.h, src/platforms/wayland/displayclient.cpp
=> wl_display_roundtrip() must be called on the Wayland thread

.travis.yml, CMakeLists.txt, spread.yaml, spread/build/sbuild/task.yaml, tools/process_snaps.py
We no longer need 18.04 and 20.10 has been released
=> Update Ubuntu series

examples/miral-shell/miral-app.sh
Avoid a racy startup, give better diagnostics on failure, tidy up help options
=> [miral-app] more robust launcher script

examples/mir_demo_server/server_example_test_client.cpp
And, if they don't, issue a "warning".
=> Allow a longer timeout (up to 10s) for clients to exit

.github/workflows/spread.yml, bors.toml
Now that Travis isn't throttling us, this should be enough.
=> [bors] reduce timeout to 30 minutes and fix bors

tests/unit-tests/dispatch/test_threaded_dispatcher.cpp
Rewrite declaration do do what the compiler now wants.
Fixes: #1834
=> Fix FTBFS on Hirsute

.github/workflows/snaps.yml
---
This shows it working: https://github.com/MirServer/mir/runs/1509462025
=> Review edge

.github/workflows/spread.yml
It has to be a boolean, empty doesn't cut it.
=> [gha] fix `allow-fail` default value

.github/workflows/ppa-upload.yml
---
This simulates a master push: https://github.com/MirServer/mir/actions/runs/408292731
=> [gha] use org-wide GPG secret

src/server/frontend_wayland/wayland_connector.cpp
Better error message, (Fixes: #1851)
=> Better error message

include/core/mir/abnormal_exit.h, src/include/server/mir/report_exception.h, src/platform/options/default_configuration.cpp, src/server/report_exception.cpp
=> Print help text to stdout instead of stderr

tests/unit-tests/CMakeLists.txt, tests/unit-tests/test_report_exception.cpp
=> Test report_exception()

src/miral/CMakeLists.txt
Fix FTBFS on s390x. ("Borrowed" code gets a benign compiler warning)
https://bugs.launchpad.net/ubuntu/+source/mir/+bug/1889166
=> Fix FTBFS on s390x

src/platforms/gbm-kms/server/display_helpers.cpp
`ConsoleServices::acquire_device` returns a future that will resolve to a `Device` handle. Should opening the device fail this will resolve to an exception instead, so error handling needs to use `try {} catch()`.
=> gbm-kms: Correctly handle failures when resolving acquire_device future

examples/miral-shell/miral-app.sh
=> Use mktemp, not deprecated tempfile

src/miral/external_client.cpp
=> Add `app-env-amend` configuration option

examples/miral-kiosk/kiosk_window_manager.cpp
=> Kiosk: don't allow window to move

src/server/frontend_wayland/wl_pointer.cpp
=> Do not suppress motion events when relative motion is used

src/miral/open_desktop_entry.cpp
To reflect recent changes to https://github.com/snapcore/snapd/pull/8699
=> Update the snapcraft launch object path

src/server/frontend_wayland/layer_shell_v1.cpp
=> Fix resize of layer shell surfaces

src/server/frontend_wayland/layer_shell_v1.cpp
Alternative to #1989. When combined with #1990 and #1991 we pass relevant WLCS tests including those proposed in https://github.com/MirServer/wlcs/pull/194.
=> Fix layer shell resizing behavior

src/miral/basic_window_manager.cpp, src/miral/basic_window_manager.h
=> Refactor update_attached_and_fullscreen_sets()

src/miral/basic_window_manager.cpp
With clearer logic for placing windows into 1st and 2nd passes some duplicated logic can be removed.
(We could also drop explicit `first_pass` and `second_pass` vectors, but that probably doesn't improve readability.)
=> Tidy BasicWindowManager::update_application_zones_and_attached_windows()

bors.toml
Bors now supports doing this on merge.
Ref: #1141, https://bors.tech/documentation/#configuration-borstoml
=> [bors] update base on branch deletion

src/platforms/x11/graphics/display.cpp
=> [Mir on X] Add hostname to title when remote over X-forwarding

src/server/frontend_wayland/layer_shell_v1.cpp, src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.cpp, src/wayland/generated/wlr-layer-shell-unstable-v1_wrapper.h, src/wayland/protocol/wlr-layer-shell-unstable-v1.xml
=> Bump wlr_layer_shell_unstable_v1 version from 3 to 4

include/client/mir/events/event_builders.h, src/client/events/event_builders.cpp, src/client/symbols.map, src/server/input/default_event_builder.cpp, src/server/input/key_repeat_dispatcher.cpp, src/server/input/seat_input_device_tracker.cpp, src/server/input/surface_input_dispatcher.cpp, src/server/input/validator.cpp, src/server/scene/application_session.cpp, src/server/scene/surface_event_source.cpp, tests/unit-tests/input/test_event_builders.cpp, tests/unit-tests/input/test_event_filter_chain_dispatcher.cpp, tests/unit-tests/input/test_key_repeat_dispatcher.cpp, tests/unit-tests/input/test_surface_input_dispatcher.cpp, tests/unit-tests/input/test_validator.cpp, tests/unit-tests/scene/test_abstract_shell.cpp, tests/unit-tests/scene/test_surface.cpp, tests/unit-tests/scene/test_surface_impl.cpp, tests/unit-tests/shell/test_decoration_basic_decoration.cpp
We already broke ABI, so now is a good time
=> Improve event builder names

src/server/frontend_wayland/wl_seat.cpp
Fixes same issue as #2104 without reverting
=> Do not use keymap after move

include/platform/mir/renderer/sw/pixel_source.h, src/platform/graphics/cpu_buffers.cpp, src/platforms/common/server/buffer_from_wl_shm.cpp, src/platforms/common/server/shm_buffer.cpp, src/platforms/common/server/shm_buffer.h, src/platforms/rpi-dispmanx/buffer_allocator.cpp, src/platforms/rpi-dispmanx/display_buffer.cpp, tests/include/mir/test/doubles/mock_buffer.h, tests/include/mir/test/doubles/stub_buffer.h, tests/unit-tests/graphics/test_shm_buffer.cpp
=> Reverts #2067

include/platform/mir/renderer/sw/pixel_source.h, src/platform/graphics/cpu_buffers.cpp, src/platforms/common/server/buffer_from_wl_shm.cpp, src/platforms/common/server/shm_buffer.cpp, src/platforms/common/server/shm_buffer.h, src/platforms/rpi-dispmanx/buffer_allocator.cpp, src/platforms/rpi-dispmanx/display_buffer.cpp, src/server/frontend_wayland/wl_pointer.cpp, tests/include/mir/test/doubles/mock_buffer.h, tests/include/mir/test/doubles/stub_buffer.h, tests/unit-tests/graphics/test_shm_buffer.cpp
=> platform/graphics: Remove now-unused renderer::software::PixelSource, take 2

include/platform/mir/options/configuration.h, src/platform/options/default_configuration.cpp, src/platform/symbols.map, tools/mir-smoke-test-runner.sh
Drop obsolete options and references to options discovered in my travels around the codebase
=> Drop dead code

src/server/frontend_wayland/CMakeLists.txt, src/server/frontend_wayland/input_method_grab_keyboard_v2.cpp, src/server/frontend_wayland/input_method_grab_keyboard_v2.h, src/server/frontend_wayland/input_method_v2.cpp, src/server/frontend_wayland/input_method_v2.h, src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/wayland_connector.h, src/server/frontend_wayland/wayland_default_configuration.cpp
=> Input method: implement keyboard grabs

include/common/mir/events/event_builders.h, include/common/mir_toolkit/events/input/pointer_event.h, include/core/mir_toolkit/events/enums.h, include/platform/mir/input/event_builder.h, src/common/events/event_builders.cpp, src/common/events/pointer_event.cpp, src/common/input/input_event.cpp, src/common/symbols.map, src/include/common/mir/events/pointer_event.h, src/platforms/evdev/libinput_device.cpp, src/platforms/wayland/display.cpp, src/platforms/wayland/display.h, src/platforms/wayland/display_input.h, src/platforms/wayland/input_device.cpp, src/platforms/wayland/input_device.h, src/platforms/x11/input/input_device.cpp, src/platforms/x11/input/input_device.h, src/platforms/x11/input/input_platform.cpp, src/server/frontend_wayland/wl_pointer.cpp, src/server/input/default_event_builder.cpp, src/server/input/default_event_builder.h, tests/unit-tests/input/evdev/test_libinput_device.cpp
=> Add axis source to pointer events

.github/workflows/spread.yml, tests/CMakeLists.txt
=> Fix Debian/sid

src/include/server/mir/graphics/default_display_configuration_policy.h, src/miral/display_configuration_option.cpp, src/server/graphics/default_display_configuration_policy.cpp, tests/unit-tests/graphics/test_default_display_configuration_policy.cpp
=> Do not rescale on every output resize

src/server/frontend_xwayland/xwayland_surface.cpp, src/server/frontend_xwayland/xwayland_surface.h
The first, smaller commit fixes #2250, the 2nd one makes the behavior more complaint with the spec. I've tested this with intellij (which I was able to reproduce #2250 on), Kate and a couple other things. More manual testing is highly advised since correct behavior in this area is entirely non-obvious.
=> XWayland fixes for dialog window type

.github/workflows/spread.yml, src/platforms/evdev/libinput_device.cpp
=> Don't request axis values from libinput when axis is unset

.github/workflows/spread.yml
=> Reinstate Alpine/edge

src/miral/external_client.cpp
Clear any override for the Qt input method. (It prevents Qt using the OSK)
See discussion in #2271
=> Fix Qt input method

src/include/server/mir/shell/abstract_shell.h, src/server/shell/abstract_shell.cpp
=> Revert "Merge #2246"

src/include/server/mir/shell/abstract_shell.h, src/server/shell/abstract_shell.cpp, tests/include/mir/test/doubles/mock_surface.h, tests/unit-tests/scene/test_abstract_shell.cpp
Fixes #2279 and restores most of #2246. Also adds tests.
=> Revert "Revert \"Merge #2246\" #2280"

src/include/platform/mir/udev/wrapper.h, src/platform/graphics/gamma_curves.cpp, src/platforms/common/server/kms-utils/drm_mode_resources.h, tests/platform_test_harness/graphics_platform_test_harness.cpp
=> [ci] bring Fedora Rawhide back in line

debian/rules
=> Revert "[debian] enable LTO on jammy again"

src/server/frontend_wayland/wl_pointer.cpp
=> wl_pointer: do not send events when not compatible with version

src/server/frontend_wayland/wl_keyboard.cpp
=> Revert "Merge #2245"

include/test/miral/test_display_server.h, tests/acceptance-tests/wayland/test_wlcs_display_server.cpp, tests/integration-tests/test_display_server_main_loop_events.cpp, tests/mir_test_framework/async_server_runner.cpp, tests/mir_test_framework/server_runner.cpp, tests/mir_test_framework/test_display_server.cpp, tests/miral/external_client.cpp, tests/performance-tests/system_performance_test.cpp, tests/performance-tests/system_performance_test.h, tools/mir-smoke-test-runner.sh
=> Update test fixtures to ensure XDG_RUNTIME_DIR is set

tests/miral/external_client.cpp
=> Fix cannot_start_X_server()

examples/miral-shell/spinner/miregl.cpp, tools/mir-smoke-test-runner.sh
=> [spinner] synchronize buffer swaps to video frame

include/core/mir/fatal.h, src/core/fatal.cpp, src/server/run_mir.cpp
Fixes: #2364, MirServer/wlcs#30
=> mir::Server: Fix signal handling

include/common/mir/executor.h, include/common/mir/linearising_executor.h, include/common/mir/system_executor.h, include/test/mir/test/doubles/mock_idle_hub.h, src/common/linearising_executor.cpp, src/common/system_executor.cpp, src/include/server/mir/scene/idle_hub.h, src/server/scene/basic_idle_hub.cpp, src/server/scene/basic_idle_hub.h, tests/include/mir/test/doubles/explicit_executor.h
=> Add NonBlockingExecutor type

src/server/run_mir.cpp
=> Initialize `sig_handler_desc.sa_mask`

examples/example-server-lib/floating_window_manager.cpp, examples/example-server-lib/wayland_app.cpp, src/platforms/evdev/platform.cpp, src/platforms/x11/graphics/display.cpp, src/platforms/x11/graphics/graphics.cpp, src/platforms/x11/graphics/platform.cpp, src/server/frontend_wayland/CMakeLists.txt, src/server/frontend_wayland/std_layout_uptr.h, src/server/frontend_wayland/wayland_default_configuration.cpp, src/server/frontend_wayland/wayland_surface_observer.cpp, src/server/frontend_wayland/wl_client.cpp, src/server/frontend_wayland/wl_surface.cpp, src/server/frontend_xwayland/xcb_connection.cpp, src/server/frontend_xwayland/xcb_connection.h, src/server/frontend_xwayland/xwayland_surface.cpp, src/server/frontend_xwayland/xwayland_surface_observer.cpp, src/server/scene/surface_event_source.cpp, src/server/server.cpp, src/wayland/generator/emitter.cpp
I've got tired of not being able to build with Clang on 22.04, so as a birthday
present to me here's a branch fixing the build.
=> Fix Clang build on 22.04

include/wayland/mir/wayland/wayland_base.h, src/platform/graphics/linux_dmabuf.cpp, src/server/frontend_wayland/wl_keyboard.cpp, src/server/frontend_wayland/wl_pointer.cpp, src/server/frontend_wayland/wl_seat.cpp, src/server/frontend_wayland/wlr_screencopy_v1.cpp, src/server/frontend_wayland/xdg_output_v1.cpp, src/wayland/generator/event.cpp, src/wayland/symbols.map, src/wayland/wayland_base.cpp, tests/acceptance-tests/wayland-generator/CMakeLists.txt, tests/acceptance-tests/wayland-generator/expected.cpp, tests/acceptance-tests/wayland-generator/expected.h, tests/acceptance-tests/wayland-generator/update_wayland_generator_test.sh.in
=> Kill clients with error instead of sending unsupported protocol messages

src/platforms/wayland/display.cpp
=> Explicitly ask for a GLESv2 context

src/server/frontend_wayland/text_input_v2.cpp
It appears Qt, our only client I know of that uses this protocol, doesn't care about the serial. Both previous and new version seem to work with it, but better to be correct.
=> Text Input v2: do not use commit count as serial

src/server/frontend_wayland/text_input_v1.cpp
Especially when the code does not have ownership of the object!
Fixes: #2454
=> Don't use delete in application logic

src/platforms/wayland/display.cpp, src/platforms/wayland/displayclient.cpp, src/platforms/wayland/displayclient.h
Fixes #2447, based on top of #2437 (thus draft PR until that lands). This is also a step towards being able to run the Wayland platform in windowed mode.
=> Wayland platform size from configure

debian/control, debian/libmircore1.install, debian/libmircore2.install, debian/libmircore2.symbols, src/core/CMakeLists.txt, src/core/symbols.map, tests/unit-tests/shared_library_test.cpp
=> Bump mircore soname

tests/include/mir/test/doubles/mock_scene_session.h
Another minor modernization pulled out of the surface observer PR
=> Use new MOCK_METHOD macro in MockSceneSession

src/include/server/mir/shell/abstract_shell.h, src/server/shell/abstract_shell.cpp, tests/unit-tests/scene/test_abstract_shell.cpp
This area is and continues to be a mess. These changes fix some problems with the new surface observer stuff I'm working on.
=> AbstractShell: refactor confinement

debian/libmircore2.symbols
Re-add symbol expectations that the PPA was complaining were missing
=> Testing this spread builds 

src/miral/launch_app.cpp
=> [miral] Unblock signals before execing child processes

tests/mir_test_framework/mmap_wrapper.cpp
`mmap` has two different declarations, depending on whether `_FILE_OFFSET_BITS=64` is defined.
On 64-bit platforms `off_t` and `off64_t` are both 64 bits, but on 32-bit platforms `off_t`
is 32 bits and `off64_t` is 64 bits. Hello, armhf!
Use the `mmap64` symbol when `off_t` is `typedef`ed to `off64_t` (ie: when
`_FILE_OFFSET_BITS=64`).
=> mtf/mmap_wrapper: Pick correct mmap symbol on 32bit platforms

src/server/compositor/multi_threaded_compositor.cpp
=> Don't destroy CompositingFunctors that are not ready 

debian/libmiral5.symbols, include/miral/miral/external_client.h, src/miral/external_client.cpp, src/miral/symbols.map, tests/miral/external_client.cpp
Don't force clients to split command lines themselves
=> [miral] Improvement to ExternalClientLauncher

debian/libmiral5.symbols, include/miral/miral/append_event_filter.h, include/miral/miral/prepend_event_filter.h, src/miral/CMakeLists.txt, src/miral/append_event_filter.cpp, src/miral/prepend_event_filter.cpp, src/miral/symbols.map
1. Correct the AppendEventFilter signature;
2. Add PrependEventFilter; and,
3. Add some doc comments
=> [miral] Tidy up event filtering API

debian/libmiral5.symbols, examples/mir_demo_server/server_example.cpp, include/miral/miral/wayland_extensions.h, src/miral/symbols.map, src/miral/wayland_extensions.cpp
=> Add virtual pointer protocol name to miral

include/miral/miral/prepend_event_filter.h
=> Fix include guard

src/platforms/x11/input/input_device.cpp, src/platforms/x11/input/input_device.h, src/platforms/x11/input/input_platform.cpp, src/platforms/x11/input/input_platform.h
Non-urgant, but makes scroll on X11 a bit less jank
=> X11 platform: send discrete scroll

tests/acceptance-tests/wayland-generator/CMakeLists.txt, tests/acceptance-tests/wayland-generator/expected.h, tests/acceptance-tests/wayland-generator/test_wayland_generator.sh.in
=> Ensure test_wayland_generator runs (and fix test)

src/include/server/mir/shell/abstract_shell.h, src/include/server/mir/shell/focus_controller.h, src/include/server/mir/shell/shell_wrapper.h, src/miral/basic_window_manager.cpp, src/miral/minimal_window_manager.cpp, src/server/shell/abstract_shell.cpp, src/server/shell/shell_wrapper.cpp, src/server/symbols.map, tests/include/mir/test/doubles/stub_shell.h, tests/miral/test_window_manager_tools.cpp, tests/unit-tests/scene/test_abstract_shell.cpp
Fixes #2604 and #2585 by decoupling focus state from dismissing popup grabs. Draft because it doesn't have tests yet, but it should work.
=> Better grabbing popups

src/platforms/common/server/buffer_from_wl_shm.cpp, src/platforms/common/server/shm_buffer.cpp
=> Fix rendering that spans outputs

src/server/frontend_wayland/wl_pointer.cpp, src/server/frontend_wayland/wl_pointer.h
=> Ignore wl_pointer.set_cursor if incorrect serial is given

src/server/frontend_wayland/keyboard_helper.cpp
=> Track keyboard modifiers better

CMakeLists.txt, tests/CMakeLists.txt
Merge #2634 broke builds in ppa:mir-team/dev
(Revert pending investigation)
Fixes:  #2636
=> Revert "Merge #2634"

src/server/run_mir.cpp
=> server: fix unused variable

src/platforms/x11/graphics/display.cpp, src/platforms/x11/graphics/display.h, src/platforms/x11/x11_resources.cpp, src/platforms/x11/x11_resources.h, tests/include/mir/test/doubles/mock_x11_resources.h
=> Implement X11 platform pixel format selection correctly

src/server/frontend_wayland/xdg_output_v1.cpp
=> Do not send zxdg_output.name after initialization

src/platforms/common/server/buffer_from_wl_shm.cpp
(I know Chris wants to improve the code around here, but this fixes the specific problem quickly)
Fixes: #2643
=> [shm buffers] notify consumed for all methods of consumption

src/server/frontend_wayland/text_input_v1.cpp, src/server/frontend_wayland/text_input_v2.cpp, src/server/frontend_wayland/text_input_v3.cpp
=> Disable text input when client is unfocused

src/platforms/gbm-kms/server/kms/real_kms_output.cpp
=> Deal with confused state of KMS outputs better

spread/build/fedora/task.yaml
=> ci: fix Fedora environment

src/platforms/wayland/displayclient.cpp
=> Change mmap to MAP_PRIVATE in example clients

src/platforms/gbm-kms/server/kms/real_kms_display_configuration.cpp
=> Drive-by cleanup

src/server/report/logging/display_configuration_report.cpp, src/server/scene/mediating_display_changer.cpp
Inspired by logs attached to #2695
Fixes #2615
=> Improve logging by DisplayConfigurationReport

src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/wayland_connector.h
By reverting the commit that broke it
=> Fix VT switching

src/miral/internal_client.cpp
Once a Wayland error has occurred on a wl_display it can no longer be used. Check whether the display is in an error state before trying to do a roundtrip on internal client cleanup.
Fixes: #2344
=> miral/InternalClient: don't use a dead wl_display.

src/server/frontend_wayland/idle_inhibit_v1.cpp
I just stumbled across this by accident. Wondering how I snuck this in there 🤔
=> IdleInhibit cleanup

.github/workflows/snap.yml, .github/workflows/spread.yml
=> spread/snap: move back to focal

src/server/frontend_wayland/wl_surface_role.h
Not having this was giving @graysonguarino  trouble
=> Delete WlSurfaceRole copy and assignment

.github/workflows/snap.yml
This was just a waste, never uploaded anywhere and not looked at by bors.
=> bors: skip snapping

tests/unit-tests/scene/test_mediating_display_changer.cpp
There's some legacy style that can be cleaned up
=> Some test code clean up  (before I make changes)

src/platform/graphics/overlapping_output_grouping.cpp
=> Fix overlapping outputs of different scale

examples/example-server-lib/sw_splash.cpp
=> sw_splash: Avoid racy teardown surface

include/miral/miral/wayland_extensions.h
=> Document that extension filter callbacks are called multiple times

CMakeLists.txt, tests/mir_test_doubles/mock_drm.cpp
We no longer care about the older versions that need these
=> Drop some legacy defines

src/miral/static_display_config.cpp, src/miral/static_display_config.h, src/platforms/gbm-kms/server/kms/display.cpp, src/platforms/gbm-kms/server/kms/real_kms_display_configuration.cpp, src/server/scene/mediating_display_changer.cpp
=> Provide sensible output names on kms based platforms

src/server/console/logind-session.xml, src/server/console/logind_console_services.cpp
=> Set the logind session type

src/server/scene/basic_idle_hub.cpp, src/server/scene/basic_idle_hub.h
Makes maintaining thread safety easier. Should not have an impact on behavior.
=> Migrate BasicIdleHub to use Synchronised<T>

src/server/scene/basic_idle_hub.cpp, src/server/scene/basic_idle_hub.h, tests/unit-tests/scene/test_basic_idle_hub.cpp
I've noticed a number of edge cases that cause `BasicIdleHub` to misbehave. Tests are written, implementation to come.
=> Fix BasicIdleHub behavior

src/server/frontend_wayland/xdg_shell_stable.cpp, src/server/frontend_wayland/xdg_shell_v6.cpp
Passes the test, but still doesn't work perfectly with gedit. Might be an issue in precedence order. Will take out of draft when I sort that out. 
Fixes #2857
=> Implement XDG poup constraint adjustment support

src/platforms/evdev/platform_factory.cpp
If we're trying the evdev platform, then there is no fallback. Testing that it can work work in practice causes problems.
And this testing doesn't gain much: a marginally better error message when things don't work. ("No appropriate input platform module found")
Fixes: #2837
=> Assume evdev platform is supported

src/platforms/eglstream-kms/server/kms_display_configuration.cpp
=> Fix naming of outputs on Nvidia cards

src/include/server/mir/default_server_configuration.h, src/include/server/mir/frontend/pointer_input_dispatcher.h, src/include/server/mir/scene/clipboard.h, src/include/server/mir/scene/data_exchange.h, src/server/frontend_wayland/CMakeLists.txt, src/server/frontend_wayland/primary_selection_v1.cpp, src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/wayland_connector.h, src/server/frontend_wayland/wayland_default_configuration.cpp, src/server/frontend_wayland/wayland_input_dispatcher.cpp, src/server/frontend_wayland/wl_data_device.cpp, src/server/frontend_wayland/wl_data_device.h, src/server/frontend_wayland/wl_data_device_manager.cpp, src/server/frontend_wayland/wl_data_device_manager.h, src/server/frontend_wayland/wl_data_source.cpp, src/server/frontend_wayland/wl_data_source.h, src/server/frontend_wayland/wl_pointer.cpp, src/server/frontend_wayland/wl_pointer.h, src/server/frontend_wayland/wl_seat.cpp, src/server/frontend_wayland/wl_seat.h, src/server/frontend_xwayland/xwayland_clipboard_provider.cpp, src/server/frontend_xwayland/xwayland_clipboard_source.cpp, src/server/input/default_configuration.cpp, src/server/input/surface_input_dispatcher.cpp, src/server/input/surface_input_dispatcher.h, src/server/scene/basic_clipboard.cpp, src/server/scene/basic_clipboard.h, src/server/symbols.map, tests/unit-tests/scene/test_basic_clipboard.cpp
This is a cleaned up version of the "spike" implementation.
I need to have a think about how automate testing. The problem for testing is that there's a lot of state spread between the source, the target and parts of this implementation.
While I think about that (that may take some time), please feel free to  do some exploratory testing and to review the code.
Easy way to test:
snap install --classic --channel edge/mir-pr2965 miriway
=> Drag and drop

.github/workflows/snap.yml
=> snap: fix multi arch matrix

debian/rules, tests/unit-tests/CMakeLists.txt, tests/unit-tests/input/test_touchspot_controller.cpp
=> Refactor in an attempt to avoid compiler issues

.github/workflows/spread.yml
=> ci: add ubsan to standard CI

README.md
=> Pointing our README at RTD instead of the old mir-server.io

src/platforms/virtual/display.cpp, src/platforms/virtual/display.h, tests/unit-tests/platforms/virtual/test_display.cpp
=> Support configuration of virtual displays

src/server/graphics/default_configuration.cpp
=> Make egl-generic the rendering platform of last resort

include/miral/miral/keymap.h
=> xkb countrycode for uk keyboard is 'gb'

src/miral/basic_window_manager.cpp
Fixes: #3116
See also #3040, as the fix for that introduced this problem.
=> Don't allow fullscreen surfaces to be resized

src/server/frontend_xwayland/xwayland_surface.cpp
This is a version of some tracing I found useful fixing some of the CLion menu/gloss/tip weirdness.
I still occasionally see, for example, the right click popup on the git log panel being transparant to mouse input. So having this additional logging could help understand what is happening.
=> More X11/Xwayland debug logging

src/renderers/gl/renderer.cpp
When the layout of the texture disagrees with the layout of the output surface, then the clip area needs to be modified
Fixes: #3201
=> (#3201) When the layout of the texture disagrees with the layout of the output surface, then the clip area needs to be modified

.github/.jira_sync_config.yaml
Ref.: https://github.com/canonical/gh-jira-sync-bot
=> jira: add sync config

src/wayland/generator/request.cpp, tests/acceptance-tests/wayland-generator/expected.cpp, tests/acceptance-tests/wayland-generator/expected.h
This reverts commit e351efa6117d22f476d5652a2d943ccd834ad460.
=> Revert "Revert "Merge pull request #3243 from canonical/feature/3241""

src/server/graphics/platform_probe.cpp
Fixes: #3261
Note: this is a "quick and dirty" fix to unbreak main.
A fix with tests needs a rework of `mg::select_display_modules()` so that it doesn't both load the available platform modules and select amongst them. That will need a little more time.
=> Do not assume there is a "mir:virtual" platform

tests/unit-tests/test_observer_multiplexer.cpp
This PR suggests a unit test for the "early observers" feature added to `ObserverRegistrar` in #3244.
=> Add unit test for early observers

.github/workflows/spread.yml, spread.yaml, src/miral/static_display_config.cpp, src/server/graphics/multiplexing_display.cpp
Fixes: https://github.com/canonical/ubuntu-frame/issues/172
=> Fix propagation of custom attributes on outputs

src/platforms/gbm-kms/server/buffer_allocator.cpp, src/platforms/gbm-kms/server/buffer_allocator.h, src/platforms/gbm-kms/server/kms/platform.cpp, src/platforms/gbm-kms/server/kms/platform.h, src/server/frontend_wayland/frame_executor.cpp, src/server/frontend_wayland/frame_executor.h, src/server/report/logging/input_report.h, src/server/report/lttng/display_report.h, src/server/report/lttng/input_report.h
I don't know why these are now tripping up clang on 24.04,
(or why the built *anywhere* before), but they now do, and
they're correct changes, so :woman_shrugging:
=> Build fixes for Clang & Ubuntu 24.04

doc/sphinx/.sphinx/build_requirements.py
https://github.com/breathe-doc/breathe/issues/981
=> doc: pin sphinx

doc/sphinx/.sphinx/build_requirements.py
This reverts commit f6296889ba81e8067d2f7b6d057f362daea36b73, reversing changes made to 8407da28ddb9a535df2775f224bf5143e8770d52.
=> Revert "doc: pin sphinx (#3335)"

src/server/frontend_wayland/desktop_file_manager.cpp, src/server/frontend_wayland/foreign_toplevel_manager_v1.cpp, src/server/frontend_wayland/foreign_toplevel_manager_v1.h, tests/unit-tests/frontend_wayland/test_g_desktop_file_cache.cpp
fixes https://github.com/canonical/mir/issues/3271
=> bugfix: adding quirks to the DesktopFileManager to handle more use cases

doc/sphinx/how-to/getting_involved_in_mir.md
=> Fix broken link in docs

src/server/frontend_wayland/wl_surface.cpp
=> We can only submit a buffer if we have one already

src/server/input/default_input_device_hub.cpp
The previous ordering led to a segfault using `sudo chvt 1` - as `*pos` was null 
Also:
Fixes: #3518
Fixes: #3499
=> Unregister callback before item is nullptr

debian/rules
=> debian: bump broken binutils

src/miral/basic_window_manager.cpp
Separate out the strategy for placing child windows from `BasicWindowManager`
=> Extract child placement logic

spread.yaml, spread/build/sbuild/task.yaml
=> sbuild: don't override gcc

.github/workflows/symbols-check.yml
Alan's reporting this is fine on clang-18
=> ci: symbols on LLVM 18

src/server/frontend_wayland/wl_surface.h, src/server/frontend_xwayland/xwayland_surface.cpp, src/server/frontend_xwayland/xwayland_surface_role.cpp
=> Fix XWayland scaling attempt 2

src/server/frontend_wayland/layer_shell_v1.cpp
closes #3450 
We now ignore all LayerShellV1 configure requests except the most recent one.
=> Fix LayerShellV1 flicker

.github/workflows/tics.yml
=> tics: don't run it in parallel

src/server/shell/decoration/basic_decoration.cpp
=> A zero size is not a real size. (Wayland treats it as a special value)

src/server/shell/token_authority.cpp, tests/unit-tests/shell/CMakeLists.txt, tests/unit-tests/shell/test_token_authority.cpp
Just the tests I could come up with as I wrote. Feel free to provide edge cases or other test cases.
=> Add a basic test suite for `TokenAuthority`

examples/example-server-lib/wallpaper_config.cpp, src/server/shell/decoration/decoration_strategy.cpp
Try more fonts and more locations when drawing SSD text
=> Fix SSD text

tests/unit-tests/shell/test_token_authority.cpp
=> tests: increase token expiration time tolerance

debian/changelog, src/miral/application_selector.cpp, src/miral/basic_window_manager.cpp, src/miral/basic_window_manager.h
Fixes: https://github.com/canonical/mir/issues/3786
=> test-revert-3698

src/miral/wayland_extensions.cpp, tests/miral/wayland_extensions.cpp
=> Quit on attempt to duplicate wayland extensions

tests/window_management_tests/test_minimal_window_manager.cpp
- Adding more tests for how different attached surfaces interact with one another given an exclusion zone that takes up the full dimensions of the surface
These tests are a bit redundant with those found in `window_placement_attached.cpp`, but this tests more of end-to-end scenario, so I think it is worthwhile
1. Build the project
2. Run `mir_window_management_tests`
=> testing: adding attached surface tests for all compass directions

CMakeLists.txt, examples/CMakeLists.txt, examples/tests/CMakeLists.txt
=> Enable examples testing only if testing is set to true

src/miral/mousekeys_config.cpp
=> Fix TOCTTOU bug in `MouseKeysConfig` setters

examples/mir_demo_server/server_example.cpp
Added in 482b661b845ad8a2894941e4d94192b2a539d470.
=> Remove unused object

tests/include/mir/test/doubles/queued_alarm_stub_main_loop.h, tests/include/mir/test/doubles/stub_notifying_alarm.h, tests/mir_test_doubles/CMakeLists.txt, tests/mir_test_doubles/queued_alarm_stub_main_loop.cpp, tests/mir_test_doubles/stub_notifying_alarm.cpp, tests/unit-tests/shell/test_mouse_keys_transformer.cpp
Pulls out common testing code used in accessibility method testing from #3873.
=> Add `StubNotifyingAlarm` and `QueuedAlarmStubMainLoop`

tests/miral/CMakeLists.txt
Fix intermittent failures in CI
=> All the TestConfigFile depend on filesystem interaction - and can fail intermittently in CI

src/server/frontend_wayland/wayland_connector.cpp, src/server/frontend_wayland/window_wl_surface_role.cpp, src/server/frontend_wayland/window_wl_surface_role.h, src/server/frontend_wayland/wl_keyboard.cpp, src/server/frontend_wayland/wl_pointer.cpp, src/server/frontend_wayland/wl_seat.cpp, src/server/frontend_wayland/wl_surface.cpp, src/server/frontend_wayland/wl_surface.h, src/server/frontend_wayland/wl_touch.cpp, wayland-protocols/wayland.xml
=> Update of core wayland extensions

src/platforms/gbm-kms/server/kms/real_kms_output.cpp, tests/include/mir/test/doubles/mock_drm.h, tests/mir_test_doubles/mock_drm.cpp, tests/unit-tests/platforms/gbm-kms/kms-utils/test_drm_mode_resources.cpp, tests/unit-tests/platforms/gbm-kms/kms/test_display_configuration.cpp, tests/unit-tests/platforms/gbm-kms/kms/test_display_multi_monitor.cpp
Copied from the atomic-kms backend
Fixes https://github.com/canonical/mir/issues/3466
=> Check DRM for supported formats

src/renderers/gl/renderer.cpp
Was previously defaulting to invert always.
=> Choose correct shader source for output filter.

src/miral/basic_window_manager.cpp, tests/window_management_tests/test_minimal_window_manager.cpp
Not sure why this code was here. Doesn't seem to belong
=> Don't raise the parent of windows sent to the back

examples/client/spinner.cpp, examples/client/wayland_runner.cpp, src/common/logging/logger.cpp, src/common/time/posix_clock.cpp, src/platforms/eglstream-kms/server/utils.cpp, src/server/console/linux_virtual_terminal.cpp, src/server/frontend_wayland/foreign_toplevel_manager_v1.cpp, src/server/frontend_wayland/xdg_shell_stable.cpp, src/server/frontend_wayland/xdg_shell_v6.cpp, src/server/frontend_xwayland/xwayland_client_manager.cpp, src/server/frontend_xwayland/xwayland_spawner.cpp, src/server/glib_main_loop_sources.cpp, src/server/run_mir.cpp, src/server/shm_backing.cpp, tests/mir_test_framework/udev_environment.cpp, tests/performance-tests/system_performance_test.cpp, tests/unit-tests/dispatch/test_threaded_dispatcher.cpp, tests/unit-tests/graphics/test_anonymous_shm_file.cpp, tests/unit-tests/test_shm_backing.cpp, tests/unit-tests/test_udev_wrapper.cpp
=> Initialize structs.

tests/mir_test_doubles/stub_buffer_allocator.cpp
We now use a real graphics platform in the WLCS tests, so don't need to fake stuff here!
=> mtd::StubBufferAllocator: Drop read-from-ShmBuffer hack

debian/rules
Add check for yet another binutils
=> binutils 2.44.50.20250616 for arm64 still breaks LTO builds

doc/sphinx/Makefile
=> ci: fix documentation checks

src/server/shell/basic_accessibility_manager.cpp
=> Fix use of std::clamp

doc/sphinx/explanation/component_reports.md
Removed in 7c91fb87b67d7c5d46d9fa62371c03b875252971
=> Remove documentation for removed legacy input report

doc/sphinx/explanation/desktop-environment.md, doc/sphinx/explanation/index.md
Adds explanation/desktop-environment.md to documentation
=> MIRENG-1018-desktop-environment

doc/sphinx/api/library_root.rst
I think Saviq was right, this is nicer
=> Use the exhale class view over the unabriged api view

include/miral/miral/application_info.h
* Improve doxygen comments on `miral::ApplicationInfo`
=> Better documenting the miral::ApplicationInfo class

include/miral/miral/window_info.h
* Adding documentation to miral::WindowInfo
=> Add documentation to window_info.h

.github/pull_request_template.md
Reduce what needs to be deleted/replaced in the PR template, and drop header levels.
Just see the `.md` source.
=> gh: tweak pull request template formatting and placeholders

doc/sphinx/configuring-index.md, doc/sphinx/contributing-index.md, doc/sphinx/index.md, doc/sphinx/reference/configuring-index.md, doc/sphinx/tutorial/configuring-index.md, doc/sphinx/tutorial/contributing-index.md
Tidies away empty documentation categories
=> MIRENG-1412-Housekeep-documentation-pages-drop-empty-categories

include/miral/miral/application.h, include/miral/miral/display_configuration.h, include/miral/miral/external_client.h, include/miral/miral/minimal_window_manager.h, include/miral/miral/output.h, include/miral/miral/prepend_event_filter.h, include/miral/miral/runner.h, include/miral/miral/wayland_extensions.h, include/miral/miral/window.h, include/miral/miral/window_info.h, include/miral/miral/window_manager_tools.h, include/miral/miral/window_specification.h, include/miral/miral/x11_support.h, include/miral/miral/zone.h, include/test/miral/test_display_server.h, src/miral/application_selector.h
=> Drop references to MirAL 2.x and 3.x

include/platform/mir/graphics/buffer.h
- Adds Doxygen documentation for `mg::Buffer`
=> Add documentation for `mg::Buffer`

include/platform/mir/renderer/sw/pixel_source.h
- Adds initial docs for `BufferDescriptor`
=> Add initial docs for `mg::software::BufferDescriptor`

.github/workflows/tics.yml
Only generate LCOV output for TICS
TICS happy.
=> Tics fix coverage
